export type LessonCheckQuestion =
  | {
      id: string;
      kind: "text";
      prompt: string;
      acceptedAnswers: string[];
      explanation: string;
    }
  | {
      id: string;
      kind: "numeric";
      prompt: string;
      value: number;
      unit?: string;
      tolerance?: number;
      explanation: string;
    };

export type LessonCheck = {
  id: string;
  title: string;
  description: string;
  questions: LessonCheckQuestion[];
};

export const lessonChecks: LessonCheck[] = [
  {
    id: "arithmetic-units-core-check",
    title: "Arithmetic, Units, and Estimation Check",
    description:
      "Enter the result with units when units are requested. These checks are intentionally small so you can verify the core habits before moving on.",
    questions: [
      {
        id: "quantity-parts",
        kind: "text",
        prompt: "What two parts does a measured quantity have?",
        acceptedAnswers: ["number and unit", "a number and a unit", "number plus unit", "value and unit"],
        explanation: "A measured quantity combines a numerical value with a unit, such as 12 V or 3.5 A.",
      },
      {
        id: "minutes-to-hours",
        kind: "numeric",
        prompt: "Convert 30 minutes to hours.",
        value: 0.5,
        unit: "h",
        tolerance: 0.0001,
        explanation: "30 minutes is 30 / 60 hours, which is 0.5 h.",
      },
      {
        id: "speed-time-distance",
        kind: "numeric",
        prompt: "A rover moves at 0.6 m/s for 20 s. How far does it travel?",
        value: 12,
        unit: "m",
        tolerance: 0.0001,
        explanation: "Distance = speed x time = 0.6 m/s x 20 s = 12 m.",
      },
      {
        id: "ma-to-a",
        kind: "numeric",
        prompt: "Convert 75 mA to amps.",
        value: 0.075,
        unit: "A",
        tolerance: 0.000001,
        explanation: "1 mA = 0.001 A, so 75 mA = 75 x 0.001 A = 0.075 A.",
      },
      {
        id: "scientific-notation",
        kind: "text",
        prompt: "Write 0.0068 in scientific notation.",
        acceptedAnswers: ["6.8 x 10^-3", "6.8*10^-3", "6.8x10^-3", "6.8e-3", "6.8 x 10-3"],
        explanation: "Move the decimal 3 places right to get 6.8, so the power of ten is -3.",
      },
    ],
  },
  {
    id: "fractions-ratios-core-check",
    title: "Fractions, Ratios, and Proportions Check",
    description:
      "Use labels and units where requested. The goal is to verify whether you know what is being compared.",
    questions: [
      {
        id: "simplify-fraction",
        kind: "text",
        prompt: "Simplify 6/9.",
        acceptedAnswers: ["2/3", "two thirds", "2 thirds"],
        explanation: "Divide numerator and denominator by 3: 6/9 = 2/3.",
      },
      {
        id: "unit-rate",
        kind: "numeric",
        prompt: "A robot travels 15 m in 3 s. What is its unit rate?",
        value: 5,
        unit: "m/s",
        tolerance: 0.0001,
        explanation: "Unit rate = 15 m / 3 s = 5 m/s.",
      },
      {
        id: "map-scale",
        kind: "numeric",
        prompt: "A map scale is 1 cm = 2.5 m. A line is 12 cm. What real distance does it represent?",
        value: 30,
        unit: "m",
        tolerance: 0.0001,
        explanation: "12 cm is 12 times the map unit, so 12 x 2.5 m = 30 m.",
      },
      {
        id: "gear-ratio",
        kind: "numeric",
        prompt: "A motor spins at 1800 RPM through a 6:1 reduction. What is output RPM?",
        value: 300,
        unit: "RPM",
        tolerance: 0.0001,
        explanation: "For a 6:1 reduction, output RPM = 1800 / 6 = 300 RPM.",
      },
      {
        id: "part-whole",
        kind: "text",
        prompt: "A kit has 2 motors and 6 propellers. What fraction of the 8 total parts are motors?",
        acceptedAnswers: ["1/4", "2/8", "one fourth", "one quarter", "0.25"],
        explanation: "There are 2 motors out of 8 total parts, so 2/8 = 1/4.",
      },
    ],
  },
  {
    id: "signed-numbers-core-check",
    title: "Signed Numbers and Order of Operations Check",
    description:
      "Check signs, parentheses, and physical meaning carefully. Most mistakes in this lesson are small marks with large consequences.",
    questions: [
      {
        id: "opposite",
        kind: "numeric",
        prompt: "What is the opposite of -8?",
        value: 8,
        tolerance: 0,
        explanation: "The opposite is the same distance from zero on the other side, so the opposite of -8 is 8.",
      },
      {
        id: "absolute-value",
        kind: "numeric",
        prompt: "What is |-12|?",
        value: 12,
        tolerance: 0,
        explanation: "Absolute value is distance from zero. Distance is never negative.",
      },
      {
        id: "subtract-negative",
        kind: "numeric",
        prompt: "Calculate 5 - (-4).",
        value: 9,
        tolerance: 0,
        explanation: "Subtracting a negative is adding the opposite: 5 - (-4) = 5 + 4 = 9.",
      },
      {
        id: "negative-square-no-parentheses",
        kind: "numeric",
        prompt: "Calculate -3^2.",
        value: -9,
        tolerance: 0,
        explanation: "Without parentheses, the exponent applies to 3 first, then the negative sign is applied: -3^2 = -(9) = -9.",
      },
      {
        id: "distance-vs-displacement",
        kind: "text",
        prompt: "Which can be negative: distance or displacement?",
        acceptedAnswers: ["displacement", "displacement can be negative", "displacement can"],
        explanation: "Distance is total path length and is never negative. Displacement is change in position and can be positive, negative, or zero.",
      },
    ],
  },
  {
    id: "place-value-and-whole-number-arithmetic-check",
    title: "Place Value and Whole-Number Arithmetic Check",
    description:
      "Quick checks on positional notation, expanded form, the standard arithmetic algorithms, and estimation.",
    questions: [
      {
        id: "expanded-form-thousand-place",
        kind: "numeric",
        prompt: "In the number 6,073, what digit is in the thousands place?",
        value: 6,
        tolerance: 0,
        explanation: "Reading from the left: 6 is thousands, 0 is hundreds, 7 is tens, 3 is ones.",
      },
      {
        id: "expanded-form-zero-role",
        kind: "text",
        prompt: "What role does the 0 play in 6,073? Answer in two or three words.",
        acceptedAnswers: ["placeholder", "place holder", "holds a place", "holds the hundreds place", "placeholder for hundreds"],
        explanation: "The 0 holds the hundreds place. Without it, the number would collapse to 673.",
      },
      {
        id: "addition-with-carries",
        kind: "numeric",
        prompt: "Compute 487 + 296.",
        value: 783,
        tolerance: 0,
        explanation: "7 + 6 = 13 (write 3, carry 1). 8 + 9 + 1 = 18 (write 8, carry 1). 4 + 2 + 1 = 7. Result 783.",
      },
      {
        id: "subtraction-with-borrows",
        kind: "numeric",
        prompt: "Compute 1,000 - 1.",
        value: 999,
        tolerance: 0,
        explanation: "Cascading borrow: 1,000 - 1 = 999.",
      },
      {
        id: "multiplication-shift",
        kind: "numeric",
        prompt: "Compute 43 × 27.",
        value: 1161,
        tolerance: 0,
        explanation: "43 × 7 = 301; 43 × 20 = 860; sum = 1,161.",
      },
      {
        id: "binary-to-decimal",
        kind: "numeric",
        prompt: "Convert the binary number 1011 to decimal.",
        value: 11,
        tolerance: 0,
        explanation: "1·8 + 0·4 + 1·2 + 1·1 = 11.",
      },
      {
        id: "hex-to-decimal",
        kind: "numeric",
        prompt: "Convert the hexadecimal number FF to decimal.",
        value: 255,
        tolerance: 0,
        explanation: "15·16 + 15·1 = 240 + 15 = 255.",
      },
      {
        id: "estimation",
        kind: "numeric",
        prompt: "Estimate 9,183 × 421 by rounding each to its leading digit. What is the rough estimate?",
        value: 3600000,
        tolerance: 200000,
        explanation: "9,183 ≈ 9,000 and 421 ≈ 400. 9,000 × 400 = 3,600,000. (The exact answer is 3,866,043 — same order of magnitude.)",
      },
    ],
  },
  {
    id: "multiplication-tables-and-factor-fluency-check",
    title: "Multiplication Tables and Factor Fluency Check",
    description:
      "Quick checks on single-digit products, squares, factor lists, divisibility rules, and prime recognition.",
    questions: [
      {
        id: "times-7-8",
        kind: "numeric",
        prompt: "Compute 7 × 8.",
        value: 56,
        tolerance: 0,
        explanation: "56. One of the highest-traffic single-digit facts; learn it cold.",
      },
      {
        id: "times-9-6",
        kind: "numeric",
        prompt: "Compute 9 × 6.",
        value: 54,
        tolerance: 0,
        explanation: "54. Pattern check: digits sum to 9 (5 + 4 = 9).",
      },
      {
        id: "square-15",
        kind: "numeric",
        prompt: "Compute 15 squared.",
        value: 225,
        tolerance: 0,
        explanation: "15² = 225. Worth knowing on sight.",
      },
      {
        id: "factor-of-36",
        kind: "numeric",
        prompt: "How many distinct positive factors does 36 have? (Hint: 36 = 2^2 · 3^2.)",
        value: 9,
        tolerance: 0,
        explanation: "Factors of 36 are {1, 2, 3, 4, 6, 9, 12, 18, 36} — nine factors.",
      },
      {
        id: "divisible-by-3",
        kind: "text",
        prompt: "Is 471 divisible by 3? Answer 'yes' or 'no'.",
        acceptedAnswers: ["yes", "yes it is", "yes 471 is divisible by 3"],
        explanation: "The digit sum is 4 + 7 + 1 = 12, which is divisible by 3, so 471 is divisible by 3 (471 / 3 = 157).",
      },
      {
        id: "is-91-prime",
        kind: "text",
        prompt: "Is 91 prime? Answer 'yes' or 'no'.",
        acceptedAnswers: ["no", "no it is not prime", "no it isn't prime", "not prime"],
        explanation: "91 = 7 × 13. Not prime.",
      },
      {
        id: "primes-under-20",
        kind: "numeric",
        prompt: "How many prime numbers are there between 2 and 20 inclusive?",
        value: 8,
        tolerance: 0,
        explanation: "{2, 3, 5, 7, 11, 13, 17, 19} — eight primes.",
      },
    ],
  },
  {
    id: "long-division-and-divisibility-check",
    title: "Long Division and Divisibility Check",
    description:
      "Quick checks on the long-division algorithm, decimal expansions, the divisibility rules, and a touch of modular arithmetic.",
    questions: [
      {
        id: "quotient-no-remainder",
        kind: "numeric",
        prompt: "Compute 792 ÷ 6.",
        value: 132,
        tolerance: 0,
        explanation: "6 × 132 = 792.",
      },
      {
        id: "quotient-with-remainder",
        kind: "numeric",
        prompt: "Compute 785 ÷ 23. Give the quotient only (ignore the remainder).",
        value: 34,
        tolerance: 0,
        explanation: "23 × 34 = 782; remainder 3.",
      },
      {
        id: "remainder",
        kind: "numeric",
        prompt: "Compute the remainder of 785 ÷ 23.",
        value: 3,
        tolerance: 0,
        explanation: "23 × 34 = 782; 785 − 782 = 3.",
      },
      {
        id: "decimal-terminate",
        kind: "numeric",
        prompt: "Compute 13 ÷ 8 as a decimal.",
        value: 1.625,
        tolerance: 0.0001,
        explanation: "8 × 1.625 = 13. The decimal terminates because 8 = 2³ has only 2 as a prime factor.",
      },
      {
        id: "mod-by-7",
        kind: "numeric",
        prompt: "What is 123 mod 7?",
        value: 4,
        tolerance: 0,
        explanation: "123 = 7 · 17 + 4, so 123 mod 7 = 4.",
      },
      {
        id: "div-by-9-rule",
        kind: "text",
        prompt: "Is 1,234,567 divisible by 9? Answer 'yes' or 'no'.",
        acceptedAnswers: ["no", "no it is not", "no, it is not"],
        explanation: "Digit sum: 1+2+3+4+5+6+7 = 28. 28 is not divisible by 9, so 1,234,567 is not divisible by 9.",
      },
      {
        id: "time-conversion",
        kind: "numeric",
        prompt: "How many full hours are in 10,000 seconds?",
        value: 2,
        tolerance: 0,
        explanation: "10,000 ÷ 3,600 = 2 hours with remainder 2,800 seconds.",
      },
    ],
  },
  {
    id: "fractions-meaning-and-equivalence-check",
    title: "Fractions: Meaning and Equivalence Check",
    description:
      "Quick checks on the three meanings of a fraction, the cross-product equality test, simplification with GCD, and comparison.",
    questions: [
      {
        id: "simplify-420-1050",
        kind: "text",
        prompt: "Simplify 420/1050 to lowest terms.",
        acceptedAnswers: ["2/5", "2 / 5", "two fifths"],
        explanation: "gcd(420, 1050) = 210. 420/210 = 2, 1050/210 = 5. So 420/1050 = 2/5.",
      },
      {
        id: "aspect-ratio-1920-1080",
        kind: "text",
        prompt: "Simplify 1920/1080 (the HDTV aspect ratio) to lowest terms.",
        acceptedAnswers: ["16/9", "16 / 9", "16:9"],
        explanation: "gcd(1920, 1080) = 120. 1920/120 = 16, 1080/120 = 9. So 1920/1080 = 16/9.",
      },
      {
        id: "cross-product-equality",
        kind: "text",
        prompt: "Are 6/9 and 14/21 equal? Answer 'yes' or 'no'.",
        acceptedAnswers: ["yes", "yes they are", "yes equal", "yes they are equal"],
        explanation: "Cross-product: 6 * 21 = 126 = 9 * 14. They are equal (both simplify to 2/3).",
      },
      {
        id: "compare-fractions-cross",
        kind: "text",
        prompt: "Which is larger, 5/7 or 7/10? Answer with the fraction.",
        acceptedAnswers: ["5/7", "5 / 7", "five sevenths"],
        explanation: "Cross-multiplication: 5 * 10 = 50, 7 * 7 = 49. Since 50 > 49, 5/7 > 7/10.",
      },
      {
        id: "improper-to-mixed",
        kind: "text",
        prompt: "Convert 47/8 to a mixed number. Write as 'whole numerator/denominator', e.g., '5 7/8'.",
        acceptedAnswers: ["5 7/8", "5-7/8", "5 and 7/8", "5 7 / 8"],
        explanation: "47 = 5 * 8 + 7, so 47/8 = 5 and 7/8.",
      },
      {
        id: "mixed-to-improper",
        kind: "text",
        prompt: "Convert 4 and 3/7 (the mixed number 4 3/7) to an improper fraction.",
        acceptedAnswers: ["31/7", "31 / 7", "thirty-one sevenths"],
        explanation: "4 * 7 + 3 = 31. So 4 3/7 = 31/7.",
      },
      {
        id: "adc-fraction",
        kind: "text",
        prompt: "A 12-bit ADC (0 to 4095 counts) reads 2048. Express the reading as a fraction of full scale in lowest terms.",
        acceptedAnswers: ["2048/4095", "2048 / 4095"],
        explanation: "gcd(2048, 4095) = 1 (since 4095 = 3^2 * 5 * 7 * 13 has no factor of 2). So 2048/4095 is already in lowest terms.",
      },
    ],
  },
  {
    id: "fractions-add-subtract-multiply-divide-check",
    title: "Fractions: Arithmetic Operations Check",
    description:
      "Quick checks on the four arithmetic operations on fractions, the reciprocal, parallel-resistance application, and common error patterns.",
    questions: [
      {
        id: "add-1-2-1-3",
        kind: "text",
        prompt: "Compute 1/2 + 1/3. Give the answer as a fraction in lowest terms.",
        acceptedAnswers: ["5/6", "5 / 6", "five sixths"],
        explanation: "Common denominator 6: 1/2 = 3/6, 1/3 = 2/6. Sum = 5/6.",
      },
      {
        id: "subtract-7-8-2-3",
        kind: "text",
        prompt: "Compute 7/8 - 2/3. Give the answer as a fraction in lowest terms.",
        acceptedAnswers: ["5/24", "5 / 24"],
        explanation: "Common denominator 24: 7/8 = 21/24, 2/3 = 16/24. Difference = 5/24.",
      },
      {
        id: "multiply-2-3-9-14",
        kind: "text",
        prompt: "Compute (2/3) * (9/14). Give the answer as a fraction in lowest terms.",
        acceptedAnswers: ["3/7", "3 / 7", "three sevenths"],
        explanation: "Cancel before multiplying: 2/14 = 1/7, then (1/3)*9 = 3, so 3/7. Or 18/42 = 3/7.",
      },
      {
        id: "divide-3-4-1-2",
        kind: "text",
        prompt: "Compute (3/4) / (1/2). Give the answer as a fraction in lowest terms.",
        acceptedAnswers: ["3/2", "3 / 2", "1 1/2", "one and a half"],
        explanation: "Invert and multiply: (3/4) * (2/1) = 6/4 = 3/2.",
      },
      {
        id: "reciprocal",
        kind: "text",
        prompt: "What is the reciprocal of 7/3?",
        acceptedAnswers: ["3/7", "3 / 7", "three sevenths"],
        explanation: "The reciprocal swaps numerator and denominator: reciprocal of 7/3 is 3/7.",
      },
      {
        id: "parallel-resistors",
        kind: "numeric",
        prompt: "Two resistors 4 ohm and 6 ohm in parallel. Equivalent resistance (in ohms)?",
        value: 2.4,
        unit: "ohm",
        tolerance: 0.01,
        explanation: "1/R = 1/4 + 1/6 = 3/12 + 2/12 = 5/12. So R = 12/5 = 2.4 ohm.",
      },
      {
        id: "compound-fraction",
        kind: "text",
        prompt: "Compute (1/2 + 1/3) / (1/2 - 1/3). Give the answer as a fraction in lowest terms.",
        acceptedAnswers: ["5/1", "5", "5/1 ", "5 / 1"],
        explanation: "Top: 1/2 + 1/3 = 5/6. Bottom: 1/2 - 1/3 = 1/6. Quotient: (5/6) / (1/6) = 5.",
      },
    ],
  },
  {
    id: "decimals-and-decimal-arithmetic-check",
    title: "Decimals and Decimal Arithmetic Check",
    description:
      "Quick checks on decimal place value, conversions to/from fractions, the terminating-decimal theorem, decimal arithmetic, and floating-point awareness.",
    questions: [
      {
        id: "decimal-to-fraction",
        kind: "text",
        prompt: "Convert 0.625 to a fraction in lowest terms.",
        acceptedAnswers: ["5/8", "5 / 8", "five eighths"],
        explanation: "0.625 = 625/1000. gcd(625, 1000) = 125. 625/125 = 5, 1000/125 = 8. So 5/8.",
      },
      {
        id: "fraction-to-decimal-terminate",
        kind: "numeric",
        prompt: "Convert 7/16 to a decimal.",
        value: 0.4375,
        tolerance: 0.00001,
        explanation: "16 = 2^4, so the decimal terminates. 7/16 = 0.4375 (long division or multiply by 625/625).",
      },
      {
        id: "repeating-to-fraction",
        kind: "text",
        prompt: "Convert the repeating decimal 0.272727... (where 27 repeats forever) to a fraction in lowest terms.",
        acceptedAnswers: ["3/11", "3 / 11"],
        explanation: "Let x = 0.272727... Then 100x = 27.272727... Subtract: 99x = 27, so x = 27/99 = 3/11.",
      },
      {
        id: "terminates-or-not",
        kind: "text",
        prompt: "Does 1/12 have a terminating decimal expansion? Answer 'yes' or 'no'.",
        acceptedAnswers: ["no", "no it does not", "no it does not terminate", "no it doesn't"],
        explanation: "12 = 2^2 * 3. The factor of 3 forces the decimal to repeat. 1/12 = 0.08333...",
      },
      {
        id: "decimal-multiply",
        kind: "numeric",
        prompt: "Compute 0.04 * 0.6.",
        value: 0.024,
        tolerance: 0.0001,
        explanation: "Ignore decimal points: 4 * 6 = 24. Decimal places: 2 + 1 = 3. So 0.024.",
      },
      {
        id: "decimal-divide",
        kind: "numeric",
        prompt: "Compute 12.6 / 0.4.",
        value: 31.5,
        tolerance: 0.001,
        explanation: "Multiply both by 10: 126 / 4 = 31.5.",
      },
      {
        id: "float-equality",
        kind: "text",
        prompt: "In standard IEEE 754 floating-point, is 0.1 + 0.2 exactly equal to 0.3? Answer 'yes' or 'no'.",
        acceptedAnswers: ["no", "no it is not", "no they are not equal", "no not equal"],
        explanation: "0.1 in binary is the repeating 0.0001100110011... which gets truncated. The sum 0.1 + 0.2 is approximately 0.30000000000000004, not exactly 0.3.",
      },
    ],
  },
  {
    id: "percent-and-percent-change-check",
    title: "Percent and Percent Change Check",
    description:
      "Quick checks on percent-fraction-decimal conversions, the three classes of percent problems, percent change, consecutive changes, and the percentage-point distinction.",
    questions: [
      {
        id: "percent-of",
        kind: "numeric",
        prompt: "What is 15% of 240?",
        value: 36,
        tolerance: 0,
        explanation: "0.15 * 240 = 36.",
      },
      {
        id: "what-percent",
        kind: "numeric",
        prompt: "18 is what percent of 75? Answer as a number only (do not include the percent sign).",
        value: 24,
        tolerance: 0.01,
        explanation: "18/75 = 0.24 = 24%.",
      },
      {
        id: "find-whole",
        kind: "numeric",
        prompt: "36 is 12% of what number?",
        value: 300,
        tolerance: 0.01,
        explanation: "36 / 0.12 = 300.",
      },
      {
        id: "percent-change",
        kind: "numeric",
        prompt: "A drone's flight time was 22 min and is now 28 min. Percent improvement? Answer as a number only (do not include the percent sign). Round to 2 decimal places.",
        value: 27.27,
        tolerance: 0.05,
        explanation: "(28 - 22) / 22 = 6/22 ≈ 0.2727 ≈ 27.27%.",
      },
      {
        id: "consecutive-changes",
        kind: "numeric",
        prompt: "A stock rises 20% then falls 20%. Net percent change? Answer as a number only (negative if a loss).",
        value: -4,
        tolerance: 0.01,
        explanation: "Factors multiply: 1.20 * 0.80 = 0.96. Net change: -4%, not 0%.",
      },
      {
        id: "compound-growth",
        kind: "numeric",
        prompt: "$1000 invested at 5% annual compound interest for 10 years. Final balance in dollars (round to nearest dollar)?",
        value: 1629,
        tolerance: 2,
        explanation: "1000 * 1.05^10 ≈ 1628.89, round to $1629.",
      },
      {
        id: "percentage-points",
        kind: "text",
        prompt: "An interest rate rose from 4% to 5%. By how many PERCENTAGE POINTS did it rise? Answer as a number only.",
        acceptedAnswers: ["1", "1 percentage point", "one percentage point"],
        explanation: "1 percentage point. (The relative percent change is 25%; these are different units.)",
      },
    ],
  },
  {
    id: "negative-numbers-and-the-number-line-check",
    title: "Negative Numbers and the Number Line Check",
    description:
      "Quick checks on the number-line model, signed arithmetic, absolute value, and engineering interpretations of sign.",
    questions: [
      {
        id: "absolute-value",
        kind: "numeric",
        prompt: "Compute |-15|.",
        value: 15,
        tolerance: 0,
        explanation: "Absolute value is distance from zero — always nonnegative.",
      },
      {
        id: "compare-negatives",
        kind: "text",
        prompt: "Which is larger: -100 or -99? Answer with the number.",
        acceptedAnswers: ["-99", "negative 99", "minus 99"],
        explanation: "-99 is closer to zero, so it is greater. -100 is more negative (further left on the number line).",
      },
      {
        id: "subtract-negative",
        kind: "numeric",
        prompt: "Compute -3 - (-8).",
        value: 5,
        tolerance: 0,
        explanation: "Subtracting a negative is adding the positive: -3 - (-8) = -3 + 8 = 5.",
      },
      {
        id: "multiply-three-negatives",
        kind: "numeric",
        prompt: "Compute (-2)(-3)(-4).",
        value: -24,
        tolerance: 0,
        explanation: "Three negatives multiplied: odd number of negative factors gives a negative result. (-2)(-3) = 6, then 6 * (-4) = -24.",
      },
      {
        id: "negate-squared",
        kind: "numeric",
        prompt: "Compute -3^2 (no parentheses around the 3).",
        value: -9,
        tolerance: 0,
        explanation: "Exponent binds tighter than the unary minus: -3^2 = -(3^2) = -9. For +9, you would need (-3)^2.",
      },
      {
        id: "displacement",
        kind: "numeric",
        prompt: "A rover is at position -5 m and moves to +12 m. What is its displacement in meters?",
        value: 17,
        unit: "m",
        tolerance: 0,
        explanation: "Displacement = new - old = 12 - (-5) = 17 m.",
      },
      {
        id: "twos-complement-neg-one",
        kind: "text",
        prompt: "What is -1 in 8-bit two's complement binary?",
        acceptedAnswers: ["11111111", "1111 1111", "11111111b", "0xff", "0xFF"],
        explanation: "All bits set: 11111111. To verify: invert to 00000000, add 1 to get 1, negate to -1.",
      },
    ],
  },
  {
    id: "integer-exponents-and-rules-check",
    title: "Integer Exponents and Rules Check",
    description:
      "Quick checks on the seven laws of integer exponents, the zero and negative-exponent cases, and powers of two and ten.",
    questions: [
      {
        id: "product-rule",
        kind: "numeric",
        prompt: "Compute 2^3 * 2^7 (apply the product rule).",
        value: 1024,
        tolerance: 0,
        explanation: "Same base; exponents add: 2^(3+7) = 2^10 = 1024.",
      },
      {
        id: "quotient-rule",
        kind: "numeric",
        prompt: "Compute 5^9 / 5^4.",
        value: 3125,
        tolerance: 0,
        explanation: "Same base; exponents subtract: 5^(9-4) = 5^5 = 3125.",
      },
      {
        id: "power-rule",
        kind: "numeric",
        prompt: "Compute (3^2)^4.",
        value: 6561,
        tolerance: 0,
        explanation: "Power of a power; exponents multiply: 3^(2*4) = 3^8 = 6561.",
      },
      {
        id: "negative-exponent",
        kind: "text",
        prompt: "Compute 2^(-3). Give answer as a fraction or decimal.",
        acceptedAnswers: ["1/8", "0.125", "1 / 8", ".125"],
        explanation: "Negative exponent means reciprocal: 2^(-3) = 1/(2^3) = 1/8 = 0.125.",
      },
      {
        id: "zero-exponent",
        kind: "numeric",
        prompt: "Compute 73^0.",
        value: 1,
        tolerance: 0,
        explanation: "Any nonzero base to the zero power is 1. Forced by the quotient rule.",
      },
      {
        id: "neg-three-squared-vs",
        kind: "numeric",
        prompt: "Compute (-3)^2 (note the parentheses).",
        value: 9,
        tolerance: 0,
        explanation: "Parentheses include the negative: (-3)(-3) = 9.",
      },
      {
        id: "power-of-two-twenty",
        kind: "numeric",
        prompt: "Compute 2^20 (this is roughly one mega).",
        value: 1048576,
        tolerance: 0,
        explanation: "2^20 = (2^10)^2 = 1024^2 = 1,048,576. About 10^6 (mega).",
      },
    ],
  },
  {
    id: "roots-and-radicals-check",
    title: "Roots and Radicals Check",
    description:
      "Quick checks on principal square roots, higher roots, simplification, fractional exponents, and the Pythagorean theorem.",
    questions: [
      {
        id: "simple-sqrt",
        kind: "numeric",
        prompt: "Compute the principal square root of 144.",
        value: 12,
        tolerance: 0,
        explanation: "12^2 = 144, and the principal root is the nonnegative one.",
      },
      {
        id: "cube-root-neg",
        kind: "numeric",
        prompt: "Compute the cube root of -27.",
        value: -3,
        tolerance: 0,
        explanation: "(-3)^3 = -27. Odd roots of negative numbers are real.",
      },
      {
        id: "simplify-radical",
        kind: "text",
        prompt: "Simplify sqrt(72). Write as 'a sqrt b' or 'a*sqrt(b)', e.g., '6 sqrt 2'.",
        acceptedAnswers: ["6 sqrt 2", "6*sqrt(2)", "6sqrt(2)", "6 sqrt(2)", "6 root 2", "6 * sqrt 2"],
        explanation: "72 = 36 * 2 = 6^2 * 2. So sqrt(72) = 6 sqrt(2).",
      },
      {
        id: "fractional-exponent",
        kind: "numeric",
        prompt: "Compute 8^(2/3).",
        value: 4,
        tolerance: 0,
        explanation: "8^(2/3) = (cube root of 8)^2 = 2^2 = 4.",
      },
      {
        id: "negative-fractional-exponent",
        kind: "text",
        prompt: "Compute 16^(-1/2). Give answer as a fraction or decimal.",
        acceptedAnswers: ["1/4", "0.25", "1 / 4", ".25"],
        explanation: "16^(-1/2) = 1/16^(1/2) = 1/4 = 0.25.",
      },
      {
        id: "pythagorean",
        kind: "numeric",
        prompt: "A right triangle has legs of length 5 and 12. What is the length of the hypotenuse?",
        value: 13,
        tolerance: 0,
        explanation: "c = sqrt(5^2 + 12^2) = sqrt(25 + 144) = sqrt(169) = 13.",
      },
      {
        id: "sqrt-x-squared",
        kind: "text",
        prompt: "What is sqrt(x^2) for general real x? (Hint: it depends on the sign of x.)",
        acceptedAnswers: ["|x|", "abs(x)", "absolute value of x", "the absolute value of x"],
        explanation: "Because the square root function is always nonnegative, sqrt(x^2) = |x|, not just x.",
      },
    ],
  },
  {
    id: "scientific-notation-check",
    title: "Scientific Notation Check",
    description:
      "Quick checks on converting to and from scientific notation, arithmetic across orders of magnitude, SI prefixes, and order-of-magnitude estimation.",
    questions: [
      {
        id: "to-scientific",
        kind: "text",
        prompt: "Convert 0.000452 to normalized scientific notation. Write as '4.52e-4' or '4.52 x 10^-4'.",
        acceptedAnswers: ["4.52e-4", "4.52 x 10^-4", "4.52*10^-4", "4.52x10^-4", "4.52 x 10-4"],
        explanation: "First nonzero is 4. Place decimal: 4.52. Shift was 4 places left (negative): 4.52 x 10^-4.",
      },
      {
        id: "from-scientific",
        kind: "numeric",
        prompt: "Convert 3.5 x 10^4 to standard decimal.",
        value: 35000,
        tolerance: 0,
        explanation: "Shift the decimal in 3.5 four places right: 35000.",
      },
      {
        id: "multiply-scientific",
        kind: "text",
        prompt: "Compute (3 x 10^4) * (2 x 10^-7) in normalized scientific notation. Write as 'a e b'.",
        acceptedAnswers: ["6e-3", "6 e -3", "6 x 10^-3", "6*10^-3", "6x10^-3"],
        explanation: "Multiply coefficients: 3 * 2 = 6. Add exponents: 4 + (-7) = -3. Result: 6 x 10^-3.",
      },
      {
        id: "add-aligned-exponents",
        kind: "text",
        prompt: "Compute (7 x 10^4) + (3 x 10^2) in normalized scientific notation. Write as 'a e b'.",
        acceptedAnswers: ["7.03e4", "7.03 x 10^4", "7.03*10^4", "7.03x10^4"],
        explanation: "Align exponents: 3 x 10^2 = 0.03 x 10^4. Add: 7 + 0.03 = 7.03. Result: 7.03 x 10^4.",
      },
      {
        id: "si-prefix",
        kind: "text",
        prompt: "What SI prefix corresponds to 10^-6? Give the prefix name (e.g., 'kilo' for 10^3).",
        acceptedAnswers: ["micro", "µ", "u"],
        explanation: "10^-6 is the micro prefix, symbol µ (or 'u' in ASCII).",
      },
      {
        id: "order-of-magnitude",
        kind: "numeric",
        prompt: "What is the order of magnitude (the integer exponent in scientific notation) of 4.5 x 10^7?",
        value: 7,
        tolerance: 0,
        explanation: "In scientific notation 4.5 x 10^7, the exponent is 7, which is the order of magnitude.",
      },
      {
        id: "seconds-in-year",
        kind: "numeric",
        prompt: "Estimate the number of seconds in a year. Give your answer in scientific notation (just the exponent on a base 10 power, e.g., enter '7' if you estimate ~10^7).",
        value: 7,
        tolerance: 0,
        explanation: "365 * 24 * 3600 = 31,536,000 ≈ 3.15 x 10^7 s ≈ 10^7. Memorize: 'pi x 10^7 seconds in a year' is a famous mnemonic (since 3.15 ≈ pi).",
      },
    ],
  },
  {
    id: "gcd-lcm-and-prime-factorization-check",
    title: "GCD, LCM, and Prime Factorization Check",
    description:
      "Quick checks on prime factorization, GCD via Euclidean algorithm, LCM, and modular inverses.",
    questions: [
      {
        id: "factor-1260-power-of-3",
        kind: "numeric",
        prompt: "In the prime factorization of 1,260, what is the exponent on the prime 3?",
        value: 2,
        tolerance: 0,
        explanation: "1,260 = 2² · 3² · 5 · 7. The exponent on 3 is 2.",
      },
      {
        id: "gcd-of-72-and-120",
        kind: "numeric",
        prompt: "What is gcd(72, 120)?",
        value: 24,
        tolerance: 0,
        explanation: "72 = 2³·3², 120 = 2³·3·5. Common: 2³·3 = 24.",
      },
      {
        id: "lcm-of-72-and-120",
        kind: "numeric",
        prompt: "What is lcm(72, 120)?",
        value: 360,
        tolerance: 0,
        explanation: "Max exponents: 2³·3²·5 = 360. Check: gcd·lcm = 24·360 = 8640 = 72·120. ✓",
      },
      {
        id: "euclidean-1071-462",
        kind: "numeric",
        prompt: "Use the Euclidean algorithm to compute gcd(1071, 462).",
        value: 21,
        tolerance: 0,
        explanation: "1071 = 2·462 + 147; 462 = 3·147 + 21; 147 = 7·21. GCD = 21.",
      },
      {
        id: "coprime-15-22",
        kind: "text",
        prompt: "Are 15 and 22 coprime? Answer 'yes' or 'no'.",
        acceptedAnswers: ["yes", "yes they are", "yes they are coprime"],
        explanation: "15 = 3·5 and 22 = 2·11. No shared primes, so gcd = 1 and they are coprime.",
      },
      {
        id: "mod-inverse",
        kind: "numeric",
        prompt: "Find the multiplicative inverse of 3 modulo 7 (return a value between 1 and 6).",
        value: 5,
        tolerance: 0,
        explanation: "3 · 5 = 15 = 2·7 + 1, so 3·5 ≡ 1 (mod 7). The inverse is 5.",
      },
      {
        id: "lcm-blink",
        kind: "numeric",
        prompt: "Two LEDs blink every 7 and 9 seconds respectively. After how many seconds do they next blink together?",
        value: 63,
        tolerance: 0,
        explanation: "lcm(7, 9) = 63 since 7 and 9 are coprime.",
      },
    ],
  },
  {
    id: "significant-figures-and-uncertainty-check",
    title: "Significant Figures and Uncertainty Check",
    description:
      "Quick checks on counting sig figs, arithmetic with measured quantities, and propagating uncertainty in quadrature.",
    questions: [
      {
        id: "count-sig-figs-trailing-zeros",
        kind: "numeric",
        prompt: "How many significant figures are in 0.004500?",
        value: 4,
        tolerance: 0,
        explanation: "Leading zeros never count. The digits 4, 5, 0, 0 all count (trailing zeros after a decimal point are significant). 4 sig figs.",
      },
      {
        id: "count-sig-figs-scientific",
        kind: "numeric",
        prompt: "How many significant figures are in 3.20 x 10^5?",
        value: 3,
        tolerance: 0,
        explanation: "In scientific notation, every digit shown in the coefficient counts: 3, 2, 0 -> 3 sig figs.",
      },
      {
        id: "multiplication-keeps-fewest",
        kind: "text",
        prompt: "Compute 4.27 * 3.1 and report with the correct number of sig figs. (Format like '13' or '13.2'.)",
        acceptedAnswers: ["13", "13."],
        explanation: "4.27 has 3 sf, 3.1 has 2 sf. Multiplication keeps the fewest: 2 sf. 4.27*3.1 = 13.237 -> 13.",
      },
      {
        id: "addition-keeps-lowest-place",
        kind: "numeric",
        prompt: "Compute 27.31 + 4.1, reported to the correct decimal place. (Numeric, e.g., 31.4.)",
        value: 31.4,
        tolerance: 0.01,
        explanation: "Addition keeps the lowest decimal place. 27.31 has 2 decimal places, 4.1 has 1; result has 1 decimal place: 31.41 -> 31.4.",
      },
      {
        id: "propagate-quadrature-sum",
        kind: "numeric",
        prompt: "Two independent measurements have uncertainties sigma_x = 3 and sigma_y = 4. What is the propagated uncertainty for z = x + y (in quadrature)?",
        value: 5,
        tolerance: 0.01,
        explanation: "For independent sums, variances add: sigma_z = sqrt(3^2 + 4^2) = sqrt(25) = 5.",
      },
      {
        id: "propagate-relative-product",
        kind: "numeric",
        prompt: "Two independent measurements have relative uncertainties 0.02 and 0.03. What is the relative uncertainty of their product (in quadrature)? Give as a decimal to 4 places, e.g., 0.0361.",
        value: 0.0361,
        tolerance: 0.0005,
        explanation: "For products, relative uncertainties add in quadrature: sqrt(0.02^2 + 0.03^2) = sqrt(0.0004 + 0.0009) = sqrt(0.0013) ~ 0.0361.",
      },
      {
        id: "expanded-uncertainty",
        kind: "numeric",
        prompt: "A measurement has standard uncertainty u = 0.5 mV. What is the expanded uncertainty U at coverage factor k = 2?",
        value: 1.0,
        tolerance: 0.01,
        explanation: "U = k * u = 2 * 0.5 = 1.0 mV (covers approximately 95% under a normal model).",
      },
      {
        id: "round-half-to-even",
        kind: "numeric",
        prompt: "Round 2.5 to the nearest integer using banker's rounding (round-half-to-even).",
        value: 2,
        tolerance: 0,
        explanation: "Banker's rounding rounds 0.5 to the nearest EVEN integer. 2.5 -> 2 (not 3). This avoids the upward bias of always-round-up.",
      },
    ],
  },
  {
    id: "engineering-estimation-and-fermi-problems-check",
    title: "Engineering Estimation and Fermi Problems Check",
    description:
      "Quick checks on order-of-magnitude reasoning, geometric-mean bracketing, and chained Fermi estimates.",
    questions: [
      {
        id: "seconds-in-year-mnemonic",
        kind: "numeric",
        prompt: "What is the famous mnemonic for seconds in a year, expressed as pi times a power of ten? Give the exponent (e.g., enter 7 if the mnemonic is pi x 10^7).",
        value: 7,
        tolerance: 0,
        explanation: "pi x 10^7 s/year. The exact value is 3.156 x 10^7, and pi ~ 3.14, so the mnemonic is accurate to better than 1%.",
      },
      {
        id: "geomean-bracket",
        kind: "numeric",
        prompt: "You believe an unknown quantity is somewhere between 10 and 1000. What is the geometric-mean best-estimate? (numeric)",
        value: 100,
        tolerance: 1,
        explanation: "geomean(10, 1000) = sqrt(10 * 1000) = sqrt(10000) = 100. This is the right midpoint on a logarithmic scale.",
      },
      {
        id: "order-of-magnitude-7",
        kind: "numeric",
        prompt: "Round the number 7 to the nearest power of ten (i.e., is it closer to 10^0 = 1 or 10^1 = 10?). Give the exponent.",
        value: 1,
        tolerance: 0,
        explanation: "log10(7) ~ 0.85, so 7 is closer to 10^1 = 10 than to 10^0 = 1. Round to 10^1.",
      },
      {
        id: "piano-tuners-chicago",
        kind: "numeric",
        prompt: "Fermi: Chicago has ~3 million people, ~1 piano per 50 people, each tuned ~once per year, and a tuner can do ~1000 tunings per year. Estimate the number of piano tuners in Chicago.",
        value: 60,
        tolerance: 10,
        explanation: "Pianos: 3e6 / 50 = 6e4. Tunings per year: 6e4. Tuners: 6e4 / 1e3 = 60. The historical count was actually around 100, which Fermi-estimates accurately to within a factor of 2.",
      },
      {
        id: "log-error-random-walk",
        kind: "text",
        prompt: "If each of 4 estimated factors has log-error standard deviation of 0.3 decades, what is the approximate total log-error standard deviation? Give as a decimal (sqrt(n) * sigma).",
        acceptedAnswers: ["0.6", "0.60"],
        explanation: "Log-errors add in quadrature (random walk): sigma_total = sigma * sqrt(n) = 0.3 * sqrt(4) = 0.3 * 2 = 0.6 decades. So the final estimate is within ~10^0.6 ~ 4x of the truth.",
      },
      {
        id: "earth-circumference",
        kind: "numeric",
        prompt: "Earth's radius is approximately 6.4 x 10^6 m. Estimate Earth's circumference in meters, rounded to the nearest 10^7.",
        value: 40000000,
        tolerance: 5000000,
        explanation: "C = 2*pi*r = 2*pi*6.4e6 ~ 4.0 x 10^7 m = 40,000 km. Famous round number from the original definition of the meter (1/40,000,000 of a meridian).",
      },
      {
        id: "human-body-power",
        kind: "numeric",
        prompt: "Estimate the average power consumption of a resting human body in watts.",
        value: 100,
        tolerance: 30,
        explanation: "A typical adult consumes ~2000 kcal/day. 2000 kcal * 4184 J/kcal / 86400 s/day = 97 W ~ 100 W. This is the canonical 'human is a 100W appliance' Fermi number.",
      },
    ],
  },
  {
    id: "reading-data-tables-and-charts-check",
    title: "Reading Data Tables and Charts Check",
    description:
      "Quick checks on chart anatomy, log vs linear scales, Cleveland's perception hierarchy, and common chart deceptions.",
    questions: [
      {
        id: "cleveland-best-encoding",
        kind: "text",
        prompt: "According to Cleveland's perception hierarchy, what is the most accurately decoded visual encoding for a quantitative comparison? (one word)",
        acceptedAnswers: ["position", "position on common scale", "position on a common scale"],
        explanation: "Position on a common scale (e.g., bar height on a common baseline, point on a shared axis) is the most accurate. Length, angle, area, and color are progressively worse.",
      },
      {
        id: "log-scale-cue",
        kind: "text",
        prompt: "What visual cue tells you a chart's axis is logarithmic (not linear)? (short phrase)",
        acceptedAnswers: ["gridlines at powers of ten", "powers of ten", "powers of 10", "decade gridlines", "spacing by powers of ten", "logarithmic spacing", "unequal spacing"],
        explanation: "The gridlines are spaced by factors of 10 (or some other base), not by equal increments. Each 'decade' takes the same horizontal/vertical distance.",
      },
      {
        id: "truncated-axis-deception",
        kind: "text",
        prompt: "A bar chart's y-axis starts at 0.9 (not 0), making bar X look '2x taller' than bar Y when their actual values are 1.0 and 0.95. What is this deception called? (short phrase)",
        acceptedAnswers: ["truncated axis", "truncated y-axis", "truncated y axis", "broken axis", "y-axis truncation"],
        explanation: "A 'truncated y-axis' visually exaggerates small differences. The remedy is to start bar charts at zero unless the deviation from zero is itself the story.",
      },
      {
        id: "pie-chart-limit",
        kind: "text",
        prompt: "Roughly above how many categories should you prefer a sorted bar chart to a pie chart? (numeric or short phrase)",
        acceptedAnswers: ["4", "five", "5", "four", "more than 4", "more than four"],
        explanation: "Above ~4-5 slices, the eye cannot reliably compare slice angles. A sorted bar chart preserves order and uses position-on-a-common-scale (the strongest encoding).",
      },
      {
        id: "best-graphic-ever",
        kind: "text",
        prompt: "Which 1869 statistical graphic, depicting Napoleon's 1812 Russian campaign, is often called the best statistical graphic ever made? Give the cartographer's last name.",
        acceptedAnswers: ["minard", "Minard", "charles minard", "Charles Minard"],
        explanation: "Charles Joseph Minard's flow-map of Napoleon's losses in the 1812 Russian campaign. Tufte called it 'probably the best statistical graphic ever drawn.'",
      },
      {
        id: "tufte-data-ink",
        kind: "text",
        prompt: "What term, coined by Edward Tufte, refers to the proportion of a chart's ink that conveys actual data (vs decoration)? (two words)",
        acceptedAnswers: ["data-ink ratio", "data ink ratio", "data-ink"],
        explanation: "Tufte's 'data-ink ratio' (from *The Visual Display of Quantitative Information*, 1983). Maximize data ink; minimize chartjunk.",
      },
    ],
  },
  {
    id: "basic-probability-intuition-check",
    title: "Basic Probability Intuition Check",
    description:
      "Quick checks on equally-likely outcomes, addition and multiplication rules, conditional probability, and Bayes' rule.",
    questions: [
      {
        id: "two-coins-both-heads",
        kind: "numeric",
        prompt: "Flip two fair coins. What is the probability both show heads? (Decimal, e.g., 0.25.)",
        value: 0.25,
        tolerance: 0.001,
        explanation: "P(HH) = 1/2 * 1/2 = 1/4 = 0.25. Coin flips are independent, so probabilities multiply.",
      },
      {
        id: "at-least-one-head-three-flips",
        kind: "numeric",
        prompt: "Flip three fair coins. What is the probability of AT LEAST one head? (Decimal to 3 places.)",
        value: 0.875,
        tolerance: 0.001,
        explanation: "Use complement: P(no heads) = (1/2)^3 = 1/8. P(at least one) = 1 - 1/8 = 7/8 = 0.875.",
      },
      {
        id: "die-roll-even-or-prime",
        kind: "numeric",
        prompt: "Roll a fair 6-sided die. What is P(even OR prime)? (Decimal.) Hint: primes on a die are 2, 3, 5.",
        value: 0.8333,
        tolerance: 0.005,
        explanation: "Even = {2,4,6}, prime = {2,3,5}, intersection = {2}. P(even) + P(prime) - P(both) = 3/6 + 3/6 - 1/6 = 5/6 ~ 0.833.",
      },
      {
        id: "conditional-aces",
        kind: "numeric",
        prompt: "Shuffle a standard 52-card deck. Draw 2 cards without replacement. What is the probability both are aces? Give as a decimal to 5 places.",
        value: 0.00452,
        tolerance: 0.00005,
        explanation: "P(A1) = 4/52 = 1/13. P(A2 | A1) = 3/51 = 1/17. Product: 1/13 * 1/17 = 1/221 ~ 0.00452.",
      },
      {
        id: "bayes-medical-test",
        kind: "numeric",
        prompt: "Disease prevalence is 1%. Test has 99% sensitivity (P(+|D)) and 95% specificity (P(-|H), so P(+|H)=5%). Given a positive test, what is P(disease)? (Decimal, 2-3 places.)",
        value: 0.167,
        tolerance: 0.01,
        explanation: "P(+) = 0.99*0.01 + 0.05*0.99 = 0.0099 + 0.0495 = 0.0594. P(D|+) = 0.99*0.01 / 0.0594 ~ 0.167. The base rate (1% prevalence) dominates the sensitivity.",
      },
      {
        id: "monty-hall-switch",
        kind: "numeric",
        prompt: "In the classic 3-door Monty Hall problem, what is the probability of winning the car by ALWAYS switching after Monty reveals a goat? (Decimal to 3 places.)",
        value: 0.667,
        tolerance: 0.005,
        explanation: "Switching wins iff your initial pick was wrong, which happens with probability 2/3. So P(win | switch) = 2/3 ~ 0.667. Staying wins only 1/3 of the time.",
      },
      {
        id: "series-reliability",
        kind: "numeric",
        prompt: "Three independent components in SERIES each have reliability 0.99. What is the overall system reliability? (Decimal to 4 places.)",
        value: 0.9703,
        tolerance: 0.0005,
        explanation: "Series: all must work. R_total = 0.99^3 = 0.970299 ~ 0.9703.",
      },
      {
        id: "complement",
        kind: "numeric",
        prompt: "If P(A) = 0.7, what is P(A^c) (the complement)?",
        value: 0.3,
        tolerance: 0.001,
        explanation: "P(A^c) = 1 - P(A) = 1 - 0.7 = 0.3.",
      },
    ],
  },
  {
    id: "basic-statistics-mean-median-mode-check",
    title: "Basic Statistics Check",
    description:
      "Quick checks on measures of center, variance and standard deviation, percentiles, the 68-95-99.7 rule, and Z-scores.",
    questions: [
      {
        id: "mean-of-six",
        kind: "numeric",
        prompt: "Compute the mean of the dataset {2, 4, 4, 4, 5, 5, 7, 9}.",
        value: 5,
        tolerance: 0.001,
        explanation: "Sum = 40. n = 8. Mean = 40/8 = 5.",
      },
      {
        id: "median-of-six",
        kind: "numeric",
        prompt: "Compute the median of the dataset {2, 4, 4, 4, 5, 5, 7, 9}.",
        value: 4.5,
        tolerance: 0.001,
        explanation: "n = 8 is even, so median is the average of the 4th and 5th values when sorted: (4 + 5) / 2 = 4.5.",
      },
      {
        id: "mode-of-six",
        kind: "numeric",
        prompt: "Compute the mode of the dataset {2, 4, 4, 4, 5, 5, 7, 9}.",
        value: 4,
        tolerance: 0,
        explanation: "4 appears 3 times, more than any other value. Mode = 4.",
      },
      {
        id: "population-sd-classic",
        kind: "numeric",
        prompt: "Compute the POPULATION standard deviation of {2, 4, 4, 4, 5, 5, 7, 9} (divide by N=8, not n-1).",
        value: 2,
        tolerance: 0.01,
        explanation: "Deviations from mean=5: -3,-1,-1,-1,0,0,2,4. Squared: 9,1,1,1,0,0,4,16 -> sum=32. Variance = 32/8 = 4. SD = sqrt(4) = 2.",
      },
      {
        id: "bessel-correction",
        kind: "text",
        prompt: "Why does the SAMPLE variance formula divide by n-1 instead of n? (One-word answer.)",
        acceptedAnswers: ["bessel", "Bessel", "bessel's correction", "unbiased", "unbiasedness", "degrees-of-freedom", "degrees of freedom"],
        explanation: "Bessel's correction (n-1 'degrees of freedom') makes the sample variance an UNBIASED estimator of the population variance. Dividing by n would systematically underestimate.",
      },
      {
        id: "iq-above-130",
        kind: "numeric",
        prompt: "IQ scores have mean 100 and SD 15. Approximately what fraction of people have IQ > 130 (i.e., > 2 SDs above the mean)? Use the 68-95-99.7 rule. Give as a decimal.",
        value: 0.025,
        tolerance: 0.005,
        explanation: "95% lie within 2 SDs, so 5% lie outside. By symmetry, 2.5% are above +2sigma. So P(IQ > 130) ~ 0.025 = 2.5%.",
      },
      {
        id: "z-score",
        kind: "numeric",
        prompt: "A measurement is x = 73 from a distribution with mu = 60 and sigma = 10. Compute the Z-score.",
        value: 1.3,
        tolerance: 0.01,
        explanation: "z = (x - mu)/sigma = (73 - 60)/10 = 1.3. The measurement is 1.3 standard deviations above the mean.",
      },
      {
        id: "iqr",
        kind: "numeric",
        prompt: "A dataset has Q1 = 12 and Q3 = 27. What is the interquartile range (IQR)?",
        value: 15,
        tolerance: 0,
        explanation: "IQR = Q3 - Q1 = 27 - 12 = 15. By the 1.5*IQR rule, outliers fall below Q1 - 22.5 = -10.5 or above Q3 + 22.5 = 49.5.",
      },
    ],
  },
  {
    id: "solving-multi-step-linear-equations-check",
    title: "Solving Multi-Step Linear Equations Check",
    description:
      "Quick checks on combining like terms, the distributive property, and the four-step isolation discipline.",
    questions: [
      {
        id: "combine-like-terms",
        kind: "numeric",
        prompt: "Simplify 3x + 5x - 4 = 12. What is x?",
        value: 2,
        tolerance: 0.001,
        explanation: "Combine like terms: 8x - 4 = 12. Add 4: 8x = 16. Divide by 8: x = 2.",
      },
      {
        id: "distribute-first",
        kind: "numeric",
        prompt: "Solve 2(x + 3) - 5 = 11. What is x?",
        value: 5,
        tolerance: 0.001,
        explanation: "Distribute: 2x + 6 - 5 = 11 -> 2x + 1 = 11. Subtract 1: 2x = 10. Divide by 2: x = 5.",
      },
      {
        id: "distribute-combine",
        kind: "numeric",
        prompt: "Solve 4(x - 2) + 3x = 27. What is x?",
        value: 5,
        tolerance: 0.001,
        explanation: "Distribute: 4x - 8 + 3x = 27. Combine: 7x - 8 = 27. Add 8: 7x = 35. Divide by 7: x = 5.",
      },
      {
        id: "negative-distribution",
        kind: "text",
        prompt: "Expand -(x - 3). Write the simplified expression (e.g., '-x + 3' or '3 - x').",
        acceptedAnswers: ["-x + 3", "3 - x", "-x+3", "3-x", "-1*x + 3", "-1x+3"],
        explanation: "Distributing -1 across (x - 3) gives -x + 3 (NOT -x - 3 -- the minus sign flips both terms).",
      },
      {
        id: "kvl-current",
        kind: "numeric",
        prompt: "Kirchhoff's voltage law for a series circuit: 10*I + 20*I + 30*I = 12 V. Solve for I in amperes (decimal).",
        value: 0.2,
        tolerance: 0.005,
        explanation: "Combine like terms: 60*I = 12. Divide by 60: I = 0.2 A. Units check: V / Ohm = A.",
      },
      {
        id: "verification-discipline",
        kind: "text",
        prompt: "After solving a multi-step equation, what is the final discipline that catches arithmetic mistakes? (one or two words)",
        acceptedAnswers: ["check", "checking", "verify", "verification", "substitution", "back-substitution", "back substitution", "substitute back"],
        explanation: "Back-substitution: plug your solution into the ORIGINAL equation and verify both sides equal. This catches sign flips and arithmetic errors.",
      },
      {
        id: "multi-distribute-challenge",
        kind: "numeric",
        prompt: "Solve 3(2x + 4) - 2(x - 1) = 5(x + 3). What is x?",
        value: -1,
        tolerance: 0.001,
        explanation: "Distribute: 6x + 12 - 2x + 2 = 5x + 15. Combine: 4x + 14 = 5x + 15. Subtract 4x: 14 = x + 15. Subtract 15: x = -1.",
      },
    ],
  },
  {
    id: "equations-with-variables-on-both-sides-check",
    title: "Equations with Variables on Both Sides Check",
    description:
      "Quick checks on collecting variable terms, clearing fractions and decimals, and recognizing identities vs no-solution equations.",
    questions: [
      {
        id: "collect-and-solve",
        kind: "numeric",
        prompt: "Solve 5x - 3 = 2x + 9 for x.",
        value: 4,
        tolerance: 0.001,
        explanation: "Subtract 2x from both sides: 3x - 3 = 9. Add 3: 3x = 12. Divide: x = 4.",
      },
      {
        id: "negative-coefficient-strategy",
        kind: "numeric",
        prompt: "Solve 7 - 4x = 2x + 1 for x.",
        value: 1,
        tolerance: 0.001,
        explanation: "Add 4x to BOTH sides (to make the variable coefficient positive): 7 = 6x + 1. Subtract 1: 6 = 6x. Divide: x = 1.",
      },
      {
        id: "clear-fractions-lcd",
        kind: "numeric",
        prompt: "Solve (x + 2)/3 = (x - 1)/4 by clearing fractions (multiply both sides by LCD = 12). What is x?",
        value: -11,
        tolerance: 0.001,
        explanation: "Multiply by 12: 4(x + 2) = 3(x - 1). Distribute: 4x + 8 = 3x - 3. Subtract 3x: x + 8 = -3. Subtract 8: x = -11.",
      },
      {
        id: "clear-decimals",
        kind: "numeric",
        prompt: "Solve 0.05x + 0.3 = 0.2x - 0.6 (clear decimals by multiplying by 100). What is x?",
        value: 6,
        tolerance: 0.01,
        explanation: "Multiply by 100: 5x + 30 = 20x - 60. Subtract 5x: 30 = 15x - 60. Add 60: 90 = 15x. Divide: x = 6.",
      },
      {
        id: "identity-recognition",
        kind: "text",
        prompt: "An equation simplifies to '0 = 0' after all operations. How many solutions does it have? (one word, e.g., 'one', 'none', 'infinite', or 'all')",
        acceptedAnswers: ["infinite", "infinitely many", "all", "all reals", "all real numbers", "infinite many", "all values"],
        explanation: "An identity has infinitely many solutions -- every real number satisfies it. The equation is a tautology.",
      },
      {
        id: "no-solution-recognition",
        kind: "text",
        prompt: "An equation simplifies to '5 = 7'. How many solutions does it have? (one word)",
        acceptedAnswers: ["none", "zero", "no solution", "no solutions", "0"],
        explanation: "A contradiction has NO solutions -- the equation is false for every x.",
      },
      {
        id: "parallel-resistors",
        kind: "numeric",
        prompt: "Two resistors in parallel: 1/R = 1/R1 + 1/R2, with R = 6 ohms and R1 = 10 ohms. Solve for R2 in ohms.",
        value: 15,
        tolerance: 0.01,
        explanation: "1/6 = 1/10 + 1/R2. So 1/R2 = 1/6 - 1/10 = 5/30 - 3/30 = 2/30 = 1/15. Therefore R2 = 15 ohms.",
      },
      {
        id: "zero-one-infinite",
        kind: "numeric",
        prompt: "How many solutions can a single linear equation in one unknown have? Choose 0, 1, or 'infinite'. (Numeric: enter the number of FINITE solutions if unique, else enter 0 for none.)",
        value: 1,
        tolerance: 0,
        explanation: "A well-posed linear equation has exactly one solution. The other cases are degenerate: identity (infinite) and contradiction (none). This is the rank-nullity theorem at its baby level.",
      },
    ],
  },
  {
    id: "rearranging-engineering-formulas-check",
    title: "Rearranging Engineering Formulas Check",
    description:
      "Quick checks on symbolic rearrangement of physical formulas, reciprocals, square roots, and the units sanity habit.",
    questions: [
      {
        id: "ohms-law-for-I",
        kind: "text",
        prompt: "Rearrange V = IR to solve for I. Write the formula (e.g., 'I = V/R').",
        acceptedAnswers: ["I = V/R", "I=V/R", "V/R", "I = V / R"],
        explanation: "Divide both sides by R: I = V/R. Units check: V / Ohm = A.",
      },
      {
        id: "fma-for-m",
        kind: "text",
        prompt: "Rearrange F = ma to solve for m. Write the formula.",
        acceptedAnswers: ["m = F/a", "m=F/a", "F/a", "m = F / a"],
        explanation: "Divide both sides by a: m = F/a. Units check: N / (m/s^2) = kg.",
      },
      {
        id: "ohms-law-numerical",
        kind: "numeric",
        prompt: "A 5 V battery drives a 10 ohm resistor. What is the current in amperes?",
        value: 0.5,
        tolerance: 0.001,
        explanation: "I = V/R = 5 V / 10 Ohm = 0.5 A. Solve symbolically first, then substitute.",
      },
      {
        id: "kinetic-energy-for-v",
        kind: "numeric",
        prompt: "E = (1/2)m*v^2. With E = 100 J and m = 1 kg, what is v in m/s? (positive root)",
        value: 14.14,
        tolerance: 0.05,
        explanation: "Solve symbolically: v = sqrt(2E/m). Substitute: v = sqrt(200) ~ 14.14 m/s. Units: sqrt(J/kg) = sqrt(m^2/s^2) = m/s.",
      },
      {
        id: "letters-only-rule",
        kind: "text",
        prompt: "What discipline says you should solve symbolically before plugging in numbers? Give the phrase (e.g., 'letters only', 'symbolic first').",
        acceptedAnswers: ["letters only", "letters-only", "letters only rule", "letters-only rule", "symbolic first", "solve symbolically first", "solve symbolically"],
        explanation: "The 'letters-only' rule: keep symbols until the very last step, then substitute once. This avoids rounding errors, lets you re-use the result, and lets units catch mistakes.",
      },
      {
        id: "ideal-gas-for-T",
        kind: "text",
        prompt: "Rearrange PV = nRT to solve for T. Write the formula.",
        acceptedAnswers: ["T = PV/(nR)", "T = PV/nR", "T=PV/(nR)", "T=PV/nR", "PV/(nR)", "PV/nR"],
        explanation: "Divide both sides by nR: T = PV/(nR). Units check: (Pa*m^3) / (mol * J/(mol*K)) = K.",
      },
      {
        id: "square-root-caveat",
        kind: "text",
        prompt: "When you take the square root of both sides of an equation, what sign issue arises? (one or two words)",
        acceptedAnswers: ["plus-minus", "plus or minus", "+/-", "+-", "two roots", "both signs", "sign ambiguity", "positive and negative", "negative root", "extraneous"],
        explanation: "Square-rooting gives both a positive and negative root (+/-). In a physics problem you pick the one that's physical (e.g., positive speed).",
      },
      {
        id: "parallel-resistor-symbolic",
        kind: "text",
        prompt: "Rearrange 1/R = 1/R1 + 1/R2 to solve for R2. Write the symbolic answer (e.g., 'R2 = R*R1/(R1-R)').",
        acceptedAnswers: ["R2 = R*R1/(R1 - R)", "R2 = R*R1/(R1-R)", "R*R1/(R1 - R)", "R*R1/(R1-R)", "R2 = (R*R1)/(R1-R)", "R2=R*R1/(R1-R)"],
        explanation: "1/R2 = 1/R - 1/R1 = (R1 - R)/(R*R1). Take reciprocal: R2 = R*R1/(R1 - R).",
      },
    ],
  },
  {
    id: "word-problems-to-equations-check",
    title: "Word Problems to Equations Check",
    description:
      "Quick checks on the 5-step translation method (NAME-RELATE-SOLVE-CHECK-INTERPRET) and the translation dictionary.",
    questions: [
      {
        id: "three-more-than-twice",
        kind: "numeric",
        prompt: "Three more than twice a number is 17. What is the number?",
        value: 7,
        tolerance: 0,
        explanation: "Let x = the number. Translate: 2x + 3 = 17. Solve: 2x = 14, x = 7.",
      },
      {
        id: "five-less-than-twice",
        kind: "text",
        prompt: "Translate '5 less than twice x' into an algebraic expression.",
        acceptedAnswers: ["2x - 5", "2x-5", "-5 + 2x", "2*x - 5", "2*x-5"],
        explanation: "'5 less than A' means A - 5, NOT 5 - A. So '5 less than twice x' = 2x - 5. This is the #1 translation pitfall.",
      },
      {
        id: "polya-author",
        kind: "text",
        prompt: "Who wrote the canonical 1945 book 'How to Solve It' on problem-solving methodology?",
        acceptedAnswers: ["polya", "Polya", "Pólya", "george polya", "George Polya", "George Pólya"],
        explanation: "George Pólya (1887-1985), Hungarian-American mathematician. His 4-step method (understand, plan, carry out, look back) is the parent of the 5-step word-problem method.",
      },
      {
        id: "rectangle-perimeter",
        kind: "numeric",
        prompt: "A rectangle has perimeter 30 m and length 4 m more than width. Find the width in meters.",
        value: 5.5,
        tolerance: 0.05,
        explanation: "Let w = width (in m). Length = w + 4. Perimeter = 2w + 2(w+4) = 30. So 4w + 8 = 30, 4w = 22, w = 5.5 m.",
      },
      {
        id: "first-step-name",
        kind: "text",
        prompt: "What is the FIRST step of the 5-step word-problem method? (one word from NAME, RELATE, SOLVE, CHECK, INTERPRET)",
        acceptedAnswers: ["name", "NAME", "Name", "naming", "name the unknowns"],
        explanation: "Step 1: NAME each unknown with a letter AND its unit ('let v = drone speed in m/s'). Without this, every later step is shakier.",
      },
      {
        id: "kvl-device-resistance",
        kind: "numeric",
        prompt: "A 12 V battery powers two devices in series. Device A has 200 ohm resistance. Current is 30 mA. What is the resistance of device B in ohms?",
        value: 200,
        tolerance: 1,
        explanation: "V = I(R_A + R_B). 12 = 0.030*(200 + R_B). 400 = 200 + R_B. R_B = 200 ohms.",
      },
      {
        id: "drone-hover-time",
        kind: "numeric",
        prompt: "A drone consumes 100 W in hover; its battery stores 90 Wh; allow 20% reserve. How many minutes can it hover?",
        value: 43.2,
        tolerance: 0.5,
        explanation: "Usable energy = 0.80 * 90 Wh = 72 Wh. Time = 72 Wh / 100 W = 0.72 h = 43.2 min.",
      },
      {
        id: "saline-mixing",
        kind: "numeric",
        prompt: "How many liters of 10% saline must be added to 5 L of 30% saline to produce a 20% saline solution?",
        value: 5,
        tolerance: 0.05,
        explanation: "Let x = L of 10% saline added. Salt balance: 0.10*x + 0.30*5 = 0.20*(x + 5). 0.10*x + 1.5 = 0.20*x + 1. 0.5 = 0.10*x. x = 5 L.",
      },
    ],
  },
];

export function getLessonCheck(id: string) {
  return lessonChecks.find((check) => check.id === id);
}
