import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "coding-foundations";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const technicalPythonLessons: Lesson[] = [
  future(
    "technical-python",
    2,
    "python-introduction-and-setup",
    "Python Introduction and Setup",
    "Install Python and a working editor, run your first scripts, and understand the REPL and script execution models for engineering work.",
  ),
  future(
    "technical-python",
    3,
    "python-expressions-and-numeric-types",
    "Python Expressions and Numeric Types",
    "Integer, float, and complex types, arithmetic operators, and the precision gotchas every engineer hits when porting formulas to code.",
  ),
  future(
    "technical-python",
    4,
    "python-strings-and-formatting",
    "Python Strings and Formatting",
    "String literals, escape sequences, f-strings, format specifiers, and producing clean numeric output for engineering reports.",
  ),
  future(
    "technical-python",
    5,
    "python-booleans-and-comparisons",
    "Python Booleans and Comparisons",
    "Boolean values, comparison operators, truthiness rules, short-circuit evaluation, and writing readable predicates for control logic.",
  ),
  future(
    "technical-python",
    6,
    "python-variables-and-assignment",
    "Python Variables, Names, and Assignment",
    "Variable binding versus mutation, naming conventions, augmented assignment, and the mental model of references rather than boxes.",
  ),
  future(
    "technical-python",
    7,
    "python-control-flow-conditionals",
    "Control Flow: Conditionals",
    "If, elif, else statements, nested conditionals, conditional expressions, and writing branching logic without losing clarity.",
  ),
  future(
    "technical-python",
    8,
    "python-control-flow-loops",
    "Control Flow: While and For Loops",
    "While loops, for loops, range, break, continue, and choosing the right loop construct for iteration over engineering data.",
  ),
  future(
    "technical-python",
    9,
    "python-lists-and-sequences",
    "Lists and Sequence Operations",
    "Creating, indexing, slicing, and mutating lists; sequence protocol operations; and idioms for working with ordered collections.",
  ),
  future(
    "technical-python",
    10,
    "python-tuples-and-immutability",
    "Tuples and Immutability",
    "Tuples as immutable sequences, packing and unpacking, named tuples, and when immutability prevents bugs in scientific code.",
  ),
  future(
    "technical-python",
    11,
    "python-dictionaries-and-sets",
    "Dictionaries and Sets",
    "Dict and set semantics, hashing, lookups, common methods, and using these structures for configuration and deduplication.",
  ),
  future(
    "technical-python",
    12,
    "python-comprehensions",
    "List, Dict, and Set Comprehensions",
    "Comprehension syntax, when comprehensions beat explicit loops, nested comprehensions, and readability tradeoffs.",
  ),
  future(
    "technical-python",
    13,
    "python-functions-fundamentals",
    "Function Fundamentals",
    "Defining functions, positional and keyword arguments, default values, return values, and structuring small calculators as functions.",
    { prerequisites: ["python-functions-for-technical-tools"] },
  ),
  future(
    "technical-python",
    14,
    "python-function-scope-and-closures",
    "Function Scope and Closures",
    "Local, enclosing, global, and built-in scopes; the LEGB rule; closures; and why nested functions capture variables the way they do.",
  ),
  future(
    "technical-python",
    15,
    "python-lambdas-and-higher-order-functions",
    "Lambdas and Higher-Order Functions",
    "Lambda expressions, passing functions as arguments, map, filter, sorted with key functions, and functional patterns in engineering code.",
  ),
  future(
    "technical-python",
    16,
    "python-args-and-kwargs",
    "Variable Arguments: *args and **kwargs",
    "Variable-length positional and keyword arguments, argument unpacking, and writing flexible wrapper and adapter functions.",
  ),
  future(
    "technical-python",
    17,
    "python-modules-and-imports",
    "Modules and Imports",
    "Splitting code across files, the import system, absolute and relative imports, and avoiding circular import traps.",
  ),
  future(
    "technical-python",
    18,
    "python-packages-and-init",
    "Packages and __init__.py",
    "Building multi-file packages, __init__.py conventions, package layout standards, and structuring a small engineering tool as a package.",
    { prerequisites: ["python-modules-and-imports"] },
  ),
  future(
    "technical-python",
    19,
    "python-classes-and-objects",
    "Classes and Objects",
    "Defining classes, instance attributes, methods, the role of self, and modeling engineering concepts as objects.",
  ),
  future(
    "technical-python",
    20,
    "python-inheritance-and-polymorphism",
    "Inheritance and Polymorphism",
    "Class inheritance, method overriding, super(), multiple inheritance and the MRO, and when composition is the better tool.",
    { prerequisites: ["python-classes-and-objects"] },
  ),
  future(
    "technical-python",
    21,
    "python-dunder-methods-and-protocols",
    "Dunder Methods and Protocols",
    "Special methods like __repr__, __eq__, __add__, __iter__; implementing protocols so your objects integrate with Python idioms.",
    { prerequisites: ["python-classes-and-objects"] },
  ),
  future(
    "technical-python",
    22,
    "python-dataclasses-and-value-types",
    "Dataclasses and Value Types",
    "Using @dataclass to declare data-holding classes concisely, frozen dataclasses, and modeling engineering records cleanly.",
    { prerequisites: ["python-classes-and-objects"] },
  ),
  future(
    "technical-python",
    23,
    "python-exceptions-and-error-handling",
    "Exceptions and Error Handling",
    "Try/except/else/finally, raising exceptions, custom exception classes, and writing engineering scripts that fail loudly and informatively.",
  ),
  future(
    "technical-python",
    24,
    "python-file-io-and-paths",
    "File I/O and Pathlib",
    "Reading and writing text and binary files, the with-statement, and using pathlib for portable filesystem code in data pipelines.",
  ),
  future(
    "technical-python",
    25,
    "python-csv-and-json",
    "CSV and JSON Data Handling",
    "Parsing and writing CSV and JSON files with the standard library, handling edge cases, and bridging Python with engineering data formats.",
    { prerequisites: ["python-file-io-and-paths"] },
  ),
  future(
    "technical-python",
    26,
    "python-iterators-and-generators",
    "Iterators and Generators",
    "The iterator protocol, generator functions, yield, generator expressions, and lazy evaluation for streaming data and infinite sequences.",
  ),
  future(
    "technical-python",
    27,
    "python-context-managers",
    "Context Managers and the with Statement",
    "Writing custom context managers with __enter__/__exit__ and contextlib, and using them to manage files, locks, and hardware sessions.",
  ),
  future(
    "technical-python",
    28,
    "python-decorators",
    "Decorators",
    "Functions as values, writing decorators, functools.wraps, parameterized decorators, and using them for logging, caching, and timing.",
    { prerequisites: ["python-function-scope-and-closures"] },
  ),
  future(
    "technical-python",
    29,
    "python-virtual-environments-and-pip",
    "Virtual Environments and pip",
    "Creating isolated environments with venv, installing packages with pip, requirements files, and avoiding the dependency soup of global installs.",
  ),
  future(
    "technical-python",
    30,
    "python-type-hints-and-mypy",
    "Type Hints and Static Checking",
    "Type annotations, the typing module, generics, Optional and Union, and using mypy to catch errors before they reach the robot.",
  ),
  future(
    "technical-python",
    31,
    "python-testing-debugging-and-tooling",
    "Testing, Debugging, and Project Tooling",
    "Writing pytest tests, using pdb to step through code, formatters and linters, and packaging a small Python tool with pyproject.toml.",
  ),
];

const dataStructuresAndAlgorithmsLessons: Lesson[] = [
  future(
    "data-structures-and-algorithms",
    1,
    "algorithmic-thinking-and-problem-solving",
    "Algorithmic Thinking and Problem Solving",
    "A framework for analyzing problems, identifying input-output structure, and breaking computational tasks into precise steps.",
  ),
  future(
    "data-structures-and-algorithms",
    2,
    "big-o-and-asymptotic-analysis",
    "Big-O and Asymptotic Analysis",
    "Big-O, Big-Omega, and Big-Theta notation, asymptotic comparison of functions, and reasoning about scaling rather than constants.",
  ),
  future(
    "data-structures-and-algorithms",
    3,
    "time-and-space-complexity",
    "Time and Space Complexity",
    "Counting operations and memory, analyzing nested loops and recursive calls, and amortized analysis for dynamic structures.",
    { prerequisites: ["big-o-and-asymptotic-analysis"] },
  ),
  future(
    "data-structures-and-algorithms",
    4,
    "arrays-and-dynamic-arrays",
    "Arrays and Dynamic Arrays",
    "Static and dynamic arrays, contiguous memory, amortized append, and why arrays remain the workhorse of high-performance code.",
  ),
  future(
    "data-structures-and-algorithms",
    5,
    "linked-lists-singly-and-doubly",
    "Linked Lists: Singly and Doubly",
    "Node-based linked structures, insertion and deletion at both ends, and the tradeoffs versus arrays for cache locality.",
  ),
  future(
    "data-structures-and-algorithms",
    6,
    "stacks-and-queues",
    "Stacks and Queues",
    "LIFO and FIFO disciplines, array and linked-list implementations, and using them for parsing, scheduling, and traversal.",
  ),
  future(
    "data-structures-and-algorithms",
    7,
    "deques-and-priority-queues",
    "Deques and Priority Queues",
    "Double-ended queues, priority queues backed by heaps, and choosing the right queue discipline for event-driven systems.",
  ),
  future(
    "data-structures-and-algorithms",
    8,
    "hash-tables-and-hash-functions",
    "Hash Tables and Hash Functions",
    "Hashing, collision resolution by chaining and open addressing, load factors, and expected versus worst-case performance.",
  ),
  future(
    "data-structures-and-algorithms",
    9,
    "sets-and-multisets",
    "Sets and Multisets",
    "Set abstract data types, set operations (union, intersection, difference), and multiset/bag variants used in counting problems.",
    { prerequisites: ["hash-tables-and-hash-functions"] },
  ),
  future(
    "data-structures-and-algorithms",
    10,
    "recursion-and-call-stacks",
    "Recursion and Call Stacks",
    "Writing recursive functions, base cases and recursive cases, how the call stack works, and converting between recursion and iteration.",
  ),
  future(
    "data-structures-and-algorithms",
    11,
    "trees-and-binary-trees",
    "Trees and Binary Trees",
    "Tree terminology, binary trees, tree traversals (preorder, inorder, postorder), and recursive tree algorithms.",
  ),
  future(
    "data-structures-and-algorithms",
    12,
    "binary-search-trees",
    "Binary Search Trees",
    "BST invariants, search/insert/delete operations, in-order traversal yielding sorted order, and degenerate-tree pitfalls.",
    { prerequisites: ["trees-and-binary-trees"] },
  ),
  future(
    "data-structures-and-algorithms",
    13,
    "balanced-trees-avl-and-red-black",
    "Balanced Trees: AVL and Red-Black",
    "Self-balancing tree invariants, rotations, and why production map/set implementations use balanced trees under the hood.",
    { prerequisites: ["binary-search-trees"] },
  ),
  future(
    "data-structures-and-algorithms",
    14,
    "heaps-and-binary-heap",
    "Heaps and the Binary Heap",
    "Max-heap and min-heap properties, array-backed binary heaps, sift-up and sift-down operations, and heap construction.",
  ),
  future(
    "data-structures-and-algorithms",
    15,
    "graphs-representations",
    "Graphs and Graph Representations",
    "Directed and undirected graphs, adjacency lists versus adjacency matrices, and choosing the right representation for the problem.",
  ),
  future(
    "data-structures-and-algorithms",
    16,
    "graph-traversal-bfs-and-dfs",
    "Graph Traversal: BFS and DFS",
    "Breadth-first and depth-first search, iterative and recursive forms, and using traversals to discover connectivity and reachability.",
    { prerequisites: ["graphs-representations"] },
  ),
  future(
    "data-structures-and-algorithms",
    17,
    "shortest-paths-dijkstra-and-bellman-ford",
    "Shortest Paths: Dijkstra and Bellman-Ford",
    "Single-source shortest-path algorithms for weighted graphs, negative edges, and choosing the right algorithm for the input.",
    { prerequisites: ["graph-traversal-bfs-and-dfs"] },
  ),
  future(
    "data-structures-and-algorithms",
    18,
    "elementary-sorting-algorithms",
    "Elementary Sorting Algorithms",
    "Insertion sort, selection sort, and bubble sort; correctness, complexity, and when these still beat fancier algorithms.",
  ),
  future(
    "data-structures-and-algorithms",
    19,
    "merge-sort-and-quick-sort",
    "Merge Sort and Quick Sort",
    "Two cornerstone divide-and-conquer sorts, their recurrences and average-case analysis, and pivot strategies for quicksort.",
  ),
  future(
    "data-structures-and-algorithms",
    20,
    "heap-sort-and-non-comparison-sorts",
    "Heap Sort and Non-Comparison Sorts",
    "Heap sort via the binary heap, the comparison-sort lower bound, and counting/radix/bucket sorts for restricted inputs.",
    { prerequisites: ["heaps-and-binary-heap"] },
  ),
  future(
    "data-structures-and-algorithms",
    21,
    "binary-search-and-search-techniques",
    "Binary Search and Search Techniques",
    "Binary search on sorted arrays, the off-by-one minefield, binary search on the answer, and using search to convert decision into optimization.",
  ),
  future(
    "data-structures-and-algorithms",
    22,
    "divide-and-conquer",
    "Divide-and-Conquer Strategy",
    "The general divide-and-conquer pattern, the master theorem for recurrences, and applications beyond sorting.",
    { prerequisites: ["merge-sort-and-quick-sort"] },
  ),
  future(
    "data-structures-and-algorithms",
    23,
    "dynamic-programming-fundamentals",
    "Dynamic Programming Fundamentals",
    "Optimal substructure and overlapping subproblems, memoization versus tabulation, and the discipline of defining DP states.",
  ),
  future(
    "data-structures-and-algorithms",
    24,
    "greedy-algorithms",
    "Greedy Algorithms",
    "Greedy choice property, proving correctness by exchange arguments, and when greedy fails versus when it is provably optimal.",
  ),
  future(
    "data-structures-and-algorithms",
    25,
    "complexity-classes-p-np-and-beyond",
    "Complexity Classes: P, NP, and Beyond",
    "Decision versus optimization problems, P, NP, NP-completeness via reduction, and recognizing intractable problems in engineering.",
  ),
];

const numericalAndScientificPythonLessons: Lesson[] = [
  future(
    "numerical-and-scientific-python",
    1,
    "numpy-arrays-and-dtypes",
    "NumPy Arrays and dtypes",
    "Creating ndarrays, dtypes and memory layout, the difference between Python lists and NumPy arrays, and shape and strides.",
  ),
  future(
    "numerical-and-scientific-python",
    2,
    "numpy-indexing-and-slicing",
    "NumPy Indexing and Slicing",
    "Basic slicing, fancy indexing, boolean masks, views versus copies, and the subtle aliasing rules that bite scientific code.",
    { prerequisites: ["numpy-arrays-and-dtypes"] },
  ),
  future(
    "numerical-and-scientific-python",
    3,
    "numpy-broadcasting",
    "NumPy Broadcasting",
    "The broadcasting rules, how shapes align, axis insertion with None, and writing vectorized expressions that scale with array size.",
    { prerequisites: ["numpy-arrays-and-dtypes"] },
  ),
  future(
    "numerical-and-scientific-python",
    4,
    "numpy-universal-functions",
    "NumPy Universal Functions",
    "ufuncs, element-wise operations, reductions (sum, mean, max), accumulations, and choosing operations that stay in C.",
  ),
  future(
    "numerical-and-scientific-python",
    5,
    "numpy-linear-algebra",
    "Linear Algebra with NumPy",
    "Matrix multiplication with @, np.linalg routines for solve, inverse, eig, svd, and the conventions for vectors versus matrices.",
  ),
  future(
    "numerical-and-scientific-python",
    6,
    "numpy-random-and-sampling",
    "NumPy Random Numbers and Sampling",
    "The new Generator API, seeding for reproducibility, sampling from common distributions, and Monte Carlo experiments.",
  ),
  future(
    "numerical-and-scientific-python",
    7,
    "vectorization-versus-loops",
    "Vectorization Versus Python Loops",
    "Why Python loops are slow, rewriting iterative code as array operations, and recognizing patterns that vectorize cleanly.",
    { prerequisites: ["numpy-broadcasting"] },
  ),
  future(
    "numerical-and-scientific-python",
    8,
    "numerical-precision-and-pitfalls",
    "Numerical Precision and Pitfalls",
    "IEEE 754 floats, cancellation, catastrophic loss of precision, and the patterns that produce silently wrong scientific results.",
  ),
  future(
    "numerical-and-scientific-python",
    9,
    "scipy-overview-and-modules",
    "SciPy Overview and Module Map",
    "A tour of SciPy submodules: optimize, integrate, interpolate, signal, sparse, stats, and how they fit together.",
    { prerequisites: ["numpy-arrays-and-dtypes"] },
  ),
  future(
    "numerical-and-scientific-python",
    10,
    "scipy-optimization",
    "Optimization with SciPy",
    "scipy.optimize for root finding and minimization, choosing methods, providing gradients, and constrained optimization basics.",
  ),
  future(
    "numerical-and-scientific-python",
    11,
    "scipy-integration-and-odes",
    "Integration and ODEs with SciPy",
    "Quadrature with scipy.integrate, initial value problem solvers, choosing solver tolerances, and validating numerical solutions.",
  ),
  future(
    "numerical-and-scientific-python",
    12,
    "scipy-signal-processing-basics",
    "Signal Processing with SciPy",
    "scipy.signal for filtering, FFTs, convolution, and basic spectral analysis on sensor and audio data.",
  ),
  future(
    "numerical-and-scientific-python",
    13,
    "pandas-series-and-dataframes",
    "pandas Series and DataFrames",
    "The Series and DataFrame data structures, indexes, dtypes, and the mental model that pandas is NumPy plus labels.",
  ),
  future(
    "numerical-and-scientific-python",
    14,
    "pandas-indexing-and-selection",
    "pandas Indexing and Selection",
    "loc and iloc, boolean indexing, MultiIndex basics, and avoiding chained-assignment surprises.",
    { prerequisites: ["pandas-series-and-dataframes"] },
  ),
  future(
    "numerical-and-scientific-python",
    15,
    "pandas-data-cleaning-and-reshaping",
    "Data Cleaning and Reshaping with pandas",
    "Missing values, type coercion, dropping and filling, merge/join, and pivot/melt for reshaping engineering datasets.",
    { prerequisites: ["pandas-series-and-dataframes"] },
  ),
  future(
    "numerical-and-scientific-python",
    16,
    "pandas-groupby-and-aggregation",
    "GroupBy and Aggregation",
    "The split-apply-combine pattern, groupby with named aggregations, transform versus apply, and time-aware grouping.",
    { prerequisites: ["pandas-series-and-dataframes"] },
  ),
  future(
    "numerical-and-scientific-python",
    17,
    "matplotlib-fundamentals",
    "Matplotlib Fundamentals",
    "The Figure/Axes object model, pyplot versus object-oriented API, and producing publication-quality static plots.",
  ),
  future(
    "numerical-and-scientific-python",
    18,
    "matplotlib-plot-types-and-conventions",
    "Plot Types and Scientific Plotting Conventions",
    "Line, scatter, bar, histogram, contour, and image plots; axis scales; and the conventions of clear engineering figures.",
    { prerequisites: ["matplotlib-fundamentals"] },
  ),
  future(
    "numerical-and-scientific-python",
    19,
    "performance-profiling-of-numerical-code",
    "Profiling Numerical Code",
    "Timing with %timeit, line profilers, identifying hotspots in array code, and reasoning about memory bandwidth and cache behavior.",
  ),
  future(
    "numerical-and-scientific-python",
    20,
    "numba-cython-and-going-faster",
    "Numba, Cython, and Going Faster",
    "When NumPy alone is not enough, accelerating hot loops with Numba JIT or Cython, and interfacing with compiled libraries.",
    { prerequisites: ["vectorization-versus-loops"] },
  ),
];

const softwareEngineeringPracticeLessons: Lesson[] = [
  future(
    "software-engineering-practice",
    1,
    "git-fundamentals",
    "Git Fundamentals",
    "The repository, working tree, and index; init, add, commit, status, log, and diff; and the mental model behind Git's content storage.",
  ),
  future(
    "software-engineering-practice",
    2,
    "git-branching-and-merging",
    "Git Branching and Merging",
    "Branches as movable pointers, fast-forward versus three-way merges, resolving conflicts, and the standard feature-branch workflow.",
    { prerequisites: ["git-fundamentals"] },
  ),
  future(
    "software-engineering-practice",
    3,
    "git-remotes-and-collaboration",
    "Git Remotes and Collaboration",
    "Working with remotes, push and pull, pull requests on GitHub or GitLab, code review etiquette, and rebasing versus merging in teams.",
    { prerequisites: ["git-branching-and-merging"] },
  ),
  future(
    "software-engineering-practice",
    4,
    "unit-testing-with-pytest",
    "Unit Testing with pytest",
    "Writing your first pytest tests, assert idioms, parametrization, fixtures, and the discipline of test-driven engineering code.",
  ),
  future(
    "software-engineering-practice",
    5,
    "test-doubles-mocks-and-fakes",
    "Test Doubles: Mocks, Stubs, and Fakes",
    "Isolating units under test, using unittest.mock and pytest-mock, and choosing between mocks, stubs, fakes, and real dependencies.",
    { prerequisites: ["unit-testing-with-pytest"] },
  ),
  future(
    "software-engineering-practice",
    6,
    "integration-and-end-to-end-tests",
    "Integration and End-to-End Tests",
    "Beyond unit tests: integration tests across modules, end-to-end tests across services, and the test pyramid for engineering systems.",
    { prerequisites: ["unit-testing-with-pytest"] },
  ),
  future(
    "software-engineering-practice",
    7,
    "debugging-with-pdb-and-print",
    "Debugging with pdb and Print",
    "Strategic prints, the pdb/breakpoint() workflow, IDE debuggers, and a methodology for narrowing bugs from symptoms to causes.",
  ),
  future(
    "software-engineering-practice",
    8,
    "profiling-python-programs",
    "Profiling Python Programs",
    "cProfile, snakeviz, line_profiler, and memory_profiler; reading their output; and finding the real bottleneck before optimizing.",
  ),
  future(
    "software-engineering-practice",
    9,
    "logging-and-observability",
    "Logging and Observability",
    "Replacing print debugging with structured logging, log levels, configuring handlers, and basic observability for long-running scripts.",
  ),
  future(
    "software-engineering-practice",
    10,
    "packaging-python-projects",
    "Packaging Python Projects",
    "pyproject.toml, build backends, building wheels and source distributions, and publishing internal or open-source packages.",
  ),
  future(
    "software-engineering-practice",
    11,
    "dependency-management-and-lockfiles",
    "Dependency Management and Lockfiles",
    "Requirements files, pip-tools and Poetry, lockfiles for reproducible installs, and the dependency hell that lockfiles prevent.",
  ),
  future(
    "software-engineering-practice",
    12,
    "ci-cd-fundamentals",
    "CI/CD Fundamentals",
    "Continuous integration concepts, configuring GitHub Actions, running tests on push, and the basics of continuous delivery pipelines.",
  ),
  future(
    "software-engineering-practice",
    13,
    "linting-formatting-and-code-quality",
    "Linting, Formatting, and Code Quality",
    "ruff, black, isort, mypy in CI, and the value of automated style and type checks for keeping a codebase readable over years.",
  ),
  future(
    "software-engineering-practice",
    14,
    "documentation-and-docstrings",
    "Documentation and Docstrings",
    "Docstring conventions, generating documentation with Sphinx or mkdocs, writing READMEs that work, and documenting decisions.",
  ),
  future(
    "software-engineering-practice",
    15,
    "code-review-and-pull-requests",
    "Code Review and Pull Requests",
    "What good code review looks like, writing PR descriptions that invite review, and giving and receiving feedback as an engineer.",
    { prerequisites: ["git-remotes-and-collaboration"] },
  ),
];

const cppForSystemsLessons: Lesson[] = [
  future(
    "cpp-for-systems",
    1,
    "cpp-toolchain-and-hello-world",
    "C++ Toolchain and Hello World",
    "Installing a modern C++ compiler, compiling and running a first program, and the conceptual difference between Python and C++ workflows.",
  ),
  future(
    "cpp-for-systems",
    2,
    "cpp-types-and-values",
    "C++ Types and Values",
    "Fundamental types, fixed-width integers, signedness, floating-point types, and the type system as the contract you sign with the compiler.",
  ),
  future(
    "cpp-for-systems",
    3,
    "cpp-control-flow-and-functions",
    "C++ Control Flow and Functions",
    "If, switch, for, while, function declarations and definitions, parameter passing modes, and translating Python patterns into idiomatic C++.",
  ),
  future(
    "cpp-for-systems",
    4,
    "cpp-pointers-and-memory-addresses",
    "Pointers and Memory Addresses",
    "Pointers as addresses, address-of and dereference operators, pointer arithmetic, and the mental model of memory as a flat array of bytes.",
  ),
  future(
    "cpp-for-systems",
    5,
    "cpp-references",
    "C++ References",
    "References as aliases, the differences between references and pointers, reference parameters, and when each tool is appropriate.",
    { prerequisites: ["cpp-pointers-and-memory-addresses"] },
  ),
  future(
    "cpp-for-systems",
    6,
    "cpp-arrays-and-cstrings",
    "Arrays and C-Strings",
    "Raw arrays, array decay to pointers, C-strings versus std::string, and why modern C++ prefers containers over raw arrays.",
  ),
  future(
    "cpp-for-systems",
    7,
    "cpp-stack-vs-heap-allocation",
    "Stack vs Heap Allocation",
    "Automatic versus dynamic storage, new and delete, lifetime, and the costs of heap allocation in latency-sensitive code.",
    { prerequisites: ["cpp-pointers-and-memory-addresses"] },
  ),
  future(
    "cpp-for-systems",
    8,
    "cpp-classes-and-encapsulation",
    "C++ Classes and Encapsulation",
    "Defining classes, access specifiers, constructors and destructors, and the principle of bundling state with the operations that manage it.",
  ),
  future(
    "cpp-for-systems",
    9,
    "cpp-raii-and-resource-management",
    "RAII and Resource Management",
    "Resource Acquisition Is Initialization, deterministic destruction, and using RAII to manage memory, files, locks, and hardware handles.",
    { prerequisites: ["cpp-classes-and-encapsulation"] },
  ),
  future(
    "cpp-for-systems",
    10,
    "cpp-copy-and-rule-of-three",
    "Copy Semantics and the Rule of Three",
    "Copy constructors and copy assignment, deep versus shallow copies, and the Rule of Three for safe value-type classes.",
    { prerequisites: ["cpp-raii-and-resource-management"] },
  ),
  future(
    "cpp-for-systems",
    11,
    "cpp-move-semantics-and-rvalue-references",
    "Move Semantics and Rvalue References",
    "Lvalues and rvalues, rvalue references, move constructors and move assignment, and the Rule of Five for modern C++ classes.",
    { prerequisites: ["cpp-copy-and-rule-of-three"] },
  ),
  future(
    "cpp-for-systems",
    12,
    "cpp-smart-pointers",
    "Smart Pointers: unique_ptr and shared_ptr",
    "std::unique_ptr, std::shared_ptr, std::weak_ptr, when to choose each, and replacing raw new/delete with smart pointer ownership.",
    { prerequisites: ["cpp-move-semantics-and-rvalue-references"] },
  ),
  future(
    "cpp-for-systems",
    13,
    "cpp-inheritance-and-virtual-functions",
    "Inheritance and Virtual Functions",
    "Public inheritance for is-a relationships, virtual functions, virtual destructors, and the cost of dynamic dispatch.",
    { prerequisites: ["cpp-classes-and-encapsulation"] },
  ),
  future(
    "cpp-for-systems",
    14,
    "cpp-polymorphism-and-interfaces",
    "Polymorphism and Abstract Interfaces",
    "Abstract base classes, pure virtual functions, dependency inversion, and using interfaces to decouple modules in robotics code.",
    { prerequisites: ["cpp-inheritance-and-virtual-functions"] },
  ),
  future(
    "cpp-for-systems",
    15,
    "cpp-templates-and-generic-programming",
    "Templates and Generic Programming",
    "Function and class templates, template instantiation, type deduction, and the compile-time computation model behind generic C++.",
  ),
  future(
    "cpp-for-systems",
    16,
    "cpp-stl-containers",
    "STL Containers",
    "vector, array, deque, list, map, unordered_map, set, and choosing the right container for the access pattern and complexity guarantee.",
  ),
  future(
    "cpp-for-systems",
    17,
    "cpp-stl-iterators-and-algorithms",
    "STL Iterators and Algorithms",
    "Iterator categories, the algorithms in <algorithm>, ranges (C++20), and the iterator-based decoupling of containers from algorithms.",
    { prerequisites: ["cpp-stl-containers"] },
  ),
  future(
    "cpp-for-systems",
    18,
    "cpp-lambdas-and-functional-objects",
    "Lambdas and Function Objects",
    "Function objects, lambda expressions, captures, std::function, and using callables with STL algorithms.",
  ),
  future(
    "cpp-for-systems",
    19,
    "cpp-exceptions-and-error-handling",
    "Exceptions and Error Handling",
    "throw/try/catch, exception safety guarantees, noexcept, and the tradeoffs between exceptions and error codes in real-time systems.",
  ),
  future(
    "cpp-for-systems",
    20,
    "cpp-modern-cpp-features",
    "Modern C++ Features (C++11/14/17/20)",
    "auto, range-for, structured bindings, optional, variant, concepts, and the language additions that make modern C++ feel different.",
  ),
  future(
    "cpp-for-systems",
    21,
    "cpp-compilation-linking-and-headers",
    "Compilation, Linking, and Headers",
    "Translation units, the preprocessor, declaration versus definition, header guards, and the ODR rule that powers C++'s build model.",
  ),
  future(
    "cpp-for-systems",
    22,
    "cpp-cmake-and-build-systems",
    "CMake and Build Systems",
    "Writing CMakeLists.txt for libraries and executables, find_package, build configurations, and modern target-based CMake.",
    { prerequisites: ["cpp-compilation-linking-and-headers"] },
  ),
  future(
    "cpp-for-systems",
    23,
    "cpp-debugging-and-sanitizers",
    "Debugging C++ with gdb and Sanitizers",
    "Using gdb effectively, AddressSanitizer, UndefinedBehaviorSanitizer, ThreadSanitizer, and catching memory bugs before deployment.",
  ),
  future(
    "cpp-for-systems",
    24,
    "cpp-testing-with-gtest-and-catch2",
    "Testing C++ with GoogleTest and Catch2",
    "Setting up a test target in CMake, writing fixtures and parameterized tests, and integrating tests into your build.",
    { prerequisites: ["cpp-cmake-and-build-systems"] },
  ),
  future(
    "cpp-for-systems",
    25,
    "cpp-python-interop-pybind11",
    "C++/Python Interop with pybind11",
    "Calling C++ from Python and vice versa, exposing classes and functions with pybind11, and the patterns for hot-path acceleration.",
    { prerequisites: ["cpp-cmake-and-build-systems"] },
  ),
];

const performanceAndConcurrencyLessons: Lesson[] = [
  future(
    "performance-and-concurrency",
    1,
    "performance-mental-model",
    "A Performance Mental Model",
    "Latency versus throughput, the memory hierarchy, CPU pipelines, and the rule that you cannot optimize what you have not measured.",
  ),
  future(
    "performance-and-concurrency",
    2,
    "profiling-tools-and-methodology",
    "Profiling Tools and Methodology",
    "Sampling versus instrumentation profilers, flame graphs, perf, py-spy, and a disciplined workflow from hypothesis to measurement.",
  ),
  future(
    "performance-and-concurrency",
    3,
    "cpu-bound-vs-io-bound",
    "CPU-Bound vs I/O-Bound Workloads",
    "Diagnosing whether a program is CPU-bound or I/O-bound, why this determines your concurrency strategy, and how to measure it.",
  ),
  future(
    "performance-and-concurrency",
    4,
    "threads-and-processes-fundamentals",
    "Threads and Processes Fundamentals",
    "OS threads versus processes, shared versus isolated memory, context switching costs, and the kernel's view of concurrency.",
  ),
  future(
    "performance-and-concurrency",
    5,
    "python-threading-and-the-gil",
    "Python Threading and the GIL",
    "The Global Interpreter Lock, what threads do and do not buy you in CPython, and patterns where threading still helps.",
    { prerequisites: ["threads-and-processes-fundamentals"] },
  ),
  future(
    "performance-and-concurrency",
    6,
    "python-multiprocessing",
    "Python Multiprocessing",
    "The multiprocessing module, process pools, inter-process communication, and using processes to escape the GIL on CPU-bound work.",
    { prerequisites: ["python-threading-and-the-gil"] },
  ),
  future(
    "performance-and-concurrency",
    7,
    "synchronization-locks-and-races",
    "Synchronization: Locks, Mutexes, and Races",
    "Data races and race conditions, mutexes and locks, deadlock conditions, and patterns for safe shared mutable state.",
    { prerequisites: ["threads-and-processes-fundamentals"] },
  ),
  future(
    "performance-and-concurrency",
    8,
    "async-await-and-event-loops",
    "Async/Await and Event Loops",
    "Cooperative multitasking, the asyncio event loop, async functions and tasks, and concurrency without threads for I/O-bound code.",
  ),
  future(
    "performance-and-concurrency",
    9,
    "message-passing-and-queues",
    "Message Passing and Queues",
    "Producer-consumer patterns, in-process and inter-process queues, and message-passing concurrency as an alternative to shared memory.",
  ),
  future(
    "performance-and-concurrency",
    10,
    "memory-hierarchy-and-cache-effects",
    "Memory Hierarchy and Cache Effects",
    "L1/L2/L3 caches, cache lines, data-oriented design, and writing code that respects how the hardware actually moves bytes.",
  ),
  future(
    "performance-and-concurrency",
    11,
    "simd-and-vector-instructions",
    "SIMD and Vector Instructions",
    "Single Instruction Multiple Data, how compilers and libraries exploit it, and writing numerical code that auto-vectorizes well.",
  ),
  future(
    "performance-and-concurrency",
    12,
    "distributed-systems-fundamentals",
    "Distributed Systems Fundamentals",
    "Why distributed systems exist, partial failure as the central problem, and the gulf between local function calls and remote ones.",
  ),
  future(
    "performance-and-concurrency",
    13,
    "cap-theorem-and-consistency-models",
    "CAP Theorem and Consistency Models",
    "Consistency, availability, partition tolerance; strong versus eventual consistency; and the tradeoffs you cannot avoid in distributed data.",
    { prerequisites: ["distributed-systems-fundamentals"] },
  ),
  future(
    "performance-and-concurrency",
    14,
    "rpc-and-message-brokers",
    "RPC and Message Brokers",
    "Synchronous RPC (gRPC) versus asynchronous brokers (RabbitMQ, Kafka, MQTT), delivery guarantees, and choosing for robotics fleets.",
  ),
  future(
    "performance-and-concurrency",
    15,
    "latency-throughput-and-real-time-budgets",
    "Latency, Throughput, and Real-Time Budgets",
    "Tail latency, queueing theory intuition, real-time deadlines, and constructing latency budgets for physical AI control loops.",
  ),
];

export const codingFoundationsLessons: Lesson[] = [
  ...technicalPythonLessons,
  ...dataStructuresAndAlgorithmsLessons,
  ...numericalAndScientificPythonLessons,
  ...softwareEngineeringPracticeLessons,
  ...cppForSystemsLessons,
  ...performanceAndConcurrencyLessons,
];
