import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "computer-vision";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const imageFundamentalsLessons: Lesson[] = [
  future("image-fundamentals", 1, "digital-image-representation", "Digital Image Representation", "How a digital image is stored as a grid of pixels with sampling, quantization, bit depth, and image file formats."),
  future("image-fundamentals", 2, "rgb-color-and-color-models", "RGB Color and Additive Color Models", "The RGB color cube, additive color mixing, color channels, and per-channel image arithmetic for digital displays and cameras."),
  future("image-fundamentals", 3, "yuv-and-broadcast-color-spaces", "YUV and Broadcast Color Spaces", "Luminance-chrominance separation in YUV, YCbCr, and YIQ; chroma subsampling; and why broadcast video decouples brightness from color."),
  future("image-fundamentals", 4, "hsv-and-perceptual-color-spaces", "HSV and Perceptual Color Spaces", "Hue, saturation, value as a cylindrical color model; HSL, Lab, and how perceptual color spaces support color-based segmentation."),
  future("image-fundamentals", 5, "image-histograms-and-statistics", "Image Histograms and Statistics", "Per-channel histograms, cumulative distributions, image moments, and reading exposure and contrast from a histogram."),
  future("image-fundamentals", 6, "histogram-equalization-and-clahe", "Histogram Equalization and CLAHE", "Global histogram equalization for contrast stretching, its failure modes, and adaptive variants like CLAHE for local contrast."),
  future("image-fundamentals", 7, "point-operations-and-look-up-tables", "Point Operations and Look-Up Tables", "Pixel-wise operations including brightness, contrast, thresholding, and inversion implemented efficiently with look-up tables."),
  future("image-fundamentals", 8, "gamma-correction-and-tone-mapping", "Gamma Correction and Tone Mapping", "Display gamma, sRGB encoding, linearizing pixel values before processing, and tone-mapping HDR content to standard displays."),
  future("image-fundamentals", 9, "linear-filtering-and-correlation", "Linear Filtering and Correlation", "Linear shift-invariant filters, correlation as sliding inner products, and the difference between correlation and convolution."),
  future("image-fundamentals", 10, "convolution-and-kernel-design", "Convolution and Kernel Design", "Convolution operation, separability, padding modes, and designing kernels for smoothing, sharpening, and feature emphasis."),
  future("image-fundamentals", 11, "box-and-gaussian-smoothing-kernels", "Box and Gaussian Smoothing Kernels", "Box blur, Gaussian smoothing, the Gaussian kernel's separability, and choosing sigma for the noise-detail tradeoff."),
  future("image-fundamentals", 12, "sobel-and-derivative-kernels", "Sobel and Derivative Kernels", "Sobel, Prewitt, and Scharr operators as image derivative approximations; gradient magnitude and direction images."),
  future("image-fundamentals", 13, "median-and-rank-filters", "Median and Rank Filters", "Non-linear rank filters, the median filter for impulse noise removal, and edge preservation compared to linear smoothing."),
  future("image-fundamentals", 14, "bilateral-and-edge-preserving-filters", "Bilateral and Edge-Preserving Filters", "Bilateral filtering with range and spatial weights, guided filter, and applications to denoising while preserving edges."),
  future("image-fundamentals", 15, "gradient-operators-and-edge-strength", "Gradient Operators and Edge Strength", "Image gradients in x and y, gradient magnitude, orientation, and Laplacian as a second-order edge detector."),
  future("image-fundamentals", 16, "canny-edge-detector", "Canny Edge Detector", "The five stages of Canny edge detection: smoothing, gradient, non-maximum suppression, double threshold, and hysteresis tracking."),
  future("image-fundamentals", 17, "morphological-erosion-and-dilation", "Morphological Erosion and Dilation", "Binary morphology fundamentals, structuring elements, erosion and dilation, and grayscale morphology generalizations."),
  future("image-fundamentals", 18, "opening-closing-and-morphological-gradients", "Opening, Closing, and Morphological Gradients", "Compound morphological operations for noise removal and gap filling, plus top-hat, black-hat, and morphological gradients."),
  future("image-fundamentals", 19, "connected-components-and-contour-finding", "Connected Components and Contour Finding", "Connected component labeling with 4- and 8-connectivity, contour tracing algorithms, and contour hierarchy from binary images."),
  future("image-fundamentals", 20, "image-pyramids-and-interpolation", "Image Pyramids, Resizing, and Interpolation", "Gaussian and Laplacian pyramids for multi-scale processing, nearest-neighbor, bilinear, and bicubic interpolation for resizing."),
];

const geometricVisionLessons: Lesson[] = [
  future("geometric-vision", 1, "pinhole-camera-model", "The Pinhole Camera Model", "Perspective projection through a pinhole, the image plane, focal length, and the basic equations mapping 3D points to 2D pixels."),
  future("geometric-vision", 2, "intrinsic-camera-parameters", "Intrinsic Camera Parameters", "The intrinsic matrix K with focal lengths, principal point, and skew; converting between normalized and pixel coordinates."),
  future("geometric-vision", 3, "extrinsic-camera-parameters", "Extrinsic Camera Parameters", "The world-to-camera rigid transform, rotation matrices and translation vectors, and the full projection matrix P = K[R|t]."),
  future("geometric-vision", 4, "lens-distortion-models", "Lens Distortion Models", "Radial and tangential distortion, the Brown-Conrady model, fisheye and equidistant models, and undistortion via inverse mapping."),
  future("geometric-vision", 5, "zhang-single-view-calibration", "Single-View Calibration with Zhang's Method", "Zhang's planar checkerboard calibration: homography per view, closed-form intrinsics, and non-linear refinement of all parameters."),
  future("geometric-vision", 6, "homography-and-planar-projective-transforms", "Homography and Planar Projective Transforms", "The 3x3 homography matrix mapping points between planes, estimation from four point correspondences, and applications."),
  future("geometric-vision", 7, "projective-geometry-essentials", "Projective Geometry Essentials for Vision", "Homogeneous coordinates, points and lines at infinity, the projective plane, and why projective geometry naturally describes cameras."),
  future("geometric-vision", 8, "epipolar-geometry-and-the-epipolar-constraint", "Epipolar Geometry and the Epipolar Constraint", "Epipoles, epipolar lines, epipolar planes, and the constraint relating corresponding points across two views of a static scene."),
  future("geometric-vision", 9, "the-fundamental-matrix", "The Fundamental Matrix", "Definition of F, the eight-point algorithm, normalization for numerical stability, and rank-2 enforcement."),
  future("geometric-vision", 10, "the-essential-matrix", "The Essential Matrix", "Calibrated form of the epipolar constraint, decomposition of E into rotation and translation, and the four-fold motion ambiguity."),
  future("geometric-vision", 11, "stereo-rig-geometry-and-rectification", "Stereo Rig Geometry and Rectification", "Canonical stereo geometry with parallel optical axes, image rectification to align epipolar lines with image rows, and rectification homographies."),
  future("geometric-vision", 12, "disparity-and-depth-from-stereo", "Disparity and Depth from Stereo", "The disparity-depth relation z = fB/d, baseline-focal tradeoffs, and propagating disparity uncertainty into depth uncertainty."),
  future("geometric-vision", 13, "stereo-block-matching", "Stereo Block Matching", "Local stereo correspondence via SAD, SSD, and NCC windows; aggregation, sub-pixel refinement, and left-right consistency checks."),
  future("geometric-vision", 14, "dense-stereo-and-cost-volumes", "Dense Stereo and Cost Volumes", "Building disparity cost volumes, winner-take-all selection, and scanline dynamic programming for dense depth maps."),
  future("geometric-vision", 15, "semi-global-matching", "Semi-Global Matching", "SGM as multi-path aggregation of stereo costs, smoothness penalties, and the dominant classical algorithm in production stereo systems."),
  future("geometric-vision", 16, "triangulation-and-depth-recovery", "Triangulation and Depth Recovery", "Linear and optimal triangulation from two or more views, midpoint method, and minimizing reprojection error for robust depth."),
  future("geometric-vision", 17, "multi-view-geometry-overview", "Multi-View Geometry Overview", "Trifocal tensor, multi-camera constraints, generalized epipolar geometry, and how N-view geometry extends two-view ideas."),
  future("geometric-vision", 18, "perspective-n-point-pnp", "Perspective-n-Point (PnP)", "Estimating camera pose from 2D-3D correspondences via P3P, EPnP, and iterative refinement; minimal and overdetermined formulations."),
  future("geometric-vision", 19, "camera-pose-estimation-pipelines", "Camera Pose Estimation Pipelines", "End-to-end pose estimation: feature extraction, matching to a 3D map, PnP solution, and pose tracking with motion models."),
  future("geometric-vision", 20, "ransac-for-robust-geometric-estimation", "RANSAC for Robust Geometric Estimation", "The RANSAC algorithm, sample size and iteration count, inlier thresholds, and variants like MSAC, PROSAC, and LO-RANSAC."),
];

const classicalFeaturesAndTrackingLessons: Lesson[] = [
  future("classical-features-and-tracking", 1, "harris-and-shi-tomasi-corners", "Harris and Shi-Tomasi Corners", "The structure tensor, Harris corner response, Shi-Tomasi's minimum-eigenvalue criterion, and non-maximum suppression for corners."),
  future("classical-features-and-tracking", 2, "fast-corner-detector", "FAST Corner Detector", "Features from Accelerated Segment Test: the circle test, machine-learned acceptance, and FAST's role in real-time tracking."),
  future("classical-features-and-tracking", 3, "sift-keypoint-detection", "SIFT Keypoint Detection", "Scale-space construction via Difference of Gaussians, extrema detection, keypoint localization, and orientation assignment."),
  future("classical-features-and-tracking", 4, "sift-descriptors", "SIFT Descriptors", "Gradient histograms in oriented patches, 128-dimensional descriptors, normalization, and rotation and scale invariance properties."),
  future("classical-features-and-tracking", 5, "surf-and-orb-descriptors", "SURF and ORB Descriptors", "SURF's integral-image acceleration, ORB combining oriented FAST with rotated BRIEF, and the speed-accuracy tradeoff."),
  future("classical-features-and-tracking", 6, "brief-and-brisk-binary-descriptors", "BRIEF and BRISK Binary Descriptors", "Binary descriptors from pixel-pair comparisons, Hamming distance matching, and BRISK's scale-aware sampling pattern."),
  future("classical-features-and-tracking", 7, "feature-matching-strategies", "Feature Matching Strategies", "Brute-force matching, k-d trees and FLANN for approximate nearest neighbors, cross-checking, and matching at scale."),
  future("classical-features-and-tracking", 8, "lowes-ratio-test-and-outlier-filtering", "Lowe's Ratio Test and Outlier Filtering", "Lowe's ratio test for distinctive matches, symmetric matching, and combining ratio tests with geometric verification."),
  future("classical-features-and-tracking", 9, "ransac-for-homography-estimation", "RANSAC for Homography Estimation", "Applying RANSAC to four-point homography hypotheses, planar scene assumptions, and panorama-stitching pipelines."),
  future("classical-features-and-tracking", 10, "ransac-for-fundamental-matrix", "RANSAC for Fundamental Matrix Estimation", "Seven- and eight-point RANSAC for F, degeneracy handling, and combining geometric and photometric verification of matches."),
  future("classical-features-and-tracking", 11, "lucas-kanade-optical-flow", "Lucas-Kanade Optical Flow", "Brightness constancy, the aperture problem, the Lucas-Kanade window assumption, and pyramidal Lucas-Kanade for large motions."),
  future("classical-features-and-tracking", 12, "horn-schunck-dense-optical-flow", "Horn-Schunck Dense Optical Flow", "Variational dense flow with a global smoothness prior, Euler-Lagrange equations, and iterative solution schemes."),
  future("classical-features-and-tracking", 13, "farneback-dense-optical-flow", "Farneback Dense Optical Flow", "Polynomial expansion of image neighborhoods, displacement from coefficient comparison, and multi-scale Farneback in practice."),
  future("classical-features-and-tracking", 14, "klt-feature-tracking", "KLT Feature Tracking", "Kanade-Lucas-Tomasi tracker as iterative Lucas-Kanade on selected corners, track quality monitoring, and re-detection strategies."),
  future("classical-features-and-tracking", 15, "mean-shift-and-camshift-tracking", "Mean-Shift and CamShift Tracking", "Mean-shift mode seeking on color histograms, CamShift's adaptive window, and limitations on illumination and occlusion."),
];

const deepLearningForVisionLessons: Lesson[] = [
  future("deep-learning-for-vision", 1, "cnn-basics-and-motivation", "CNN Basics and Motivation", "Why convolutions fit images, weight sharing, translation equivariance, and the historical move from MLPs to CNNs."),
  future("deep-learning-for-vision", 2, "convolution-layers-in-deep-networks", "Convolution Layers in Deep Networks", "Stride, padding, dilation, multiple input and output channels, and the parameter count of a convolutional layer."),
  future("deep-learning-for-vision", 3, "pooling-and-downsampling-strategies", "Pooling and Downsampling Strategies", "Max and average pooling, strided convolutions as learnable downsampling, and global pooling for classification heads."),
  future("deep-learning-for-vision", 4, "alexnet-vgg-and-the-imagenet-era", "AlexNet, VGG, and the ImageNet Era", "AlexNet's breakthrough, VGG's depth-uniformity recipe, and the architectural lessons that shaped modern CNNs."),
  future("deep-learning-for-vision", 5, "resnet-and-residual-learning", "ResNet and Residual Learning", "Skip connections, the degradation problem in deep networks, ResNet blocks, and identity mappings."),
  future("deep-learning-for-vision", 6, "modern-backbones-efficientnet-and-convnext", "Modern Backbones: EfficientNet and ConvNeXt", "Compound scaling in EfficientNet, ConvNeXt's transformer-inspired CNN, and current trends in backbone design."),
  future("deep-learning-for-vision", 7, "classification-training-recipes", "Classification Training Recipes", "Loss functions, learning rate schedules, label smoothing, weight decay, and the modern recipe for training image classifiers."),
  future("deep-learning-for-vision", 8, "data-augmentation-for-vision", "Data Augmentation for Vision", "Random crops, flips, color jitter, Mixup, CutMix, RandAugment, and the role of augmentation in generalization."),
  future("deep-learning-for-vision", 9, "transfer-learning-and-fine-tuning", "Transfer Learning and Fine-Tuning", "Pretraining strategies, feature extraction versus fine-tuning, layer freezing schedules, and domain shift considerations."),
  future("deep-learning-for-vision", 10, "two-stage-detection-faster-rcnn", "Two-Stage Detection with Faster R-CNN", "Region proposals, RoI pooling and RoI Align, the RPN, and the two-stage detection pipeline that defined the modern era."),
  future("deep-learning-for-vision", 11, "single-stage-detection-yolo-and-ssd", "Single-Stage Detection with YOLO and SSD", "Dense prediction grids, multi-scale feature maps, YOLO's evolution, and the speed-accuracy tradeoff against two-stage detectors."),
  future("deep-learning-for-vision", 12, "detr-transformer-based-detection", "DETR: Transformer-Based Detection", "Set prediction with bipartite matching, object queries, Hungarian loss, and how DETR removes anchors and NMS."),
  future("deep-learning-for-vision", 13, "anchor-based-vs-anchor-free-detection", "Anchor-Based vs Anchor-Free Detection", "Anchor design and matching, FCOS-style center-based detection, key-point based detectors, and the move away from anchors."),
  future("deep-learning-for-vision", 14, "semantic-segmentation-fcn-and-unet", "Semantic Segmentation with FCN and U-Net", "Fully convolutional networks, encoder-decoder architectures, skip connections in U-Net, and per-pixel classification losses."),
  future("deep-learning-for-vision", 15, "instance-segmentation-with-mask-rcnn", "Instance Segmentation with Mask R-CNN", "Adding a mask head to Faster R-CNN, RoI Align precision, and per-instance mask prediction at multi-scale."),
  future("deep-learning-for-vision", 16, "panoptic-segmentation", "Panoptic Segmentation", "Unifying semantic and instance segmentation, things versus stuff, panoptic quality metric, and panoptic FPN architectures."),
  future("deep-learning-for-vision", 17, "vision-transformers-vit", "Vision Transformers (ViT)", "Patch embeddings, positional encodings, attention over image patches, and how ViTs compare to CNNs at different data scales."),
  future("deep-learning-for-vision", 18, "swin-transformer-and-hierarchical-attention", "Swin Transformer and Hierarchical Attention", "Shifted windows, hierarchical feature maps, and Swin as a transformer backbone competitive with CNNs across dense tasks."),
  future("deep-learning-for-vision", 19, "self-supervised-learning-simclr-and-dino", "Self-Supervised Learning: SimCLR and DINO", "Contrastive learning, momentum encoders, BYOL, DINO's self-distillation, and learning visual features without labels."),
  future("deep-learning-for-vision", 20, "masked-autoencoders-and-mim", "Masked Autoencoders and Masked Image Modeling", "MAE and BEiT-style pretraining, asymmetric encoder-decoders, and masked image modeling as a scalable self-supervised recipe."),
  future("deep-learning-for-vision", 21, "clip-and-multi-modal-vision-language-models", "CLIP and Multi-Modal Vision-Language Models", "Contrastive image-text pretraining, zero-shot classification with CLIP, and the foundation-model approach to vision."),
  future("deep-learning-for-vision", 22, "diffusion-models-for-vision", "Diffusion Models for Vision", "Forward and reverse diffusion processes, score matching, classifier-free guidance, and latent diffusion for high-resolution generation."),
  future("deep-learning-for-vision", 23, "open-vocabulary-and-promptable-vision", "Open-Vocabulary and Promptable Vision", "SAM-style promptable segmentation, open-vocabulary detection, grounded language models, and the move beyond fixed label sets."),
  future("deep-learning-for-vision", 24, "evaluation-metrics-map-iou-f1", "Evaluation Metrics: mAP, IoU, F1", "IoU and mask IoU, precision-recall curves, average precision, mAP across IoU thresholds, and per-class F1 reporting."),
  future("deep-learning-for-vision", 25, "deployment-quantization-and-distillation", "Deployment: Quantization and Distillation", "Post-training and quantization-aware training, INT8 and FP16 inference, knowledge distillation, and runtime export formats."),
];

const threeDVisionAndReconstructionLessons: Lesson[] = [
  future("3d-vision-and-reconstruction", 1, "depth-perception-cues-overview", "Depth Perception Cues Overview", "Pictorial cues, motion parallax, stereopsis, focus and defocus, and how human and machine systems combine multiple depth cues."),
  future("3d-vision-and-reconstruction", 2, "monocular-depth-estimation", "Monocular Depth Estimation", "Learning depth from a single image, scale ambiguity, supervised and self-supervised training signals, and benchmark datasets."),
  future("3d-vision-and-reconstruction", 3, "midas-and-zero-shot-depth", "MiDaS and Zero-Shot Depth Models", "Scale- and shift-invariant losses, mixed-dataset training, MiDaS architectures, and zero-shot depth in unseen domains."),
  future("3d-vision-and-reconstruction", 4, "active-stereo-and-structured-light", "Active Stereo and Structured Light", "Projected patterns to disambiguate correspondences, coded light sequences, and commercial structured-light depth sensors."),
  future("3d-vision-and-reconstruction", 5, "time-of-flight-depth-sensing", "Time-of-Flight Depth Sensing", "Continuous-wave and pulsed ToF principles, phase wrap-around, multipath interference, and ToF cameras in robotics."),
  future("3d-vision-and-reconstruction", 6, "structure-from-motion-pipeline", "Structure from Motion Pipeline", "End-to-end SfM: feature extraction, matching, geometric verification, initial pair, incremental registration, and final bundle adjustment."),
  future("3d-vision-and-reconstruction", 7, "incremental-sfm-with-colmap", "Incremental SfM with COLMAP", "COLMAP's incremental reconstruction strategy, next-best-view selection, retriangulation, and handling of large unordered image collections."),
  future("3d-vision-and-reconstruction", 8, "bundle-adjustment", "Bundle Adjustment", "Joint non-linear refinement of cameras and 3D points, the sparse Jacobian structure, Schur complement, and Levenberg-Marquardt in practice."),
  future("3d-vision-and-reconstruction", 9, "multi-view-stereo-mvs", "Multi-View Stereo (MVS)", "Going from sparse SfM points to dense reconstructions via plane-sweeping, patch-based MVS, and depth-map fusion."),
  future("3d-vision-and-reconstruction", 10, "dense-reconstruction-and-depth-fusion", "Dense Reconstruction and Depth Fusion", "Fusing per-view depth maps into consistent 3D models, TSDF volumes, KinectFusion-style integration, and outlier handling."),
  future("3d-vision-and-reconstruction", 11, "point-cloud-filtering-and-normals", "Point Cloud Filtering and Normal Estimation", "Statistical outlier removal, voxel downsampling, normal estimation via local PCA, and consistent normal orientation."),
  future("3d-vision-and-reconstruction", 12, "point-cloud-registration-and-icp", "Point Cloud Registration with ICP", "Iterative Closest Point, point-to-point versus point-to-plane variants, coarse alignment with FPFH features, and global registration."),
  future("3d-vision-and-reconstruction", 13, "mesh-generation-from-point-clouds", "Mesh Generation from Point Clouds", "Delaunay triangulation, ball-pivoting, alpha shapes, and choosing meshing strategies for different scan densities."),
  future("3d-vision-and-reconstruction", 14, "poisson-surface-reconstruction", "Poisson Surface Reconstruction", "Casting surface reconstruction as solving a Poisson equation on oriented points, screened Poisson variants, and watertight outputs."),
  future("3d-vision-and-reconstruction", 15, "nerf-principles", "NeRF Principles", "Neural radiance fields, volumetric rendering, positional encodings, view-dependent appearance, and the original NeRF training recipe."),
  future("3d-vision-and-reconstruction", 16, "instant-ngp-and-fast-nerf-variants", "Instant-NGP and Fast NeRF Variants", "Multiresolution hash encodings, occupancy grids, and the engineering tricks that brought NeRF training from days to seconds."),
  future("3d-vision-and-reconstruction", 17, "3d-gaussian-splatting", "3D Gaussian Splatting", "Explicit anisotropic Gaussian primitives, differentiable rasterization, densification and pruning, and the real-time rendering breakthrough."),
  future("3d-vision-and-reconstruction", 18, "neural-surface-reconstruction", "Neural Surface Reconstruction", "Signed distance field representations, NeuS and VolSDF, surface extraction via marching cubes, and accuracy versus radiance-field methods."),
  future("3d-vision-and-reconstruction", 19, "scene-representations-comparison", "Scene Representations Comparison", "Voxels, point clouds, meshes, implicit fields, and Gaussians compared on memory, rendering speed, editability, and downstream usability."),
  future("3d-vision-and-reconstruction", 20, "evaluation-of-3d-reconstructions", "Evaluation of 3D Reconstructions", "Chamfer and Hausdorff distances, F-score on point sets, novel-view PSNR and SSIM, and the limits of each reconstruction metric."),
];

const industrialVisionAndMetrologyLessons: Lesson[] = [
  future("industrial-vision-and-metrology", 1, "machine-vision-vs-computer-vision", "Machine Vision vs Computer Vision", "Determinism, latency, repeatability, and certification requirements that separate factory machine vision from general computer vision."),
  future("industrial-vision-and-metrology", 2, "industrial-lighting-design", "Industrial Lighting Design", "Backlight, dome, ring, dark-field, and coaxial lighting; matching illumination geometry to surface and defect characteristics."),
  future("industrial-vision-and-metrology", 3, "industrial-camera-selection", "Industrial Camera Selection", "Sensor format and resolution, global versus rolling shutter, GigE Vision, USB3 Vision, Camera Link, and lens mount considerations."),
  future("industrial-vision-and-metrology", 4, "calibration-for-metrology", "Calibration for Metrology", "Traceable calibration artifacts, telecentric lenses, scale-bar verification, and uncertainty budgets for measurement-grade vision systems."),
  future("industrial-vision-and-metrology", 5, "sub-pixel-feature-finding", "Sub-Pixel Feature Finding", "Sub-pixel edge localization, parabolic and Gaussian peak fitting, ellipse and circle fitting at sub-pixel accuracy for gauging tasks."),
  future("industrial-vision-and-metrology", 6, "classical-defect-detection-methods", "Classical Defect Detection Methods", "Golden-template comparison, blob analysis, edge-based gauging, and Fourier-domain methods for repetitive textures."),
  future("industrial-vision-and-metrology", 7, "deep-anomaly-detection-for-vision", "Deep Anomaly Detection for Vision", "PaDiM, PatchCore, and reconstruction-based anomaly detectors that learn normality from defect-free examples for surface inspection."),
  future("industrial-vision-and-metrology", 8, "ocr-for-industrial-applications", "OCR for Industrial Applications", "Date codes, lot codes, serial numbers, and dot-peen marks; classical OCR pipelines versus deep OCR for low-contrast industrial text."),
  future("industrial-vision-and-metrology", 9, "integration-with-plcs-and-robots", "Integration with PLCs and Robots", "Triggering, strobing, fieldbus communication (PROFINET, EtherCAT, EtherNet/IP), and pass/fail signaling into PLC and robot controllers."),
  future("industrial-vision-and-metrology", 10, "machine-vision-standards-and-safety", "Machine Vision Standards and Safety", "GenICam, GigE Vision, EMVA 1288 sensor characterization, and where machine vision fits within functional-safety requirements."),
];

export const computerVisionLessons: Lesson[] = [
  ...imageFundamentalsLessons,
  ...geometricVisionLessons,
  ...classicalFeaturesAndTrackingLessons,
  ...deepLearningForVisionLessons,
  ...threeDVisionAndReconstructionLessons,
  ...industrialVisionAndMetrologyLessons,
];
