import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "drones-gis-remote-sensing";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const coordinateSystemsLessons: Lesson[] = [
  future(
    "coordinate-systems",
    2,
    "geodetic-vs-geocentric-coordinates",
    "Geodetic vs Geocentric Coordinates",
    "Distinguish geodetic latitude defined by the ellipsoid normal from geocentric latitude defined by the Earth's center.",
  ),
  future(
    "coordinate-systems",
    3,
    "wgs84-datum-and-reference-ellipsoid",
    "WGS84 Datum and the Reference Ellipsoid",
    "Why the Earth is modeled as an ellipsoid, the parameters that define WGS84, and how datums anchor coordinates to the planet.",
  ),
  future(
    "coordinate-systems",
    4,
    "latitude-longitude-conventions",
    "Latitude and Longitude Conventions",
    "Sign conventions, decimal degrees versus degrees-minutes-seconds, and the prime meridian and equator as reference lines.",
  ),
  future(
    "coordinate-systems",
    5,
    "utm-projection-fundamentals",
    "UTM Projection Fundamentals",
    "How the Universal Transverse Mercator projection slices the globe into zones and flattens each into a planar grid for surveying.",
  ),
  future(
    "coordinate-systems",
    6,
    "ecef-earth-centered-earth-fixed",
    "ECEF: Earth-Centered Earth-Fixed Coordinates",
    "The Cartesian frame fixed to the rotating Earth, its axes and origin, and conversions between ECEF and geodetic coordinates.",
  ),
  future(
    "coordinate-systems",
    7,
    "enu-local-tangent-frame",
    "ENU Local Tangent Frame",
    "The East-North-Up local frame anchored to a reference point and how to build it from a tangent plane to the ellipsoid.",
  ),
  future(
    "coordinate-systems",
    8,
    "ned-frame-for-aerospace",
    "NED Frame for Aerospace",
    "The North-East-Down frame used in aerospace, why down is positive, and how it relates to ENU and body conventions.",
  ),
  future(
    "coordinate-systems",
    9,
    "body-frame-of-an-aircraft",
    "Body Frame of an Aircraft",
    "The forward-right-down body frame attached to an airframe, its axes, and its role in describing roll, pitch, and yaw.",
  ),
  future(
    "coordinate-systems",
    10,
    "world-frame-and-inertial-references",
    "World Frame and Inertial References",
    "What makes a frame inertial in practice, the world frame used by autopilots, and assumptions about Earth rotation at drone scales.",
  ),
  future(
    "coordinate-systems",
    11,
    "frame-transformations-and-rotation-matrices",
    "Frame Transformations and Rotation Matrices",
    "Composing rotations and translations to move points between body, world, ENU, and ECEF frames using rotation matrices.",
  ),
  future(
    "coordinate-systems",
    12,
    "gps-coordinates-in-software",
    "GPS Coordinates in Software",
    "Common library APIs for parsing, storing, and converting GPS coordinates, plus floating-point precision gotchas at survey scales.",
  ),
  future(
    "coordinate-systems",
    13,
    "utm-zones-in-practice",
    "UTM Zones in Practice",
    "Selecting the right UTM zone, handling missions that straddle zone boundaries, and northing conventions in the southern hemisphere.",
  ),
  future(
    "coordinate-systems",
    14,
    "mgrs-military-grid-reference-system",
    "MGRS: Military Grid Reference System",
    "How MGRS encodes location as alphanumeric grid squares, when it is used, and conversions to and from UTM and lat/lon.",
  ),
  future(
    "coordinate-systems",
    15,
    "geofence-representation",
    "Geofence Representation",
    "Encoding polygonal and circular geofences, point-in-polygon tests, and how autopilots use them to constrain flight envelopes.",
  ),
  future(
    "coordinate-systems",
    16,
    "coordinate-system-pitfalls",
    "Coordinate System Pitfalls",
    "Common mistakes including mixing datums, swapping lat/lon order, integer truncation, and silent frame mismatches in production code.",
  ),
];

const aerodynamicsAndFlightMechanicsLessons: Lesson[] = [
  future(
    "aerodynamics-and-flight-mechanics",
    1,
    "continuity-equation-for-fluids",
    "The Continuity Equation for Fluids",
    "Mass conservation in a streamtube, the relationship between area and velocity, and intuition for incompressible flow.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    2,
    "bernoullis-principle",
    "Bernoulli's Principle",
    "The energy balance along a streamline that links pressure and velocity, with applications to wings, pitot tubes, and venturis.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    3,
    "lift-and-drag-intuition",
    "Lift and Drag Intuition",
    "The two forces a wing produces, where they point, and qualitative pictures connecting flow turning and pressure differentials to force.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    4,
    "airfoil-shapes-and-geometry",
    "Airfoil Shapes and Geometry",
    "Chord, camber, thickness, and leading and trailing edges, and how shape choices affect performance across speed regimes.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    5,
    "angle-of-attack",
    "Angle of Attack",
    "The angle between the chord line and the relative wind, how lift scales with it, and how pilots and controllers manage it.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    6,
    "stall-and-flow-separation",
    "Stall and Flow Separation",
    "Why lift collapses beyond a critical angle of attack, the boundary-layer story behind it, and stall recovery basics.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    7,
    "lift-coefficient",
    "Lift Coefficient",
    "The dimensionless lift coefficient, its dependence on angle of attack and Reynolds number, and reading lift curves.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    8,
    "drag-coefficient-and-drag-polar",
    "Drag Coefficient and the Drag Polar",
    "Parasite and induced drag, the drag polar curve, and lift-to-drag ratio as a key performance metric.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    9,
    "thrust-from-propellers",
    "Thrust from Propellers",
    "How a rotating airfoil generates thrust, the role of disk area and airspeed change, and propeller efficiency curves.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    10,
    "propeller-pitch-and-diameter",
    "Propeller Pitch and Diameter",
    "What pitch and diameter mean for a propeller, how they trade off thrust and speed, and matching props to motors and airframes.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    11,
    "blade-element-theory-basics",
    "Blade Element Theory Basics",
    "Slicing a rotor blade into infinitesimal airfoil elements, integrating local lift and drag, and where the theory breaks.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    12,
    "momentum-theory-of-rotors",
    "Momentum Theory of Rotors",
    "Modeling the rotor as an actuator disk that imparts momentum to the air, deriving ideal hover power and figure of merit.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    13,
    "hovering-flight",
    "Hovering Flight",
    "The mechanics of hover for multirotors and helicopters, induced velocity, and why hover is the most demanding flight regime.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    14,
    "vertical-climb-and-descent",
    "Vertical Climb and Descent",
    "How rotor inflow changes with vertical motion, vortex ring state during fast descent, and safe descent profiles.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    15,
    "forward-flight-of-rotorcraft",
    "Forward Flight of Rotorcraft",
    "How a tilted rotor disk produces translational thrust, advancing and retreating blade asymmetry, and power versus speed curves.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    16,
    "fixed-wing-flight-mechanics",
    "Fixed-Wing Flight Mechanics",
    "Steady level flight, climb, glide, and turn equations, and the four forces in balance for a fixed-wing aircraft.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    17,
    "tail-configurations",
    "Tail Configurations: V-Tail and Conventional",
    "How conventional, T-tail, V-tail, and inverted-V empennages provide stability and control, with tradeoffs for drone platforms.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    18,
    "control-surfaces",
    "Control Surfaces",
    "Ailerons, elevators, rudders, flaps, and elevons; how they generate moments about each axis to command attitude changes.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    19,
    "stability-axes-and-conventions",
    "Stability Axes and Conventions",
    "Body, wind, and stability axis systems, sign conventions for forces and moments, and translating between frames for analysis.",
  ),
  future(
    "aerodynamics-and-flight-mechanics",
    20,
    "longitudinal-and-lateral-stability",
    "Longitudinal and Lateral Stability",
    "Static and dynamic stability about pitch, roll, and yaw, the role of CG location, and modes like phugoid, short period, and dutch roll.",
  ),
];

const flightControlFirmwareLessons: Lesson[] = [
  future(
    "flight-control-firmware",
    1,
    "px4-vs-ardupilot",
    "PX4 vs ArduPilot",
    "A comparison of the two dominant open-source autopilot stacks, their design philosophies, ecosystems, and supported airframes.",
  ),
  future(
    "flight-control-firmware",
    2,
    "autopilot-architecture-overview",
    "Autopilot Architecture Overview",
    "The high-level modules of a modern autopilot: sensors, estimator, controller, mixer, drivers, and the messaging spine that connects them.",
  ),
  future(
    "flight-control-firmware",
    3,
    "the-cascaded-control-loop",
    "The Cascaded Control Loop",
    "How position, velocity, attitude, and rate loops nest from outer to inner, and why bandwidth must increase as you go inward.",
  ),
  future(
    "flight-control-firmware",
    4,
    "attitude-control",
    "Attitude Control",
    "Tracking a desired orientation in roll, pitch, and yaw using quaternion error and producing body-rate setpoints for the inner loop.",
  ),
  future(
    "flight-control-firmware",
    5,
    "rate-control",
    "Rate Control",
    "The innermost loop that drives body angular rates to their setpoints, typically with a PID acting on gyro measurements.",
  ),
  future(
    "flight-control-firmware",
    6,
    "position-control",
    "Position Control",
    "The outer loop that turns waypoint or velocity commands into thrust and tilt setpoints in the world or local frame.",
  ),
  future(
    "flight-control-firmware",
    7,
    "sensor-fusion-with-ekf",
    "Sensor Fusion with the EKF",
    "How an Extended Kalman Filter combines IMU, GPS, barometer, and magnetometer measurements into a single state estimate.",
  ),
  future(
    "flight-control-firmware",
    8,
    "gps-denied-flight",
    "GPS-Denied Flight",
    "Strategies for flying without GPS using optical flow, visual-inertial odometry, motion capture, and beacons for indoor or urban missions.",
  ),
  future(
    "flight-control-firmware",
    9,
    "altitude-estimation",
    "Altitude Estimation",
    "Fusing barometer, GPS, rangefinder, and IMU to track altitude robustly, and handling pressure drift and ground effect.",
  ),
  future(
    "flight-control-firmware",
    10,
    "mag-interference-handling",
    "Magnetometer Interference Handling",
    "Sources of magnetic interference on a drone, calibration procedures, and detection of in-flight mag failures.",
  ),
  future(
    "flight-control-firmware",
    11,
    "pid-tuning-for-drones",
    "PID Tuning for Drones",
    "A practical workflow for tuning the rate and attitude PIDs, recognizing oscillation and sluggishness, and adjusting one gain at a time.",
  ),
  future(
    "flight-control-firmware",
    12,
    "autotune-procedures",
    "Autotune Procedures",
    "How autotune routines perturb the airframe to identify gains, when they succeed or fail, and post-autotune verification flights.",
  ),
  future(
    "flight-control-firmware",
    13,
    "parameter-tree-and-storage",
    "Parameter Tree and Storage",
    "How PX4 and ArduPilot organize tunable parameters, store them in nonvolatile memory, and expose them to ground control software.",
  ),
  future(
    "flight-control-firmware",
    14,
    "hardware-abstraction-layer",
    "Hardware Abstraction Layer",
    "How autopilot code is decoupled from specific boards through HALs and drivers, enabling the same firmware to run on many flight controllers.",
  ),
  future(
    "flight-control-firmware",
    15,
    "flight-modes",
    "Flight Modes",
    "Stabilized, altitude hold, position hold, mission, offboard, and acro modes, and what loops are active in each.",
  ),
  future(
    "flight-control-firmware",
    16,
    "rc-failsafe",
    "RC Failsafe",
    "Detecting loss of radio control link, configuring failsafe actions like RTL or land, and testing failsafes safely on the bench.",
  ),
  future(
    "flight-control-firmware",
    17,
    "telemetry-over-mavlink",
    "Telemetry over MAVLink",
    "The MAVLink protocol for streaming heartbeats, attitude, GPS, and commands between vehicles and ground stations.",
  ),
  future(
    "flight-control-firmware",
    18,
    "log-analysis",
    "Flight Log Analysis",
    "Reading ULog and BIN logs to diagnose oscillations, sensor faults, and crashes using tools like Flight Review and MAVExplorer.",
  ),
  future(
    "flight-control-firmware",
    19,
    "firmware-build-and-upload",
    "Firmware Build and Upload",
    "Cloning, building, and flashing PX4 or ArduPilot firmware to a flight controller, including custom configurations and airframe definitions.",
  ),
  future(
    "flight-control-firmware",
    20,
    "custom-modules-and-uorb-mavlink",
    "Custom Modules: uORB and MAVLink Integration",
    "Writing a custom autopilot module that publishes and subscribes to uORB topics and exchanges MAVLink messages with companions.",
  ),
];

const missionPlanningAndOperationsLessons: Lesson[] = [
  future(
    "mission-planning-and-operations",
    1,
    "mission-planner-tools",
    "Mission Planner Tools",
    "An overview of QGroundControl, Mission Planner, and Auterion Suite, and choosing a ground station for your workflow.",
  ),
  future(
    "mission-planning-and-operations",
    2,
    "waypoint-missions",
    "Waypoint Missions",
    "Building a sequence of waypoints with altitudes, speeds, and actions, and uploading missions to the autopilot for autonomous execution.",
  ),
  future(
    "mission-planning-and-operations",
    3,
    "mission-item-types",
    "Mission Item Types",
    "Takeoff, waypoint, loiter, survey, do-jump, and camera-trigger items, and how the autopilot sequences them at runtime.",
  ),
  future(
    "mission-planning-and-operations",
    4,
    "geofencing-types",
    "Geofencing Types",
    "Inclusion and exclusion zones, polygon and circular fences, altitude ceilings, and how breaches trigger configurable responses.",
  ),
  future(
    "mission-planning-and-operations",
    5,
    "return-to-launch-logic",
    "Return-to-Launch Logic",
    "How RTL chooses an altitude, navigates home, and lands, and configuration options for safe behavior across terrain and battery states.",
  ),
  future(
    "mission-planning-and-operations",
    6,
    "fail-safes",
    "Fail-Safes",
    "Layered fail-safes for radio loss, GPS loss, battery low, geofence breach, and engine failure, and the order in which they fire.",
  ),
  future(
    "mission-planning-and-operations",
    7,
    "battery-management",
    "Battery Management",
    "Estimating remaining flight time, tracking cell voltages, configuring low-battery actions, and safely storing and charging LiPos.",
  ),
  future(
    "mission-planning-and-operations",
    8,
    "weather-considerations",
    "Weather Considerations",
    "Reading METARs and TAFs, wind limits, density altitude, precipitation, icing, and how each affects mission go/no-go.",
  ),
  future(
    "mission-planning-and-operations",
    9,
    "bvlos-regulations",
    "BVLOS Regulations",
    "Beyond Visual Line of Sight operations, the additional risk mitigations regulators require, and the waiver process in major jurisdictions.",
  ),
  future(
    "mission-planning-and-operations",
    10,
    "part-107-in-the-us",
    "Part 107 in the United States",
    "The FAA's small UAS rule, certification, operational limits, airspace authorization via LAANC, and recurrent knowledge requirements.",
  ),
  future(
    "mission-planning-and-operations",
    11,
    "easa-rules-in-europe",
    "EASA Rules in Europe",
    "The EASA Open, Specific, and Certified categories, drone classes C0 through C6, and operator and pilot registration requirements.",
  ),
  future(
    "mission-planning-and-operations",
    12,
    "no-fly-zones",
    "No-Fly Zones",
    "Sources of airspace restrictions including TFRs, NOTAMs, and prohibited and restricted areas, and tools for checking them pre-flight.",
  ),
  future(
    "mission-planning-and-operations",
    13,
    "pre-flight-checklist",
    "Pre-Flight Checklist",
    "A repeatable checklist covering airframe, propulsion, sensors, comms, weather, airspace, and crew briefing before every flight.",
  ),
  future(
    "mission-planning-and-operations",
    14,
    "post-flight-log-review",
    "Post-Flight Log Review",
    "What to inspect in every log after landing, trending metrics across flights, and how routine review catches problems before failure.",
  ),
  future(
    "mission-planning-and-operations",
    15,
    "incident-response",
    "Incident Response",
    "What to do immediately after a crash or near-miss, evidence preservation, regulatory reporting obligations, and root-cause analysis.",
  ),
];

const gisAndPhotogrammetryLessons: Lesson[] = [
  future(
    "gis-and-photogrammetry",
    1,
    "vector-and-raster-data",
    "Vector and Raster Data",
    "The two fundamental representations in GIS, their strengths and limitations, and when to convert between them.",
  ),
  future(
    "gis-and-photogrammetry",
    2,
    "shapefiles",
    "Shapefiles",
    "The Esri shapefile format, its component files, attribute tables, and why it persists despite well-known shortcomings.",
  ),
  future(
    "gis-and-photogrammetry",
    3,
    "geojson",
    "GeoJSON",
    "A JSON-native geospatial format, its geometry types, feature collections, and its role in web mapping and tooling pipelines.",
  ),
  future(
    "gis-and-photogrammetry",
    4,
    "geotiff",
    "GeoTIFF",
    "TIFF imagery with geospatial metadata baked in, internal tiling and overviews, and Cloud-Optimized GeoTIFF for fast remote access.",
  ),
  future(
    "gis-and-photogrammetry",
    5,
    "projection-systems",
    "Projection Systems",
    "How map projections trade off shape, area, distance, and direction, and choosing a projection appropriate to your task and region.",
  ),
  future(
    "gis-and-photogrammetry",
    6,
    "epsg-codes",
    "EPSG Codes",
    "How EPSG identifiers name coordinate reference systems precisely, looking them up, and using them in GDAL, PROJ, and GIS tooling.",
  ),
  future(
    "gis-and-photogrammetry",
    7,
    "qgis-workflow",
    "QGIS Workflow",
    "A guided tour of QGIS for loading data, styling layers, running geoprocessing tools, and producing print-quality maps.",
  ),
  future(
    "gis-and-photogrammetry",
    8,
    "georeferencing-imagery",
    "Georeferencing Imagery",
    "Aligning scanned maps or oblique imagery to a coordinate system using ground control points and polynomial or spline warps.",
  ),
  future(
    "gis-and-photogrammetry",
    9,
    "structure-from-motion-theory",
    "Structure-from-Motion Theory",
    "How overlapping photos taken from different viewpoints jointly recover camera poses and a sparse 3D scene reconstruction.",
  ),
  future(
    "gis-and-photogrammetry",
    10,
    "feature-matching",
    "Feature Matching",
    "Detectors and descriptors like SIFT, SURF, ORB, and Superpoint, and matching strategies including ratio tests and geometric verification.",
  ),
  future(
    "gis-and-photogrammetry",
    11,
    "photogrammetry-bundle-adjustment",
    "Bundle Adjustment for Photogrammetry",
    "The nonlinear least-squares optimization that refines camera poses and 3D points jointly, and the sparse structure that makes it tractable.",
  ),
  future(
    "gis-and-photogrammetry",
    12,
    "dense-reconstruction",
    "Dense Reconstruction",
    "Growing a dense point cloud from sparse SfM output using multi-view stereo, patch-based or plane-sweep methods.",
  ),
  future(
    "gis-and-photogrammetry",
    13,
    "orthomosaic-generation",
    "Orthomosaic Generation",
    "Reprojecting and blending many aerial images into a single seamless top-down orthorectified map of the survey area.",
  ),
  future(
    "gis-and-photogrammetry",
    14,
    "dem-vs-dsm",
    "DEMs vs DSMs",
    "Digital Elevation Models, Digital Surface Models, and Digital Terrain Models, and which one to produce for which application.",
  ),
  future(
    "gis-and-photogrammetry",
    15,
    "contour-generation",
    "Contour Generation",
    "Producing contour lines from elevation rasters, choosing intervals, and exporting them as vector data for engineering plans.",
  ),
  future(
    "gis-and-photogrammetry",
    16,
    "area-and-volume-measurements",
    "Area and Volume Measurements",
    "Calculating planar and surface area, and stockpile or cut-and-fill volumes from photogrammetric DEMs with uncertainty estimates.",
  ),
  future(
    "gis-and-photogrammetry",
    17,
    "gcp-placement",
    "Ground Control Point Placement",
    "How and where to place GCPs in a survey to anchor a reconstruction to real-world coordinates with minimal residual error.",
  ),
  future(
    "gis-and-photogrammetry",
    18,
    "pix4d-vs-agisoft-vs-opendronemap",
    "PIX4D vs Agisoft vs OpenDroneMap",
    "A comparison of the leading photogrammetry packages on accuracy, throughput, cost, automation, and reproducibility.",
  ),
  future(
    "gis-and-photogrammetry",
    19,
    "tiling-and-web-map-services",
    "Tiling and Web Map Services",
    "Slippy map tiles, WMS, WMTS, and XYZ schemes, and serving large rasters and vectors efficiently to browsers and mobile clients.",
  ),
  future(
    "gis-and-photogrammetry",
    20,
    "spatial-databases-and-postgis",
    "Spatial Databases and PostGIS",
    "Storing and querying geospatial data in PostGIS, spatial indexes, and common SQL patterns for buffers, intersections, and joins.",
  ),
];

const multispectralThermalAndLidarLessons: Lesson[] = [
  future(
    "multispectral-thermal-and-lidar",
    1,
    "electromagnetic-spectrum-review",
    "Electromagnetic Spectrum Review",
    "The bands of the EM spectrum used in remote sensing, from visible through near-infrared, thermal infrared, and microwave.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    2,
    "multispectral-cameras",
    "Multispectral Cameras",
    "How multispectral sensors split incoming light into discrete spectral bands using filters or beam splitters, and common products.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    3,
    "common-bands-nir-red-edge",
    "Common Bands: NIR and Red Edge",
    "The physical reason near-infrared and red-edge bands are uniquely informative for vegetation health and stress detection.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    4,
    "vegetation-indices-ndvi",
    "Vegetation Indices: NDVI and Friends",
    "Computing NDVI, NDRE, EVI, and SAVI from multispectral bands, what each index emphasizes, and how to interpret index maps.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    5,
    "thermal-cameras-and-radiometric-measurement",
    "Thermal Cameras and Radiometric Measurement",
    "How microbolometers measure long-wave infrared, what radiometric calibration provides, and emissivity corrections for real surfaces.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    6,
    "lidar-principles",
    "LiDAR Principles",
    "Active ranging with pulsed laser light, return detection, and the components that make up an airborne LiDAR system.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    7,
    "time-of-flight-vs-phase-shift",
    "Time-of-Flight vs Phase-Shift LiDAR",
    "Two ways to measure distance with light, their accuracy and range tradeoffs, and which technology dominates in different drone payloads.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    8,
    "point-cloud-data-formats",
    "Point Cloud Data Formats",
    "LAS, LAZ, and COPC formats, point record fields, classification codes, and best practices for storage and exchange.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    9,
    "ground-filtering",
    "Ground Filtering",
    "Algorithms like progressive morphological filtering and cloth simulation that separate ground returns from above-ground objects.",
  ),
  future(
    "multispectral-thermal-and-lidar",
    10,
    "lidar-mission-planning",
    "LiDAR Mission Planning",
    "Choosing altitude, speed, scan angle, and overlap to achieve a target point density and accuracy on the ground.",
  ),
];

export const dronesGisRemoteSensingLessons: Lesson[] = [
  ...coordinateSystemsLessons,
  ...aerodynamicsAndFlightMechanicsLessons,
  ...flightControlFirmwareLessons,
  ...missionPlanningAndOperationsLessons,
  ...gisAndPhotogrammetryLessons,
  ...multispectralThermalAndLidarLessons,
];
