import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "electronics-and-circuits";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const circuitLawsLessons: Lesson[] = [
  future(
    "circuit-laws",
    2,
    "kirchhoffs-voltage-law",
    "Kirchhoff's Voltage Law",
    "The sum of voltage drops around any closed loop equals zero, with sign conventions and worked loop examples.",
  ),
  future(
    "circuit-laws",
    3,
    "kirchhoffs-current-law",
    "Kirchhoff's Current Law",
    "Current into a node equals current out, the conservation-of-charge view, and applying KCL to multi-branch nodes.",
  ),
  future(
    "circuit-laws",
    4,
    "series-resistance-combinations",
    "Series Resistance Combinations",
    "Resistors in series add directly, why current is shared, and reducing chains of resistors to a single equivalent value.",
  ),
  future(
    "circuit-laws",
    5,
    "parallel-resistance-combinations",
    "Parallel Resistance Combinations",
    "Reciprocal addition for parallel resistors, the product-over-sum shortcut, and why parallel equivalents are always smaller than each branch.",
  ),
  future(
    "circuit-laws",
    6,
    "voltage-divider-rule",
    "The Voltage Divider Rule",
    "Deriving the divider equation, when it applies, and why a loaded divider deviates from the unloaded prediction.",
  ),
  future(
    "circuit-laws",
    7,
    "current-divider-rule",
    "The Current Divider Rule",
    "How current splits inversely with resistance through parallel branches, with derivation and worked examples.",
  ),
  future(
    "circuit-laws",
    8,
    "real-world-resistors-and-tolerance",
    "Real-World Resistors and Tolerance",
    "Resistor color codes, tolerance bands, power ratings, temperature coefficients, and choosing parts for a target accuracy.",
  ),
  future(
    "circuit-laws",
    9,
    "power-dissipation-in-resistive-circuits",
    "Power Dissipation in Resistive Circuits",
    "Three equivalent forms of P = VI, picking the right one for the data you have, and sizing resistors so they do not overheat.",
  ),
  future(
    "circuit-laws",
    10,
    "ideal-vs-real-voltage-sources",
    "Ideal vs Real Voltage Sources",
    "Internal resistance, loaded output voltage, source droop, and the line between an ideal model and the real battery or supply.",
  ),
  future(
    "circuit-laws",
    11,
    "ideal-vs-real-current-sources",
    "Ideal vs Real Current Sources",
    "Internal parallel resistance, compliance voltage, and where current sources appear inside op-amps and transistor bias circuits.",
  ),
  future(
    "circuit-laws",
    12,
    "conductance-and-siemens",
    "Conductance and the Siemens",
    "Conductance as the reciprocal of resistance, why parallel circuits are easier in conductance, and the siemens unit.",
  ),
  future(
    "circuit-laws",
    13,
    "delta-wye-transformations",
    "Delta-Wye Transformations",
    "Converting between delta and wye (pi and tee) resistor networks to simplify circuits that have no obvious series-parallel reduction.",
  ),
  future(
    "circuit-laws",
    14,
    "network-simplification-strategies",
    "Network Simplification Strategies",
    "A systematic approach to reducing complicated resistor networks by combining series, parallel, and delta-wye steps in sequence.",
  ),
  future(
    "circuit-laws",
    15,
    "measuring-voltage-current-and-resistance",
    "Measuring Voltage, Current, and Resistance",
    "Using a multimeter correctly, meter loading effects, the difference between in-series and across-the-element measurements, and safety.",
  ),
  future(
    "circuit-laws",
    16,
    "open-and-short-circuits",
    "Open and Short Circuits",
    "What truly happens at an open or a short, recognizing them in schematics, and using them as boundary conditions during analysis.",
  ),
];

const dcCircuitAnalysisLessons: Lesson[] = [
  future(
    "dc-circuit-analysis",
    1,
    "nodal-analysis-fundamentals",
    "Nodal Analysis Fundamentals",
    "Picking a reference node, writing KCL equations at each remaining node, and solving the resulting linear system for node voltages.",
  ),
  future(
    "dc-circuit-analysis",
    2,
    "nodal-analysis-with-voltage-sources",
    "Nodal Analysis with Voltage Sources",
    "Handling voltage sources between nodes, when a source pins a node directly, and preparing for the supernode technique.",
  ),
  future(
    "dc-circuit-analysis",
    3,
    "supernode-analysis",
    "Supernode Analysis",
    "Combining two nodes joined by an ideal voltage source into a supernode, writing one KCL equation, and pairing it with the source constraint.",
  ),
  future(
    "dc-circuit-analysis",
    4,
    "mesh-analysis-fundamentals",
    "Mesh Analysis Fundamentals",
    "Defining mesh currents in planar circuits, writing KVL around each mesh, and solving the linear system for the loop currents.",
  ),
  future(
    "dc-circuit-analysis",
    5,
    "mesh-analysis-with-current-sources",
    "Mesh Analysis with Current Sources",
    "Treating a current source that sits in a single mesh, shared current sources between meshes, and the path to supermeshes.",
  ),
  future(
    "dc-circuit-analysis",
    6,
    "supermesh-analysis",
    "Supermesh Analysis",
    "Combining two meshes that share a current source into a supermesh, writing one KVL equation, and adding the current-source constraint.",
  ),
  future(
    "dc-circuit-analysis",
    7,
    "linearity-and-the-superposition-principle",
    "Linearity and the Superposition Principle",
    "What linearity means for circuits, turning off independent sources correctly, and adding the partial responses to obtain the full answer.",
  ),
  future(
    "dc-circuit-analysis",
    8,
    "applying-superposition-to-multi-source-circuits",
    "Applying Superposition to Multi-Source Circuits",
    "Step-by-step walkthroughs of superposition on circuits with multiple voltage and current sources, including dependent-source cautions.",
  ),
  future(
    "dc-circuit-analysis",
    9,
    "source-transformations",
    "Source Transformations",
    "Converting between a voltage source with series resistance and a current source with parallel resistance to simplify analysis.",
  ),
  future(
    "dc-circuit-analysis",
    10,
    "thevenin-equivalent-circuits",
    "Thevenin Equivalent Circuits",
    "Reducing any linear two-terminal network to a single voltage source and series resistance from the load's point of view.",
  ),
  future(
    "dc-circuit-analysis",
    11,
    "norton-equivalent-circuits",
    "Norton Equivalent Circuits",
    "The dual of Thevenin: a current source in parallel with a resistance, and converting freely between Thevenin and Norton.",
  ),
  future(
    "dc-circuit-analysis",
    12,
    "finding-thevenin-resistance-with-dependent-sources",
    "Finding Thevenin Resistance with Dependent Sources",
    "Using a test-source method to find equivalent resistance when independent sources cannot simply be deactivated.",
  ),
  future(
    "dc-circuit-analysis",
    13,
    "maximum-power-transfer-theorem",
    "Maximum Power Transfer Theorem",
    "Deriving the load that extracts the most power from a Thevenin source, the efficiency tradeoff, and when this matching matters in practice.",
  ),
  future(
    "dc-circuit-analysis",
    14,
    "capacitors-in-dc-circuits",
    "Capacitors in DC Circuits",
    "Capacitance defined, Q = CV, the capacitor as an open circuit in steady state, and combining capacitors in series and parallel.",
  ),
  future(
    "dc-circuit-analysis",
    15,
    "inductors-in-dc-circuits",
    "Inductors in DC Circuits",
    "Inductance defined, V = L di/dt, the inductor as a short in steady state, and combining inductors in series and parallel.",
  ),
  future(
    "dc-circuit-analysis",
    16,
    "rc-charging-and-discharging",
    "RC Charging and Discharging",
    "First-order RC response, derivation of the exponential charge and discharge equations, and the meaning of initial and final values.",
  ),
  future(
    "dc-circuit-analysis",
    17,
    "rl-transient-response",
    "RL Transient Response",
    "First-order RL transients, the dual exponentials for current build-up and decay, and the inductive kick when current is interrupted.",
  ),
  future(
    "dc-circuit-analysis",
    18,
    "time-constants-and-settling",
    "Time Constants and Settling",
    "The time constant tau as a single number that characterizes first-order systems, settling to 1 percent, and reading tau from a scope trace.",
  ),
  future(
    "dc-circuit-analysis",
    19,
    "energy-stored-in-capacitors-and-inductors",
    "Energy Stored in Capacitors and Inductors",
    "Deriving (1/2) C V squared and (1/2) L I squared, and tracing energy flow through charge and discharge cycles.",
  ),
  future(
    "dc-circuit-analysis",
    20,
    "second-order-rlc-natural-response",
    "Second-Order RLC Natural Response",
    "Series and parallel RLC circuits, the characteristic equation, and overdamped, critically damped, and underdamped behavior.",
  ),
];

const acAndReactiveCircuitsLessons: Lesson[] = [
  future(
    "ac-and-reactive-circuits",
    1,
    "sinusoidal-sources-and-waveforms",
    "Sinusoidal Sources and Waveforms",
    "Amplitude, frequency, angular frequency, and phase for sinusoidal signals, and why nature, mains power, and oscillators choose sinusoids.",
  ),
  future(
    "ac-and-reactive-circuits",
    2,
    "phasor-representation-of-sinusoids",
    "Phasor Representation of Sinusoids",
    "Encoding a sinusoid as a complex number that captures amplitude and phase, and why this turns calculus into algebra.",
  ),
  future(
    "ac-and-reactive-circuits",
    3,
    "complex-impedance-of-resistors",
    "Complex Impedance of Resistors",
    "Why a resistor's impedance is a real number equal to R, and the in-phase voltage-current relationship.",
  ),
  future(
    "ac-and-reactive-circuits",
    4,
    "complex-impedance-of-inductors",
    "Complex Impedance of Inductors",
    "Inductor impedance jomegaL, current lagging voltage by 90 degrees, and frequency dependence.",
  ),
  future(
    "ac-and-reactive-circuits",
    5,
    "complex-impedance-of-capacitors",
    "Complex Impedance of Capacitors",
    "Capacitor impedance 1 over jomegaC, current leading voltage by 90 degrees, and frequency dependence.",
  ),
  future(
    "ac-and-reactive-circuits",
    6,
    "impedance-combination-rules",
    "Impedance Combination Rules",
    "Series and parallel rules for complex impedance, and treating phasor circuits with the same techniques as DC resistive circuits.",
  ),
  future(
    "ac-and-reactive-circuits",
    7,
    "ac-nodal-and-mesh-analysis",
    "AC Nodal and Mesh Analysis",
    "Applying nodal and mesh analysis in the phasor domain with complex impedances, then converting back to time-domain sinusoids.",
  ),
  future(
    "ac-and-reactive-circuits",
    8,
    "rms-and-average-values",
    "RMS and Average Values",
    "Root-mean-square as the DC-equivalent heating value, why mains is quoted as RMS, and the form factor for non-sinusoidal waves.",
  ),
  future(
    "ac-and-reactive-circuits",
    9,
    "average-and-instantaneous-ac-power",
    "Average and Instantaneous AC Power",
    "Instantaneous power oscillating at twice the source frequency, average power, and the role of the cosine of the phase angle.",
  ),
  future(
    "ac-and-reactive-circuits",
    10,
    "real-reactive-and-apparent-power",
    "Real, Reactive, and Apparent Power",
    "The power triangle, units of watts, vars, and VA, and the meaning of reactive power in transmission and motor systems.",
  ),
  future(
    "ac-and-reactive-circuits",
    11,
    "power-factor-and-correction",
    "Power Factor and Power Factor Correction",
    "Why utilities care about power factor, leading and lagging loads, and adding capacitors to correct an inductive load.",
  ),
  future(
    "ac-and-reactive-circuits",
    12,
    "ideal-transformers",
    "Ideal Transformers",
    "Voltage and current turn ratios, impedance reflection across a transformer, and the role of transformers in power distribution.",
  ),
  future(
    "ac-and-reactive-circuits",
    13,
    "series-rlc-circuits",
    "Series RLC Circuits",
    "Total impedance of a series RLC branch, magnitude and phase versus frequency, and the resonant frequency where reactance cancels.",
  ),
  future(
    "ac-and-reactive-circuits",
    14,
    "parallel-rlc-circuits",
    "Parallel RLC Circuits",
    "Total admittance of a parallel RLC branch, the impedance peak at resonance, and contrast with the series case.",
  ),
  future(
    "ac-and-reactive-circuits",
    15,
    "resonance-and-the-quality-factor",
    "Resonance and the Quality Factor",
    "Defining Q as energy stored over energy dissipated per cycle, bandwidth, selectivity, and the tradeoff between sharpness and damping.",
  ),
  future(
    "ac-and-reactive-circuits",
    16,
    "transfer-functions",
    "Transfer Functions",
    "Defining H(jomega) as the ratio of output to input phasor, and reading gain and phase shift directly from the transfer function.",
  ),
  future(
    "ac-and-reactive-circuits",
    17,
    "frequency-response-and-bode-plots",
    "Frequency Response and Bode Plots",
    "Plotting magnitude in decibels and phase in degrees on a log frequency axis, and the rules for sketching Bode plots by inspection.",
  ),
  future(
    "ac-and-reactive-circuits",
    18,
    "passive-low-pass-and-high-pass-filters",
    "Passive Low-Pass and High-Pass Filters",
    "First-order RC and RL filters, cutoff frequency at minus 3 dB, and the universal first-order roll-off of 20 dB per decade.",
  ),
  future(
    "ac-and-reactive-circuits",
    19,
    "band-pass-and-band-stop-filters",
    "Band-Pass and Band-Stop Filters",
    "Combining low-pass and high-pass behavior, RLC band-pass and notch topologies, and selecting components for a target center frequency.",
  ),
  future(
    "ac-and-reactive-circuits",
    20,
    "decibels-and-logarithmic-scales",
    "Decibels and Logarithmic Scales",
    "Decibels for power and voltage ratios, why log scales make filter cascades simple, and common dB landmarks worth memorizing.",
  ),
];

const semiconductorsAndTransistorCircuitsLessons: Lesson[] = [
  future(
    "semiconductors-and-transistor-circuits",
    1,
    "semiconductor-physics-basics",
    "Semiconductor Physics Basics",
    "Conductors, insulators, and semiconductors; doping with donors and acceptors; carriers, holes, and the meaning of band gap.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    2,
    "the-pn-junction",
    "The P-N Junction",
    "Forming a junction by joining p-type and n-type silicon, the depletion region, and the built-in potential barrier.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    3,
    "diode-i-v-characteristics",
    "Diode I-V Characteristics",
    "The Shockley diode equation, the exponential I-V curve, forward voltage drop, and reverse leakage and breakdown.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    4,
    "diode-circuit-models",
    "Diode Circuit Models",
    "The ideal diode, constant-voltage-drop model, piecewise-linear model, and choosing the right level of detail for the question at hand.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    5,
    "half-wave-and-full-wave-rectifiers",
    "Half-Wave and Full-Wave Rectifiers",
    "Converting AC to pulsating DC, the half-wave circuit, the full-wave bridge, and adding a filter capacitor to smooth the output.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    6,
    "zener-diode-voltage-regulators",
    "Zener Diode Voltage Regulators",
    "Operating a diode in reverse breakdown to clamp a voltage, sizing the series resistor, and load-current limits of a Zener regulator.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    7,
    "leds-photodiodes-and-special-diodes",
    "LEDs, Photodiodes, and Special Diodes",
    "Light-emitting diodes, photodiodes and solar cells, Schottky diodes, and varactors as voltage-controlled capacitors.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    8,
    "bjt-physics-and-structure",
    "BJT Physics and Structure",
    "Two back-to-back junctions, the emitter-base-collector structure, NPN and PNP polarities, and the role of minority carriers.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    9,
    "bjt-operating-modes",
    "BJT Operating Modes",
    "Cutoff, active, and saturation regions; recognizing each from the junction voltages; and choosing the right mode for the application.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    10,
    "bjt-as-a-switch",
    "BJT as a Switch",
    "Driving the transistor between cutoff and saturation, computing the base resistor, and using a BJT to switch LEDs and small loads.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    11,
    "bjt-biasing-techniques",
    "BJT Biasing Techniques",
    "Fixed bias, emitter degeneration, and voltage-divider bias; the stability tradeoffs; and designing for a target quiescent collector current.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    12,
    "common-emitter-amplifier",
    "Common-Emitter Amplifier",
    "Topology, voltage gain, input and output impedance, and the inverting nature of the common-emitter configuration.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    13,
    "common-collector-and-common-base",
    "Common-Collector and Common-Base Amplifiers",
    "Emitter follower as a buffer, common-base as a current-driven stage, and where each is preferred in a real signal chain.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    14,
    "bjt-small-signal-models",
    "BJT Small-Signal Models",
    "Hybrid-pi and tee models, computing g_m and r_pi from bias, and using small-signal models for hand analysis.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    15,
    "mosfet-physics-and-structure",
    "MOSFET Physics and Structure",
    "The metal-oxide-semiconductor stack, channel formation, enhancement and depletion modes, and N-channel versus P-channel devices.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    16,
    "mosfet-i-v-characteristics",
    "MOSFET I-V Characteristics",
    "Threshold voltage, triode and saturation regions, the square-law drain current, and reading characteristics off a datasheet.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    17,
    "mosfet-as-a-switch",
    "MOSFET as a Switch",
    "Driving a MOSFET hard on and off, R_DS(on), gate-drive considerations, and using a MOSFET for power switching loads.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    18,
    "mosfet-amplifier-stages",
    "MOSFET Amplifier Stages",
    "Common-source, common-drain (source follower), and common-gate amplifiers; comparing them to the BJT counterparts.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    19,
    "mosfet-biasing-and-small-signal-models",
    "MOSFET Biasing and Small-Signal Models",
    "Self-bias and voltage-divider bias for FETs, the small-signal MOSFET model, and using g_m and r_o for gain calculations.",
  ),
  future(
    "semiconductors-and-transistor-circuits",
    20,
    "introduction-to-cmos-logic",
    "Introduction to CMOS Logic",
    "Complementary N and P MOSFETs forming inverters and NAND gates, low static power, and CMOS as the foundation of modern digital ICs.",
  ),
];

const opAmpsAndAnalogLessons: Lesson[] = [
  future(
    "op-amps-and-analog",
    1,
    "the-ideal-op-amp",
    "The Ideal Op-Amp",
    "Infinite gain, infinite input impedance, zero output impedance, and using the ideal model to analyze circuits at lightning speed.",
  ),
  future(
    "op-amps-and-analog",
    2,
    "the-virtual-short-principle",
    "The Virtual Short Principle",
    "How negative feedback drives the differential input voltage to zero, and using the virtual short to solve op-amp circuits by inspection.",
  ),
  future(
    "op-amps-and-analog",
    3,
    "inverting-amplifier",
    "Inverting Amplifier",
    "Closed-loop gain set by two resistors, the virtual ground at the inverting input, and input and output impedance of the topology.",
  ),
  future(
    "op-amps-and-analog",
    4,
    "non-inverting-amplifier",
    "Non-Inverting Amplifier",
    "Closed-loop gain of 1 + Rf/Rg, very high input impedance, and unity-gain buffers as the simplest special case.",
  ),
  future(
    "op-amps-and-analog",
    5,
    "summing-amplifier",
    "Summing Amplifier",
    "Adding multiple weighted input voltages at a virtual ground, and using the summing junction for analog mixing and DACs.",
  ),
  future(
    "op-amps-and-analog",
    6,
    "differential-amplifier",
    "Differential Amplifier",
    "Subtracting two input voltages, common-mode rejection, and choosing resistor ratios to make the configuration work as advertised.",
  ),
  future(
    "op-amps-and-analog",
    7,
    "instrumentation-amplifier",
    "Instrumentation Amplifier",
    "The three-op-amp instrumentation amplifier, sky-high input impedance, programmable gain, and use with strain gauges and thermocouples.",
  ),
  future(
    "op-amps-and-analog",
    8,
    "integrator-circuit",
    "Op-Amp Integrator",
    "Capacitor in the feedback path makes the output proportional to the integral of the input, with leakage resistor for DC stability.",
  ),
  future(
    "op-amps-and-analog",
    9,
    "differentiator-circuit",
    "Op-Amp Differentiator",
    "Capacitor in the input path makes the output proportional to the derivative of the input, with input resistor for noise control.",
  ),
  future(
    "op-amps-and-analog",
    10,
    "real-op-amp-limitations",
    "Real Op-Amp Limitations",
    "Finite open-loop gain, gain-bandwidth product, slew rate, input bias and offset, and CMRR; choosing the right part for the job.",
  ),
  future(
    "op-amps-and-analog",
    11,
    "comparators-and-schmitt-triggers",
    "Comparators and Schmitt Triggers",
    "Open-loop comparators, the chatter problem, and adding positive feedback to create hysteresis with the Schmitt trigger.",
  ),
  future(
    "op-amps-and-analog",
    12,
    "active-filters",
    "Active Filters",
    "Sallen-Key and multiple-feedback topologies for low-pass, high-pass, and band-pass filters that exceed passive performance.",
  ),
  future(
    "op-amps-and-analog",
    13,
    "op-amp-oscillators",
    "Op-Amp Oscillators",
    "Wien-bridge, phase-shift, and relaxation oscillators; the Barkhausen criterion; and amplitude stabilization techniques.",
  ),
  future(
    "op-amps-and-analog",
    14,
    "signal-conditioning-for-sensors",
    "Signal Conditioning for Sensors",
    "Amplifying, filtering, and level-shifting raw sensor signals so an ADC sees a clean voltage in the right range.",
  ),
  future(
    "op-amps-and-analog",
    15,
    "voltage-references-and-precision-techniques",
    "Voltage References and Precision Techniques",
    "Bandgap references, choosing a reference for an ADC or DAC, chopper stabilization, and auto-zero techniques for precision measurement.",
  ),
];

const digitalLogicAndArchitectureLessons: Lesson[] = [
  future(
    "digital-logic-and-architecture",
    1,
    "binary-and-hexadecimal-representation",
    "Binary and Hexadecimal Representation",
    "Counting in binary and hex, conversions between bases, and why bytes naturally group into nibbles when humans read addresses.",
  ),
  future(
    "digital-logic-and-architecture",
    2,
    "twos-complement-and-signed-integers",
    "Two's Complement and Signed Integers",
    "Representing negative numbers without a sign bit kludge, range of an n-bit value, and addition that just works for signed and unsigned.",
  ),
  future(
    "digital-logic-and-architecture",
    3,
    "boolean-algebra-fundamentals",
    "Boolean Algebra Fundamentals",
    "Boolean variables, the operations AND, OR, NOT, axioms, identities, and the duality between sum-of-products and product-of-sums.",
  ),
  future(
    "digital-logic-and-architecture",
    4,
    "logic-gates-and-truth-tables",
    "Logic Gates and Truth Tables",
    "Symbols, truth tables, and CMOS implementations of AND, OR, NOT, NAND, NOR, XOR, and XNOR.",
  ),
  future(
    "digital-logic-and-architecture",
    5,
    "universal-gates-and-functional-completeness",
    "Universal Gates and Functional Completeness",
    "Why NAND alone or NOR alone can build any logic function, and what that means for VLSI design and CPU fabrication.",
  ),
  future(
    "digital-logic-and-architecture",
    6,
    "karnaugh-maps-and-logic-minimization",
    "Karnaugh Maps and Logic Minimization",
    "K-maps for two through six variables, grouping ones, dealing with don't-cares, and reading a minimized expression off the map.",
  ),
  future(
    "digital-logic-and-architecture",
    7,
    "combinational-circuit-design",
    "Combinational Circuit Design",
    "A methodology for going from a problem statement, to a truth table, to a minimized Boolean expression, to a gate-level schematic.",
  ),
  future(
    "digital-logic-and-architecture",
    8,
    "multiplexers-and-demultiplexers",
    "Multiplexers and Demultiplexers",
    "Selecting one of N inputs, routing one input to one of N outputs, and using MUXes as universal logic elements.",
  ),
  future(
    "digital-logic-and-architecture",
    9,
    "encoders-and-decoders",
    "Encoders and Decoders",
    "Binary and priority encoders, 3-to-8 and similar decoders, and using decoders for memory chip selection.",
  ),
  future(
    "digital-logic-and-architecture",
    10,
    "adders-and-arithmetic-circuits",
    "Adders and Arithmetic Circuits",
    "Half adder, full adder, ripple-carry and carry-look-ahead adders, and the central role of the adder in any ALU.",
  ),
  future(
    "digital-logic-and-architecture",
    11,
    "comparators-and-arithmetic-logic-units",
    "Comparators and Arithmetic Logic Units",
    "Magnitude comparators, combining adders with logic gates to form an ALU, and the ALU's place inside a CPU datapath.",
  ),
  future(
    "digital-logic-and-architecture",
    12,
    "latches-and-flip-flops",
    "Latches and Flip-Flops",
    "SR, D, JK, and T elements; the distinction between level-sensitive latches and edge-triggered flip-flops; setup and hold time.",
  ),
  future(
    "digital-logic-and-architecture",
    13,
    "registers-and-shift-registers",
    "Registers and Shift Registers",
    "Parallel-load registers, serial-in serial-out, serial-in parallel-out, and shift registers for serial-to-parallel conversion.",
  ),
  future(
    "digital-logic-and-architecture",
    14,
    "counters-and-timing-circuits",
    "Counters and Timing Circuits",
    "Asynchronous ripple counters, synchronous counters, modulo-N counters, and the timing diagrams that justify each design.",
  ),
  future(
    "digital-logic-and-architecture",
    15,
    "finite-state-machine-fundamentals",
    "Finite-State Machine Fundamentals",
    "States, transitions, inputs, outputs, Moore and Mealy machines, and drawing the state diagram before writing any logic.",
  ),
  future(
    "digital-logic-and-architecture",
    16,
    "designing-finite-state-machines",
    "Designing Finite-State Machines",
    "From state diagram to state table to flip-flop-based implementation, with state-encoding choices and worked examples.",
  ),
  future(
    "digital-logic-and-architecture",
    17,
    "memory-organization-rom-and-ram",
    "Memory Organization: ROM and RAM",
    "Static and dynamic RAM, ROM and EEPROM, address decoding, memory cell structure, and the speed-density-cost tradeoff.",
  ),
  future(
    "digital-logic-and-architecture",
    18,
    "clock-distribution-and-timing",
    "Clock Distribution and Timing",
    "Clock skew, jitter, the fundamental cycle-time equation, and why a chip's clock tree is some of its trickiest engineering.",
  ),
  future(
    "digital-logic-and-architecture",
    19,
    "von-neumann-and-harvard-architectures",
    "Von Neumann and Harvard Architectures",
    "Single shared bus versus separate program and data buses, and where you actually see each in modern microcontrollers.",
  ),
  future(
    "digital-logic-and-architecture",
    20,
    "instruction-set-architecture",
    "Instruction Set Architecture",
    "ISA as the contract between hardware and software, instruction formats, addressing modes, and RISC versus CISC philosophies.",
  ),
  future(
    "digital-logic-and-architecture",
    21,
    "cpu-datapath-design",
    "CPU Datapath Design",
    "Registers, ALU, multiplexers, and memory interface wired into a single-cycle datapath, traced for one example instruction.",
  ),
  future(
    "digital-logic-and-architecture",
    22,
    "control-unit-design",
    "Control Unit Design",
    "Hardwired control versus microcoded control, generating control signals from the opcode, and the FSM at the heart of the control unit.",
  ),
  future(
    "digital-logic-and-architecture",
    23,
    "pipelining-basics",
    "Pipelining Basics",
    "Breaking instruction execution into stages, the throughput gain, and pipeline hazards: structural, data, and control.",
  ),
  future(
    "digital-logic-and-architecture",
    24,
    "memory-hierarchy-and-caches",
    "Memory Hierarchy and Caches",
    "Registers, L1, L2, L3 caches, main memory, and storage; locality of reference; and why caches make modern CPUs feel fast.",
  ),
  future(
    "digital-logic-and-architecture",
    25,
    "introduction-to-fpgas-and-hdls",
    "Introduction to FPGAs and HDLs",
    "Look-up tables, configurable logic blocks, hardware description languages, and how an FPGA differs from a general-purpose CPU.",
  ),
];

const microcontrollerEmbeddedProgrammingLessons: Lesson[] = [
  future(
    "microcontroller-embedded-programming",
    1,
    "microcontroller-architecture-overview",
    "Microcontroller Architecture Overview",
    "CPU core, memory map, peripherals, clocks, and buses inside a typical microcontroller, and the mental model for embedded work.",
  ),
  future(
    "microcontroller-embedded-programming",
    2,
    "memory-map-and-special-function-registers",
    "Memory Map and Special Function Registers",
    "Flash, SRAM, and peripheral regions; memory-mapped I/O; and reading and writing special function registers from C.",
  ),
  future(
    "microcontroller-embedded-programming",
    3,
    "gpio-configuration-and-control",
    "GPIO Configuration and Control",
    "Setting up pin direction, pull-ups, drive strength, and alternate functions; and reading and writing GPIO ports.",
  ),
  future(
    "microcontroller-embedded-programming",
    4,
    "digital-input-with-debouncing",
    "Digital Input with Debouncing",
    "Reading switches and buttons, the bounce problem, software and hardware debouncing techniques, and detecting edges versus levels.",
  ),
  future(
    "microcontroller-embedded-programming",
    5,
    "digital-output-driving-loads",
    "Digital Output and Driving Loads",
    "Source and sink current limits, driving LEDs through resistors, and using transistors or buffers for larger loads.",
  ),
  future(
    "microcontroller-embedded-programming",
    6,
    "analog-to-digital-converters",
    "Analog-to-Digital Converters",
    "Successive approximation and sigma-delta ADCs, resolution, sampling rate, reference voltage, and reading a sensor with the on-chip ADC.",
  ),
  future(
    "microcontroller-embedded-programming",
    7,
    "digital-to-analog-converters",
    "Digital-to-Analog Converters",
    "On-chip DACs, output range and impedance, and using a DAC for audio, waveform generation, and analog control voltages.",
  ),
  future(
    "microcontroller-embedded-programming",
    8,
    "pulse-width-modulation",
    "Pulse-Width Modulation",
    "PWM as a way to control average power, choosing frequency and duty cycle, and applications to LEDs, motors, and servos.",
  ),
  future(
    "microcontroller-embedded-programming",
    9,
    "timers-and-counters",
    "Timers and Counters",
    "Hardware timers, prescalers, compare and capture modes, and using timers for precise delays and event counting.",
  ),
  future(
    "microcontroller-embedded-programming",
    10,
    "interrupts-and-isrs",
    "Interrupts and Interrupt Service Routines",
    "Interrupt vectors, priorities, latency, nesting, and writing ISRs that finish fast and play well with the rest of the firmware.",
  ),
  future(
    "microcontroller-embedded-programming",
    11,
    "uart-serial-communication",
    "UART Serial Communication",
    "Asynchronous serial framing, baud rate, parity and stop bits, and using a USB-to-UART bridge for printf-style debugging.",
  ),
  future(
    "microcontroller-embedded-programming",
    12,
    "i2c-protocol",
    "I2C Protocol",
    "Two-wire I2C bus, master and slave roles, addressing, start and stop conditions, and connecting sensors and EEPROMs.",
  ),
  future(
    "microcontroller-embedded-programming",
    13,
    "spi-protocol",
    "SPI Protocol",
    "Four-wire SPI, master and slave, clock polarity and phase modes, and high-speed transfers to displays and flash chips.",
  ),
  future(
    "microcontroller-embedded-programming",
    14,
    "can-and-other-embedded-buses",
    "CAN and Other Embedded Buses",
    "Controller Area Network for robust multi-node automotive and industrial messaging, plus a tour of RS-485 and 1-Wire.",
  ),
  future(
    "microcontroller-embedded-programming",
    15,
    "sleep-modes-and-low-power-design",
    "Sleep Modes and Low-Power Design",
    "Run, sleep, stop, and standby modes; choosing the right wake sources; and designing firmware for battery life.",
  ),
  future(
    "microcontroller-embedded-programming",
    16,
    "watchdog-timers-and-reliability",
    "Watchdog Timers and Reliability",
    "Independent and window watchdogs, brown-out detection, recovering from a hung firmware path, and writing watchdog-safe code.",
  ),
  future(
    "microcontroller-embedded-programming",
    17,
    "bootloaders-and-firmware-updates",
    "Bootloaders and Firmware Updates",
    "How a bootloader hands off to the application image, in-system programming, and designing a safe over-the-air update flow.",
  ),
  future(
    "microcontroller-embedded-programming",
    18,
    "firmware-project-structure",
    "Firmware Project Structure",
    "Organizing source into HAL, drivers, application, and tests; managing build configurations; and keeping a project sane as it grows.",
  ),
  future(
    "microcontroller-embedded-programming",
    19,
    "arduino-ide-workflow",
    "Arduino IDE Workflow",
    "Boards, libraries, the setup-and-loop pattern, and using Arduino as a productive starting point for AVR, SAMD, and ESP boards.",
  ),
  future(
    "microcontroller-embedded-programming",
    20,
    "stm32-and-cubeide-workflow",
    "STM32 and CubeIDE Workflow",
    "Picking an STM32 part, generating initialization code with CubeMX, using the HAL library, and debugging with ST-Link.",
  ),
  future(
    "microcontroller-embedded-programming",
    21,
    "esp32-architecture-and-toolchain",
    "ESP32 Architecture and Toolchain",
    "Dual-core Xtensa or RISC-V cores, the ESP-IDF framework, partition tables, and how the ESP32 differs from classic 32-bit MCUs.",
  ),
  future(
    "microcontroller-embedded-programming",
    22,
    "esp32-wifi-and-bluetooth",
    "ESP32 Wi-Fi and Bluetooth",
    "Bringing up Wi-Fi station and AP modes, simple TCP and HTTP clients, BLE GATT services, and provisioning a device on a network.",
  ),
  future(
    "microcontroller-embedded-programming",
    23,
    "freertos-tasks-and-scheduling",
    "FreeRTOS Tasks and Scheduling",
    "Tasks, priorities, the scheduler, stack sizing, and migrating from a bare-metal super-loop to a preemptive RTOS.",
  ),
  future(
    "microcontroller-embedded-programming",
    24,
    "freertos-synchronization-primitives",
    "FreeRTOS Synchronization Primitives",
    "Queues, semaphores, mutexes, event groups, and choosing the right primitive to avoid priority inversion and deadlocks.",
  ),
  future(
    "microcontroller-embedded-programming",
    25,
    "debugging-embedded-systems",
    "Debugging Embedded Systems",
    "Using a JTAG or SWD debugger, hard-fault analysis, logic analyzers and scopes, and a disciplined approach to embedded bugs.",
  ),
];

export const electronicsAndCircuitsLessons: Lesson[] = [
  ...circuitLawsLessons,
  ...dcCircuitAnalysisLessons,
  ...acAndReactiveCircuitsLessons,
  ...semiconductorsAndTransistorCircuitsLessons,
  ...opAmpsAndAnalogLessons,
  ...digitalLogicAndArchitectureLessons,
  ...microcontrollerEmbeddedProgrammingLessons,
];
