import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "machine-learning-and-ai";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const mlFoundations: Lesson[] = [
  future("ml-foundations", 1, "what-is-machine-learning", "What Is Machine Learning?", "A working definition of learning from data, the contrast with classical programming, and where ML actually earns its keep."),
  future("ml-foundations", 2, "supervised-unsupervised-and-reinforcement-learning", "Supervised, Unsupervised, and Reinforcement Learning", "The three canonical learning settings, their data assumptions, and the kinds of problems each one solves."),
  future("ml-foundations", 3, "the-loss-and-optimization-framing", "The Loss and Optimization Framing", "Reframing learning as minimizing a loss function over a hypothesis class, the universal recipe behind almost every ML algorithm."),
  future("ml-foundations", 4, "empirical-risk-minimization", "Empirical Risk Minimization", "The principle of choosing the hypothesis that minimizes loss on the training sample, with its assumptions and failure modes."),
  future("ml-foundations", 5, "training-versus-test-error", "Training Versus Test Error", "Why training error underestimates true error, the role of held-out data, and the meaning of generalization gap."),
  future("ml-foundations", 6, "bias-variance-decomposition", "Bias-Variance Decomposition", "Splitting expected prediction error into bias, variance, and irreducible noise, and the tradeoff this exposes."),
  future("ml-foundations", 7, "the-no-free-lunch-theorem", "The No-Free-Lunch Theorem", "Why no learning algorithm is universally best across all problems, and what this means for inductive bias in practice."),
  future("ml-foundations", 8, "generalization-bounds-intuition", "Generalization Bounds Intuition", "How probabilistic bounds on test error scale with sample size, hypothesis class complexity, and confidence level."),
  future("ml-foundations", 9, "vc-dimension", "VC Dimension", "Vapnik-Chervonenkis dimension as a combinatorial measure of hypothesis class capacity, with worked examples."),
  future("ml-foundations", 10, "regularization-theory", "Regularization Theory", "Regularization as a structural prior on the hypothesis class, the bias-variance lens, and L1 versus L2 penalties."),
  future("ml-foundations", 11, "cross-validation", "Cross-Validation", "K-fold and leave-one-out cross-validation as estimators of generalization error, with bias-variance properties of each."),
  future("ml-foundations", 12, "model-selection", "Model Selection", "Principled comparison of candidate models, validation sets, information criteria, and the danger of leakage."),
  future("ml-foundations", 13, "the-curse-of-dimensionality", "The Curse of Dimensionality", "How distance, density, and sample requirements degrade in high dimensions, and which methods are most affected."),
  future("ml-foundations", 14, "kernel-intuition", "Kernel Intuition", "Implicit feature maps via kernels, the kernel trick, and why nonlinear similarity is computable without explicit lifting."),
  future("ml-foundations", 15, "hypothesis-classes", "Hypothesis Classes", "Hypothesis classes as the search space of a learner, the role of expressiveness, and matching class capacity to problem complexity."),
];

const classicalMlAlgorithms: Lesson[] = [
  future("classical-ml-algorithms", 1, "linear-regression-ols", "Linear Regression by Ordinary Least Squares", "The closed-form OLS solution, geometric interpretation as projection, and the Gauss-Markov assumptions."),
  future("classical-ml-algorithms", 2, "ridge-regression", "Ridge Regression", "L2-penalized regression, its closed-form solution, and the bias-variance bargain it makes against OLS."),
  future("classical-ml-algorithms", 3, "lasso-regression", "Lasso Regression", "L1-penalized regression, sparsity as a feature selection mechanism, and the coordinate descent solver."),
  future("classical-ml-algorithms", 4, "polynomial-regression", "Polynomial Regression", "Fitting nonlinear curves with polynomial features, the overfitting risk at high degree, and feature engineering trade-offs."),
  future("classical-ml-algorithms", 5, "logistic-regression", "Logistic Regression", "The sigmoid link function, maximum likelihood estimation for binary outcomes, and decision boundaries."),
  future("classical-ml-algorithms", 6, "multinomial-classification", "Multinomial Classification", "Softmax regression for multi-class problems, cross-entropy loss, and one-vs-rest versus one-vs-one schemes."),
  future("classical-ml-algorithms", 7, "naive-bayes-classifier", "Naive Bayes Classifier", "The conditional independence assumption, Gaussian and multinomial variants, and why naive Bayes works despite being wrong."),
  future("classical-ml-algorithms", 8, "k-nearest-neighbors", "k-Nearest Neighbors", "Lazy learning, distance metrics, the role of k, and computational tradeoffs of memory-based prediction."),
  future("classical-ml-algorithms", 9, "decision-trees", "Decision Trees", "Recursive partitioning of feature space, greedy split selection, and stopping criteria that prevent overfitting."),
  future("classical-ml-algorithms", 10, "entropy-and-information-gain", "Entropy and Information Gain", "Information-theoretic split criteria including entropy, Gini impurity, and how trees choose features to maximize purity."),
  future("classical-ml-algorithms", 11, "random-forests", "Random Forests", "Bagging plus feature subsampling to decorrelate trees, out-of-bag error, and feature importance measurement."),
  future("classical-ml-algorithms", 12, "gradient-boosting", "Gradient Boosting (XGBoost, LightGBM)", "Sequential weak learners fit to residuals, regularized boosting, and why GBDTs dominate tabular benchmarks."),
  future("classical-ml-algorithms", 13, "hard-margin-svms", "Hard-Margin SVMs", "Maximum margin classifiers, the support vector formulation, and the quadratic program at the heart of an SVM."),
  future("classical-ml-algorithms", 14, "soft-margin-svms", "Soft-Margin SVMs", "Slack variables for non-separable data, the hinge loss interpretation, and the role of the C hyperparameter."),
  future("classical-ml-algorithms", 15, "kernel-svms", "Kernel SVMs", "Polynomial, RBF, and sigmoid kernels, the dual formulation, and SVMs as universal nonlinear classifiers."),
  future("classical-ml-algorithms", 16, "k-means-clustering", "k-Means Clustering", "Lloyd's algorithm, the k-means objective, initialization with k-means++, and choosing k via the elbow and silhouette."),
  future("classical-ml-algorithms", 17, "hierarchical-clustering", "Hierarchical Clustering", "Agglomerative and divisive clustering, linkage criteria, and reading dendrograms to choose cluster counts."),
  future("classical-ml-algorithms", 18, "gaussian-mixture-models-and-em", "Gaussian Mixture Models and EM", "Soft clustering with mixture models, the expectation-maximization algorithm, and convergence to local optima."),
  future("classical-ml-algorithms", 19, "principal-component-analysis", "Principal Component Analysis", "PCA as variance-maximizing projection, its SVD-based computation, and how to interpret principal components."),
  future("classical-ml-algorithms", 20, "t-sne-and-umap", "t-SNE and UMAP", "Nonlinear manifold embeddings for visualization, perplexity and neighborhood parameters, and reading 2D embeddings honestly."),
];

const deepLearningTheory: Lesson[] = [
  future("deep-learning-theory", 1, "perceptrons-and-biological-motivation", "Perceptrons and Biological Motivation", "The Rosenblatt perceptron, its linear separability limits, and the loose biological analogy that inspired neural networks."),
  future("deep-learning-theory", 2, "multilayer-perceptrons", "Multilayer Perceptrons", "Stacking linear layers with nonlinearities to gain expressive power, and the basic feedforward architecture."),
  future("deep-learning-theory", 3, "activation-functions", "Activation Functions", "Sigmoid, tanh, ReLU, GELU, and SiLU, with the tradeoffs between gradient flow, saturation, and computational cost."),
  future("deep-learning-theory", 4, "universal-approximation-theorem", "The Universal Approximation Theorem", "Why a single hidden layer can approximate any continuous function, and why depth still matters in practice."),
  future("deep-learning-theory", 5, "forward-and-backward-propagation", "Forward and Backward Propagation", "Forward pass to compute outputs and loss, backward pass to compute gradients, and the data flow of training."),
  future("deep-learning-theory", 6, "the-chain-rule-for-backprop", "The Chain Rule for Backpropagation", "Backprop as a careful application of the chain rule, with derivations for a small two-layer network worked by hand."),
  future("deep-learning-theory", 7, "computational-graphs", "Computational Graphs", "Representing computation as a DAG of operations, autodiff in forward and reverse mode, and the basis of modern frameworks."),
  future("deep-learning-theory", 8, "gradient-descent-variants", "Gradient Descent Variants", "Batch, mini-batch, and stochastic gradient descent, with the variance and convergence properties of each."),
  future("deep-learning-theory", 9, "momentum", "Momentum", "Classical and Nesterov momentum as exponential averaging of gradients, and the geometry of escaping ravines."),
  future("deep-learning-theory", 10, "rmsprop", "RMSProp", "Per-parameter adaptive learning rates based on running gradient magnitudes, and the path from AdaGrad to RMSProp."),
  future("deep-learning-theory", 11, "adam-optimizer", "The Adam Optimizer", "Combining momentum with adaptive learning rates, bias correction, and Adam's role as a default for deep nets."),
  future("deep-learning-theory", 12, "adamw-and-weight-decay", "AdamW and Decoupled Weight Decay", "Why L2 regularization and weight decay differ for adaptive optimizers, and the AdamW fix that became standard."),
  future("deep-learning-theory", 13, "learning-rate-schedules", "Learning Rate Schedules", "Step, cosine, warmup, and one-cycle schedules, and how schedule choice interacts with batch size and model depth."),
  future("deep-learning-theory", 14, "weight-initialization", "Weight Initialization (Xavier, He)", "Variance-preserving initialization for sigmoid and ReLU networks, and what happens when initialization is wrong."),
  future("deep-learning-theory", 15, "batch-normalization", "Batch Normalization", "Normalizing activations across the batch, the affine parameters, and why batch norm trains faster but introduces train/eval differences."),
  future("deep-learning-theory", 16, "layer-normalization", "Layer Normalization", "Per-sample normalization across features, why it works for transformers, and contrasts with batch and group norm."),
  future("deep-learning-theory", 17, "dropout", "Dropout", "Random unit deactivation as implicit ensembling, inverted dropout at training time, and the connection to Bayesian inference."),
  future("deep-learning-theory", 18, "data-augmentation", "Data Augmentation", "Label-preserving input transformations for images, audio, and text, and augmentation as a form of regularization."),
  future("deep-learning-theory", 19, "label-smoothing", "Label Smoothing", "Soft targets in place of one-hot labels, the calibration benefits, and the cost when distillation is the downstream goal."),
  future("deep-learning-theory", 20, "overfitting-and-regularization", "Overfitting and Regularization", "Symptoms of overfitting in deep nets, weight decay, early stopping, and the menu of regularizers in modern training."),
  future("deep-learning-theory", 21, "double-descent", "Double Descent", "The non-monotonic relationship between model size and generalization, and what double descent reveals about classical wisdom."),
  future("deep-learning-theory", 22, "lottery-ticket-hypothesis", "The Lottery Ticket Hypothesis", "Sparse subnetworks inside dense networks that train in isolation, and what this implies about initialization and pruning."),
  future("deep-learning-theory", 23, "training-dynamics-intuition", "Training Dynamics Intuition", "Loss landscapes, edge of stability, grokking, and the empirical phenomena that govern how deep nets actually learn."),
  future("deep-learning-theory", 24, "scaling-laws", "Scaling Laws", "Power-law relationships between model size, data, and compute, and how Chinchilla-style scaling guides model design."),
  future("deep-learning-theory", 25, "mixed-precision-training", "Mixed Precision Training", "FP16 and BF16 training with loss scaling, when precision matters, and how mixed precision halves memory without hurting accuracy."),
];

const deepLearningArchitectures: Lesson[] = [
  future("deep-learning-architectures", 1, "cnn-basics-and-feature-hierarchy", "CNN Basics and Feature Hierarchy", "Convolutions as translation-equivariant filters, channels, strides, padding, and the emergent feature hierarchy."),
  future("deep-learning-architectures", 2, "classic-cnn-architectures", "Classic CNN Architectures (LeNet, AlexNet, VGG)", "The progression from LeNet through AlexNet to VGG, and the design decisions that defined each generation."),
  future("deep-learning-architectures", 3, "residual-networks", "Residual Networks", "Skip connections that enable training of very deep networks, the identity mapping argument, and ResNet variants."),
  future("deep-learning-architectures", 4, "batch-norm-in-cnns", "Batch Norm in CNNs", "How batch normalization integrates with convolutional layers, channel-wise statistics, and inference-time behavior."),
  future("deep-learning-architectures", 5, "modern-cnn-backbones", "Modern CNN Backbones (ResNet, EfficientNet, ConvNeXt)", "Compound scaling, depthwise separable convolutions, and the ConvNeXt redesign that closes the gap with transformers."),
  future("deep-learning-architectures", 6, "rnn-basics", "RNN Basics", "Recurrent computation through time, hidden state as memory, and the vanilla RNN forward pass."),
  future("deep-learning-architectures", 7, "vanishing-gradients-in-rnns", "Vanishing Gradients in RNNs", "Why backprop through time fails for long sequences, the role of Jacobian eigenvalues, and gradient clipping as a partial fix."),
  future("deep-learning-architectures", 8, "lstm-cells", "LSTM Cells", "The cell state, input, forget, and output gates, and how LSTMs preserve gradient flow over long ranges."),
  future("deep-learning-architectures", 9, "gru-cells", "GRU Cells", "Gated recurrent units as a simpler alternative to LSTMs, the update and reset gates, and the empirical tradeoffs."),
  future("deep-learning-architectures", 10, "sequence-to-sequence-models", "Sequence-to-Sequence Models", "Encoder-decoder RNNs for variable-length input and output, teacher forcing, and the original machine translation setup."),
  future("deep-learning-architectures", 11, "encoder-decoder-architecture", "The Encoder-Decoder Architecture", "Separating representation construction from generation, with applications across translation, summarization, and speech."),
  future("deep-learning-architectures", 12, "attention-mechanism", "The Attention Mechanism", "Bahdanau attention as a soft alignment between decoder and encoder states, and the conceptual leap from fixed context vectors."),
  future("deep-learning-architectures", 13, "scaled-dot-product-attention", "Scaled Dot-Product Attention", "Query, key, value formulation, the scaling factor, and the softmax normalization at the core of every transformer."),
  future("deep-learning-architectures", 14, "multi-head-attention", "Multi-Head Attention", "Parallel attention heads as multiple views of relationships, parameter sharing, and the role of head count."),
  future("deep-learning-architectures", 15, "the-transformer-architecture", "The Transformer Architecture", "The full encoder-decoder transformer with attention, feedforward layers, residual connections, and layer norm."),
  future("deep-learning-architectures", 16, "positional-encoding", "Positional Encoding", "Sinusoidal, learned, and relative positional encodings, and why attention needs explicit position information."),
  future("deep-learning-architectures", 17, "encoder-only-models-bert", "Encoder-Only Models (BERT)", "Bidirectional pretraining with masked language modeling, next-sentence prediction, and the BERT fine-tuning recipe."),
  future("deep-learning-architectures", 18, "decoder-only-models-gpt", "Decoder-Only Models (GPT)", "Causal self-attention, autoregressive pretraining, and why decoder-only transformers came to dominate the scale frontier."),
  future("deep-learning-architectures", 19, "encoder-decoder-transformers-t5", "Encoder-Decoder Transformers (T5)", "T5's text-to-text framing, span corruption pretraining, and unified treatment of NLP tasks."),
  future("deep-learning-architectures", 20, "graph-neural-networks", "Graph Neural Networks", "Learning on graph-structured data, node and edge features, and the basic graph convolutional layer."),
  future("deep-learning-architectures", 21, "message-passing", "Message Passing", "The message-passing framework that unifies most GNNs, with aggregation and update steps generalizing convolution to graphs."),
  future("deep-learning-architectures", 22, "attention-on-graphs", "Attention on Graphs", "Graph attention networks, learned edge weights, and how attention extends to irregular structures."),
  future("deep-learning-architectures", 23, "sparse-and-efficient-transformers", "Sparse and Efficient Transformers", "Linear, sparse, and local attention variants that escape quadratic complexity, with Longformer, Performer, and FlashAttention."),
  future("deep-learning-architectures", 24, "mixture-of-experts", "Mixture of Experts", "Conditional computation with expert routing, sparsely-activated layers, and the load-balancing tricks that make MoE work."),
  future("deep-learning-architectures", 25, "architecture-design-principles", "Architecture Design Principles", "Synthesizing what we have learned: inductive bias, compute efficiency, scaling behavior, and the principles guiding new architectures."),
];

const reinforcementLearning: Lesson[] = [
  future("reinforcement-learning", 1, "rl-setup-and-the-reward-hypothesis", "RL Setup and the Reward Hypothesis", "Agent, environment, action, observation, reward, and Sutton's reward hypothesis as the foundation of RL."),
  future("reinforcement-learning", 2, "markov-decision-processes", "Markov Decision Processes", "States, actions, transitions, rewards, and discount factors, with the Markov property as the central assumption."),
  future("reinforcement-learning", 3, "bellman-equations", "Bellman Equations", "Bellman expectation and optimality equations for value and action-value functions, and their recursive structure."),
  future("reinforcement-learning", 4, "value-iteration", "Value Iteration", "Iterative application of the Bellman optimality operator, convergence to the optimal value function, and contraction arguments."),
  future("reinforcement-learning", 5, "policy-iteration", "Policy Iteration", "Alternating policy evaluation and policy improvement, why it converges in finite steps for finite MDPs."),
  future("reinforcement-learning", 6, "model-free-versus-model-based-rl", "Model-Free Versus Model-Based RL", "When to learn a model of the environment and when to learn values or policies directly, with sample complexity implications."),
  future("reinforcement-learning", 7, "monte-carlo-methods-in-rl", "Monte Carlo Methods in RL", "Learning from sampled returns of complete episodes, first-visit and every-visit estimators, and exploration via exploring starts."),
  future("reinforcement-learning", 8, "temporal-difference-learning", "Temporal Difference Learning", "Bootstrapping on the next state's estimate, the TD error, and TD(0) as the simplest TD algorithm."),
  future("reinforcement-learning", 9, "sarsa", "SARSA", "On-policy TD control with the SARSA update, epsilon-greedy exploration, and on-policy versus off-policy distinctions."),
  future("reinforcement-learning", 10, "q-learning-tabular", "Q-Learning (Tabular)", "Off-policy TD control via the Q-learning update, convergence guarantees in the tabular case, and exploration policies."),
  future("reinforcement-learning", 11, "function-approximation-in-rl", "Function Approximation in RL", "Replacing tables with parametric value functions, linear and neural function approximators, and the deadly triad of instability."),
  future("reinforcement-learning", 12, "deep-q-networks", "Deep Q-Networks (DQN)", "Combining Q-learning with deep neural networks, experience replay, target networks, and the Atari breakthrough."),
  future("reinforcement-learning", 13, "double-dqn-and-dueling", "Double DQN and Dueling Architectures", "Mitigating Q-value overestimation with double DQN, and the dueling architecture's value-advantage decomposition."),
  future("reinforcement-learning", 14, "policy-gradients-reinforce", "Policy Gradients (REINFORCE)", "The policy gradient theorem, the REINFORCE algorithm, and variance reduction with baselines."),
  future("reinforcement-learning", 15, "actor-critic-methods", "Actor-Critic Methods", "Combining policy gradient with learned value functions, the bias-variance bargain, and the actor-critic architecture."),
  future("reinforcement-learning", 16, "a2c-and-a3c", "A2C and A3C", "Synchronous and asynchronous advantage actor-critic, parallel workers, and the move toward scalable on-policy methods."),
  future("reinforcement-learning", 17, "trust-region-policy-optimization", "Trust Region Policy Optimization (TRPO)", "Monotonic improvement guarantees via KL-divergence trust regions, and the natural gradient interpretation."),
  future("reinforcement-learning", 18, "proximal-policy-optimization", "Proximal Policy Optimization (PPO)", "Clipped surrogate objectives as a simpler alternative to TRPO, and why PPO became the workhorse of modern RL."),
  future("reinforcement-learning", 19, "soft-actor-critic", "Soft Actor-Critic (SAC)", "Maximum entropy RL, the soft Q-function, and SAC as a sample-efficient off-policy algorithm for continuous control."),
  future("reinforcement-learning", 20, "ddpg-and-td3", "DDPG and TD3", "Deterministic policy gradients for continuous actions, target policies with noise, and TD3's twin critics and delayed updates."),
  future("reinforcement-learning", 21, "model-based-rl", "Model-Based RL", "Learning environment dynamics and planning with the learned model, with Dyna-style architectures and PETS-style ensembles."),
  future("reinforcement-learning", 22, "world-models", "World Models", "Latent dynamics models that imagine rollouts in a compressed space, from Dreamer to MuZero-style planning."),
  future("reinforcement-learning", 23, "exploration-strategies", "Exploration Strategies", "Epsilon-greedy, optimism in the face of uncertainty, count-based exploration, and curiosity-driven exploration via prediction error."),
  future("reinforcement-learning", 24, "sim-to-real-transfer", "Sim-to-Real Transfer", "Bridging the reality gap with system identification, residual policies, and robust training for robotic deployment."),
  future("reinforcement-learning", 25, "domain-randomization", "Domain Randomization", "Randomizing simulator parameters to make policies robust to reality, with applications in dexterous manipulation and locomotion."),
];

const generativeModels: Lesson[] = [
  future("generative-models", 1, "probabilistic-modeling-motivation", "Probabilistic Modeling Motivation", "Why we model probability distributions over data, the sampling versus density-estimation goals, and the menu of generative families."),
  future("generative-models", 2, "autoregressive-models-for-sequences", "Autoregressive Models for Sequences", "Factorizing joint distributions via the chain rule, training by next-token prediction, and the generality of autoregression."),
  future("generative-models", 3, "autoencoder-versus-variational-autoencoder", "Autoencoder Versus Variational Autoencoder", "Deterministic autoencoders for compression, the leap to probabilistic latent variables, and the VAE architecture."),
  future("generative-models", 4, "reparameterization-trick", "The Reparameterization Trick", "Backpropagation through stochastic nodes via reparameterized sampling, and why this unlocks gradient-based latent-variable learning."),
  future("generative-models", 5, "evidence-lower-bound", "The Evidence Lower Bound (ELBO)", "Decomposition of the ELBO into reconstruction and KL terms, the variational gap, and what the ELBO actually optimizes."),
  future("generative-models", 6, "gan-basics", "GAN Basics", "Generator and discriminator as adversaries, the original GAN value function, and the implicit density-estimation framing."),
  future("generative-models", 7, "the-gan-training-game", "The GAN Training Game", "Nash equilibria, alternating optimization, and why GAN training is notoriously unstable."),
  future("generative-models", 8, "mode-collapse-and-gan-tricks", "Mode Collapse and GAN Tricks", "Mode collapse diagnostics, Wasserstein GANs, spectral normalization, and the bag of tricks that make GANs work."),
  future("generative-models", 9, "normalizing-flows", "Normalizing Flows (RealNVP, Glow)", "Invertible transformations with tractable Jacobians, exact likelihood training, and the affine coupling layer."),
  future("generative-models", 10, "score-matching", "Score Matching", "Learning the gradient of log-density instead of the density itself, denoising score matching, and the bridge to diffusion."),
  future("generative-models", 11, "diffusion-forward-process", "Diffusion Models: Forward Process", "The fixed noise-adding Markov chain, closed-form marginals, and why the forward process needs no learning."),
  future("generative-models", 12, "diffusion-reverse-process", "Diffusion Models: Reverse Process", "Learning to invert the noise process step by step, parameterizing the reverse transitions, and sampling via iterative denoising."),
  future("generative-models", 13, "ddpm", "Denoising Diffusion Probabilistic Models (DDPM)", "The DDPM training objective as noise prediction, the simplified loss, and the connection between DDPM and score matching."),
  future("generative-models", 14, "classifier-free-guidance", "Classifier-Free Guidance", "Conditional generation without an explicit classifier, the guidance scale tradeoff, and why classifier-free guidance dominates."),
  future("generative-models", 15, "latent-diffusion-stable-diffusion", "Latent Diffusion (Stable Diffusion)", "Running diffusion in a VAE-compressed latent space, conditioning via cross-attention, and the architecture of Stable Diffusion."),
  future("generative-models", 16, "foundation-models", "Foundation Models", "Large pretrained models as adaptable substrates, the emergent abilities thesis, and the foundation-model paradigm shift."),
  future("generative-models", 17, "llm-pretraining", "Large Language Model Pretraining", "Next-token prediction at scale, the data and compute requirements, and the choices that distinguish modern LLM pretraining runs."),
  future("generative-models", 18, "instruction-tuning-and-rlhf", "Instruction Tuning and RLHF", "Supervised fine-tuning on instruction data, learning from human preferences, and the PPO-based RLHF pipeline."),
  future("generative-models", 19, "multimodal-models-clip-and-gpt4v", "Multimodal Models (CLIP, GPT-4V)", "Joint vision-language embedding via contrastive learning, and the architectures that ground language models in pixels."),
  future("generative-models", 20, "generative-modeling-frontiers", "Generative Modeling Frontiers", "Synthesizing where generative modeling stands: scaling, controllability, evaluation, and the open problems on the frontier."),
];

const mlSystemsEngineering: Lesson[] = [
  future("ml-systems-engineering", 1, "the-ml-systems-stack", "The ML Systems Stack", "A tour of the layered stack from accelerator hardware up to product surfaces, and where each role and tool fits."),
  future("ml-systems-engineering", 2, "data-pipelines", "Data Pipelines", "Ingestion, transformation, and serving of training data with batch and streaming patterns, and the operational reality of data plumbing."),
  future("ml-systems-engineering", 3, "feature-stores", "Feature Stores", "Centralized feature management, online versus offline parity, and the role of feature stores in production ML."),
  future("ml-systems-engineering", 4, "data-versioning", "Data Versioning", "Versioning datasets and labels for reproducibility, the limits of git for large data, and tools like DVC and lakeFS."),
  future("ml-systems-engineering", 5, "single-machine-training-optimization", "Single-Machine Training Optimization", "Profiling and accelerating training on one GPU with operator fusion, kernel choice, and data loading optimization."),
  future("ml-systems-engineering", 6, "multi-gpu-training", "Multi-GPU Training (Data Parallel, Model Parallel, ZeRO)", "Distributing training across GPUs with data, tensor, and ZeRO-style sharded parallelism."),
  future("ml-systems-engineering", 7, "pipeline-parallelism", "Pipeline Parallelism", "Layer-wise sharding across devices, microbatching to keep GPUs busy, and the bubble overhead of pipeline schedules."),
  future("ml-systems-engineering", 8, "mixed-precision-and-bfloat16", "Mixed Precision Training and bfloat16", "FP16 versus BF16 numerics, loss scaling, and the precision choices behind modern frontier training runs."),
  future("ml-systems-engineering", 9, "gradient-accumulation", "Gradient Accumulation", "Simulating large batches under memory constraints, interaction with learning rate scaling, and gotchas with normalization layers."),
  future("ml-systems-engineering", 10, "distributed-training-frameworks", "Distributed Training Frameworks (DeepSpeed, FSDP)", "DeepSpeed ZeRO stages and PyTorch FSDP, when each is the right choice, and how they reshape memory."),
  future("ml-systems-engineering", 11, "model-serving", "Model Serving (TorchServe, Triton)", "Inference servers, batching strategies, and the operational requirements of high-throughput serving."),
  future("ml-systems-engineering", 12, "onnx-and-tensorrt", "ONNX and TensorRT", "Cross-framework model export with ONNX, accelerator-specific compilation with TensorRT, and the inference optimization toolchain."),
  future("ml-systems-engineering", 13, "monitoring-deployed-models", "Monitoring Deployed Models", "Logging inputs, outputs, and metrics in production, latency and quality SLOs, and the observability stack for ML."),
  future("ml-systems-engineering", 14, "drift-detection", "Drift Detection", "Covariate, label, and concept drift, statistical tests for distribution shift, and triggering retraining from drift signals."),
  future("ml-systems-engineering", 15, "mlops-stack-and-model-registry", "MLOps Stack, Model Registry, and A/B Testing", "Tying together experiment tracking, model registries, deployment, and A/B testing for safe iteration on production ML."),
];

const aiSafetyAndAlignment: Lesson[] = [
  future("ai-safety-and-alignment", 1, "the-alignment-problem", "The Alignment Problem", "Why specifying what we want is hard, the gap between optimization targets and human intent, and a taxonomy of misalignment."),
  future("ai-safety-and-alignment", 2, "specification-gaming-and-reward-hacking", "Specification Gaming and Reward Hacking", "Empirical examples of agents exploiting reward functions, Goodhart's law in RL, and patterns of misspecification."),
  future("ai-safety-and-alignment", 3, "adversarial-examples", "Adversarial Examples", "Imperceptible input perturbations that flip model predictions, the FGSM and PGD attacks, and what they reveal about decision boundaries."),
  future("ai-safety-and-alignment", 4, "robustness-training", "Robustness Training", "Adversarial training, certified defenses, and the robustness-accuracy tradeoff in practice."),
  future("ai-safety-and-alignment", 5, "interpretability-methods", "Interpretability Methods (Saliency, Integrated Gradients)", "Post-hoc explanation techniques, saliency maps, integrated gradients, and the honest limits of feature attribution."),
  future("ai-safety-and-alignment", 6, "mechanistic-interpretability", "Mechanistic Interpretability", "Reverse-engineering circuits inside neural networks, induction heads, superposition, and the dream of a complete decompilation."),
  future("ai-safety-and-alignment", 7, "eval-harnesses-and-benchmarks", "Eval Harnesses and Benchmarks", "Designing evaluations that actually measure capability, contamination and overfitting to benchmarks, and the role of held-out evals."),
  future("ai-safety-and-alignment", 8, "red-teaming", "Red-Teaming", "Adversarial probing of model behavior, jailbreaks, prompt injection, and the workflow of a frontier-model red team."),
  future("ai-safety-and-alignment", 9, "rlhf-safety-considerations", "RLHF Safety Considerations", "Reward model overoptimization, sycophancy, deceptive alignment risks, and the open problems in preference-based training."),
  future("ai-safety-and-alignment", 10, "frontier-risks-and-governance", "Frontier Risks and Governance", "Catastrophic risk scenarios from advanced AI, responsible scaling policies, and the emerging governance landscape."),
];

export const machineLearningAndAiLessons: Lesson[] = [
  ...mlFoundations,
  ...classicalMlAlgorithms,
  ...deepLearningTheory,
  ...deepLearningArchitectures,
  ...reinforcementLearning,
  ...generativeModels,
  ...mlSystemsEngineering,
  ...aiSafetyAndAlignment,
];
