import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "mathematical-foundations";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

function available(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[]; checkId?: string; mdxPath?: string } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "available",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    checkId: options.checkId,
    mdxPath: options.mdxPath ?? `content/lessons/${slug}.mdx`,
  };
}

const mathReentryToolkit: Lesson[] = [
  available(
    "math-reentry-toolkit",
    1,
    "arithmetic-units-and-estimation",
    "Arithmetic, Units, and Estimation",
    "Rebuild number sense, unit awareness, and quick reasonableness checks for technical work.",
    { estimatedMinutes: 35, checkId: "arithmetic-units-core-check" },
  ),
  available(
    "math-reentry-toolkit",
    2,
    "place-value-and-whole-number-arithmetic",
    "Place Value and Whole-Number Arithmetic",
    "Place value, mental addition and subtraction, multiplication and division of whole numbers, and reading large numbers without losing track.",
    { estimatedMinutes: 75, checkId: "place-value-and-whole-number-arithmetic-check" },
  ),
  available(
    "math-reentry-toolkit",
    3,
    "multiplication-tables-and-factor-fluency",
    "Multiplication Tables and Factor Fluency",
    "Mastery of multiplication facts to 12 by 12, recognizing factors, and using divisibility tests for fast mental math.",
    { estimatedMinutes: 90, checkId: "multiplication-tables-and-factor-fluency-check" },
  ),
  available(
    "math-reentry-toolkit",
    4,
    "long-division-and-divisibility",
    "Long Division and Divisibility",
    "The long-division algorithm, quotient and remainder, and using divisibility rules to spot factors quickly.",
    { estimatedMinutes: 90, checkId: "long-division-and-divisibility-check" },
  ),
  available(
    "math-reentry-toolkit",
    5,
    "gcd-lcm-and-prime-factorization",
    "GCD, LCM, and Prime Factorization",
    "Prime numbers, factor trees, the greatest common divisor and least common multiple, and how prime factorization underwrites cryptography.",
    { estimatedMinutes: 105, checkId: "gcd-lcm-and-prime-factorization-check" },
  ),
  available(
    "math-reentry-toolkit",
    6,
    "fractions-meaning-and-equivalence",
    "Fractions: Meaning and Equivalence",
    "What a fraction actually represents, equivalent fractions, simplifying to lowest terms, and comparing fractions on a number line.",
    { estimatedMinutes: 100, checkId: "fractions-meaning-and-equivalence-check" },
  ),
  available(
    "math-reentry-toolkit",
    7,
    "fractions-add-subtract-multiply-divide",
    "Fractions: Add, Subtract, Multiply, Divide",
    "Common-denominator addition and subtraction, multiplication, reciprocals, and division of fractions, with worked examples for engineering ratios.",
    { estimatedMinutes: 110, checkId: "fractions-add-subtract-multiply-divide-check" },
  ),
  available(
    "math-reentry-toolkit",
    8,
    "fractions-ratios-and-proportions",
    "Fractions, Ratios, and Proportions",
    "Use fractions and ratios as engineering language for scaling, mixtures, maps, gears, and sensors.",
    { estimatedMinutes: 40, prerequisites: ["arithmetic-units-and-estimation"] },
  ),
  available(
    "math-reentry-toolkit",
    9,
    "decimals-and-decimal-arithmetic",
    "Decimals and Decimal Arithmetic",
    "Decimal place value, conversions to and from fractions, decimal arithmetic, and when to use decimals versus fractions in engineering.",
    { estimatedMinutes: 105, checkId: "decimals-and-decimal-arithmetic-check" },
  ),
  available(
    "math-reentry-toolkit",
    10,
    "percent-and-percent-change",
    "Percent and Percent Change",
    "What a percent really means, percent of a number, percent change, error as a percent, and engineering tolerance.",
    { estimatedMinutes: 95, checkId: "percent-and-percent-change-check" },
  ),
  future(
    "math-reentry-toolkit",
    11,
    "negative-numbers-and-the-number-line",
    "Negative Numbers and the Number Line",
    "Negative numbers as positions and directions, ordering signed numbers, and the number line as a mental model for direction.",
  ),
  available(
    "math-reentry-toolkit",
    12,
    "signed-numbers-and-order-of-operations",
    "Signed Numbers and Order of Operations",
    "Handle negative values, parentheses, exponents, and calculation order without losing the physical meaning.",
    {
      estimatedMinutes: 35,
      prerequisites: ["fractions-ratios-and-proportions"],
      checkId: "signed-numbers-core-check",
    },
  ),
  future(
    "math-reentry-toolkit",
    13,
    "integer-exponents-and-rules",
    "Integer Exponents and Exponent Rules",
    "Integer exponents (positive, zero, negative), the laws of exponents, and why a zero or negative exponent has the value it does.",
  ),
  future(
    "math-reentry-toolkit",
    14,
    "roots-and-radicals",
    "Roots and Radicals",
    "Square roots, higher roots, simplifying radical expressions, and the relationship between roots and fractional exponents.",
  ),
  future(
    "math-reentry-toolkit",
    15,
    "scientific-notation",
    "Scientific Notation",
    "Writing very large and very small numbers compactly, doing arithmetic in scientific notation, and the order-of-magnitude habit.",
  ),
  future(
    "math-reentry-toolkit",
    16,
    "significant-figures-and-uncertainty",
    "Significant Figures and Measurement Uncertainty",
    "Counting significant figures, rules for arithmetic with measured quantities, and tracking uncertainty through a calculation.",
  ),
  future(
    "math-reentry-toolkit",
    17,
    "engineering-estimation-and-fermi-problems",
    "Engineering Estimation and Fermi Problems",
    "Order-of-magnitude reasoning, breaking unknown quantities into knowable pieces, and the Fermi estimation method for sanity-checking.",
  ),
  future(
    "math-reentry-toolkit",
    18,
    "reading-data-tables-and-charts",
    "Reading Data Tables and Charts",
    "Reading bar charts, line plots, scatterplots, and data tables; spotting misleading axes, scales, and aggregation choices.",
  ),
  future(
    "math-reentry-toolkit",
    19,
    "basic-probability-intuition",
    "Basic Probability Intuition",
    "What probability is, simple counting arguments, and using probabilities to reason about reliability and risk.",
  ),
  future(
    "math-reentry-toolkit",
    20,
    "basic-statistics-mean-median-mode",
    "Basic Statistics: Mean, Median, Mode, and Spread",
    "Mean, median, and mode; standard deviation as a measure of spread; and choosing the right summary statistic for engineering data.",
  ),
];

const engineeringAlgebraGeometry: Lesson[] = [
  available(
    "equations-units-and-graphs",
    1,
    "solving-equations-from-zero",
    "Solving Equations from Zero",
    "Learn equations as balance statements and solve for unknowns one reversible step at a time.",
    {
      estimatedMinutes: 45,
      prerequisites: ["signed-numbers-and-order-of-operations"],
    },
  ),
  future(
    "equations-units-and-graphs",
    2,
    "solving-multi-step-linear-equations",
    "Solving Multi-Step Linear Equations",
    "Combining like terms, distributing, multi-step isolation of a variable, and using checks to catch arithmetic mistakes.",
  ),
  future(
    "equations-units-and-graphs",
    3,
    "equations-with-variables-on-both-sides",
    "Equations with Variables on Both Sides",
    "Collecting variables to one side, eliminating fractions and decimals, and recognizing identities and no-solution equations.",
  ),
  future(
    "equations-units-and-graphs",
    4,
    "rearranging-engineering-formulas",
    "Rearranging Engineering Formulas",
    "Algebraic manipulation of physical formulas (V = IR, F = ma, P = VI) to solve for any variable, including with units carried through.",
  ),
  future(
    "equations-units-and-graphs",
    5,
    "word-problems-to-equations",
    "Translating Word Problems into Equations",
    "A systematic method for turning English-language problems into algebra: identify unknowns, name them, write relationships, solve, and check.",
  ),
  available(
    "equations-units-and-graphs",
    6,
    "units-and-dimensional-analysis",
    "Units and Dimensional Analysis",
    "Use units as a debugging system for formulas, calculations, simulations, and lab measurements.",
    {
      estimatedMinutes: 40,
      prerequisites: ["solving-equations-from-zero"],
    },
  ),
  future(
    "equations-units-and-graphs",
    7,
    "functions-definition-and-notation",
    "Functions: Definition and Notation",
    "What a function is, the notation f(x), domain and range as engineering input and output, and evaluating functions at specific values.",
  ),
  future(
    "equations-units-and-graphs",
    8,
    "domain-range-and-function-types",
    "Domain, Range, and Function Types",
    "Domain restrictions in physical models (no negative time, no division by zero), and recognizing linear, piecewise, and step functions.",
  ),
  future(
    "equations-units-and-graphs",
    9,
    "slope-and-y-intercept",
    "Slope and y-Intercept",
    "Slope as rate of change, y-intercept as starting value, and reading both from data tables, equations, and graphs.",
  ),
  future(
    "equations-units-and-graphs",
    10,
    "slope-intercept-form",
    "Slope-Intercept Form",
    "Writing linear equations as y = mx + b, sketching lines from this form, and modeling linear physical relationships.",
  ),
  future(
    "equations-units-and-graphs",
    11,
    "point-slope-and-standard-forms",
    "Point-Slope and Standard Forms of a Line",
    "Two more linear equation forms, when each is convenient, and converting between slope-intercept, point-slope, and standard form.",
  ),
  future(
    "equations-units-and-graphs",
    12,
    "parallel-and-perpendicular-lines",
    "Parallel and Perpendicular Lines",
    "Slopes of parallel and perpendicular lines, and using them to construct geometric arguments and engineering layouts.",
  ),
  available(
    "equations-units-and-graphs",
    13,
    "graphing-functions-for-builders",
    "Graphing Functions for Builders",
    "Read and sketch graphs as stories about change, systems, sensors, and design tradeoffs.",
    {
      estimatedMinutes: 45,
      prerequisites: ["units-and-dimensional-analysis"],
    },
  ),
  available(
    "equations-units-and-graphs",
    14,
    "algebra-for-engineering-systems",
    "Algebra for Engineering Systems",
    "Use equations as models for physical relationships, constraints, and system behavior.",
    {
      estimatedMinutes: 35,
      prerequisites: ["graphing-functions-for-builders"],
    },
  ),
  future(
    "equations-units-and-graphs",
    15,
    "linear-inequalities-one-variable",
    "Linear Inequalities in One Variable",
    "Solving inequalities including the sign-flip on negative multiplication, expressing solutions as intervals, and modeling physical bounds.",
  ),
  future(
    "equations-units-and-graphs",
    16,
    "linear-inequalities-two-variables",
    "Linear Inequalities in Two Variables",
    "Graphical solution regions for linear inequalities, modeling feasibility in design problems, and basic linear programming intuition.",
  ),
  future(
    "equations-units-and-graphs",
    17,
    "systems-of-linear-equations",
    "Systems of Linear Equations",
    "Solving 2x2 systems by substitution, elimination, and graphical methods; recognizing no-solution and infinite-solution cases.",
  ),
  future(
    "equations-units-and-graphs",
    18,
    "linear-modeling-applications",
    "Linear Modeling Applications",
    "Building linear models for sensor calibration, mixture problems, work and travel-time problems, and budget constraints.",
  ),
];

const geometryTrigVectors: Lesson[] = [
  future(
    "geometry-trig-and-vectors",
    1,
    "points-lines-planes-angles",
    "Points, Lines, Planes, and Angles",
    "The primitive objects of geometry, angle measurement in degrees and radians, and angle relationships (vertical, supplementary, complementary).",
  ),
  future(
    "geometry-trig-and-vectors",
    2,
    "triangle-congruence-and-similarity",
    "Triangle Congruence and Similarity",
    "SSS, SAS, ASA, AAS, and HL congruence rules; AA similarity; and using these to deduce missing lengths and angles in engineering layouts.",
  ),
  future(
    "geometry-trig-and-vectors",
    3,
    "pythagorean-theorem-and-applications",
    "The Pythagorean Theorem and Applications",
    "Statement and proof of the Pythagorean theorem, its converse, common Pythagorean triples, and applications to distance and structural design.",
  ),
  future(
    "geometry-trig-and-vectors",
    4,
    "perimeter-area-of-plane-figures",
    "Perimeter and Area of Plane Figures",
    "Perimeter and area formulas for triangles, parallelograms, trapezoids, and circles; and where they come from rather than just memorizing them.",
  ),
  future(
    "geometry-trig-and-vectors",
    5,
    "circles-arcs-sectors",
    "Circles: Arcs, Sectors, and Tangents",
    "Circumference and area, arc length, sector area, inscribed and central angles, and tangent properties of circles.",
  ),
  future(
    "geometry-trig-and-vectors",
    6,
    "surface-area-and-volume-of-solids",
    "Surface Area and Volume of Solids",
    "Surface area and volume formulas for prisms, cylinders, cones, spheres, and pyramids; deriving these formulas with integration intuition.",
  ),
  future(
    "geometry-trig-and-vectors",
    7,
    "right-triangle-trigonometry",
    "Right-Triangle Trigonometry",
    "Sine, cosine, and tangent as side-length ratios, SOH-CAH-TOA, and solving right triangles given partial information.",
  ),
  available(
    "geometry-trig-and-vectors",
    8,
    "trigonometry-for-drones-and-robotics",
    "Trigonometry for Drones and Robotics",
    "Convert angles and distances into components, heights, bearings, and field measurements.",
    {
      estimatedMinutes: 40,
      prerequisites: ["algebra-for-engineering-systems"],
    },
  ),
  future(
    "geometry-trig-and-vectors",
    9,
    "the-unit-circle",
    "The Unit Circle",
    "Trigonometric functions defined on the unit circle, the unit-circle values for special angles, and trigonometric functions for any angle including negatives.",
  ),
  future(
    "geometry-trig-and-vectors",
    10,
    "trigonometric-identities",
    "Trigonometric Identities",
    "Pythagorean, reciprocal, quotient, and angle-sum identities; using identities to simplify expressions in physics and signal processing.",
  ),
  future(
    "geometry-trig-and-vectors",
    11,
    "inverse-trig-functions",
    "Inverse Trigonometric Functions",
    "Arcsin, arccos, arctan, and atan2; their domain restrictions; and which one to pick when reconstructing an angle from components.",
  ),
  future(
    "geometry-trig-and-vectors",
    12,
    "radians-and-arc-length",
    "Radians and Arc Length",
    "Radians as natural angle units, converting between radians and degrees, and computing arc length and sector area in radians.",
  ),
  available(
    "geometry-trig-and-vectors",
    13,
    "vectors-from-zero",
    "Vectors from Zero",
    "Understand vectors as quantities with size and direction, then use components for motion and force.",
    {
      estimatedMinutes: 60,
      prerequisites: ["algebra-for-engineering-systems"],
    },
  ),
  future(
    "geometry-trig-and-vectors",
    14,
    "vector-arithmetic-and-scaling",
    "Vector Arithmetic and Scaling",
    "Component-wise addition and subtraction, scalar multiplication, distance between points, and using vectors to express displacements and forces.",
    { prerequisites: ["vectors-from-zero"] },
  ),
  future(
    "geometry-trig-and-vectors",
    15,
    "dot-product-and-projections",
    "Dot Product and Projections",
    "The dot product as a measure of alignment, the geometric formula |a||b|cos(theta), and using it to project one vector onto another.",
    { prerequisites: ["vectors-from-zero"] },
  ),
  future(
    "geometry-trig-and-vectors",
    16,
    "cross-product-and-right-hand-rule",
    "The Cross Product and the Right-Hand Rule",
    "The cross product in 3D, the right-hand rule for orientation, magnitude as parallelogram area, and applications to torque and angular momentum.",
    { prerequisites: ["vectors-from-zero"] },
  ),
];

const preCalculus: Lesson[] = [
  future("pre-calculus", 1, "functions-review-and-piecewise", "Functions Review and Piecewise Definitions", "A formal review of functions, function composition, and piecewise-defined functions for engineering models with regime changes."),
  future("pre-calculus", 2, "polynomial-functions-and-end-behavior", "Polynomial Functions and End Behavior", "Polynomials of arbitrary degree, end behavior at infinity, and the relationship between degree and roots."),
  future("pre-calculus", 3, "quadratic-functions-and-the-quadratic-formula", "Quadratic Functions and the Quadratic Formula", "Standard, vertex, and factored forms of quadratics, completing the square, and the quadratic formula with its discriminant."),
  future("pre-calculus", 4, "polynomial-factoring-techniques", "Polynomial Factoring Techniques", "Factoring by grouping, the rational root theorem, and synthetic division for higher-degree polynomials."),
  future("pre-calculus", 5, "polynomial-division-and-factor-theorem", "Polynomial Division and the Factor Theorem", "Long division of polynomials, the remainder and factor theorems, and using them to find roots of polynomial equations."),
  future("pre-calculus", 6, "rational-functions-and-asymptotes", "Rational Functions and Asymptotes", "Vertical, horizontal, and slant asymptotes; holes; and graphing rational functions used in control-system transfer functions."),
  future("pre-calculus", 7, "exponential-functions", "Exponential Functions", "Exponential growth and decay, the base e, and the universal shape of exponential graphs."),
  future("pre-calculus", 8, "logarithmic-functions", "Logarithmic Functions", "Logarithms as inverses of exponentials, natural log and common log, and log scales for engineering data."),
  future("pre-calculus", 9, "properties-of-logarithms", "Properties of Logarithms", "Product, quotient, and power rules for logarithms; the change-of-base formula; and simplifying log expressions."),
  future("pre-calculus", 10, "solving-exponential-and-log-equations", "Solving Exponential and Logarithmic Equations", "Algebraic techniques for solving equations involving exponentials and logarithms, including for time-to-decay problems."),
  future("pre-calculus", 11, "exponential-growth-and-decay-modeling", "Exponential Growth and Decay Modeling", "Building exponential models for population, capacitor charge, radioactive decay, and noise."),
  future("pre-calculus", 12, "compound-interest-and-continuous-growth", "Compound Interest and Continuous Growth", "Discrete and continuous compounding, the natural base e from a limit, and time-value-of-money applications."),
  future("pre-calculus", 13, "arithmetic-and-geometric-sequences", "Arithmetic and Geometric Sequences", "Defining sequences explicitly and recursively, partial sums of arithmetic and geometric sequences, and series convergence intuition."),
  future("pre-calculus", 14, "series-and-sigma-notation", "Series and Sigma Notation", "Compact notation for series, partial sums, telescoping series, and the first taste of infinite-series convergence."),
  future("pre-calculus", 15, "mathematical-induction", "Mathematical Induction", "The principle of mathematical induction, strong induction, and writing proofs for formulas, divisibility, and inequalities."),
  future("pre-calculus", 16, "parabolas", "Parabolas", "The parabola as a locus and as a quadratic graph, focus and directrix, and applications to reflectors and projectile motion."),
  future("pre-calculus", 17, "ellipses", "Ellipses", "Ellipse as a locus, semi-major and semi-minor axes, foci, and orbits as elliptical paths."),
  future("pre-calculus", 18, "hyperbolas", "Hyperbolas", "Hyperbolas as loci, asymptotes, and applications to navigation, signal triangulation, and cosmology."),
  future("pre-calculus", 19, "complex-numbers", "Complex Numbers", "The imaginary unit i, complex arithmetic, modulus and argument, and the geometric picture in the complex plane."),
  future("pre-calculus", 20, "polar-form-of-complex-numbers", "Polar Form of Complex Numbers and De Moivre's Theorem", "Polar representation of complex numbers, De Moivre's theorem, roots of unity, and the bridge to Fourier analysis."),
];

const calculusI: Lesson[] = [
  future("calculus-i-differentiation", 1, "functions-and-graphical-representations", "Functions and Graphical Representations", "A precalculus review focused on the function types that recur throughout calculus: linear, polynomial, rational, trig, exponential, log."),
  future("calculus-i-differentiation", 2, "the-concept-of-a-limit", "The Concept of a Limit", "Intuitive and graphical view of a limit, table-based computation, and the meaning of approaching a value without reaching it."),
  future("calculus-i-differentiation", 3, "computing-limits-algebraically", "Computing Limits Algebraically", "Algebraic techniques: factoring, rationalizing, and limit laws; identifying when a limit fails to exist."),
  future("calculus-i-differentiation", 4, "one-sided-and-infinite-limits", "One-Sided and Infinite Limits", "Left and right limits, limits at infinity, vertical and horizontal asymptotes from limit behavior."),
  future("calculus-i-differentiation", 5, "continuity-and-ivt", "Continuity and the Intermediate Value Theorem", "The three conditions for continuity, classification of discontinuities, and the Intermediate Value Theorem with its proof sketch."),
  future("calculus-i-differentiation", 6, "the-derivative-definition", "The Derivative: Definition", "The derivative as the slope of a tangent line, the limit definition, and the meaning of instantaneous rate of change."),
  future("calculus-i-differentiation", 7, "the-derivative-as-a-function", "The Derivative as a Function", "Going from f(x) to f'(x), graphing f' from a graph of f, and the relationship between a function and its derivative."),
  future("calculus-i-differentiation", 8, "power-rule-and-basic-derivatives", "Power Rule and Basic Derivatives", "The power rule with proof, derivatives of constants, and combining basic derivatives into polynomials."),
  future("calculus-i-differentiation", 9, "sum-difference-constant-multiple-rules", "Sum, Difference, and Constant-Multiple Rules", "The linearity properties of differentiation, used to differentiate any polynomial or finite sum of basic functions."),
  future("calculus-i-differentiation", 10, "product-rule", "The Product Rule", "The product rule for derivatives, derivation, and worked examples in physics and engineering."),
  future("calculus-i-differentiation", 11, "quotient-rule", "The Quotient Rule", "The quotient rule, when it is needed versus when algebraic simplification is better, and worked examples."),
  future("calculus-i-differentiation", 12, "the-chain-rule", "The Chain Rule", "The chain rule for composite functions, with both notational and intuitive derivations; the central rule of differential calculus."),
  future("calculus-i-differentiation", 13, "derivatives-of-trigonometric-functions", "Derivatives of Trigonometric Functions", "Derivatives of sin, cos, tan, sec, csc, cot; the small-angle derivation of d/dx sin = cos; and engineering applications."),
  future("calculus-i-differentiation", 14, "derivatives-of-exp-and-log-functions", "Derivatives of Exponential and Logarithmic Functions", "Derivatives of e^x, a^x, ln x, log_a x, and the unique property of e^x that makes it ubiquitous in physics."),
  future("calculus-i-differentiation", 15, "implicit-differentiation", "Implicit Differentiation", "Differentiating equations that are not solved for y, with applications to curves like circles, ellipses, and astroids."),
  future("calculus-i-differentiation", 16, "logarithmic-differentiation", "Logarithmic Differentiation", "Taking logs before differentiating, used for variable-base exponentials and products of many factors."),
  future("calculus-i-differentiation", 17, "derivatives-of-inverse-functions", "Derivatives of Inverse Functions", "Computing derivatives of inverse functions including arcsin, arccos, arctan, and their engineering uses."),
  future("calculus-i-differentiation", 18, "higher-order-derivatives", "Higher-Order Derivatives", "Second, third, and higher derivatives; physical meanings (velocity, acceleration, jerk); and notation conventions."),
  future("calculus-i-differentiation", 19, "linearization-and-differentials", "Linearization and Differentials", "Approximating a function by its tangent line near a point, error estimation, and the differential dy = f'(x) dx."),
  future("calculus-i-differentiation", 20, "related-rates", "Related Rates", "Modeling situations where multiple quantities change in time and one rate is given while another is unknown."),
  future("calculus-i-differentiation", 21, "extrema-and-first-derivative-test", "Extrema and the First Derivative Test", "Local and global maxima and minima, critical points, the first derivative test, and bounded-interval optimization."),
  future("calculus-i-differentiation", 22, "concavity-and-second-derivative-test", "Concavity and the Second Derivative Test", "Concavity, inflection points, the second derivative test, and using both derivatives to sketch curves accurately."),
  future("calculus-i-differentiation", 23, "optimization-problems", "Optimization Problems", "A methodology for translating real engineering optimization problems into calculus, with worked examples in design and economics."),
  future("calculus-i-differentiation", 24, "lhopitals-rule-and-indeterminate-forms", "L'Hopital's Rule and Indeterminate Forms", "L'Hopital's rule for 0/0 and infinity/infinity forms, transformations for other indeterminate forms, and when it does not apply."),
  future("calculus-i-differentiation", 25, "newtons-method", "Newton's Method", "Newton's method for finding roots of equations numerically, convergence properties, and failure modes."),
];

const calculusII: Lesson[] = [
  future("calculus-ii-integration-and-series", 1, "antiderivatives-and-indefinite-integrals", "Antiderivatives and Indefinite Integrals", "The reverse of differentiation, indefinite integral notation, and the family of antiderivatives differing by a constant."),
  future("calculus-ii-integration-and-series", 2, "riemann-sums-and-definite-integral", "Riemann Sums and the Definite Integral", "The definite integral as a limit of Riemann sums, the area-under-a-curve interpretation, and properties of definite integrals."),
  future("calculus-ii-integration-and-series", 3, "fundamental-theorem-of-calculus", "The Fundamental Theorem of Calculus", "Both parts of the fundamental theorem, the connection between differentiation and integration, and its enormous practical consequence."),
  future("calculus-ii-integration-and-series", 4, "u-substitution", "u-Substitution", "Substitution as the chain rule in reverse, choosing u carefully, and changing limits of integration in definite integrals."),
  future("calculus-ii-integration-and-series", 5, "integration-by-parts", "Integration by Parts", "Integration by parts as the product rule in reverse, choosing u and dv, and applying it iteratively or with tabular notation."),
  future("calculus-ii-integration-and-series", 6, "trigonometric-integrals", "Trigonometric Integrals", "Standard reductions for integrals of products of sines, cosines, secants, and tangents."),
  future("calculus-ii-integration-and-series", 7, "trigonometric-substitution", "Trigonometric Substitution", "Substitutions of the form x = a sin theta, x = a tan theta, x = a sec theta to evaluate radical integrals."),
  future("calculus-ii-integration-and-series", 8, "partial-fractions-integration", "Partial Fractions", "Decomposing rational functions into simpler pieces, then integrating each piece; applications to control systems and Laplace transforms."),
  future("calculus-ii-integration-and-series", 9, "improper-integrals", "Improper Integrals", "Integrals with infinite limits or with integrands that blow up, convergence and divergence tests."),
  future("calculus-ii-integration-and-series", 10, "area-between-curves", "Area Between Curves", "Setting up integrals for areas between curves with respect to x or y, choosing the easier variable."),
  future("calculus-ii-integration-and-series", 11, "volumes-by-disks-and-washers", "Volumes by Disks and Washers", "Solids of revolution computed by integrating cross-sectional area; choosing axis and method."),
  future("calculus-ii-integration-and-series", 12, "volumes-by-cylindrical-shells", "Volumes by Cylindrical Shells", "An alternative volume method that often shortens the algebra when the disk method is cumbersome."),
  future("calculus-ii-integration-and-series", 13, "arc-length-computation", "Arc Length", "Computing the length of a curve as a definite integral, and the parametric and polar versions of arc length."),
  future("calculus-ii-integration-and-series", 14, "surface-area-of-revolution", "Surface Area of Revolution", "Surface area of solids of revolution, including the parametric and polar variants."),
  future("calculus-ii-integration-and-series", 15, "average-value-and-work-applications", "Average Value and Work Applications", "Integrals to compute averages of functions and physical work done by variable forces."),
  future("calculus-ii-integration-and-series", 16, "sequences-and-convergence", "Sequences and Convergence", "Definition of sequence convergence, monotonic and bounded sequences, and the squeeze theorem for sequences."),
  future("calculus-ii-integration-and-series", 17, "series-and-partial-sums", "Series and Partial Sums", "Definition of series convergence via partial sums, the harmonic series example, and divergence test."),
  future("calculus-ii-integration-and-series", 18, "geometric-and-telescoping-series", "Geometric and Telescoping Series", "Closed-form formulas for geometric series, when they converge, and telescoping techniques."),
  future("calculus-ii-integration-and-series", 19, "integral-test-and-p-series", "The Integral Test and p-Series", "Using improper integrals to test series convergence, and the convergence/divergence of p-series."),
  future("calculus-ii-integration-and-series", 20, "comparison-tests-for-series", "Comparison Tests for Series", "Direct comparison and limit comparison tests for positive-term series."),
  future("calculus-ii-integration-and-series", 21, "ratio-and-root-tests", "Ratio and Root Tests", "Tests that detect convergence by behavior of consecutive terms or nth roots, particularly useful for factorials and powers."),
  future("calculus-ii-integration-and-series", 22, "alternating-series-and-absolute-convergence", "Alternating Series and Absolute Convergence", "The alternating series test, absolute versus conditional convergence, and rearrangement caveats."),
  future("calculus-ii-integration-and-series", 23, "power-series-and-radius-of-convergence", "Power Series and Radius of Convergence", "Power series as functions, the interval of convergence, and operations on power series."),
  future("calculus-ii-integration-and-series", 24, "taylor-and-maclaurin-series", "Taylor and Maclaurin Series", "Taylor's theorem with remainder, Maclaurin series of standard functions, and series-based approximation in engineering."),
  future("calculus-ii-integration-and-series", 25, "applications-of-power-series", "Applications of Power Series", "Solving differential equations with series, computing limits, evaluating integrals that lack closed form, and Euler's identity."),
];

const multivariableCalculus: Lesson[] = [
  future("multivariable-calculus", 1, "three-d-coordinate-system-and-distance", "3D Coordinate System and Distance", "Three-dimensional Cartesian coordinates, right-hand convention, distance formula, and equations of spheres."),
  future("multivariable-calculus", 2, "vectors-in-three-d-review", "Vectors in 3D — Review and Extension", "3D vectors, magnitude, unit vectors, and the standard basis i, j, k extended to three dimensions."),
  future("multivariable-calculus", 3, "cross-product-and-triple-products", "Cross Product and Triple Products", "Cross product in 3D, geometric meaning, scalar triple product as volume, and vector triple product identities."),
  future("multivariable-calculus", 4, "lines-and-planes-in-three-d", "Lines and Planes in 3D", "Parametric and symmetric equations of lines, normal-vector and scalar equations of planes, intersections and distances."),
  future("multivariable-calculus", 5, "cylinders-and-quadric-surfaces", "Cylinders and Quadric Surfaces", "Ruled surfaces, the six standard quadric surfaces (ellipsoid, paraboloid, hyperboloid, etc.), and recognizing them from equations."),
  future("multivariable-calculus", 6, "vector-functions-and-space-curves", "Vector Functions and Space Curves", "Vector-valued functions of one variable, parametric space curves, and tangent vectors."),
  future("multivariable-calculus", 7, "tangent-and-normal-vectors", "Tangent and Normal Vectors", "Unit tangent, unit normal, and binormal vectors, defining a moving frame along a curve (the Frenet frame)."),
  future("multivariable-calculus", 8, "arc-length-and-curvature", "Arc Length and Curvature", "Arc length parameterization, curvature as the rate of turning, and the radius of curvature."),
  future("multivariable-calculus", 9, "velocity-and-acceleration-in-three-d", "Velocity and Acceleration in 3D", "Velocity and acceleration vectors for space curves, tangential and normal components of acceleration."),
  future("multivariable-calculus", 10, "functions-of-several-variables", "Functions of Several Variables", "Real-valued functions of two and three variables, graphs, and physical examples (temperature fields, potentials)."),
  future("multivariable-calculus", 11, "level-curves-and-level-surfaces", "Level Curves and Level Surfaces", "Contour plots, level surfaces, and visualizing multivariable functions through their level sets."),
  future("multivariable-calculus", 12, "limits-and-continuity-of-multivariable-functions", "Limits and Continuity of Multivariable Functions", "Limits in two and three variables, path dependence, and continuity in higher dimensions."),
  future("multivariable-calculus", 13, "partial-derivatives", "Partial Derivatives", "Partial derivatives as slopes in coordinate directions, higher-order partials, and Clairaut's equality theorem."),
  future("multivariable-calculus", 14, "tangent-planes-and-linear-approximation", "Tangent Planes and Linear Approximation", "Tangent planes to surfaces, linear approximation in two and three variables, and total differential."),
  future("multivariable-calculus", 15, "chain-rule-multivariable", "Chain Rule for Several Variables", "Chain rule when the inputs depend on other variables, parametric paths, and implicit differentiation revisited."),
  future("multivariable-calculus", 16, "directional-derivatives-and-the-gradient", "Directional Derivatives and the Gradient", "Directional derivatives in any direction, the gradient as the direction of steepest ascent, and gradient as a vector field."),
  future("multivariable-calculus", 17, "multivariable-maxima-and-minima", "Multivariable Maxima and Minima", "Critical points in two variables, the discriminant (second derivative test), and classifying extrema and saddle points."),
  future("multivariable-calculus", 18, "lagrange-multipliers", "Lagrange Multipliers", "Constrained optimization with one or more constraints, the geometric meaning of the multiplier, and worked engineering examples."),
  future("multivariable-calculus", 19, "double-integrals-over-rectangles", "Double Integrals over Rectangles", "Iterated integrals, Fubini's theorem, and the geometric picture as volume under a surface."),
  future("multivariable-calculus", 20, "double-integrals-over-general-regions", "Double Integrals over General Regions", "Type I and Type II regions, changing the order of integration, and choosing the easier order."),
  future("multivariable-calculus", 21, "polar-coordinates-and-double-integrals", "Polar Coordinates and Double Integrals", "Conversion to polar coordinates, the Jacobian factor r, and applications to circular and annular regions."),
  future("multivariable-calculus", 22, "surface-area-multivariable", "Surface Area in Multivariable Calculus", "Computing surface area of graphs of functions and parametric surfaces using double integrals."),
  future("multivariable-calculus", 23, "triple-integrals", "Triple Integrals", "Triple integrals over boxes and general 3D regions, with applications to volume, mass, and center of mass."),
  future("multivariable-calculus", 24, "cylindrical-and-spherical-coordinates", "Cylindrical and Spherical Coordinates", "Two more 3D coordinate systems, the Jacobian factors, and choosing the right system for a problem."),
  future("multivariable-calculus", 25, "change-of-variables-and-jacobians", "Change of Variables and the Jacobian", "Change-of-variables formula for multiple integrals, computing Jacobians, and choosing transformations strategically."),
  future("multivariable-calculus", 26, "vector-fields-and-line-integrals", "Vector Fields and Line Integrals", "Vector fields in 2D and 3D, line integrals of scalar functions and of vector fields along curves."),
  future("multivariable-calculus", 27, "fundamental-theorem-of-line-integrals", "The Fundamental Theorem for Line Integrals", "Conservative vector fields, potential functions, and path-independence of line integrals."),
  future("multivariable-calculus", 28, "greens-theorem", "Green's Theorem", "Green's theorem relating line integrals on a closed curve to double integrals over the enclosed region, with applications."),
  future("multivariable-calculus", 29, "surface-integrals-and-divergence-theorem", "Surface Integrals and the Divergence Theorem", "Surface integrals over oriented surfaces, flux through a surface, and the divergence theorem connecting flux to volume integrals."),
  future("multivariable-calculus", 30, "stokes-theorem", "Stokes' Theorem", "Stokes' theorem relating a surface integral of curl to a line integral along the boundary; the unifying theorem of vector calculus."),
];

const linearAlgebra: Lesson[] = [
  future("linear-algebra", 1, "the-geometry-of-linear-equations", "The Geometry of Linear Equations", "Linear systems viewed as row picture (intersecting lines/planes) and column picture (combinations of column vectors)."),
  future("linear-algebra", 2, "matrices-and-matrix-vector-products", "Matrices and Matrix-Vector Products", "Two interpretations of Ax: as combinations of A's columns, and as inner products with A's rows."),
  future("linear-algebra", 3, "gaussian-elimination", "Gaussian Elimination", "Systematic row reduction to triangular form, pivots, and back-substitution."),
  future("linear-algebra", 4, "row-echelon-and-rref", "Row Echelon Form and Reduced Row Echelon Form", "Definitions of row echelon and RREF, uniqueness of RREF, and reading solutions directly from RREF."),
  future("linear-algebra", 5, "matrix-multiplication", "Matrix Multiplication", "Four equivalent ways to multiply matrices, when products are defined, and noncommutativity."),
  future("linear-algebra", 6, "matrix-inverse", "Matrix Inverse", "Two-sided inverses, finding inverses via Gauss-Jordan, and when an inverse fails to exist."),
  future("linear-algebra", 7, "lu-decomposition", "LU Decomposition", "Factoring A = LU, when it exists, and using LU to solve multiple systems efficiently."),
  future("linear-algebra", 8, "transposes-and-permutations", "Transposes and Permutations", "Transpose properties, symmetric matrices, permutation matrices, and PA = LU for general matrices."),
  future("linear-algebra", 9, "vector-spaces-and-subspaces", "Vector Spaces and Subspaces", "Eight axioms of a vector space, examples and non-examples of subspaces, and closure under addition and scalar multiplication."),
  future("linear-algebra", 10, "null-space-and-column-space", "Null Space and Column Space", "Defining the null space N(A) and column space C(A), their physical meaning, and finding them computationally."),
  future("linear-algebra", 11, "solving-ax-equals-zero", "Solving Ax = 0", "Special solutions in terms of free variables, complete description of N(A)."),
  future("linear-algebra", 12, "solving-ax-equals-b", "Solving Ax = b", "Particular solution plus null-space solutions, conditions for solvability, and the complete solution set."),
  future("linear-algebra", 13, "linear-independence-basis-dimension", "Linear Independence, Basis, and Dimension", "Independence as a property of vector sets, basis as a minimal spanning set, and dimension as the invariant size of any basis."),
  future("linear-algebra", 14, "four-fundamental-subspaces", "The Four Fundamental Subspaces", "Column space, null space, row space, and left null space — their dimensions and orthogonality relationships."),
  future("linear-algebra", 15, "orthogonality-and-orthogonal-complements", "Orthogonality and Orthogonal Complements", "Orthogonal vectors, orthogonal subspaces, and the orthogonal complement to a subspace."),
  future("linear-algebra", 16, "projection-onto-subspaces", "Projection onto Subspaces", "Projection of a vector onto a line and onto a higher-dimensional subspace, geometric meaning and formula."),
  future("linear-algebra", 17, "projection-matrices-and-least-squares", "Projection Matrices and Least Squares", "Projection matrices P = A(A^T A)^-1 A^T, idempotency and symmetry, and least-squares regression."),
  future("linear-algebra", 18, "gram-schmidt-orthogonalization", "Gram-Schmidt Orthogonalization", "Constructing an orthonormal basis from any basis, and orthonormal sets for numerical stability."),
  future("linear-algebra", 19, "qr-factorization", "QR Factorization", "Factoring A = QR with Q orthonormal and R upper triangular, and its use in least-squares and eigenvalue algorithms."),
  future("linear-algebra", 20, "determinants-definition-and-properties", "Determinants: Definition and Properties", "The determinant as a multilinear, alternating, normalized function; its ten core properties."),
  future("linear-algebra", 21, "determinants-formulas-and-cramers-rule", "Determinants: Formulas and Cramer's Rule", "Cofactor expansion, the Leibniz formula, and Cramer's rule for solving Ax = b."),
  future("linear-algebra", 22, "eigenvalues-and-eigenvectors", "Eigenvalues and Eigenvectors", "The characteristic equation det(A - lambda I) = 0, geometric meaning of eigenvectors, and computing them by hand."),
  future("linear-algebra", 23, "diagonalization", "Diagonalization", "Conditions for a matrix to be diagonalizable, the factorization A = S Lambda S^-1, and powers of A made easy."),
  future("linear-algebra", 24, "powers-and-exponentials-of-matrices", "Powers and Exponentials of Matrices", "Computing A^k and e^A via diagonalization, and the matrix exponential as the solution of linear ODE systems."),
  future("linear-algebra", 25, "solving-de-systems-with-eigenvalues", "Solving Differential Equation Systems with Eigenvalues", "Solving systems dx/dt = Ax using eigenvalues and eigenvectors of A, with applications to coupled oscillators."),
  future("linear-algebra", 26, "symmetric-matrices", "Symmetric Matrices", "Real eigenvalues, orthogonal eigenvectors, and the spectral theorem A = Q Lambda Q^T."),
  future("linear-algebra", 27, "positive-definite-matrices", "Positive Definite Matrices", "Definitions, tests for positive definiteness, and their importance in optimization and physics."),
  future("linear-algebra", 28, "singular-value-decomposition", "Singular Value Decomposition", "SVD A = U Sigma V^T, the most important factorization, with applications to image compression, PCA, and pseudoinverse."),
  future("linear-algebra", 29, "linear-transformations-and-change-of-basis", "Linear Transformations and Change of Basis", "Linear transformations as matrices in chosen bases, and how the matrix changes when the basis changes."),
  future("linear-algebra", 30, "svd-applications-and-pseudoinverse", "SVD Applications and the Pseudoinverse", "Moore-Penrose pseudoinverse, low-rank approximation, and the SVD's central role in modern data analysis."),
];

const differentialEquations: Lesson[] = [
  future("differential-equations", 1, "first-order-odes-and-direction-fields", "First-Order ODEs and Direction Fields", "What a differential equation is, direction fields as a visualization tool, and qualitative reasoning about solutions."),
  future("differential-equations", 2, "separable-equations", "Separable Equations", "The separation of variables technique, including initial value problems and implicit solutions."),
  future("differential-equations", 3, "linear-first-order-equations", "Linear First-Order Equations", "The integrating factor method for solving y' + p(t)y = g(t), and steady-state versus transient solutions."),
  future("differential-equations", 4, "bernoulli-and-exact-equations", "Bernoulli and Exact Equations", "Bernoulli equations linearized by a substitution, and exact equations recognized by partial-derivative conditions."),
  future("differential-equations", 5, "existence-and-uniqueness-theorems", "Existence and Uniqueness Theorems", "Conditions under which an initial value problem has a unique solution, and what failure of these conditions means."),
  future("differential-equations", 6, "modeling-with-first-order-equations", "Modeling with First-Order Equations", "Population growth, Newton's law of cooling, RC circuits, and free fall with air resistance modeled as first-order ODEs."),
  future("differential-equations", 7, "second-order-linear-odes-constant-coefficients", "Second-Order Linear ODEs with Constant Coefficients", "The homogeneous case ay'' + by' + cy = 0, characteristic equation, and case analysis by discriminant sign."),
  future("differential-equations", 8, "homogeneous-solutions-and-characteristic-equation", "Homogeneous Solutions and the Characteristic Equation", "Building the general homogeneous solution from roots of the characteristic equation, including repeated and complex roots."),
  future("differential-equations", 9, "method-of-undetermined-coefficients", "Method of Undetermined Coefficients", "Finding particular solutions to nonhomogeneous ODEs by guessing the form, when it works, and when it does not."),
  future("differential-equations", 10, "variation-of-parameters", "Variation of Parameters", "A more general technique for particular solutions, including when the right-hand side does not fit standard guess patterns."),
  future("differential-equations", 11, "mechanical-and-electrical-vibrations", "Mechanical and Electrical Vibrations", "Spring-mass-damper systems and RLC circuits as second-order linear ODEs, with under-, critical-, and over-damped behavior."),
  future("differential-equations", 12, "forced-vibrations-and-resonance", "Forced Vibrations and Resonance", "Driven oscillators, the resonance phenomenon, beats, and engineering implications for bridges and aircraft."),
  future("differential-equations", 13, "systems-of-linear-odes", "Systems of Linear ODEs", "Coupled linear ODEs as vector equations, and the matrix form dx/dt = Ax."),
  future("differential-equations", 14, "matrix-methods-for-systems", "Matrix Methods for Systems", "Solving linear ODE systems via eigenvalues and eigenvectors of the coefficient matrix."),
  future("differential-equations", 15, "phase-portraits", "Phase Portraits", "Trajectories in state space, classification of fixed points (node, spiral, saddle, center), and stability analysis."),
  future("differential-equations", 16, "nonlinear-systems-and-linearization", "Nonlinear Systems and Linearization", "Local analysis of nonlinear systems via linearization at fixed points, and the Hartman-Grobman theorem."),
  future("differential-equations", 17, "stability-analysis", "Stability Analysis", "Lyapunov functions, asymptotic stability, and engineering implications for control system design."),
  future("differential-equations", 18, "laplace-transforms", "Laplace Transforms", "Definition of the Laplace transform, key properties, and table of transforms for standard functions."),
  future("differential-equations", 19, "solving-odes-with-laplace", "Solving ODEs with Laplace Transforms", "Transforming an ODE to an algebraic equation, solving, and transforming back, including discontinuous inputs."),
  future("differential-equations", 20, "convolution-and-impulse-response", "Convolution and Impulse Response", "The convolution theorem, impulse and step responses, and connections to control system theory."),
  future("differential-equations", 21, "step-functions-and-dirac-delta", "Step Functions and the Dirac Delta", "Heaviside step function, Dirac delta as a generalized function, and using both in modeling and Laplace transforms."),
  future("differential-equations", 22, "fourier-series-intro", "Introduction to Fourier Series", "Representing periodic functions as sums of sines and cosines, computing Fourier coefficients."),
  future("differential-equations", 23, "heat-equation-and-separation-of-variables", "The Heat Equation and Separation of Variables", "Deriving the heat equation, solving it on a 1D rod by separation of variables, and the role of boundary conditions."),
  future("differential-equations", 24, "wave-equation", "The Wave Equation", "1D wave equation, d'Alembert's solution, and applications to strings, sound, and electromagnetic waves."),
  future("differential-equations", 25, "laplaces-equation-bvps", "Laplace's Equation and Boundary Value Problems", "Laplace's equation as the steady-state heat equation, solutions on a rectangle and a disk, and harmonic functions."),
];

const probabilityAndStatistics: Lesson[] = [
  future("probability-and-statistics", 1, "sample-spaces-and-events", "Sample Spaces and Events", "Outcomes, sample spaces, and events; combining events with unions, intersections, and complements."),
  future("probability-and-statistics", 2, "axioms-of-probability", "Axioms of Probability", "The Kolmogorov axioms, basic consequences, inclusion-exclusion, and the difference between empirical and axiomatic probability."),
  future("probability-and-statistics", 3, "conditional-probability-and-independence", "Conditional Probability and Independence", "Conditional probability as restricted sample spaces, independence as a precise statement, and common student pitfalls."),
  future("probability-and-statistics", 4, "bayes-theorem", "Bayes' Theorem", "Bayes' theorem derivation, prior and posterior probabilities, and worked examples in diagnosis and inference."),
  future("probability-and-statistics", 5, "discrete-random-variables", "Discrete Random Variables", "Definition of a random variable, probability mass functions, and cumulative distribution functions for discrete cases."),
  future("probability-and-statistics", 6, "binomial-geometric-poisson-distributions", "Binomial, Geometric, and Poisson Distributions", "Three common discrete distributions, when each applies, and worked engineering examples."),
  future("probability-and-statistics", 7, "continuous-random-variables", "Continuous Random Variables", "Probability density functions, cumulative distributions, and the meaning of probability for continuous variables."),
  future("probability-and-statistics", 8, "uniform-exponential-normal-distributions", "Uniform, Exponential, and Normal Distributions", "Three central continuous distributions, their parameters, and the moment-generating functions."),
  future("probability-and-statistics", 9, "joint-distributions", "Joint Distributions", "Joint, marginal, and conditional distributions for multiple random variables, and computing each from the others."),
  future("probability-and-statistics", 10, "covariance-and-correlation", "Covariance and Correlation", "Covariance and correlation coefficient, what each measures, and the warning that correlation is not causation."),
  future("probability-and-statistics", 11, "expectation-and-variance", "Expectation and Variance", "Expected value and variance for discrete and continuous random variables, and their interpretations."),
  future("probability-and-statistics", 12, "linearity-of-expectation", "Linearity of Expectation", "Why E[X + Y] = E[X] + E[Y] always, even for dependent X and Y, with worked examples."),
  future("probability-and-statistics", 13, "moment-generating-functions", "Moment Generating Functions", "MGF as a tool for computing moments and identifying distributions; convolution and sums of random variables."),
  future("probability-and-statistics", 14, "law-of-large-numbers", "Law of Large Numbers", "Weak and strong laws of large numbers, why averages converge, and connection to the empirical distribution."),
  future("probability-and-statistics", 15, "central-limit-theorem", "Central Limit Theorem", "The CLT statement, proof sketch via MGFs, and why normal distributions appear so often."),
  future("probability-and-statistics", 16, "estimation-bias-and-variance", "Estimation: Bias and Variance", "Estimators as random variables, bias-variance decomposition, and the trade-off in engineering inference."),
  future("probability-and-statistics", 17, "maximum-likelihood-estimation", "Maximum Likelihood Estimation", "Likelihood functions, finding the MLE, and asymptotic properties (consistency, efficiency)."),
  future("probability-and-statistics", 18, "confidence-intervals", "Confidence Intervals", "Constructing confidence intervals for means and proportions, and the correct frequentist interpretation."),
  future("probability-and-statistics", 19, "hypothesis-testing-framework", "Hypothesis Testing Framework", "Null and alternative hypotheses, test statistics, p-values, type I and type II errors."),
  future("probability-and-statistics", 20, "t-tests-and-chi-squared-tests", "t-Tests and Chi-Squared Tests", "One-sample and two-sample t-tests, chi-squared goodness-of-fit and independence tests, with worked examples."),
  future("probability-and-statistics", 21, "linear-regression", "Linear Regression", "Simple and multiple linear regression, least-squares derivation, residuals, and goodness-of-fit measures."),
  future("probability-and-statistics", 22, "bayesian-inference-intro", "Bayesian Inference: Introduction", "Bayesian reasoning, choosing priors, computing posteriors, and the philosophical differences from frequentist statistics."),
  future("probability-and-statistics", 23, "bayesian-estimation", "Bayesian Estimation", "MAP and posterior mean estimators, credible intervals, and conjugate priors for tractable Bayesian inference."),
  future("probability-and-statistics", 24, "monte-carlo-methods", "Monte Carlo Methods", "Using random sampling to approximate integrals and expectations, including importance sampling and basic MCMC."),
  future("probability-and-statistics", 25, "ab-testing-and-model-selection", "A/B Testing and Model Selection", "Designing controlled experiments, computing sample sizes, AIC/BIC for model selection, and cross-validation."),
];

const realAnalysis: Lesson[] = [
  future("real-analysis", 1, "real-numbers-and-completeness", "Real Numbers and Completeness", "Construction of the reals (Dedekind cuts or Cauchy sequences), the least upper bound property, and what makes the reals different from the rationals."),
  future("real-analysis", 2, "sequences-and-convergence-formal", "Sequences and Convergence (Formal)", "Epsilon-N definition of sequence convergence, proving convergence and divergence directly from the definition."),
  future("real-analysis", 3, "cauchy-sequences", "Cauchy Sequences", "Cauchy criterion, equivalence with convergence in complete metric spaces, and as a working definition of the reals."),
  future("real-analysis", 4, "series-and-convergence-rigorous", "Series and Convergence (Rigorous)", "Series convergence by partial sums, rearrangement theorems, and absolute versus conditional convergence."),
  future("real-analysis", 5, "open-and-closed-sets", "Open and Closed Sets", "Open and closed sets in the reals, interior and closure, limit points, and topology of R."),
  future("real-analysis", 6, "compactness-in-r", "Compactness in R", "Heine-Borel theorem, sequential compactness, and the equivalence of definitions in R^n."),
  future("real-analysis", 7, "continuity-formal-definition", "Continuity (Formal Definition)", "Epsilon-delta definition of continuity, proving continuity rigorously, and the relationship between continuity and limits."),
  future("real-analysis", 8, "uniform-continuity", "Uniform Continuity", "Uniform continuity as a stronger condition, theorems guaranteeing it on compact sets, and the distinction from pointwise continuity."),
  future("real-analysis", 9, "intermediate-value-theorem-proof", "Intermediate Value Theorem (Proof)", "Proving the IVT from the completeness axiom, and applications to root-finding."),
  future("real-analysis", 10, "extreme-value-theorem", "Extreme Value Theorem", "Proving that a continuous function on a compact set attains its max and min, with the role of compactness made explicit."),
  future("real-analysis", 11, "differentiability-formal", "Differentiability (Formal)", "Limit definition of derivative, differentiability implies continuity, and counterexamples to the converse."),
  future("real-analysis", 12, "mean-value-theorem", "Mean Value Theorem", "Rolle's theorem and the MVT, with proofs, and consequences for monotonicity and concavity."),
  future("real-analysis", 13, "taylors-theorem-with-remainder", "Taylor's Theorem with Remainder", "Taylor's theorem with explicit error bounds (Lagrange, integral form), and rigorous error analysis."),
  future("real-analysis", 14, "riemann-integration-definition", "Riemann Integration (Definition)", "Partition-based definition of the Riemann integral, upper and lower sums, and characterization of Riemann-integrable functions."),
  future("real-analysis", 15, "fundamental-theorem-rigorous", "Fundamental Theorem of Calculus (Rigorous)", "Rigorous proof of both parts of the FTC and the conditions required."),
  future("real-analysis", 16, "sequences-and-series-of-functions", "Sequences and Series of Functions", "Pointwise versus uniform convergence, why distinguishing them matters."),
  future("real-analysis", 17, "uniform-convergence", "Uniform Convergence", "Properties preserved under uniform convergence (continuity, integrability), and the Weierstrass M-test."),
  future("real-analysis", 18, "weierstrass-approximation", "Weierstrass Approximation Theorem", "Any continuous function on a compact interval can be uniformly approximated by polynomials; constructive proofs."),
  future("real-analysis", 19, "metric-spaces-introduction", "Metric Spaces: Introduction", "Generalizing the notion of distance, basic definitions (open, closed, compact) in metric spaces, and examples."),
  future("real-analysis", 20, "complete-metric-spaces", "Complete Metric Spaces", "Completeness in metric spaces, completion of a metric space, and Banach's fixed-point theorem."),
  future("real-analysis", 21, "compactness-in-metric-spaces", "Compactness in Metric Spaces", "Sequential and open-cover definitions of compactness, Arzela-Ascoli theorem, and characterizations in concrete settings."),
  future("real-analysis", 22, "contractions-and-fixed-points", "Contractions and Fixed Points", "The Banach contraction mapping theorem and its uses in differential equations and numerical analysis."),
  future("real-analysis", 23, "lebesgue-measure-introduction", "Lebesgue Measure: Introduction", "Why the Riemann integral is not enough, outer measure, Lebesgue measurable sets, and Lebesgue measure on R."),
  future("real-analysis", 24, "lp-spaces-introduction", "L^p Spaces: Introduction", "Definitions of L^1, L^2, L^p, the Holder and Minkowski inequalities, and basic properties."),
  future("real-analysis", 25, "fourier-analysis-rigorous", "Fourier Analysis (Rigorous)", "Fourier series in L^2, convergence theorems, and an introduction to the Fourier transform on R."),
];

const abstractAlgebra: Lesson[] = [
  future("abstract-algebra", 1, "binary-operations-and-groups", "Binary Operations and Groups", "Definition of a group, examples (integers under addition, symmetries, matrix groups), and basic group properties."),
  future("abstract-algebra", 2, "subgroups-and-cyclic-groups", "Subgroups and Cyclic Groups", "Subgroup definition, cyclic subgroups generated by an element, and the structure of cyclic groups."),
  future("abstract-algebra", 3, "permutations-and-symmetric-groups", "Permutations and Symmetric Groups", "The symmetric group S_n, cycle notation, sign and parity of permutations, and the alternating group."),
  future("abstract-algebra", 4, "cosets-and-lagranges-theorem", "Cosets and Lagrange's Theorem", "Left and right cosets, partitioning a group by cosets, and Lagrange's theorem on subgroup index."),
  future("abstract-algebra", 5, "normal-subgroups-and-quotient-groups", "Normal Subgroups and Quotient Groups", "Definition of a normal subgroup, the quotient group construction, and examples (Z/nZ, dihedral groups)."),
  future("abstract-algebra", 6, "group-homomorphisms-and-isomorphisms", "Group Homomorphisms and Isomorphisms", "Homomorphisms preserve group structure; kernels, images, and the first isomorphism theorem statement."),
  future("abstract-algebra", 7, "the-first-isomorphism-theorem", "The First Isomorphism Theorem", "Proof of the first isomorphism theorem, examples, and a glimpse of the second and third theorems."),
  future("abstract-algebra", 8, "group-actions", "Group Actions", "Groups acting on sets, orbits and stabilizers, the orbit-stabilizer theorem, and Burnside's counting lemma."),
  future("abstract-algebra", 9, "sylow-theorems", "Sylow Theorems", "Statement and proof sketches of the three Sylow theorems and their use in classifying finite groups."),
  future("abstract-algebra", 10, "rings-definition-and-examples", "Rings: Definition and Examples", "Definition of a ring, commutative and non-commutative examples, and basic ring properties."),
  future("abstract-algebra", 11, "ideals-and-quotient-rings", "Ideals and Quotient Rings", "Two-sided ideals, the quotient ring R/I, and the first ring isomorphism theorem."),
  future("abstract-algebra", 12, "integral-domains-and-fields", "Integral Domains and Fields", "Definitions, the relationship between fields and integral domains, and finite fields as a key example."),
  future("abstract-algebra", 13, "polynomial-rings", "Polynomial Rings", "Polynomials over a ring as a ring, division algorithm in F[x], and irreducible polynomials."),
  future("abstract-algebra", 14, "unique-factorization-domains", "Unique Factorization Domains", "Principal ideal domains, Euclidean domains, and UFDs; their hierarchy and examples like Z, F[x], Z[i]."),
  future("abstract-algebra", 15, "field-extensions", "Field Extensions", "Algebraic and transcendental extensions, the degree of an extension, and constructing fields by adjoining roots."),
  future("abstract-algebra", 16, "minimal-polynomials-and-algebraic-elements", "Minimal Polynomials and Algebraic Elements", "Minimal polynomial of an algebraic element, its uniqueness, and the structure of simple algebraic extensions."),
  future("abstract-algebra", 17, "galois-theory-introduction", "Galois Theory: Introduction", "The Galois group of a field extension, automorphisms fixing a base field, and the meaning of separable and normal extensions."),
  future("abstract-algebra", 18, "galois-correspondence", "Galois Correspondence", "The fundamental theorem of Galois theory: a correspondence between intermediate fields and subgroups of the Galois group."),
  future("abstract-algebra", 19, "modules-over-rings", "Modules over Rings", "Modules as generalizations of vector spaces, examples (abelian groups as Z-modules, ideals as R-modules)."),
  future("abstract-algebra", 20, "classification-of-finitely-generated-modules", "Classification of Finitely Generated Modules over a PID", "The structure theorem and its consequences for abelian groups and linear algebra (Jordan form)."),
];

const topology: Lesson[] = [
  future("topology", 1, "topological-spaces-definition", "Topological Spaces: Definition", "Axioms of a topology, examples (discrete, indiscrete, standard topology on R), and motivation from metric spaces."),
  future("topology", 2, "bases-and-subbases", "Bases and Subbases", "Generating a topology from a base or subbase, and verifying that a collection is a base."),
  future("topology", 3, "continuous-functions-topology", "Continuous Functions in Topology", "The topological definition of continuity, equivalence with the epsilon-delta definition in metric spaces, and examples."),
  future("topology", 4, "subspace-topology", "Subspace Topology", "Inducing a topology on a subset, and characterizations of subspace topology."),
  future("topology", 5, "product-topology", "Product Topology", "Topology on Cartesian products, the projection maps, and the universal property of product topology."),
  future("topology", 6, "quotient-topology", "Quotient Topology", "Quotient spaces and the quotient topology, common constructions like the circle from an interval, and the Mobius band."),
  future("topology", 7, "connectedness", "Connectedness", "Connected and disconnected spaces, path-connected spaces, and connected components."),
  future("topology", 8, "path-connectedness", "Path-Connectedness", "Path-connectedness, distinction from connectedness, and the topologist's sine curve counterexample."),
  future("topology", 9, "compactness-topology", "Compactness in Topology", "Open-cover definition of compactness, examples and non-examples, and properties preserved by continuous maps."),
  future("topology", 10, "heine-borel-theorem", "Heine-Borel Theorem", "Compact subsets of R^n are exactly the closed and bounded sets; proof and counterexamples in other spaces."),
  future("topology", 11, "tychonoff-theorem", "Tychonoff's Theorem", "Products of compact spaces are compact; statement, proof sketch, and the role of the axiom of choice."),
  future("topology", 12, "separation-axioms", "Separation Axioms", "T_0 through T_4 axioms (Hausdorff, regular, normal) and the kinds of behavior each guarantees."),
  future("topology", 13, "metric-spaces-as-topological-spaces", "Metric Spaces as Topological Spaces", "Recovering metric-space results as special cases of topology, and metrizability questions."),
  future("topology", 14, "uniform-spaces-introduction", "Uniform Spaces: Introduction", "Generalizing metric spaces to allow uniform continuity without a specific metric."),
  future("topology", 15, "the-fundamental-group", "The Fundamental Group", "Loops based at a point, homotopy classes, the group operation by concatenation, and the fundamental group as a topological invariant."),
  future("topology", 16, "covering-spaces", "Covering Spaces", "Covering maps, the universal cover, and the relationship between covering spaces and subgroups of the fundamental group."),
  future("topology", 17, "seifert-van-kampen-theorem", "Seifert-van Kampen Theorem", "Computing the fundamental group of a space from the fundamental groups of its parts."),
  future("topology", 18, "simplicial-complexes", "Simplicial Complexes", "Building topological spaces from simplices, abstract versus geometric simplicial complexes."),
  future("topology", 19, "homology-introduction", "Homology: Introduction", "Simplicial homology groups, boundary operators, and topological invariants beyond the fundamental group."),
  future("topology", 20, "cohomology-introduction", "Cohomology: Introduction", "Cohomology as a dual to homology, cup product, and the bridge to differential forms and physics."),
];

export const mathematicalFoundationsLessons: Lesson[] = [
  ...mathReentryToolkit,
  ...engineeringAlgebraGeometry,
  ...geometryTrigVectors,
  ...preCalculus,
  ...calculusI,
  ...calculusII,
  ...multivariableCalculus,
  ...linearAlgebra,
  ...differentialEquations,
  ...probabilityAndStatistics,
  ...realAnalysis,
  ...abstractAlgebra,
  ...topology,
];
