import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "mechatronics";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

// Module 1: Systems Primer (orders 2-11; order 1 "what-is-mechatronics" already exists)
const systemsPrimerLessons: Lesson[] = [
  future(
    "systems-primer",
    2,
    "systems-thinking-for-machines",
    "Systems Thinking for Machines",
    "Treat a machine as interacting subsystems rather than parts in isolation, and reason about emergent behavior, interfaces, and failure modes.",
  ),
  future(
    "systems-primer",
    3,
    "block-diagrams-and-system-decomposition",
    "Block Diagrams and System Decomposition",
    "Draw block diagrams that decompose machines into mechanism, sensing, computation, actuation, and power, with clear interfaces between blocks.",
  ),
  future(
    "systems-primer",
    4,
    "signal-flow-and-information-paths",
    "Signal Flow and Information Paths",
    "Trace how information moves from physical phenomena through sensors and processing into commands that drive actuators back into the world.",
  ),
  future(
    "systems-primer",
    5,
    "transduction-energy-and-domains",
    "Transduction, Energy, and Domains",
    "Understand how energy moves between mechanical, electrical, thermal, and fluid domains, and why transducers sit at every domain boundary.",
  ),
  future(
    "systems-primer",
    6,
    "plant-versus-controller",
    "Plant versus Controller",
    "Separate the physical plant being controlled from the controller that commands it, and why this split structures all of mechatronic design.",
  ),
  future(
    "systems-primer",
    7,
    "open-loop-versus-closed-loop-control",
    "Open-Loop versus Closed-Loop Control",
    "Compare feedforward open-loop schemes with feedback closed-loop schemes, when each is appropriate, and the cost of adding a sensor.",
  ),
  future(
    "systems-primer",
    8,
    "real-world-mechatronic-subsystems",
    "Real-World Mechatronic Subsystems",
    "Tour the subsystems of representative machines like a 3D printer, a quadcopter, and an industrial arm, identifying common building blocks.",
  ),
  future(
    "systems-primer",
    9,
    "mechanical-design-language",
    "Mechanical Design Language",
    "Learn the vocabulary of mechanical design: linkages, joints, degrees of freedom, kinematic pairs, and bearings, with sketches you can read.",
  ),
  future(
    "systems-primer",
    10,
    "common-mechatronic-architectures",
    "Common Mechatronic Architectures",
    "Survey recurring system architectures from centralized microcontroller stacks to distributed CAN networks, and the tradeoffs they imply.",
  ),
  future(
    "systems-primer",
    11,
    "from-requirements-to-system-design",
    "From Requirements to System Design",
    "Move from a problem statement to a candidate architecture: clarify requirements, generate concepts, and choose subsystems with rationale.",
  ),
];

// Module 2: Sensors and Measurement (20 lessons)
const sensorsAndMeasurementLessons: Lesson[] = [
  future(
    "sensors-and-measurement",
    1,
    "sensor-taxonomy-and-roles",
    "Sensor Taxonomy and Roles",
    "Classify sensors by physical principle, output type, and role (proprioceptive vs exteroceptive) to navigate the universe of available parts.",
  ),
  future(
    "sensors-and-measurement",
    2,
    "resolution-accuracy-and-precision",
    "Resolution, Accuracy, and Precision",
    "Distinguish resolution, accuracy, precision, repeatability, and hysteresis as separate specs that all matter when choosing a sensor.",
  ),
  future(
    "sensors-and-measurement",
    3,
    "incremental-encoders",
    "Incremental Encoders",
    "How quadrature A/B channels encode rotation, counting edges, direction sensing, and index pulses for homing on incremental encoders.",
  ),
  future(
    "sensors-and-measurement",
    4,
    "absolute-encoders",
    "Absolute Encoders",
    "Single-turn and multi-turn absolute encoders, Gray-code patterns, and protocols like SSI and BiSS that report position without homing.",
  ),
  future(
    "sensors-and-measurement",
    5,
    "hall-effect-sensors",
    "Hall Effect Sensors",
    "Use Hall sensors to detect magnetic fields for current sensing, position switches, and brushless motor commutation feedback.",
  ),
  future(
    "sensors-and-measurement",
    6,
    "potentiometers-as-position-sensors",
    "Potentiometers as Position Sensors",
    "Rotary and linear potentiometers as cheap absolute position sensors, their nonlinearities, wear, and analog interface considerations.",
  ),
  future(
    "sensors-and-measurement",
    7,
    "strain-gauges-and-wheatstone-bridges",
    "Strain Gauges and Wheatstone Bridges",
    "Resistance-based strain sensing, the Wheatstone bridge circuit, gauge factor, and temperature compensation in real installations.",
  ),
  future(
    "sensors-and-measurement",
    8,
    "load-cells-and-force-sensing",
    "Load Cells and Force Sensing",
    "Single-point and multi-axis load cells, calibration with known weights, signal conditioning with instrumentation amplifiers and ADCs.",
  ),
  future(
    "sensors-and-measurement",
    9,
    "accelerometers",
    "Accelerometers",
    "MEMS accelerometers, the proof-mass model, sensitivity and noise density, and the gravity-plus-motion ambiguity in accelerometer signals.",
  ),
  future(
    "sensors-and-measurement",
    10,
    "gyroscopes",
    "Gyroscopes",
    "MEMS rate gyros, Coriolis-based sensing, bias and drift, and why integrating gyro data yields orientation only over short time windows.",
  ),
  future(
    "sensors-and-measurement",
    11,
    "magnetometers",
    "Magnetometers",
    "Three-axis magnetometers for heading reference, hard- and soft-iron distortion, and on-the-bench calibration procedures.",
  ),
  future(
    "sensors-and-measurement",
    12,
    "imu-sensor-fusion-6dof-and-9dof",
    "IMU Sensor Fusion: 6-DoF and 9-DoF",
    "Combining accelerometers, gyros, and magnetometers into 6-DoF and 9-DoF inertial measurement units, with intro fusion algorithms.",
  ),
  future(
    "sensors-and-measurement",
    13,
    "temperature-sensors",
    "Temperature Sensors",
    "Thermistors, RTDs, thermocouples, and integrated digital sensors, with their linearity, range, and interfacing tradeoffs.",
  ),
  future(
    "sensors-and-measurement",
    14,
    "ultrasonic-distance-sensors",
    "Ultrasonic Distance Sensors",
    "Time-of-flight ultrasonic ranging, beam patterns, surface and angle dependence, and limits for indoor robotics applications.",
  ),
  future(
    "sensors-and-measurement",
    15,
    "infrared-distance-sensors",
    "Infrared Distance Sensors",
    "Triangulation and time-of-flight IR ranging modules, ambient light interference, and applications for short-range proximity sensing.",
  ),
  future(
    "sensors-and-measurement",
    16,
    "lidar-basics",
    "Lidar Basics",
    "How single-beam, rotating, and solid-state lidar work, point cloud output, range and accuracy tradeoffs, and typical mechatronic use cases.",
  ),
  future(
    "sensors-and-measurement",
    17,
    "vision-as-a-sensor",
    "Vision as a Sensor",
    "Treating a camera as a measurement device, intrinsics and extrinsics, frame rate and latency, and pairing vision with classical sensors.",
  ),
  future(
    "sensors-and-measurement",
    18,
    "sensor-calibration-procedures",
    "Sensor Calibration Procedures",
    "Linear and nonlinear calibration models, gathering reference data, fitting calibration curves, and documenting calibration in firmware.",
  ),
  future(
    "sensors-and-measurement",
    19,
    "noise-sources-in-sensor-signals",
    "Noise Sources in Sensor Signals",
    "Identify thermal, shot, quantization, and environmental noise in real sensor signals, and reason about noise floors and SNR.",
  ),
  future(
    "sensors-and-measurement",
    20,
    "analog-and-digital-filtering-for-sensors",
    "Analog and Digital Filtering for Sensors",
    "RC and op-amp analog filters paired with digital moving-average, IIR, and FIR filters to clean sensor data without destroying dynamics.",
  ),
];

// Module 3: Actuators and Drives (20 lessons)
const actuatorsAndDrivesLessons: Lesson[] = [
  future(
    "actuators-and-drives",
    1,
    "dc-motor-physics",
    "DC Motor Physics",
    "How a brushed DC motor turns current and magnetic field into torque, with back-EMF, the torque-speed curve, and operating point intuition.",
  ),
  future(
    "actuators-and-drives",
    2,
    "brushed-versus-brushless-motors",
    "Brushed versus Brushless Motors",
    "Compare brushed and brushless DC motors on commutation, efficiency, life, controller complexity, and where each one belongs in a design.",
  ),
  future(
    "actuators-and-drives",
    3,
    "motor-constants-kt-and-kv",
    "Motor Constants Kt and Kv",
    "The torque constant Kt and the back-EMF constant Kv, why they are essentially the same number in SI units, and how to read a motor spec sheet.",
  ),
  future(
    "actuators-and-drives",
    4,
    "gearheads-and-gear-ratios",
    "Gearheads and Gear Ratios",
    "Spur, planetary, and harmonic gearheads, ratio selection for torque and speed, backlash, efficiency, and reflected inertia.",
  ),
  future(
    "actuators-and-drives",
    5,
    "h-bridge-motor-drivers",
    "H-Bridge Motor Drivers",
    "How an H-bridge gives forward, reverse, brake, and coast modes to a DC motor, with dead time, shoot-through, and integrated driver ICs.",
  ),
  future(
    "actuators-and-drives",
    6,
    "pwm-motor-control",
    "PWM Motor Control",
    "Pulse-width modulation as variable voltage, choosing switching frequency, current ripple, and motor heating versus driver losses.",
  ),
  future(
    "actuators-and-drives",
    7,
    "encoder-feedback-for-motors",
    "Encoder Feedback for Motors",
    "Mounting encoders on motor shafts, counts per revolution after gearing, decoding hardware, and basic velocity estimation from counts.",
  ),
  future(
    "actuators-and-drives",
    8,
    "rc-hobby-servos",
    "RC Hobby Servos",
    "The 50 Hz pulse-width protocol, internal feedback loop, torque and speed specs, and the limits of inexpensive hobby servos.",
  ),
  future(
    "actuators-and-drives",
    9,
    "industrial-servo-systems",
    "Industrial Servo Systems",
    "Industrial servo motors and amplifiers with current, velocity, and position loops, EtherCAT and analog interfaces, and tuning workflow.",
  ),
  future(
    "actuators-and-drives",
    10,
    "stepper-motor-fundamentals",
    "Stepper Motor Fundamentals",
    "How a stepper motor advances discrete steps, full step, half step, and microstepping, with torque-speed and missed-step characteristics.",
  ),
  future(
    "actuators-and-drives",
    11,
    "stepper-motor-drivers",
    "Stepper Motor Drivers",
    "Constant-current chopper drivers, current setting, microstep tables, and modern stealth and decay-mode features in chips like the TMC series.",
  ),
  future(
    "actuators-and-drives",
    12,
    "bldc-motor-commutation",
    "BLDC Motor Commutation",
    "Six-step trapezoidal commutation, sensored versus sensorless schemes, and the role of Hall sensors and back-EMF zero crossings.",
  ),
  future(
    "actuators-and-drives",
    13,
    "field-oriented-control-of-bldc",
    "Field-Oriented Control of BLDC Motors",
    "Clarke and Park transforms, direct and quadrature currents, and why field-oriented control delivers smooth low-speed torque from a BLDC.",
  ),
  future(
    "actuators-and-drives",
    14,
    "escs-for-drones-and-robots",
    "ESCs for Drones and Robots",
    "Electronic speed controllers for multirotors and robots, PWM and DShot protocols, idle behavior, regen, and choosing the right ESC.",
  ),
  future(
    "actuators-and-drives",
    15,
    "linear-actuators-and-lead-screws",
    "Linear Actuators and Lead Screws",
    "Lead screws, ball screws, belt drives, and rack-and-pinion converting rotary into linear motion, with efficiency and backdriving tradeoffs.",
  ),
  future(
    "actuators-and-drives",
    16,
    "hydraulic-actuators",
    "Hydraulic Actuators",
    "Hydraulic cylinders and rotary actuators, pumps and valves, force density advantages, and where hydraulics still beat electric drives.",
  ),
  future(
    "actuators-and-drives",
    17,
    "pneumatic-actuators",
    "Pneumatic Actuators",
    "Pneumatic cylinders, solenoid valves, regulators, compressible-fluid behavior, and why pneumatics dominate factory pick-and-place.",
  ),
  future(
    "actuators-and-drives",
    18,
    "actuator-power-electronics-and-thermal-limits",
    "Actuator Power Electronics and Thermal Limits",
    "Continuous versus peak current, MOSFET losses, heatsinking, current sense resistors, and protecting drives against shorts and overcurrent.",
  ),
  future(
    "actuators-and-drives",
    19,
    "choosing-the-right-actuator",
    "Choosing the Right Actuator",
    "A structured tradeoff between DC, BLDC, stepper, servo, hydraulic, and pneumatic actuators by torque, speed, accuracy, cost, and lifetime.",
  ),
  future(
    "actuators-and-drives",
    20,
    "safety-emergency-stop-and-brakes",
    "Safety, Emergency Stop, and Brakes",
    "Mechanical brakes, e-stop circuits, safe torque off, and architectural patterns that keep an actuated machine safe when something fails.",
  ),
];

// Module 4: Control Systems Theory (30 lessons)
const controlSystemsTheoryLessons: Lesson[] = [
  future(
    "control-systems-theory",
    1,
    "open-loop-versus-closed-loop-control-systems",
    "Open-Loop versus Closed-Loop Control Systems",
    "Revisit open- and closed-loop control with formal block diagrams, disturbance rejection, and the cost of measurement.",
  ),
  future(
    "control-systems-theory",
    2,
    "transfer-functions-in-the-s-domain",
    "Transfer Functions in the s-Domain",
    "Laplace transform basics, transfer functions of LTI systems, poles and zeros, and reading dynamics off a transfer function.",
  ),
  future(
    "control-systems-theory",
    3,
    "block-diagram-algebra",
    "Block Diagram Algebra",
    "Series, parallel, and feedback combinations of blocks, Mason's gain formula intuition, and reducing complex diagrams to a single transfer function.",
  ),
  future(
    "control-systems-theory",
    4,
    "step-response-analysis",
    "Step Response Analysis",
    "Rise time, settling time, overshoot, and steady-state error from a step response, and tying them to pole locations of the closed-loop system.",
  ),
  future(
    "control-systems-theory",
    5,
    "frequency-response-fundamentals",
    "Frequency Response Fundamentals",
    "How an LTI system responds to sinusoids, magnitude and phase as functions of frequency, and the bridge to Bode plots.",
  ),
  future(
    "control-systems-theory",
    6,
    "stability-via-routh-hurwitz",
    "Stability via Routh-Hurwitz",
    "The Routh-Hurwitz criterion for testing stability of a closed-loop characteristic polynomial without solving for the roots.",
  ),
  future(
    "control-systems-theory",
    7,
    "root-locus-method",
    "Root Locus Method",
    "How closed-loop poles move as a gain changes, sketching root loci by hand, and using them to choose a stabilizing gain.",
  ),
  future(
    "control-systems-theory",
    8,
    "pid-controller-fundamentals",
    "PID Controller Fundamentals",
    "Proportional, integral, and derivative actions, what each one does to the response, and the canonical PID block diagram.",
  ),
  future(
    "control-systems-theory",
    9,
    "pid-tuning-ziegler-nichols",
    "PID Tuning with Ziegler-Nichols",
    "The classic Ziegler-Nichols tuning rules for step-response and ultimate-gain methods, and when to trust them versus retune.",
  ),
  future(
    "control-systems-theory",
    10,
    "feedforward-control",
    "Feedforward Control",
    "Adding feedforward terms based on model knowledge or measured disturbances to improve tracking without enlarging feedback gain.",
  ),
  future(
    "control-systems-theory",
    11,
    "integral-windup-and-anti-windup",
    "Integral Windup and Anti-Windup",
    "Why integrators saturate during long errors, the consequences for overshoot, and conditional and back-calculation anti-windup schemes.",
  ),
  future(
    "control-systems-theory",
    12,
    "deadband-friction-and-stiction",
    "Deadband, Friction, and Stiction",
    "Practical nonlinearities like deadband, Coulomb friction, and stiction, and how they sabotage linear control design if ignored.",
  ),
  future(
    "control-systems-theory",
    13,
    "lead-lag-compensators",
    "Lead-Lag Compensators",
    "Classical lead and lag compensators in the frequency domain, what they do to phase margin and steady-state error, and design recipes.",
  ),
  future(
    "control-systems-theory",
    14,
    "bode-plots",
    "Bode Plots",
    "Constructing and reading Bode magnitude and phase plots, asymptotic approximations, and combining factors graphically.",
  ),
  future(
    "control-systems-theory",
    15,
    "gain-and-phase-margins",
    "Gain and Phase Margins",
    "Stability margins read from the Bode plot, what they mean physically, and target values for robust mechatronic loops.",
  ),
  future(
    "control-systems-theory",
    16,
    "nyquist-stability-criterion",
    "Nyquist Stability Criterion",
    "Mapping the s-plane contour through the open-loop transfer function and counting encirclements to determine closed-loop stability.",
  ),
  future(
    "control-systems-theory",
    17,
    "state-space-representation",
    "State-Space Representation",
    "Writing a system as x-dot = Ax + Bu, y = Cx + Du, the link to transfer functions, and why state space scales to multivariable systems.",
  ),
  future(
    "control-systems-theory",
    18,
    "controllability",
    "Controllability",
    "Definition of controllability, the controllability matrix, and what it means physically for a state to be unreachable from the input.",
  ),
  future(
    "control-systems-theory",
    19,
    "observability",
    "Observability",
    "Definition of observability, the observability matrix, and the duality between observability and controllability.",
  ),
  future(
    "control-systems-theory",
    20,
    "pole-placement-design",
    "Pole Placement Design",
    "Designing full-state feedback gains to place closed-loop poles at chosen locations, with Ackermann's formula and intuition.",
  ),
  future(
    "control-systems-theory",
    21,
    "linear-quadratic-regulator",
    "Linear Quadratic Regulator (LQR)",
    "Posing the quadratic cost on state and input, solving the algebraic Riccati equation, and tuning LQR via Q and R weighting.",
  ),
  future(
    "control-systems-theory",
    22,
    "luenberger-observers",
    "Luenberger Observers",
    "State observers that estimate unmeasured states, observer gain placement, and the separation principle for combining observer with controller.",
  ),
  future(
    "control-systems-theory",
    23,
    "kalman-filter-introduction",
    "Kalman Filter Introduction",
    "The discrete Kalman filter as an optimal state estimator under Gaussian noise, with prediction and update steps and practical tuning notes.",
  ),
  future(
    "control-systems-theory",
    24,
    "discrete-time-control",
    "Discrete-Time Control",
    "Discrete-time signals and systems, the z-transform, difference equations, and the mapping between continuous and discrete pole locations.",
  ),
  future(
    "control-systems-theory",
    25,
    "sample-and-hold-and-zoh",
    "Sample and Hold and Zero-Order Hold",
    "How sampling and zero-order hold turn a continuous plant into a discrete one, and the half-sample delay that hides inside ZOH.",
  ),
  future(
    "control-systems-theory",
    26,
    "digital-pid-implementation",
    "Digital PID Implementation",
    "Discretizing PID with backward Euler, trapezoidal, and Tustin methods, derivative filtering, and integer-arithmetic implementations.",
  ),
  future(
    "control-systems-theory",
    27,
    "anti-aliasing-and-sampling-choice",
    "Anti-Aliasing and Sampling Choice",
    "Picking a sample rate, designing anti-aliasing filters, and the interaction of filter phase lag with closed-loop stability.",
  ),
  future(
    "control-systems-theory",
    28,
    "actuator-saturation-and-rate-limits",
    "Actuator Saturation and Rate Limits",
    "How saturation, rate limits, and quantization warp ideal control laws, and design techniques that respect actuator limits.",
  ),
  future(
    "control-systems-theory",
    29,
    "real-world-disturbances-and-robustness",
    "Real-World Disturbances and Robustness",
    "Modeling uncertainty, disturbance spectra, sensitivity functions, and how robust control thinking informs everyday tuning.",
  ),
  future(
    "control-systems-theory",
    30,
    "case-studies-in-control-loops",
    "Case Studies in Control Loops",
    "Walk through complete control designs for a motor position loop, a thermal loop, and an inverted pendulum, tying the module's concepts together.",
  ),
];

// Module 5: Real-time Systems and Firmware (15 lessons)
const realTimeSystemsLessons: Lesson[] = [
  future(
    "real-time-systems-and-firmware",
    1,
    "real-time-versus-not",
    "Real-Time versus Not Real-Time",
    "What makes a system real-time, why correctness depends on timing as well as values, and which mechatronic loops require it.",
  ),
  future(
    "real-time-systems-and-firmware",
    2,
    "hard-versus-soft-real-time",
    "Hard versus Soft Real-Time",
    "The distinction between hard real-time guarantees and soft real-time best-effort behavior, with examples from robotics and audio.",
  ),
  future(
    "real-time-systems-and-firmware",
    3,
    "scheduling-theory",
    "Scheduling Theory",
    "Rate-monotonic and earliest-deadline-first scheduling, utilization bounds, and how to argue that a task set will meet its deadlines.",
  ),
  future(
    "real-time-systems-and-firmware",
    4,
    "priority-inversion",
    "Priority Inversion",
    "Unbounded priority inversion, the Mars Pathfinder case, and the priority-inheritance and priority-ceiling protocols that prevent it.",
  ),
  future(
    "real-time-systems-and-firmware",
    5,
    "rtos-concepts",
    "RTOS Concepts",
    "What an RTOS provides over bare-metal firmware: scheduler, tasks, synchronization, timers, and an API for safe concurrent code.",
  ),
  future(
    "real-time-systems-and-firmware",
    6,
    "freertos-overview",
    "FreeRTOS Overview",
    "A tour of FreeRTOS as a representative RTOS, its task model, configuration options, and porting considerations across microcontrollers.",
  ),
  future(
    "real-time-systems-and-firmware",
    7,
    "tasks-and-threads",
    "Tasks and Threads",
    "Designing tasks with clear periods, jitter budgets, and stack sizes, and avoiding the common pitfall of one giant super-loop pretending to be tasks.",
  ),
  future(
    "real-time-systems-and-firmware",
    8,
    "semaphores-and-mutexes",
    "Semaphores and Mutexes",
    "Binary and counting semaphores, mutexes with priority inheritance, and patterns for safely sharing resources between tasks.",
  ),
  future(
    "real-time-systems-and-firmware",
    9,
    "message-queues-and-mailboxes",
    "Message Queues and Mailboxes",
    "Inter-task communication via queues and mailboxes, copy-by-value versus pointers, and avoiding stale-data bugs in producer-consumer designs.",
  ),
  future(
    "real-time-systems-and-firmware",
    10,
    "interrupt-service-routine-design",
    "Interrupt Service Routine Design",
    "Writing ISRs that are short, bounded, and reentrancy-aware, with deferred work via task notifications or queues to keep latency low.",
  ),
  future(
    "real-time-systems-and-firmware",
    11,
    "watchdog-timers-and-fault-recovery",
    "Watchdog Timers and Fault Recovery",
    "Hardware watchdogs, independent task health checks, and patterns that bring a machine to a safe state when firmware misbehaves.",
  ),
  future(
    "real-time-systems-and-firmware",
    12,
    "real-time-communication-can-bus",
    "Real-Time Communication on CAN Bus",
    "How CAN's priority-based arbitration delivers bounded latency for control messages, with frame structure and bus design considerations.",
  ),
  future(
    "real-time-systems-and-firmware",
    13,
    "real-time-communication-ethercat",
    "Real-Time Communication with EtherCAT",
    "EtherCAT's processing-on-the-fly model for sub-millisecond cycle times across many drives, and where it fits in industrial mechatronics.",
  ),
  future(
    "real-time-systems-and-firmware",
    14,
    "firmware-architecture-patterns",
    "Firmware Architecture Patterns",
    "Common firmware patterns: super-loop, event-driven, state machines, and layered drivers, and choosing one for a given mechatronic system.",
  ),
  future(
    "real-time-systems-and-firmware",
    15,
    "debugging-real-time-firmware",
    "Debugging Real-Time Firmware",
    "Tools and habits for finding real-time bugs: tracing, logic analyzers, JTAG, instrumented timing, and reproducing race conditions.",
  ),
];

// Module 6: Integrated Machine Projects (15 lessons)
const integratedMachineProjectsLessons: Lesson[] = [
  future(
    "integrated-machine-projects",
    1,
    "project-planning-for-machines",
    "Project Planning for Machines",
    "Plan a multi-week mechatronic build with phases, milestones, integration points, and slack for the things that will inevitably go wrong.",
  ),
  future(
    "integrated-machine-projects",
    2,
    "writing-requirements-for-a-build",
    "Writing Requirements for a Build",
    "Translate vague goals into measurable functional and non-functional requirements that drive sensor, actuator, and control choices.",
  ),
  future(
    "integrated-machine-projects",
    3,
    "design-reviews",
    "Design Reviews",
    "Run preliminary and critical design reviews that surface risks early, with checklists and a culture of useful skeptical feedback.",
  ),
  future(
    "integrated-machine-projects",
    4,
    "bill-of-materials-and-budgeting",
    "Bill of Materials and Budgeting",
    "Build a structured BOM, track unit and quantity costs, estimate shipping and lead time, and balance budget against capability.",
  ),
  future(
    "integrated-machine-projects",
    5,
    "mechanical-assembly-best-practices",
    "Mechanical Assembly Best Practices",
    "Tolerance stacking, fastener choice, alignment, threadlocker, and the unglamorous workshop habits that produce machines that stay together.",
  ),
  future(
    "integrated-machine-projects",
    6,
    "electrical-schematic-design",
    "Electrical Schematic Design",
    "Draw clean, reviewable schematics with reference designators, named nets, power flags, and modular sheets for a real mechatronic project.",
  ),
  future(
    "integrated-machine-projects",
    7,
    "pcb-layout-basics",
    "PCB Layout Basics",
    "Component placement, ground planes, trace widths for current, EMI considerations, and a simple workflow for getting boards manufactured.",
  ),
  future(
    "integrated-machine-projects",
    8,
    "firmware-structure-for-projects",
    "Firmware Structure for Projects",
    "Organize firmware into hardware abstraction, drivers, services, and application layers so the codebase grows without becoming unmaintainable.",
  ),
  future(
    "integrated-machine-projects",
    9,
    "testing-strategy-for-integrated-systems",
    "Testing Strategy for Integrated Systems",
    "Unit, hardware-in-the-loop, and full system tests; smoke tests; regression tests after every change; and a culture of testing the seams.",
  ),
  future(
    "integrated-machine-projects",
    10,
    "debugging-integrated-systems",
    "Debugging Integrated Systems",
    "Isolating problems across mechanical, electrical, firmware, and control layers, with a deliberate triage order to avoid wasted time.",
  ),
  future(
    "integrated-machine-projects",
    11,
    "documentation-for-machines",
    "Documentation for Machines",
    "What to document and where: theory of operation, schematics, calibration logs, build photos, and the post-mortem.",
  ),
  future(
    "integrated-machine-projects",
    12,
    "demo-and-presentation-skills",
    "Demo and Presentation Skills",
    "Design a demo that survives Murphy's law, narrate it clearly, and tell the engineering story behind the machine to a technical audience.",
  ),
  future(
    "integrated-machine-projects",
    13,
    "project-mini-delta-robot",
    "Project: Mini Delta Robot",
    "A full small delta-robot build from kinematics through firmware, with three motors, a parallel arm geometry, and end-effector control.",
    { estimatedMinutes: 180 },
  ),
  future(
    "integrated-machine-projects",
    14,
    "project-balancing-platform",
    "Project: Balancing Platform",
    "Build a two-axis ball-on-plate or inverted-pendulum platform that ties IMU sensing, motor drive, and PID control into one demo.",
    { estimatedMinutes: 180 },
  ),
  future(
    "integrated-machine-projects",
    15,
    "project-small-cnc",
    "Project: Small CNC Machine",
    "A small three-axis CNC build covering frame, steppers, drivers, limit switches, G-code firmware, and a first-cut shakedown procedure.",
    { estimatedMinutes: 180 },
  ),
];

export const mechatronicsLessons: Lesson[] = [
  ...systemsPrimerLessons,
  ...sensorsAndMeasurementLessons,
  ...actuatorsAndDrivesLessons,
  ...controlSystemsTheoryLessons,
  ...realTimeSystemsLessons,
  ...integratedMachineProjectsLessons,
];
