import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "robotics";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const robotKinematicsLessons: Lesson[] = [
  future("robot-kinematics", 1, "rigid-body-transformations-overview", "Rigid Body Transformations: Overview", "Translation, rotation, and the algebra of composing rigid motions as the language of robot poses in space."),
  future("robot-kinematics", 2, "rotation-matrices-in-2d-and-3d", "Rotation Matrices in 2D and 3D", "Orthogonal matrices with determinant one, how they encode orientation, and the properties that make them composable."),
  future("robot-kinematics", 3, "euler-angles-and-their-pitfalls", "Euler Angles and Their Pitfalls", "Roll-pitch-yaw and ZYX conventions, why convention matters, and the gimbal-lock failure mode for orientation."),
  future("robot-kinematics", 4, "axis-angle-and-rodrigues-formula", "Axis-Angle Representation and Rodrigues' Formula", "Encoding a rotation as an axis plus an angle, and converting to a rotation matrix via the Rodrigues formula."),
  future("robot-kinematics", 5, "quaternions-for-rotation", "Quaternions for Rotation", "Unit quaternions as a singularity-free representation of 3D rotation, with multiplication, conjugation, and SLERP interpolation."),
  future("robot-kinematics", 6, "so3-and-the-rotation-group", "SO(3) and the Rotation Group", "The special orthogonal group as the manifold of 3D rotations, its tangent space, and why it is not a vector space."),
  future("robot-kinematics", 7, "se3-and-rigid-body-motions", "SE(3) and Rigid Body Motions", "The special Euclidean group as the manifold of rigid motions, combining rotation and translation in a single group."),
  future("robot-kinematics", 8, "homogeneous-transformations", "Homogeneous Transformations", "Packing rotation and translation into a 4x4 matrix that composes by ordinary matrix multiplication."),
  future("robot-kinematics", 9, "kinematic-chains-and-link-frames", "Kinematic Chains and Link Frames", "Modeling a manipulator as a chain of links connected by joints, and attaching a coordinate frame to each link."),
  future("robot-kinematics", 10, "denavit-hartenberg-conventions", "Denavit-Hartenberg Conventions", "Standard and modified DH parameters, the four-parameter recipe for placing link frames, and common pitfalls."),
  future("robot-kinematics", 11, "forward-kinematics-of-manipulators", "Forward Kinematics of Manipulators", "Composing DH transforms to map joint angles to end-effector pose, the bread-and-butter computation for any arm."),
  future("robot-kinematics", 12, "analytical-inverse-kinematics", "Analytical Inverse Kinematics", "Closed-form IK for 6-DOF arms with spherical wrists, geometric decomposition, and multiple-solution branches."),
  future("robot-kinematics", 13, "numerical-inverse-kinematics", "Numerical Inverse Kinematics", "Jacobian-based iterative IK using Newton, damped least squares, and pseudoinverse methods for arbitrary chains."),
  future("robot-kinematics", 14, "manipulator-jacobians", "Manipulator Jacobians", "Geometric and analytical Jacobians, mapping joint velocities to end-effector twists, and computing them column-by-column."),
  future("robot-kinematics", 15, "kinematic-singularities", "Kinematic Singularities", "Configurations where the Jacobian loses rank, the resulting loss of mobility, and how to detect and avoid them."),
  future("robot-kinematics", 16, "wrist-configurations-and-decoupling", "Wrist Configurations and Decoupling", "Spherical wrist designs that decouple position and orientation IK, and the wrist singularities that come with them."),
  future("robot-kinematics", 17, "redundant-manipulators-and-null-space", "Redundant Manipulators and Null-Space Motions", "Arms with more than six DOF, null-space projection, and using extra freedom to avoid obstacles or singularities."),
  future("robot-kinematics", 18, "parallel-robots-and-stewart-platforms", "Parallel Robots and Stewart Platforms", "Closed-chain kinematics, why forward kinematics is hard for parallel mechanisms but inverse kinematics is easy."),
  future("robot-kinematics", 19, "mobile-robot-kinematics-overview", "Mobile Robot Kinematics: Overview", "Pose on the plane, body frames, and the difference between manipulator and mobile-base kinematics."),
  future("robot-kinematics", 20, "differential-drive-kinematics", "Differential Drive Kinematics", "Forward and inverse kinematics of two-wheeled differential-drive robots, instantaneous center of rotation."),
  future("robot-kinematics", 21, "ackermann-steering-kinematics", "Ackermann Steering Kinematics", "Car-like kinematics, bicycle model, and the geometric constraints that govern wheeled vehicles with steering axles."),
  future("robot-kinematics", 22, "omnidirectional-and-mecanum-drives", "Omnidirectional and Mecanum Drives", "Kinematics of omni-wheel and mecanum-wheel platforms that can translate and rotate independently in the plane."),
  future("robot-kinematics", 23, "holonomic-vs-nonholonomic-constraints", "Holonomic vs Nonholonomic Constraints", "Configuration-space versus velocity constraints, why a car cannot park sideways, and the planning implications."),
  future("robot-kinematics", 24, "screw-theory-twists-and-wrenches", "Screw Theory, Twists, and Wrenches", "Screw axes as the natural primitive for rigid motion, twists for velocity, and wrenches for force and torque."),
  future("robot-kinematics", 25, "lie-groups-and-exponential-coordinates", "Lie Groups and Exponential Coordinates for Robotics", "The exponential map from se(3) to SE(3), the matrix logarithm, and using Lie theory to unify rotation and translation."),
];

const robotDynamicsLessons: Lesson[] = [
  future("robot-dynamics", 1, "rigid-body-dynamics-foundations", "Rigid Body Dynamics Foundations", "Linear and angular momentum, the Newton-Euler equations for a single rigid body, and the meaning of body and spatial frames."),
  future("robot-dynamics", 2, "inertia-tensors-and-principal-axes", "Inertia Tensors and Principal Axes", "The inertia tensor as a quadratic form, parallel-axis theorem, and diagonalization to principal axes for computational efficiency."),
  future("robot-dynamics", 3, "newton-euler-for-one-link", "Newton-Euler for One Link", "Writing force and torque balance for a single moving link, including gravity, inertial, and joint reaction forces."),
  future("robot-dynamics", 4, "recursive-newton-euler-algorithm", "Recursive Newton-Euler Algorithm", "The forward-backward recursion that computes inverse dynamics in linear time, the workhorse of real-time control."),
  future("robot-dynamics", 5, "lagrangian-formulation-of-robot-dynamics", "Lagrangian Formulation of Robot Dynamics", "Kinetic and potential energy, Euler-Lagrange equations, and deriving manipulator equations of motion symbolically."),
  future("robot-dynamics", 6, "the-mass-matrix-and-its-structure", "The Mass Matrix and Its Structure", "Positive-definiteness, configuration dependence, and how the manipulator mass matrix encodes coupling between joints."),
  future("robot-dynamics", 7, "coriolis-and-centrifugal-terms", "Coriolis and Centrifugal Terms", "Christoffel symbols, the C(q, q-dot) matrix, and the velocity-dependent forces that arise in rotating frames."),
  future("robot-dynamics", 8, "the-gravity-vector", "The Gravity Vector", "Configuration-dependent gravitational torques and the role of gravity compensation in joint-space control."),
  future("robot-dynamics", 9, "manipulator-equations-of-motion", "Manipulator Equations of Motion", "Assembling M(q) q-ddot + C(q, q-dot) q-dot + g(q) = tau and reading off its physical meaning for control design."),
  future("robot-dynamics", 10, "friction-modeling-in-joints", "Friction Modeling in Joints", "Coulomb, viscous, Stribeck, and presliding friction models, parameter identification, and the limits of each."),
  future("robot-dynamics", 11, "contact-dynamics-fundamentals", "Contact Dynamics Fundamentals", "Normal and frictional contact forces, complementarity conditions, and the discontinuous nature of contact."),
  future("robot-dynamics", 12, "constrained-dynamics-and-multipliers", "Constrained Dynamics and Lagrange Multipliers", "Closed loops and holonomic constraints, projected dynamics, and the role of Lagrange multipliers in solving them."),
  future("robot-dynamics", 13, "simulating-serial-manipulators", "Simulating Serial Manipulators", "Forward dynamics, integration schemes, and the practicalities of stepping a manipulator simulation reliably."),
  future("robot-dynamics", 14, "simulating-mobile-robots", "Simulating Mobile Robots", "Dynamic models for wheeled and tracked platforms, integration of nonholonomic constraints, and slip modeling."),
  future("robot-dynamics", 15, "wheel-ground-friction-models", "Wheel-Ground Friction Models", "Pacejka, brush, and simpler linear models of tire-ground interaction, and what they imply for mobile-robot dynamics."),
  future("robot-dynamics", 16, "articulated-body-algorithm", "The Articulated Body Algorithm", "Featherstone's O(n) forward-dynamics algorithm using spatial inertias and articulated-body inertias."),
  future("robot-dynamics", 17, "parallel-structure-dynamics", "Parallel Structure Dynamics", "Modeling the dynamics of closed-chain mechanisms like Stewart platforms via constraint elimination."),
  future("robot-dynamics", 18, "flexible-links-and-flexibility", "Flexible Links and Joint Flexibility", "Modeling link bending and harmonic-drive elasticity, and the slow modes that bite real arms when controllers ignore them."),
  future("robot-dynamics", 19, "vibrations-and-natural-modes", "Vibrations and Natural Modes", "Modal analysis of multi-link systems, natural frequencies, and damping ratios that shape achievable controller bandwidth."),
  future("robot-dynamics", 20, "identification-of-robot-dynamics", "Identification of Robot Dynamics", "Excitation trajectories, least-squares fitting in the linear-in-parameters form, and validating identified models."),
  future("robot-dynamics", 21, "model-parameter-estimation-techniques", "Model Parameter Estimation Techniques", "Estimating link masses, centers of mass, and inertias from motion data with physical-consistency constraints."),
  future("robot-dynamics", 22, "mujoco-for-robot-simulation", "MuJoCo for Robot Simulation", "MuJoCo's contact model, MJCF model format, and why MuJoCo is a default choice for learning-based research."),
  future("robot-dynamics", 23, "pybullet-for-robot-simulation", "PyBullet for Robot Simulation", "PyBullet's API, URDF loading, and using it for fast prototyping of grasping and manipulation experiments."),
  future("robot-dynamics", 24, "drake-for-robot-simulation", "Drake for Robot Simulation", "Drake's systems framework, multibody plant, and its strengths for trajectory optimization and contact-rich problems."),
  future("robot-dynamics", 25, "isaac-sim-for-robotics", "Isaac Sim for Robotics", "NVIDIA Isaac Sim, GPU-parallel environments, and using Isaac for large-scale reinforcement learning and sim-to-real."),
];

const motionPlanningLessons: Lesson[] = [
  future("motion-planning", 1, "configuration-space-overview", "Configuration Space Overview", "The C-space as the set of all robot poses, why planning in C-space is the right abstraction, and dimension counting."),
  future("motion-planning", 2, "obstacles-in-configuration-space", "Obstacles in Configuration Space", "Mapping workspace obstacles into C-space obstacles, the C-obstacle for a manipulator, and computational difficulty."),
  future("motion-planning", 3, "graph-search-foundations-for-planning", "Graph Search Foundations for Planning", "Discrete graphs, nodes and edges as states and actions, and the role of search in robotics planning."),
  future("motion-planning", 4, "breadth-first-search-for-planning", "Breadth-First Search for Planning", "BFS as the simplest complete search, when it finds shortest paths, and its memory and time complexity."),
  future("motion-planning", 5, "depth-first-search-and-iterative-deepening", "Depth-First Search and Iterative Deepening", "DFS, recursion versus stack, iterative deepening as a memory-efficient compromise, and pitfalls in robotics use."),
  future("motion-planning", 6, "dijkstras-algorithm", "Dijkstra's Algorithm", "Uniform-cost search for weighted graphs, priority-queue implementation, and the relaxation invariant that proves correctness."),
  future("motion-planning", 7, "a-star-and-heuristic-search", "A* and Heuristic Search", "A* search with admissible and consistent heuristics, the f = g + h decomposition, and optimality guarantees."),
  future("motion-planning", 8, "weighted-and-bounded-suboptimal-a-star", "Weighted and Bounded-Suboptimal A*", "Inflating heuristics to trade optimality for speed, and bounded-suboptimal variants used in real planners."),
  future("motion-planning", 9, "anytime-repairing-a-star", "Anytime Repairing A* (ARA*)", "Anytime planning that improves a solution as time allows, reusing search effort across replanning rounds."),
  future("motion-planning", 10, "sampling-based-planning-overview", "Sampling-Based Planning Overview", "Why exact C-space planning is intractable, and how random sampling sidesteps the dimensionality wall."),
  future("motion-planning", 11, "probabilistic-roadmaps", "Probabilistic Roadmaps (PRM)", "PRM construction and querying, multi-query planning in static environments, and roadmap connectivity."),
  future("motion-planning", 12, "rapidly-exploring-random-trees", "Rapidly-Exploring Random Trees (RRT)", "RRT growth toward random samples, Voronoi-bias, and probabilistic completeness as the central theoretical guarantee."),
  future("motion-planning", 13, "rrt-connect-for-fast-queries", "RRT-Connect for Fast Queries", "Bidirectional tree growth, greedy extend steps, and the dramatic empirical speedup over plain RRT."),
  future("motion-planning", 14, "rrt-star-for-asymptotic-optimality", "RRT* for Asymptotic Optimality", "Rewiring near new samples, the asymptotic optimality guarantee, and the practical cost-versus-optimality tradeoff."),
  future("motion-planning", 15, "informed-and-batch-informed-trees", "Informed RRT* and BIT*", "Sampling from an informed ellipsoid, batch processing of samples, and combining graph search with sampling-based planning."),
  future("motion-planning", 16, "trajectory-optimization-overview", "Trajectory Optimization Overview", "Formulating planning as nonlinear optimization over a parametrized trajectory, costs and constraints in a unified framework."),
  future("motion-planning", 17, "direct-methods-collocation-and-shooting", "Direct Methods: Collocation and Shooting", "Direct transcription of optimal control problems via multiple shooting and collocation, and their numerical properties."),
  future("motion-planning", 18, "indirect-methods-and-pontryagin", "Indirect Methods and Pontryagin's Principle", "The maximum principle, boundary-value problems for optimal trajectories, and when indirect methods still beat direct."),
  future("motion-planning", 19, "optimal-control-fundamentals", "Optimal Control Fundamentals", "Cost functionals, the Hamilton-Jacobi-Bellman equation, and LQR as the canonical solvable case."),
  future("motion-planning", 20, "chomp-trajectory-optimization", "CHOMP for Trajectory Optimization", "Covariant Hamiltonian Optimization for Motion Planning, gradient descent on a smoothness-plus-obstacle cost."),
  future("motion-planning", 21, "stomp-stochastic-trajectory-optimization", "STOMP: Stochastic Trajectory Optimization", "Sampling noisy trajectory rollouts, importance-weighted updates, and handling non-differentiable cost terms."),
  future("motion-planning", 22, "mpc-as-online-planning", "Model Predictive Control as Online Planning", "Receding-horizon planning as a controller, real-time iteration, and the planning-control boundary blur."),
  future("motion-planning", 23, "time-parameterization-of-paths", "Time Parameterization of Paths", "Converting a geometric path into a time trajectory respecting velocity, acceleration, and torque limits."),
  future("motion-planning", 24, "motion-smoothing-and-shortcutting", "Motion Smoothing and Shortcutting", "Post-processing planner output with shortcut and B-spline smoothing to produce executable trajectories."),
  future("motion-planning", 25, "collision-checking-broad-and-narrow-phase", "Collision Checking: Broad and Narrow Phase", "Bounding-volume hierarchies, GJK and EPA for convex shapes, and the trade-offs of fidelity versus speed."),
];

const perceptionAndSlamLessons: Lesson[] = [
  future("perception-and-slam", 1, "probabilistic-robotics-overview", "Probabilistic Robotics Overview", "Why every sensor and actuator is uncertain, and the probabilistic framework that turns this into engineering rigor."),
  future("perception-and-slam", 2, "sensor-models", "Sensor Models", "Beam, likelihood-field, and feature-based sensor models for range, vision, and IMU sensors."),
  future("perception-and-slam", 3, "motion-models", "Motion Models", "Odometry and velocity motion models for wheeled robots, with noise distributions calibrated from data."),
  future("perception-and-slam", 4, "the-bayes-filter", "The Bayes Filter", "Predict-update cycle, the recursive form, and the Markov assumption as the foundation of all state-estimation methods."),
  future("perception-and-slam", 5, "kalman-filter-fundamentals", "Kalman Filter Fundamentals", "The Kalman filter as the optimal linear-Gaussian Bayes filter, with the predict and update equations derived."),
  future("perception-and-slam", 6, "extended-kalman-filter", "Extended Kalman Filter", "Linearization around the current estimate, Jacobian computation, and the EKF's limits when nonlinearities are large."),
  future("perception-and-slam", 7, "unscented-kalman-filter", "Unscented Kalman Filter", "Sigma-point propagation, the unscented transform, and when UKF beats EKF in accuracy and tuning."),
  future("perception-and-slam", 8, "particle-filters", "Particle Filters", "Sequential importance resampling, sample impoverishment, and using particles to handle multimodal posteriors."),
  future("perception-and-slam", 9, "occupancy-grid-mapping", "Occupancy Grid Mapping", "Log-odds update, inverse sensor models, and producing 2D occupancy maps from range data."),
  future("perception-and-slam", 10, "scan-matching-overview", "Scan Matching Overview", "Aligning successive lidar or depth scans, correspondence-based and correspondence-free families."),
  future("perception-and-slam", 11, "iterative-closest-point", "Iterative Closest Point (ICP)", "Point-to-point and point-to-plane ICP, convergence behavior, and tricks for robust correspondences."),
  future("perception-and-slam", 12, "normal-distributions-transform", "Normal Distributions Transform (NDT)", "Cell-based Gaussian approximation of point clouds and NDT as a smoother alternative to ICP."),
  future("perception-and-slam", 13, "rgbd-odometry", "RGBD Odometry", "Photometric and depth-based dense alignment, direct methods, and the strengths of depth cameras for odometry."),
  future("perception-and-slam", 14, "visual-odometry", "Visual Odometry", "Feature extraction, matching, and frame-to-frame motion estimation from monocular and stereo cameras."),
  future("perception-and-slam", 15, "feature-based-slam", "Feature-Based SLAM", "Maintaining a map of landmarks while estimating pose, with bundle adjustment as the optimization core."),
  future("perception-and-slam", 16, "orb-slam-architecture", "ORB-SLAM Architecture", "Tracking, local mapping, and loop closure threads of ORB-SLAM, and why its design has been so influential."),
  future("perception-and-slam", 17, "lidar-inertial-odometry", "LIDAR-Inertial Odometry", "Tightly coupled LIO systems, IMU preintegration, and the robustness benefits of fusing inertial with lidar."),
  future("perception-and-slam", 18, "factor-graphs-for-state-estimation", "Factor Graphs for State Estimation", "Variables and factors, the bipartite graph structure, and why factor graphs are the modern lingua franca of SLAM."),
  future("perception-and-slam", 19, "gtsam-and-isam-introduction", "GTSAM and iSAM Introduction", "Hands-on factor-graph construction in GTSAM, incremental smoothing and mapping, and large-scale optimization."),
  future("perception-and-slam", 20, "pose-graph-optimization", "Pose Graph Optimization", "Building a graph of relative-pose constraints, nonlinear least squares, and the role of robust kernels."),
  future("perception-and-slam", 21, "loop-closure-detection", "Loop Closure Detection", "Bag-of-words methods, learned global descriptors, and verifying candidate loop closures geometrically."),
  future("perception-and-slam", 22, "semantic-slam", "Semantic SLAM", "Adding object and semantic-class information to the map, and using semantics to improve data association."),
  future("perception-and-slam", 23, "lifelong-and-multi-session-mapping", "Lifelong and Multi-Session Mapping", "Handling change over time, merging maps across sessions, and forgetting outdated structure gracefully."),
  future("perception-and-slam", 24, "multi-sensor-fusion-architectures", "Multi-Sensor Fusion Architectures", "Loose vs tight coupling, federated and centralized fusion, and design choices for sensor suites in real robots."),
  future("perception-and-slam", 25, "data-association-and-outlier-rejection", "Data Association and Outlier Rejection", "Nearest-neighbor and joint compatibility tests, RANSAC, and robust kernels for handling wrong correspondences in SLAM."),
];

const robotControlLessons: Lesson[] = [
  future("robot-control", 1, "joint-pd-with-gravity-compensation", "Joint PD with Gravity Compensation", "The simplest controller that actually works on a manipulator, why gravity compensation matters, and stability via energy arguments."),
  future("robot-control", 2, "computed-torque-control", "Computed Torque Control", "Inverse-dynamics-based feedback linearization, the resulting linear error dynamics, and dependence on model accuracy."),
  future("robot-control", 3, "task-space-control", "Task-Space Control", "Controlling end-effector pose directly using the Jacobian transpose and Jacobian inverse formulations."),
  future("robot-control", 4, "operational-space-control", "Operational Space Control", "Khatib's operational-space formulation, dynamically consistent inverse, and decoupled task-space behavior."),
  future("robot-control", 5, "impedance-control", "Impedance Control", "Imposing a desired mass-spring-damper relationship between the end effector and the environment, instead of a setpoint."),
  future("robot-control", 6, "admittance-control", "Admittance Control", "The duality of impedance and admittance, when each is the right choice, and stability concerns at contact."),
  future("robot-control", 7, "force-control-fundamentals", "Force Control Fundamentals", "Direct force feedback, force-torque sensor placement, and the bandwidth and stability challenges of pure force control."),
  future("robot-control", 8, "hybrid-position-force-control", "Hybrid Position-Force Control", "Decomposing the task into position-controlled and force-controlled subspaces with selection matrices."),
  future("robot-control", 9, "friction-compensation-strategies", "Friction Compensation Strategies", "Model-based feedforward compensation, dithering, and learning-based friction observers for joint-level control."),
  future("robot-control", 10, "model-predictive-control-for-robots", "Model Predictive Control for Robots", "Receding-horizon optimization with dynamics and constraints, and why MPC has become a default for legged and aerial robots."),
  future("robot-control", 11, "real-time-iteration-for-mpc", "Real-Time Iteration for MPC", "Sequential quadratic programming with a single iteration per step, warm-starting, and computational budgets."),
  future("robot-control", 12, "whole-body-control", "Whole-Body Control", "Hierarchical task formulation, quadratic-programming solvers, and managing many simultaneous tasks on a humanoid."),
  future("robot-control", 13, "momentum-based-balancing", "Momentum-Based Balancing", "Centroidal dynamics, angular-momentum regulation, and the role of capture-point and ZMP for balancing robots."),
  future("robot-control", 14, "mimo-control-fundamentals", "MIMO Control Fundamentals", "State-space control for multi-input multi-output systems, pole placement, and LQR design for robots."),
  future("robot-control", 15, "robust-control-for-robots", "Robust Control for Robots", "H-infinity, sliding mode, and other techniques for guaranteed performance under bounded model uncertainty."),
  future("robot-control", 16, "adaptive-control", "Adaptive Control", "Online parameter estimation feeding the controller, the certainty equivalence principle, and parameter-drift hazards."),
  future("robot-control", 17, "learning-based-control-overview", "Learning-Based Control Overview", "Imitation learning, model-based and model-free RL applied to robot control, and the safety wrappers required in practice."),
  future("robot-control", 18, "residual-policies-on-classical-controllers", "Residual Policies on Classical Controllers", "Letting a learned policy correct a baseline controller, combining the guarantees of classical control with learned adaptability."),
  future("robot-control", 19, "ros-controllers-and-controller-manager", "ROS Controllers and Controller Manager", "The ros_control architecture, hardware-interface abstraction, and standard controllers for joint and effort control."),
  future("robot-control", 20, "drake-systems-framework", "Drake's Systems Framework for Control", "Composing controllers as systems, the diagram-builder pattern, and Drake's strengths for hybrid and contact-rich control."),
];

const rosEcosystemLessons: Lesson[] = [
  future("ros-ecosystem", 1, "ros-history-and-design-goals", "ROS History and Design Goals", "Where ROS came from, the Willow Garage origins, and the design tradeoffs that shaped the platform."),
  future("ros-ecosystem", 2, "ros-nodes-and-topics", "ROS Nodes and Topics", "Process-level modularity, publish-subscribe messaging, and the topic abstraction that organizes a ROS graph."),
  future("ros-ecosystem", 3, "ros-services-and-actions", "ROS Services and Actions", "Request-response services, long-running actions with feedback, and choosing the right communication primitive."),
  future("ros-ecosystem", 4, "ros-parameters-and-configuration", "ROS Parameters and Configuration", "The parameter server, YAML-driven configuration, and the role of parameters in tunable runtime behavior."),
  future("ros-ecosystem", 5, "ros2-evolution-and-design", "ROS2 Evolution and Design", "Why ROS2 was rewritten, what changed compared to ROS1, and the path most projects take to migrate."),
  future("ros-ecosystem", 6, "dds-as-the-ros2-transport", "DDS as the ROS2 Transport", "The Data Distribution Service standard, vendor implementations, and how DDS shapes ROS2 discovery and messaging."),
  future("ros-ecosystem", 7, "qos-profiles-in-ros2", "QoS Profiles in ROS2", "Reliability, durability, history, and deadline policies, and how QoS mismatches cause silent message loss."),
  future("ros-ecosystem", 8, "real-time-considerations-in-ros2", "Real-Time Considerations in ROS2", "The executor model, real-time kernels, and what it takes to use ROS2 in a hard real-time control loop."),
  future("ros-ecosystem", 9, "launch-files-in-ros2", "Launch Files in ROS2", "Python-based launch descriptions, composition of large systems, and remapping and namespacing at launch time."),
  future("ros-ecosystem", 10, "packages-and-workspaces", "Packages and Workspaces", "Package layout, ament and colcon build systems, and managing dependencies across a multi-package workspace."),
  future("ros-ecosystem", 11, "rviz-visualization", "RViz Visualization", "The plugin-based 3D visualizer, common display types, and using RViz to debug perception and planning pipelines."),
  future("ros-ecosystem", 12, "tf2-transforms-and-frames", "tf2 Transforms and Frames", "The tf2 tree, broadcasting and listening to transforms, time interpolation, and conventions for frame naming."),
  future("ros-ecosystem", 13, "gazebo-simulation", "Gazebo Simulation", "Classic Gazebo and Gazebo Sim, world and model SDF, sensor plugins, and the ROS-Gazebo bridge."),
  future("ros-ecosystem", 14, "moveit-planning-framework", "MoveIt Planning Framework", "Motion planning, IK, and collision-aware execution for arms, configured via SRDF and connected to ROS controllers."),
  future("ros-ecosystem", 15, "ros-control-architecture", "ros_control Architecture", "Hardware interfaces, controllers, and the controller manager, and how this abstraction enables hardware portability."),
];

const fieldDeploymentLessons: Lesson[] = [
  future("field-deployment", 1, "reliability-engineering-for-robots", "Reliability Engineering for Robots", "MTBF and MTTR, redundancy, derating, and the engineering disciplines that turn a prototype into a deployable system."),
  future("field-deployment", 2, "fault-trees-for-robotic-systems", "Fault Trees for Robotic Systems", "Constructing fault trees, identifying minimal cut sets, and quantifying the probability of top-level failures."),
  future("field-deployment", 3, "fmea-failure-modes-and-effects-analysis", "FMEA: Failure Modes and Effects Analysis", "Systematic enumeration of failure modes, severity-occurrence-detection scoring, and prioritizing engineering effort."),
  future("field-deployment", 4, "recovery-behaviors-and-state-machines", "Recovery Behaviors and State Machines", "Designing the state machine of fallback behaviors that fire when nominal control fails, and how to test them."),
  future("field-deployment", 5, "logging-and-replay", "Logging and Replay", "Choosing what to log, sample rates, and structuring logs so that offline replay reproduces production behavior."),
  future("field-deployment", 6, "rosbag-and-mcap", "rosbag and MCAP", "The rosbag and MCAP formats, recording and replay tooling, and considerations for long-duration field logging."),
  future("field-deployment", 7, "debugging-from-logs", "Debugging From Logs", "Triaging field failures with only the recorded data, building intuition about what each log channel can tell you."),
  future("field-deployment", 8, "remote-teleoperation-architectures", "Remote Teleoperation Architectures", "Bandwidth and latency budgets, predictive displays, and the human-in-the-loop fallback that keeps fielded robots alive."),
  future("field-deployment", 9, "safety-analysis-for-robots", "Safety Analysis for Robots", "Hazard analysis, ISO 10218 and ISO 13482 frameworks, and translating safety analysis into engineering requirements."),
  future("field-deployment", 10, "e-stops-and-safety-rated-stops", "E-Stops and Safety-Rated Stops", "Category 0, 1, and 2 stops, dual-channel monitoring, and the wiring discipline that makes an e-stop trustworthy."),
  future("field-deployment", 11, "fail-safe-design-patterns", "Fail-Safe Design Patterns", "Designing systems so that the failure mode is the safe mode, with examples from brakes, valves, and software watchdogs."),
  future("field-deployment", 12, "certification-considerations-ul-ce", "Certification Considerations: UL, CE, and Beyond", "What UL listings, CE marking, and FCC compliance require, and how to plan for them from the start of the project."),
  future("field-deployment", 13, "field-test-protocols", "Field Test Protocols", "Designing repeatable field tests, environmental envelopes, acceptance criteria, and metrics that drive learning."),
  future("field-deployment", 14, "the-lab-to-field-gap", "The Lab-to-Field Gap", "Why robots that work in the lab fail in the field, and the categories of distribution shift that bite hardest."),
  future("field-deployment", 15, "case-studies-of-robot-deployments", "Case Studies of Robot Deployments", "Lessons from real deployments — warehouse, agriculture, autonomous vehicles, and surgical robots — distilled into design principles."),
];

export const roboticsLessons: Lesson[] = [
  ...robotKinematicsLessons,
  ...robotDynamicsLessons,
  ...motionPlanningLessons,
  ...perceptionAndSlamLessons,
  ...robotControlLessons,
  ...rosEcosystemLessons,
  ...fieldDeploymentLessons,
];
