import type { Lesson } from "../../../src/lib/types.ts";

const TRACK = "theoretical-physics";

function future(
  moduleSlug: string,
  order: number,
  slug: string,
  title: string,
  summary: string,
  options: { estimatedMinutes?: number; prerequisites?: string[] } = {},
): Lesson {
  return {
    slug,
    trackSlug: TRACK,
    moduleSlug,
    title,
    summary,
    kind: "lesson",
    status: "future",
    order,
    estimatedMinutes: options.estimatedMinutes ?? 90,
    prerequisites: options.prerequisites,
    mdxPath: `content/lessons/${slug}.mdx`,
  };
}

const mathematicalMethodsForPhysics: Lesson[] = [
  future("mathematical-methods-for-physics", 2, "vector-spaces-and-linear-operators-review", "Vector Spaces and Linear Operators Review", "A graduate-level recap of vector spaces, dual spaces, and bounded linear operators framed for the language of quantum mechanics and field theory."),
  future("mathematical-methods-for-physics", 3, "hilbert-spaces-for-physics", "Hilbert Spaces for Physics", "Inner product structure, completeness, orthonormal bases, and the spectral theorem as the foundational arena for quantum states."),
  future("mathematical-methods-for-physics", 4, "function-spaces-and-distributions", "Function Spaces and Distributions", "L^2 spaces, Schwartz functions, tempered distributions, and the Dirac delta as the rigorous backbone of physical computations."),
  future("mathematical-methods-for-physics", 5, "complex-analysis-analytic-functions", "Complex Analysis: Analytic Functions", "Holomorphy, Cauchy-Riemann equations, conformal maps, and analytic continuation as physicists actually use them."),
  future("mathematical-methods-for-physics", 6, "contour-integration-techniques", "Contour Integration Techniques", "Closed-contour integration, Jordan's lemma, principal values, and indented contours for evaluating physical integrals."),
  future("mathematical-methods-for-physics", 7, "residue-theorem-and-applications", "Residue Theorem and Applications", "Computing poles, residues, and using the residue theorem to evaluate real integrals that appear in scattering and Green's functions."),
  future("mathematical-methods-for-physics", 8, "fourier-series-and-transforms-for-physics", "Fourier Series and Transforms for Physics", "Fourier series and transforms on the line, Plancherel, convolution, and applications to wave packets and momentum-space physics."),
  future("mathematical-methods-for-physics", 9, "laplace-transforms-and-physical-systems", "Laplace Transforms and Physical Systems", "Laplace transforms, inversion via Bromwich contour, and their use in damped oscillators, transient circuits, and control."),
  future("mathematical-methods-for-physics", 10, "gamma-and-beta-functions", "Gamma and Beta Functions", "The gamma function, its analytic continuation, the beta function, and ubiquitous appearances in dimensional regularization and statistics."),
  future("mathematical-methods-for-physics", 11, "bessel-functions-and-cylindrical-problems", "Bessel Functions and Cylindrical Problems", "Bessel functions of the first and second kind, generating functions, asymptotics, and applications to wave and diffusion problems in cylinders."),
  future("mathematical-methods-for-physics", 12, "legendre-polynomials-and-spherical-harmonics", "Legendre Polynomials and Spherical Harmonics", "Legendre polynomials from Rodrigues' formula, associated Legendres, spherical harmonics, and angular eigenfunctions of the Laplacian."),
  future("mathematical-methods-for-physics", 13, "hermite-and-laguerre-polynomials", "Hermite and Laguerre Polynomials", "Orthogonal polynomial families arising from the quantum harmonic oscillator and the hydrogen atom radial equation."),
  future("mathematical-methods-for-physics", 14, "orthogonal-polynomials-general-theory", "Orthogonal Polynomials: General Theory", "Weight functions, three-term recurrences, Christoffel-Darboux identity, and unified treatment of classical orthogonal families."),
  future("mathematical-methods-for-physics", 15, "sturm-liouville-theory", "Sturm-Liouville Theory", "Self-adjoint second-order operators, eigenfunction expansions, completeness, and Sturm-Liouville as the engine behind separation of variables."),
  future("mathematical-methods-for-physics", 16, "tensor-algebra-for-physicists", "Tensor Algebra for Physicists", "Multilinear maps, tensor products, index conventions, contraction, and tensor transformation laws under change of basis."),
  future("mathematical-methods-for-physics", 17, "tensor-calculus-on-manifolds", "Tensor Calculus on Manifolds", "Coordinate-free tensors on smooth manifolds, the covariant derivative, Christoffel symbols, and intrinsic geometric reasoning."),
  future("mathematical-methods-for-physics", 18, "differential-forms-and-exterior-calculus", "Differential Forms and Exterior Calculus", "Wedge product, exterior derivative, pullbacks, integration on manifolds, and Stokes' theorem in its modern form."),
  future("mathematical-methods-for-physics", 19, "calculus-of-variations-foundations", "Calculus of Variations: Foundations", "Functionals, functional derivatives, the variational problem, and necessary conditions for extrema with worked physical examples."),
  future("mathematical-methods-for-physics", 20, "euler-lagrange-equations-and-constraints", "Euler-Lagrange Equations and Constraints", "Derivation of the Euler-Lagrange equations, multiple fields, isoperimetric constraints, and Lagrange multipliers in variational form."),
  future("mathematical-methods-for-physics", 21, "greens-functions-for-physical-pdes", "Green's Functions for Physical PDEs", "Construction of Green's functions for Poisson, Helmholtz, wave, and diffusion equations and their interpretation as response kernels."),
  future("mathematical-methods-for-physics", 22, "asymptotic-methods-and-saddle-point", "Asymptotic Methods and Saddle Point", "Watson's lemma, method of steepest descent, stationary phase, and asymptotic expansions for physical integrals."),
  future("mathematical-methods-for-physics", 23, "perturbation-theory-mathematical-framework", "Perturbation Theory: Mathematical Framework", "Regular and singular perturbation theory, matched asymptotic expansions, and the WKB method as a multiscale technique."),
  future("mathematical-methods-for-physics", 24, "group-theory-for-physics", "Group Theory for Physics", "Discrete and continuous groups, representations, characters, Schur's lemmas, and selection rules from symmetry."),
  future("mathematical-methods-for-physics", 25, "lie-groups-and-lie-algebras-introduction", "Lie Groups and Lie Algebras: Introduction", "Matrix Lie groups, the exponential map, Lie algebras as tangent spaces, and the structure constants of physical symmetry groups."),
  future("mathematical-methods-for-physics", 26, "representation-theory-of-su2-and-su3", "Representation Theory of SU(2) and SU(3)", "Irreducible representations, weight diagrams, Young tableaux, and applications to angular momentum and the quark model."),
];

const classicalMechanics: Lesson[] = [
  future("classical-mechanics", 1, "newtons-laws-rigorous-review", "Newton's Laws: A Rigorous Review", "Inertial frames, the second law as a definition versus law, and a careful re-examination of foundational mechanics."),
  future("classical-mechanics", 2, "work-energy-theorem-and-potentials", "Work-Energy Theorem and Conservative Potentials", "Line integrals of force, path independence, conservative force fields, and the relationship between force and potential energy."),
  future("classical-mechanics", 3, "conservation-laws-and-symmetries", "Conservation Laws and Symmetries", "Momentum, angular momentum, and energy conservation, derived from the structure of Newtonian mechanics and previewing Noether."),
  future("classical-mechanics", 4, "central-force-motion", "Central Force Motion", "Reduction to an effective one-dimensional problem, conservation of angular momentum, and orbit equations from the effective potential."),
  future("classical-mechanics", 5, "kepler-problem-and-orbits", "Kepler Problem and Orbits", "Solution of the inverse-square central force, conic-section orbits, Kepler's three laws, and the Laplace-Runge-Lenz vector."),
  future("classical-mechanics", 6, "two-body-problem-and-reduced-mass", "Two-Body Problem and Reduced Mass", "Reduction of the two-body problem to one body in a central potential, center-of-mass motion, and lab-versus-CM frames."),
  future("classical-mechanics", 7, "small-oscillations-and-stability", "Small Oscillations and Stability", "Linearization around equilibrium, the simple harmonic oscillator solution, and stability classification by potential curvature."),
  future("classical-mechanics", 8, "normal-modes-of-coupled-systems", "Normal Modes of Coupled Systems", "Diagonalizing coupled-oscillator systems via eigenvalue problems, mass and stiffness matrices, and frequencies as eigenvalues."),
  future("classical-mechanics", 9, "coupled-oscillators-and-wave-limits", "Coupled Oscillators and the Wave Limit", "Continuous-chain limit of coupled oscillators, dispersion relations, and the emergence of the wave equation from discrete systems."),
  future("classical-mechanics", 10, "calculus-of-variations-in-mechanics", "Calculus of Variations in Mechanics", "Variational principles, the brachistochrone, geodesics on surfaces, and the path from physics problems to functional minimization."),
  future("classical-mechanics", 11, "principle-of-least-action", "The Principle of Least Action", "Hamilton's principle, the stationary-action functional, and a derivation of Newton's laws from a variational starting point."),
  future("classical-mechanics", 12, "lagrangian-formulation-of-mechanics", "Lagrangian Formulation of Mechanics", "The Lagrangian L = T - V, equivalence to Newton's laws, and worked examples in non-Cartesian coordinates."),
  future("classical-mechanics", 13, "generalized-coordinates-and-degrees-of-freedom", "Generalized Coordinates and Degrees of Freedom", "Choosing coordinates suited to the problem geometry, configuration manifolds, and counting degrees of freedom."),
  future("classical-mechanics", 14, "constraints-and-dalemberts-principle", "Constraints and d'Alembert's Principle", "Holonomic and non-holonomic constraints, virtual work, d'Alembert's principle, and constraint forces via Lagrange multipliers."),
  future("classical-mechanics", 15, "hamiltonian-formulation", "Hamiltonian Formulation", "Legendre transform from Lagrangian to Hamiltonian, generalized momenta, and the symplectic structure of phase space."),
  future("classical-mechanics", 16, "hamiltons-equations-of-motion", "Hamilton's Equations of Motion", "First-order Hamilton's equations, examples from oscillators to charged particles, and conservation from the Hamiltonian."),
  future("classical-mechanics", 17, "phase-space-and-liouvilles-theorem", "Phase Space and Liouville's Theorem", "Phase-space flow, incompressibility of Hamiltonian dynamics, and Liouville's theorem as the foundation for statistical mechanics."),
  future("classical-mechanics", 18, "poisson-brackets-and-observables", "Poisson Brackets and Observables", "Poisson bracket algebra, equations of motion in bracket form, and the bridge to quantum commutators."),
  future("classical-mechanics", 19, "canonical-transformations", "Canonical Transformations", "Generating functions of four types, symplectic preservation, and using canonical transformations to simplify Hamiltonians."),
  future("classical-mechanics", 20, "hamilton-jacobi-theory", "Hamilton-Jacobi Theory", "The Hamilton-Jacobi equation, complete integrals, separation of variables, and connections to optics and quantum mechanics."),
  future("classical-mechanics", 21, "action-angle-variables", "Action-Angle Variables", "Action-angle coordinates for integrable systems, frequencies from the action function, and adiabatic invariants."),
  future("classical-mechanics", 22, "rigid-body-kinematics", "Rigid Body Kinematics", "Body and space frames, Euler angles, angular velocity, and the rotation group SO(3) underlying rigid-body motion."),
  future("classical-mechanics", 23, "eulers-equations-for-rigid-bodies", "Euler's Equations for Rigid Bodies", "Principal moments of inertia, the inertia tensor, and Euler's equations for torque-free and forced rotation."),
  future("classical-mechanics", 24, "gyroscopes-and-precession", "Gyroscopes and Precession", "Torque-induced precession, nutation of symmetric tops, and the heavy symmetric top as a worked Hamiltonian system."),
  future("classical-mechanics", 25, "integrable-systems-and-tori", "Integrable Systems and Invariant Tori", "Liouville integrability, invariant tori in phase space, and famous integrable systems (Toda, Calogero-Moser)."),
  future("classical-mechanics", 26, "chaos-and-kam-theory", "Chaos and KAM Theory", "Sensitive dependence, Lyapunov exponents, the KAM theorem, and the breakdown of integrability under perturbation."),
  future("classical-mechanics", 27, "continuum-mechanics-introduction", "Continuum Mechanics Introduction", "Stress and strain tensors, the Cauchy equation, conservation laws in continua, and the elastic-solid Lagrangian."),
  future("classical-mechanics", 28, "fluid-dynamics-introduction", "Fluid Dynamics Introduction", "Euler and Navier-Stokes equations, incompressibility, vorticity, Bernoulli's principle, and a glimpse of turbulence."),
  future("classical-mechanics", 29, "perturbation-methods-in-classical-mechanics", "Perturbation Methods in Classical Mechanics", "Canonical perturbation theory, Lindstedt-Poincare method, secular terms, and averaging over fast variables."),
  future("classical-mechanics", 30, "classical-scattering-theory", "Classical Scattering Theory", "Impact parameter, differential cross section, the Rutherford formula, and connections to quantum scattering."),
];

const electromagnetism: Lesson[] = [
  future("electromagnetism", 1, "electrostatics-rigorous-review", "Electrostatics: Rigorous Review", "Coulomb's law, the electric field as a vector field, energy of charge configurations, and the electrostatic potential."),
  future("electromagnetism", 2, "gausss-law-and-its-applications", "Gauss's Law and Its Applications", "Integral and differential forms, derivation from Coulomb plus superposition, and exploitation of symmetry."),
  future("electromagnetism", 3, "multipole-expansion-of-potentials", "Multipole Expansion of Potentials", "Monopole, dipole, quadrupole and higher moments, the spherical-harmonic expansion, and far-field structure."),
  future("electromagnetism", 4, "boundary-value-problems-in-electrostatics", "Boundary Value Problems in Electrostatics", "Dirichlet and Neumann problems, uniqueness theorems, method of images, and Green's functions for Laplace's equation."),
  future("electromagnetism", 5, "separation-of-variables-cartesian", "Separation of Variables in Cartesian Coordinates", "Solving Laplace's equation on rectangular domains, Fourier-series boundary matching, and worked capacitor problems."),
  future("electromagnetism", 6, "laplace-equation-in-spherical-cylindrical", "Laplace's Equation in Spherical and Cylindrical Coordinates", "Series solutions in Legendre polynomials and Bessel functions, axially symmetric problems, and conducting-sphere examples."),
  future("electromagnetism", 7, "dielectrics-and-polarization", "Dielectrics and Polarization", "Polarization vector P, bound charges, electric displacement D, linear dielectrics, and boundary conditions in matter."),
  future("electromagnetism", 8, "magnetostatics-and-currents", "Magnetostatics and Steady Currents", "Continuity equation, current density, Lorentz force, and the absence of magnetic monopoles in classical electrodynamics."),
  future("electromagnetism", 9, "biot-savart-law", "Biot-Savart Law", "The Biot-Savart law derived and applied to current loops, solenoids, and wires; cross-checks with Ampere."),
  future("electromagnetism", 10, "amperes-law-and-symmetry", "Ampere's Law and Symmetry", "Integral and differential forms, choosing Amperian loops, and computing magnetic fields of high-symmetry currents."),
  future("electromagnetism", 11, "vector-potential-and-gauge-freedom", "Vector Potential and Gauge Freedom", "Magnetic vector potential A, Coulomb and Lorenz gauges, gauge transformations, and gauge invariance of physical fields."),
  future("electromagnetism", 12, "magnetic-materials-and-magnetization", "Magnetic Materials and Magnetization", "Magnetization M, bound currents, the auxiliary field H, linear magnetic media, and ferromagnetism intuition."),
  future("electromagnetism", 13, "faradays-law-of-induction", "Faraday's Law of Induction", "Integral and differential forms, motional versus transformer EMF, Lenz's law, and induction in moving frames."),
  future("electromagnetism", 14, "maxwells-equations-and-displacement-current", "Maxwell's Equations and the Displacement Current", "Maxwell's correction to Ampere's law, the complete set of equations, and continuity as a consistency check."),
  future("electromagnetism", 15, "electromagnetic-energy-and-momentum", "Electromagnetic Energy and Momentum", "Energy density of E and B fields, the work-energy theorem in electrodynamics, and field momentum density."),
  future("electromagnetism", 16, "poynting-vector-and-energy-flow", "Poynting Vector and Energy Flow", "Derivation and physical interpretation of S = E x H / mu, Poynting's theorem, and energy flow in circuits and beams."),
  future("electromagnetism", 17, "electromagnetic-wave-equation", "The Electromagnetic Wave Equation", "Deriving the wave equation from Maxwell's equations in vacuum, the speed of light, and the structure of plane-wave solutions."),
  future("electromagnetism", 18, "polarization-of-electromagnetic-waves", "Polarization of Electromagnetic Waves", "Linear, circular, and elliptical polarization, Stokes parameters, and the Jones calculus for optical elements."),
  future("electromagnetism", 19, "wave-equations-in-source-regions", "Wave Equations in Source Regions", "Inhomogeneous wave equations for A and phi, retarded and advanced Green's functions, and causal propagation."),
  future("electromagnetism", 20, "plane-waves-in-conductors-and-skin-effect", "Plane Waves in Conductors and the Skin Effect", "Complex wave numbers in conductors, exponential attenuation, skin depth, and surface impedance."),
  future("electromagnetism", 21, "reflection-refraction-and-fresnel-equations", "Reflection, Refraction, and Fresnel Equations", "Boundary matching at dielectric interfaces, Snell's law, Fresnel coefficients, Brewster's angle, and total internal reflection."),
  future("electromagnetism", 22, "waveguides-and-mode-structure", "Waveguides and Mode Structure", "TE, TM, and TEM modes in rectangular and cylindrical waveguides, cutoff frequencies, and dispersion."),
  future("electromagnetism", 23, "resonant-cavities", "Resonant Cavities", "Eigenmodes of conducting cavities, quality factor Q, and the role of cavities in particle accelerators and lasers."),
  future("electromagnetism", 24, "radiation-from-accelerating-charges", "Radiation from Accelerating Charges", "Power radiated by accelerated charges, the radiation reaction, and the runaway/preacceleration problem of Abraham-Lorentz."),
  future("electromagnetism", 25, "larmor-formula-and-multipole-radiation", "Larmor Formula and Multipole Radiation", "Larmor's formula for nonrelativistic radiation, electric and magnetic dipole, and quadrupole radiation patterns."),
  future("electromagnetism", 26, "lienard-wiechert-potentials", "Lienard-Wiechert Potentials", "Retarded potentials of a point charge in arbitrary motion, the field decomposition into velocity and acceleration parts."),
  future("electromagnetism", 27, "radiation-patterns-and-angular-distributions", "Radiation Patterns and Angular Distributions", "Angular distribution of radiated power, the relativistic beaming forward, and synchrotron radiation introduction."),
  future("electromagnetism", 28, "antennas-and-radiation-resistance", "Antennas and Radiation Resistance", "Linear antennas, half-wave dipoles, radiation resistance, and the principles of array antennas."),
  future("electromagnetism", 29, "scattering-of-electromagnetic-waves", "Scattering of Electromagnetic Waves", "Thomson scattering, Rayleigh scattering and the color of the sky, and the optical theorem."),
  future("electromagnetism", 30, "special-relativity-in-electromagnetism", "Special Relativity in Electromagnetism", "The covariant form of Maxwell's equations, the field tensor F^{mu nu}, and transformations of E and B between frames."),
];

const quantumMechanics: Lesson[] = [
  future("quantum-mechanics", 1, "early-quantum-mechanics-and-old-quantum-theory", "Early Quantum Mechanics and Old Quantum Theory", "Blackbody radiation, photoelectric effect, Bohr atom, and the experimental crises driving the quantum revolution."),
  future("quantum-mechanics", 2, "wave-particle-duality-and-de-broglie", "Wave-Particle Duality and de Broglie", "Matter waves, the de Broglie relation, Davisson-Germer, and the breakdown of classical particle and wave concepts."),
  future("quantum-mechanics", 3, "schrodinger-equation-and-wavefunctions", "Schrodinger Equation and Wavefunctions", "Time-dependent and time-independent Schrodinger equations, probability interpretation, and the continuity equation."),
  future("quantum-mechanics", 4, "position-and-momentum-representations", "Position and Momentum Representations", "Position and momentum as conjugate variables, Fourier transform between representations, and operator forms."),
  future("quantum-mechanics", 5, "free-particle-and-wave-packets", "Free Particle and Wave Packets", "Plane-wave eigenstates, Gaussian wave packets, group versus phase velocity, and dispersive spreading."),
  future("quantum-mechanics", 6, "infinite-and-finite-square-wells", "Infinite and Finite Square Wells", "Bound-state energies and wavefunctions, parity, and the transcendental equation of the finite well."),
  future("quantum-mechanics", 7, "quantum-harmonic-oscillator-algebraic", "Quantum Harmonic Oscillator: Algebraic Method", "Ladder operators a and a-dagger, Fock-state construction, and the elegance of the algebraic eigenvalue problem."),
  future("quantum-mechanics", 8, "quantum-harmonic-oscillator-analytical", "Quantum Harmonic Oscillator: Analytical Method", "Solving the differential equation in terms of Hermite polynomials, asymptotic behavior, and explicit wavefunctions."),
  future("quantum-mechanics", 9, "barriers-and-quantum-tunneling", "Barriers and Quantum Tunneling", "Transmission and reflection coefficients, exponential tunneling through barriers, and applications from alpha decay to STM."),
  future("quantum-mechanics", 10, "dirac-formulation-bras-and-kets", "Dirac Formulation: Bras and Kets", "Abstract Hilbert space, bra-ket notation, inner products, and basis-independent expression of quantum states."),
  future("quantum-mechanics", 11, "operators-on-hilbert-space", "Operators on Hilbert Space", "Hermitian, unitary, and projection operators; spectral decomposition; and the postulates of measurement."),
  future("quantum-mechanics", 12, "heisenberg-uncertainty-principle", "Heisenberg Uncertainty Principle", "Generalized uncertainty relation from commutators, position-momentum uncertainty, and minimum-uncertainty states."),
  future("quantum-mechanics", 13, "time-evolution-and-schrodinger-picture", "Time Evolution and the Schrodinger Picture", "Unitary time evolution, the time-evolution operator, and conservation laws from commuting observables."),
  future("quantum-mechanics", 14, "heisenberg-and-interaction-pictures", "Heisenberg and Interaction Pictures", "Equivalence of Schrodinger, Heisenberg, and interaction pictures, and Ehrenfest's theorem."),
  future("quantum-mechanics", 15, "orbital-angular-momentum", "Orbital Angular Momentum", "Angular momentum operators in position representation, commutation relations, and spherical-harmonic eigenstates."),
  future("quantum-mechanics", 16, "ladder-operators-for-angular-momentum", "Ladder Operators for Angular Momentum", "Algebraic construction of |j, m> states, raising and lowering operators, and the half-integer surprise."),
  future("quantum-mechanics", 17, "spin-one-half-and-pauli-matrices", "Spin One-Half and Pauli Matrices", "Two-component spinors, Pauli matrices, the Bloch sphere, and Stern-Gerlach as the canonical spin measurement."),
  future("quantum-mechanics", 18, "addition-of-angular-momenta", "Addition of Angular Momenta", "Coupling two angular momenta, the total-J basis, and the dimensions of irreducible representations of SU(2)."),
  future("quantum-mechanics", 19, "clebsch-gordan-coefficients", "Clebsch-Gordan Coefficients", "Computing and tabulating Clebsch-Gordan coefficients, the Wigner-Eckart theorem, and selection rules."),
  future("quantum-mechanics", 20, "hydrogen-atom-solution", "Hydrogen Atom Solution", "Separation in spherical coordinates, the radial equation, Laguerre polynomial solutions, and the energy spectrum."),
  future("quantum-mechanics", 21, "fine-structure-of-hydrogen", "Fine Structure of Hydrogen", "Relativistic kinetic correction, spin-orbit coupling, the Darwin term, and the fine-structure constant alpha."),
  future("quantum-mechanics", 22, "zeeman-and-stark-effects", "Zeeman and Stark Effects", "Hydrogen in magnetic and electric fields, normal and anomalous Zeeman splitting, and Lamb shift preview."),
  future("quantum-mechanics", 23, "identical-particles-and-statistics", "Identical Particles and Statistics", "Symmetrization postulate, exchange operator, and the dichotomy between bosons and fermions."),
  future("quantum-mechanics", 24, "fermions-bosons-and-slater-determinants", "Fermions, Bosons, and Slater Determinants", "Antisymmetric many-fermion states, symmetric many-boson states, and the Pauli exclusion principle."),
  future("quantum-mechanics", 25, "time-independent-perturbation-theory-nondegenerate", "Time-Independent Perturbation Theory: Nondegenerate", "First- and second-order energy corrections, state corrections, and convergence considerations."),
  future("quantum-mechanics", 26, "degenerate-perturbation-theory", "Degenerate Perturbation Theory", "Lifting degeneracy by diagonalizing the perturbation, the secular equation, and applications to fine structure."),
  future("quantum-mechanics", 27, "time-dependent-perturbation-theory", "Time-Dependent Perturbation Theory", "Interaction picture, transition amplitudes, and first-order calculation of transition probabilities."),
  future("quantum-mechanics", 28, "fermis-golden-rule", "Fermi's Golden Rule", "Derivation of the transition rate to a continuum of final states, density of states, and applications to scattering and decay."),
  future("quantum-mechanics", 29, "variational-method", "Variational Method", "Upper-bound theorem for ground-state energy, trial wavefunctions, and applications to helium and hydrogen molecule."),
  future("quantum-mechanics", 30, "wkb-approximation", "WKB Approximation", "Semiclassical wavefunctions, connection formulas at turning points, Bohr-Sommerfeld quantization, and tunneling rates."),
];

const statisticalMechanics: Lesson[] = [
  future("statistical-mechanics", 1, "microstates-and-macrostates", "Microstates and Macrostates", "Fundamental postulate of statistical mechanics, counting microstates, and the bridge between microscopic and macroscopic worlds."),
  future("statistical-mechanics", 2, "ergodic-hypothesis-and-time-averages", "Ergodic Hypothesis and Time Averages", "Time versus ensemble averages, ergodicity, and modern understanding from chaos and KAM theory."),
  future("statistical-mechanics", 3, "microcanonical-ensemble", "Microcanonical Ensemble", "Isolated systems at fixed energy, equal a priori probabilities, and the density of states as a counting function."),
  future("statistical-mechanics", 4, "entropy-and-the-second-law", "Entropy and the Second Law", "Boltzmann's S = k log W, statistical interpretation of irreversibility, and Gibbs paradox."),
  future("statistical-mechanics", 5, "temperature-from-statistics", "Temperature from Statistics", "Temperature as 1/T = dS/dE, thermal equilibrium as entropy maximization, and absolute zero from the third law."),
  future("statistical-mechanics", 6, "canonical-ensemble", "Canonical Ensemble", "Systems in contact with a heat bath, Boltzmann distribution, and the role of temperature as a Lagrange multiplier."),
  future("statistical-mechanics", 7, "partition-function-and-free-energy", "Partition Function and Free Energy", "The partition function Z, F = -kT log Z, and partition functions as generating functions for thermodynamic observables."),
  future("statistical-mechanics", 8, "thermodynamic-potentials-and-legendre-transforms", "Thermodynamic Potentials and Legendre Transforms", "Internal energy, Helmholtz, Gibbs, and enthalpy as Legendre transforms, and Maxwell relations from mixed partials."),
  future("statistical-mechanics", 9, "grand-canonical-ensemble", "Grand Canonical Ensemble", "Chemical potential, fugacity, the grand partition function, and ensembles for open systems."),
  future("statistical-mechanics", 10, "ideal-classical-gas", "Ideal Classical Gas", "Partition function of a classical ideal gas, equation of state, equipartition, and the indistinguishability correction."),
  future("statistical-mechanics", 11, "equipartition-and-classical-heat-capacities", "Equipartition and Classical Heat Capacities", "The equipartition theorem, heat capacities of monatomic and polyatomic gases, and the Dulong-Petit law for solids."),
  future("statistical-mechanics", 12, "maxwell-boltzmann-distribution", "Maxwell-Boltzmann Distribution", "Velocity and speed distributions, mean and rms speeds, and effusion through a small hole."),
  future("statistical-mechanics", 13, "quantum-statistics-overview", "Quantum Statistics Overview", "Indistinguishable quantum particles, occupation-number formulation, and the bifurcation into Bose-Einstein and Fermi-Dirac."),
  future("statistical-mechanics", 14, "bose-einstein-statistics-and-condensation", "Bose-Einstein Statistics and Condensation", "Bose-Einstein distribution, the chemical potential of bosons, and Bose-Einstein condensation in trapped gases."),
  future("statistical-mechanics", 15, "fermi-dirac-statistics-and-degeneracy", "Fermi-Dirac Statistics and Degeneracy", "Fermi-Dirac distribution, Fermi energy and temperature, and electronic heat capacity of metals."),
  future("statistical-mechanics", 16, "photon-gas-and-blackbody-radiation", "Photon Gas and Blackbody Radiation", "Planck distribution, Stefan-Boltzmann law, radiation pressure, and the cosmic microwave background as a blackbody."),
  future("statistical-mechanics", 17, "phonons-and-solid-state-heat-capacity", "Phonons and Solid-State Heat Capacity", "Einstein and Debye models, phonon dispersion, and low-temperature T^3 heat capacity of insulators."),
  future("statistical-mechanics", 18, "quantum-versus-classical-heat-capacity", "Quantum vs Classical Heat Capacity", "Where equipartition fails, freeze-out of degrees of freedom, and the universal quantum corrections at low T."),
  future("statistical-mechanics", 19, "phase-transitions-classification", "Phase Transitions: Classification", "First- and second-order transitions, order parameters, latent heat, and Landau's symmetry-breaking framework."),
  future("statistical-mechanics", 20, "critical-phenomena-and-universality", "Critical Phenomena and Universality", "Critical exponents, scaling hypothesis, universality classes, and why microscopic details often do not matter."),
  future("statistical-mechanics", 21, "ising-model", "The Ising Model", "1D and 2D Ising models, transfer matrix solution in 1D, Onsager's exact solution intuition, and Monte Carlo simulation."),
  future("statistical-mechanics", 22, "mean-field-theory", "Mean-Field Theory", "Curie-Weiss mean-field treatment, critical exponents from mean field, and the breakdown of mean-field below the upper critical dimension."),
  future("statistical-mechanics", 23, "renormalization-group-introduction", "Renormalization Group: Introduction", "Block-spin transformations, fixed points and flows, relevant and irrelevant operators, and emergent universality."),
  future("statistical-mechanics", 24, "non-equilibrium-statistical-mechanics-introduction", "Non-Equilibrium Statistical Mechanics: Introduction", "Boltzmann equation, H-theorem, linear response, fluctuation-dissipation, and a peek at the Langevin equation."),
  future("statistical-mechanics", 25, "stochastic-processes-in-physics", "Stochastic Processes in Physics", "Brownian motion, the Langevin and Fokker-Planck equations, and the modern view of noise in physical systems."),
];

const specialRelativity: Lesson[] = [
  future("special-relativity", 1, "galilean-relativity-review", "Galilean Relativity Review", "Inertial frames, Galilean transformations, and the contradictions that arise when classical mechanics meets electromagnetism."),
  future("special-relativity", 2, "michelson-morley-and-the-ether-crisis", "Michelson-Morley and the Ether Crisis", "The Michelson-Morley experiment, the failure of the luminiferous ether, and the Lorentz-FitzGerald contraction proposal."),
  future("special-relativity", 3, "einstein-postulates-of-special-relativity", "Einstein's Postulates of Special Relativity", "The two postulates, their logical content, and the resulting upheaval in concepts of space and time."),
  future("special-relativity", 4, "lorentz-transformations-derivation", "Lorentz Transformations: Derivation", "Linear transformations preserving the speed of light, the gamma factor, and inversion to mixed-frame coordinates."),
  future("special-relativity", 5, "time-dilation", "Time Dilation", "Moving clocks tick slower, proper versus coordinate time, the muon-decay experiment, and GPS corrections."),
  future("special-relativity", 6, "length-contraction", "Length Contraction", "Moving rods are shorter along motion, proper length, and the resolution of pole-in-the-barn paradoxes."),
  future("special-relativity", 7, "relativity-of-simultaneity", "Relativity of Simultaneity", "Events simultaneous in one frame are not in another, and how this resolves apparent paradoxes."),
  future("special-relativity", 8, "relativistic-velocity-addition", "Relativistic Velocity Addition", "The Einstein velocity-addition formula, why no combination exceeds c, and consistency with Lorentz transformations."),
  future("special-relativity", 9, "relativistic-doppler-effect", "Relativistic Doppler Effect", "Longitudinal and transverse Doppler shifts, headlight effect, and applications to cosmological redshift."),
  future("special-relativity", 10, "spacetime-diagrams-and-minkowski-geometry", "Spacetime Diagrams and Minkowski Geometry", "Minkowski diagrams, world lines, light cones, and the geometric perspective on relativity."),
  future("special-relativity", 11, "light-cones-and-causal-structure", "Light Cones and Causal Structure", "Timelike, spacelike, and null intervals, causal ordering of events, and the impossibility of superluminal signaling."),
  future("special-relativity", 12, "four-vectors-and-tensors-in-spacetime", "Four-Vectors and Tensors in Spacetime", "The metric eta_{mu nu}, contravariant and covariant indices, four-vectors, and Lorentz scalars."),
  future("special-relativity", 13, "four-momentum-and-mass-energy-equivalence", "Four-Momentum and Mass-Energy Equivalence", "Energy-momentum four-vector, E = mc^2, rest energy, and invariant mass."),
  future("special-relativity", 14, "relativistic-energy-and-momentum-conservation", "Relativistic Energy and Momentum Conservation", "Conservation laws in different frames, photon four-momentum, and the limit recovering Newtonian mechanics."),
  future("special-relativity", 15, "particle-decays-and-collisions", "Particle Decays and Collisions", "Two-body decay kinematics, Mandelstam variables s, t, u, and thresholds for particle production."),
  future("special-relativity", 16, "covariant-electromagnetism", "Covariant Formulation of Electromagnetism", "The four-potential, the field tensor F^{mu nu}, and Maxwell's equations as two tensor equations."),
  future("special-relativity", 17, "field-tensor-and-lorentz-transformations-of-fields", "Field Tensor and Lorentz Transformations of Fields", "How E and B mix under boosts, the Lorentz invariants of the field, and the unified electromagnetic field."),
  future("special-relativity", 18, "twin-paradox-and-acceleration", "Twin Paradox and Acceleration", "Resolution of the twin paradox via differential aging, proper time along world lines, and uniform acceleration."),
  future("special-relativity", 19, "tachyons-and-causality", "Tachyons and Causality", "Hypothetical superluminal particles, why they violate causality, and modern reinterpretations as instabilities."),
  future("special-relativity", 20, "from-special-to-general-covariance", "From Special to General Covariance", "The principle of general covariance, the equivalence principle preview, and motivation for curved spacetime."),
];

const generalRelativity: Lesson[] = [
  future("general-relativity", 1, "equivalence-principle", "The Equivalence Principle", "Weak and strong equivalence, Einstein's elevator thought experiment, and the impossibility of distinguishing gravity locally from acceleration."),
  future("general-relativity", 2, "tensors-on-manifolds-review", "Tensors on Manifolds: Review", "Smooth manifolds, tangent and cotangent spaces, tensor fields, and the index calculus used by relativists."),
  future("general-relativity", 3, "metric-tensor-and-spacetime-geometry", "Metric Tensor and Spacetime Geometry", "The metric g_{mu nu}, line elements, raising and lowering indices, and the geometric meaning of signature (- + + +)."),
  future("general-relativity", 4, "christoffel-symbols-and-connections", "Christoffel Symbols and Connections", "The Levi-Civita connection, Christoffel symbols of the second kind, and torsion-free metric compatibility."),
  future("general-relativity", 5, "geodesic-equation", "Geodesic Equation", "Geodesics as extremals of arc length, the geodesic equation, and free fall as motion along geodesics."),
  future("general-relativity", 6, "parallel-transport-and-curvature", "Parallel Transport and Curvature", "Parallel transport along curves, holonomy, and curvature as the failure of parallel transport to be path-independent."),
  future("general-relativity", 7, "covariant-derivative", "Covariant Derivative", "Covariant differentiation of tensors of arbitrary rank, the Leibniz rule, and tensor equations as physical laws."),
  future("general-relativity", 8, "riemann-curvature-tensor", "Riemann Curvature Tensor", "Definition via commutator of covariant derivatives, symmetries, Bianchi identities, and number of independent components."),
  future("general-relativity", 9, "ricci-tensor-and-scalar-curvature", "Ricci Tensor and Scalar Curvature", "Contractions of the Riemann tensor, Einstein tensor G_{mu nu}, and the meaning of trace-free curvature."),
  future("general-relativity", 10, "einstein-field-equations", "Einstein Field Equations", "G_{mu nu} = 8 pi G T_{mu nu}, derivation from Einstein-Hilbert action, and the cosmological constant term."),
  future("general-relativity", 11, "weak-field-limit-and-newtonian-gravity", "Weak Field Limit and Newtonian Gravity", "Linearized gravity, the recovery of Newtonian gravity, and post-Newtonian corrections."),
  future("general-relativity", 12, "schwarzschild-solution", "Schwarzschild Solution", "Spherically symmetric vacuum solution, Schwarzschild metric, and the Schwarzschild radius."),
  future("general-relativity", 13, "orbits-in-schwarzschild-spacetime", "Orbits in Schwarzschild Spacetime", "Effective potential, stable and unstable circular orbits, ISCO, and qualitative differences from Newtonian orbits."),
  future("general-relativity", 14, "perihelion-precession-of-mercury", "Perihelion Precession of Mercury", "Calculation of the 43 arcsecond per century anomaly, and its historical role in confirming general relativity."),
  future("general-relativity", 15, "deflection-of-light-by-gravity", "Deflection of Light by Gravity", "Null geodesics around the sun, the Eddington 1919 measurement, and modern strong-field tests."),
  future("general-relativity", 16, "gravitational-redshift-and-time-dilation", "Gravitational Redshift and Time Dilation", "Pound-Rebka experiment, gravitational time dilation, and atomic-clock confirmations including GPS."),
  future("general-relativity", 17, "black-holes-introduction", "Black Holes: Introduction", "Coordinate versus physical singularities, the no-hair theorem, and an overview of black-hole zoology."),
  future("general-relativity", 18, "event-horizons-and-kruskal-extension", "Event Horizons and Kruskal Extension", "Eddington-Finkelstein and Kruskal-Szekeres coordinates, maximal extension, and the structure of horizons."),
  future("general-relativity", 19, "kerr-solution-and-rotating-black-holes", "Kerr Solution and Rotating Black Holes", "The Kerr metric, ergosphere, frame dragging, and the Penrose process for energy extraction."),
  future("general-relativity", 20, "gravitational-waves", "Gravitational Waves", "Linearized waves, plus and cross polarizations, generation by binary systems, and detection by LIGO."),
  future("general-relativity", 21, "cosmological-solutions-overview", "Cosmological Solutions Overview", "The cosmological principle, isotropy and homogeneity, and a survey of cosmological metrics."),
  future("general-relativity", 22, "frw-metric-and-cosmological-redshift", "FRW Metric and Cosmological Redshift", "Friedmann-Robertson-Walker metric, comoving coordinates, scale factor a(t), and redshift from cosmological expansion."),
  future("general-relativity", 23, "expanding-universe-and-friedmann-equations", "Expanding Universe and Friedmann Equations", "Derivation of the Friedmann and acceleration equations, density parameters, and the expansion history."),
  future("general-relativity", 24, "spinors-and-the-tetrad-formalism", "Spinors and the Tetrad Formalism", "Vierbein/tetrad formalism, spin connection, Dirac equation in curved spacetime, and the bridge to gauge theories of gravity."),
  future("general-relativity", 25, "gauge-theories-of-gravity-introduction", "Gauge Theories of Gravity: Introduction", "Einstein-Cartan theory, Poincare gauge theory, and the place of general relativity among gauge theories."),
];

const quantumFieldTheory: Lesson[] = [
  future("quantum-field-theory", 1, "motivation-for-quantum-fields", "Motivation for Quantum Fields", "Why nonrelativistic QM fails for high energies, causality and locality, and the necessity of fields with creation and annihilation."),
  future("quantum-field-theory", 2, "classical-field-theory", "Classical Field Theory", "Fields as dynamical variables, action functionals, Euler-Lagrange equations for fields, and energy-momentum tensor."),
  future("quantum-field-theory", 3, "klein-gordon-equation", "Klein-Gordon Equation", "Relativistic scalar wave equation, negative-energy puzzle, and its modern interpretation as a field equation."),
  future("quantum-field-theory", 4, "real-and-complex-scalar-fields", "Real and Complex Scalar Fields", "Lagrangians for real and complex scalars, internal U(1) symmetry, and conserved charge currents."),
  future("quantum-field-theory", 5, "lagrangian-density-and-action-principle", "Lagrangian Density and Action Principle", "Hamilton's principle for fields, locality, Lorentz invariance, and constraints on physically allowed Lagrangians."),
  future("quantum-field-theory", 6, "noethers-theorem-for-fields", "Noether's Theorem for Fields", "Continuous symmetries and conserved currents, energy-momentum from spacetime translations, and angular momentum tensor."),
  future("quantum-field-theory", 7, "symmetries-and-conservation-laws-in-qft", "Symmetries and Conservation Laws in QFT", "Global versus local symmetries, internal symmetries, and the connection between symmetry breaking and Goldstone bosons."),
  future("quantum-field-theory", 8, "canonical-quantization-of-scalar-field", "Canonical Quantization of the Scalar Field", "Equal-time commutators, mode expansion, and the scalar field as an infinite collection of harmonic oscillators."),
  future("quantum-field-theory", 9, "creation-and-annihilation-operators", "Creation and Annihilation Operators", "Fock space, particle interpretation of field excitations, and vacuum as the lowest-energy state."),
  future("quantum-field-theory", 10, "normal-ordering-and-vacuum-energy", "Normal Ordering and Vacuum Energy", "Removing zero-point energy by normal ordering, Casimir effect as physical evidence, and the cosmological-constant problem preview."),
  future("quantum-field-theory", 11, "propagators-and-greens-functions-in-qft", "Propagators and Green's Functions in QFT", "Feynman propagator for scalar field, time-ordered products, and the i-epsilon prescription for contour selection."),
  future("quantum-field-theory", 12, "wicks-theorem", "Wick's Theorem", "Reducing time-ordered products to normal-ordered products plus contractions, generating Feynman diagrams systematically."),
  future("quantum-field-theory", 13, "free-dirac-field", "Free Dirac Field", "Dirac equation from spinor representations, gamma matrices, plane-wave solutions for electrons and positrons."),
  future("quantum-field-theory", 14, "anti-commutation-and-fermion-statistics", "Anti-Commutation and Fermion Statistics", "Quantization of the Dirac field with anti-commutators, Pauli exclusion from algebra, and spin-statistics theorem."),
  future("quantum-field-theory", 15, "antiparticles-and-charge-conjugation", "Antiparticles and Charge Conjugation", "Antiparticles from the Dirac field, CPT symmetry, and Feynman-Stueckelberg interpretation of negative-energy solutions."),
  future("quantum-field-theory", 16, "gauge-symmetry-and-gauge-fields", "Gauge Symmetry and Gauge Fields", "Local U(1) symmetry, the gauge principle, and the necessity of a gauge field to maintain local invariance."),
  future("quantum-field-theory", 17, "qed-lagrangian-and-minimal-coupling", "QED Lagrangian and Minimal Coupling", "Quantum electrodynamics Lagrangian, minimal coupling, and gauge fixing for canonical quantization."),
  future("quantum-field-theory", 18, "feynman-rules-for-qed", "Feynman Rules for QED", "Deriving Feynman rules from the Lagrangian, vertices and propagators in QED, and book-keeping for momentum conservation."),
  future("quantum-field-theory", 19, "tree-level-processes-in-qed", "Tree-Level Processes in QED", "Computing cross sections for Compton scattering, Bhabha and Moeller scattering, and electron-positron annihilation."),
  future("quantum-field-theory", 20, "loop-corrections-and-divergences", "Loop Corrections and Divergences", "One-loop diagrams, ultraviolet and infrared divergences, and the meaning of bare versus physical parameters."),
  future("quantum-field-theory", 21, "renormalization-concept", "The Concept of Renormalization", "Absorbing infinities into counterterms, predictivity of renormalizable theories, and Wilson's effective field theory viewpoint."),
  future("quantum-field-theory", 22, "regularization-schemes", "Regularization Schemes", "Cutoff, Pauli-Villars, and dimensional regularization, with emphasis on dim-reg as the standard modern tool."),
  future("quantum-field-theory", 23, "running-couplings-and-rg-flow", "Running Couplings and RG Flow", "Beta functions, running of the QED coupling, Landau pole, and the renormalization group equations."),
  future("quantum-field-theory", 24, "yang-mills-theory", "Yang-Mills Theory", "Non-abelian gauge theories, structure constants, self-interacting gauge bosons, and SU(N) as a non-abelian generalization of QED."),
  future("quantum-field-theory", 25, "asymptotic-freedom-and-qcd", "Asymptotic Freedom and QCD", "Negative beta function of QCD, asymptotic freedom, confinement, and the 1973 discovery that earned a Nobel."),
  future("quantum-field-theory", 26, "electroweak-theory-introduction", "Electroweak Theory: Introduction", "SU(2) x U(1) gauge structure, weak interactions, parity violation, and the unification of electromagnetism with the weak force."),
  future("quantum-field-theory", 27, "higgs-mechanism", "Higgs Mechanism", "Spontaneous symmetry breaking, Goldstone bosons eaten by gauge bosons, and the mass generation of W, Z, and fermions."),
  future("quantum-field-theory", 28, "standard-model-overview", "Standard Model Overview", "The full gauge group SU(3) x SU(2) x U(1), particle content, three generations, and open problems beyond the Standard Model."),
  future("quantum-field-theory", 29, "anomalies-in-quantum-field-theory", "Anomalies in Quantum Field Theory", "Classical symmetries broken by quantization, the chiral anomaly, and anomaly cancellation as a constraint on Standard Model content."),
  future("quantum-field-theory", 30, "effective-field-theory-and-beyond-standard-model", "Effective Field Theory and Beyond Standard Model", "EFT as the modern paradigm, higher-dimensional operators, and EFT-based searches for new physics."),
];

const cosmology: Lesson[] = [
  future("cosmology", 1, "cosmological-principle-and-large-scale-isotropy", "Cosmological Principle and Large-Scale Isotropy", "Observational evidence for homogeneity and isotropy, scales at which they hold, and the resulting symmetries."),
  future("cosmology", 2, "frw-metric-and-dynamics", "FRW Metric and Dynamics", "Friedmann-Robertson-Walker metric, spatial curvature parameter k, and the dynamical role of the scale factor."),
  future("cosmology", 3, "friedmann-equations", "Friedmann Equations", "Derivation from the Einstein equations, energy-density components, and acceleration equation from continuity."),
  future("cosmology", 4, "scale-factor-and-cosmological-redshift", "Scale Factor and Cosmological Redshift", "Redshift from cosmic expansion, Hubble's law, and the relationship between distance and redshift."),
  future("cosmology", 5, "dark-matter-observational-evidence", "Dark Matter: Observational Evidence", "Galactic rotation curves, velocity dispersions in clusters, gravitational lensing, and the Bullet Cluster."),
  future("cosmology", 6, "dark-energy-and-cosmic-acceleration", "Dark Energy and Cosmic Acceleration", "Type Ia supernova observations, the cosmological constant, equation of state w, and quintessence alternatives."),
  future("cosmology", 7, "cosmic-microwave-background", "Cosmic Microwave Background", "Discovery, blackbody spectrum at 2.7 K, and the power spectrum of temperature anisotropies as a precision cosmological tool."),
  future("cosmology", 8, "recombination-and-decoupling", "Recombination and Decoupling", "Saha equation for ionization, last-scattering surface, and the freezing of CMB photons at z ~ 1100."),
  future("cosmology", 9, "big-bang-nucleosynthesis", "Big Bang Nucleosynthesis", "Production of light elements in the first three minutes, predicted abundances of H, He-4, D, Li-7, and observational tests."),
  future("cosmology", 10, "inflation-theory", "Inflation Theory", "Horizon and flatness problems, exponential expansion, slow-roll inflation, and inflaton potentials."),
  future("cosmology", 11, "primordial-perturbations-and-power-spectrum", "Primordial Perturbations and Power Spectrum", "Quantum fluctuations of the inflaton, nearly scale-invariant spectrum, and the seeds of cosmic structure."),
  future("cosmology", 12, "structure-formation-and-gravitational-collapse", "Structure Formation and Gravitational Collapse", "Linear perturbation theory, Jeans instability, growth of density contrasts, and N-body simulations."),
  future("cosmology", 13, "galaxy-clusters-and-cluster-cosmology", "Galaxy Clusters and Cluster Cosmology", "Cluster mass functions, intracluster medium, Sunyaev-Zel'dovich effect, and clusters as cosmological probes."),
  future("cosmology", 14, "large-scale-structure-of-the-universe", "Large-Scale Structure of the Universe", "Cosmic web of filaments and voids, galaxy redshift surveys, two-point correlation function and power spectrum."),
  future("cosmology", 15, "gravitational-lensing-weak-and-strong", "Gravitational Lensing: Weak and Strong", "Geometry of light deflection in cosmology, weak-lensing shear catalogs, and strong-lensing time delays for H_0."),
  future("cosmology", 16, "baryon-acoustic-oscillations", "Baryon Acoustic Oscillations", "Acoustic peaks in the photon-baryon plasma, the BAO scale as a standard ruler, and surveys (BOSS, eBOSS, DESI)."),
  future("cosmology", 17, "lambda-cdm-concordance-model", "Lambda-CDM Concordance Model", "Six-parameter Lambda-CDM, its precision tests, and the H_0 and S_8 tensions challenging the standard cosmology."),
  future("cosmology", 18, "modified-gravity-alternatives", "Modified Gravity Alternatives", "f(R) gravity, MOND, scalar-tensor theories, and observational tests that constrain alternatives to general relativity."),
  future("cosmology", 19, "alternatives-to-particle-dark-matter", "Alternatives to Particle Dark Matter", "Primordial black holes, modified inertia models, and the empirical status of competing dark-matter hypotheses."),
  future("cosmology", 20, "multiverse-and-anthropic-reasoning", "Multiverse and Anthropic Reasoning", "Eternal inflation, the string landscape, anthropic explanations for the cosmological constant, and the limits of falsifiability."),
];

const researchProblemsAndSimulations: Lesson[] = [
  future("research-problems-and-simulations", 1, "numerical-methods-for-physics-problems", "Numerical Methods for Physics Problems", "Floating-point pitfalls, ODE integrators (RK4, symplectic), root finding, and choosing the right solver for the problem."),
  future("research-problems-and-simulations", 2, "classical-mechanics-simulation-project", "Classical Mechanics Simulation Project", "Implementing symplectic integrators, simulating the n-body problem, and validating against analytic Kepler orbits."),
  future("research-problems-and-simulations", 3, "electrostatics-pde-solvers", "Electrostatics PDE Solvers", "Finite-difference and finite-element solvers for Poisson's equation, with convergence and boundary-condition checks."),
  future("research-problems-and-simulations", 4, "time-dependent-schrodinger-equation-numerically", "Time-Dependent Schrodinger Equation Numerically", "Split-operator and Crank-Nicolson schemes, conservation of probability, and wave-packet scattering experiments."),
  future("research-problems-and-simulations", 5, "lattice-methods-for-field-theories", "Lattice Methods for Field Theories", "Lattice discretization, fermion doubling, Wilson fermions, and a glimpse of lattice QCD computations."),
  future("research-problems-and-simulations", 6, "monte-carlo-for-statistical-mechanics", "Monte Carlo for Statistical Mechanics", "Metropolis algorithm for the Ising model, autocorrelation and equilibration, and finite-size scaling analysis."),
  future("research-problems-and-simulations", 7, "classical-and-quantum-monte-carlo", "Classical and Quantum Monte Carlo", "Variational and diffusion Monte Carlo, path-integral Monte Carlo, and sampling many-body wavefunctions."),
  future("research-problems-and-simulations", 8, "molecular-dynamics-simulations", "Molecular Dynamics Simulations", "Velocity-Verlet integration, Lennard-Jones systems, thermostats and barostats, and computing transport coefficients."),
  future("research-problems-and-simulations", 9, "numerical-relativity-bssn-formulation", "Numerical Relativity and the BSSN Formulation", "3+1 decomposition, BSSN evolution variables, gauge conditions, and binary black hole merger simulation strategy."),
  future("research-problems-and-simulations", 10, "reproducing-a-famous-result", "Reproducing a Famous Result", "Select a landmark physics calculation, reproduce it from primary sources, and produce a careful write-up of methodology."),
  future("research-problems-and-simulations", 11, "formulating-a-research-question", "Formulating a Research Question", "Identifying open problems, judging tractability, narrowing a vague interest into a concrete computational or theoretical question."),
  future("research-problems-and-simulations", 12, "literature-review-for-a-physics-problem", "Literature Review for a Physics Problem", "Effective use of arXiv, INSPIRE-HEP, ADS, and citation graphs; synthesizing decades of literature into a coherent landscape."),
  future("research-problems-and-simulations", 13, "small-original-computation-project", "A Small Original Computation", "Designing, executing, and validating an original computation on a niche problem, with attention to error bars and robustness."),
  future("research-problems-and-simulations", 14, "presenting-physics-results", "Presenting Physics Results", "Writing a physics paper in LaTeX, designing figures that communicate, and structuring a talk for technical audiences."),
  future("research-problems-and-simulations", 15, "peer-review-of-a-physics-writeup", "Peer Review of a Physics Write-Up", "Acting as a referee on a peer's draft, giving constructive critique, and learning from being reviewed in return."),
];

export const theoreticalPhysicsLessons: Lesson[] = [
  ...mathematicalMethodsForPhysics,
  ...classicalMechanics,
  ...electromagnetism,
  ...quantumMechanics,
  ...statisticalMechanics,
  ...specialRelativity,
  ...generalRelativity,
  ...quantumFieldTheory,
  ...cosmology,
  ...researchProblemsAndSimulations,
];
