import type { Lesson } from "../../src/lib/types";

export const lessons: Lesson[] = [
  {
    slug: "arithmetic-units-and-estimation",
    trackSlug: "mathematical-foundations",
    moduleSlug: "math-reentry-toolkit",
    title: "Arithmetic, Units, and Estimation",
    summary: "Rebuild number sense, unit awareness, and quick reasonableness checks for technical work.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    checkId: "arithmetic-units-core-check",
    mdxPath: "content/lessons/arithmetic-units-and-estimation.mdx",
  },
  {
    slug: "fractions-ratios-and-proportions",
    trackSlug: "mathematical-foundations",
    moduleSlug: "math-reentry-toolkit",
    title: "Fractions, Ratios, and Proportions",
    summary: "Use fractions and ratios as engineering language for scaling, mixtures, maps, gears, and sensors.",
    kind: "lesson",
    status: "available",
    order: 2,
    estimatedMinutes: 40,
    prerequisites: ["arithmetic-units-and-estimation"],
    checkId: "fractions-ratios-core-check",
    mdxPath: "content/lessons/fractions-ratios-and-proportions.mdx",
  },
  {
    slug: "signed-numbers-and-order-of-operations",
    trackSlug: "mathematical-foundations",
    moduleSlug: "math-reentry-toolkit",
    title: "Signed Numbers and Order of Operations",
    summary: "Handle negative values, parentheses, exponents, and calculation order without losing the physical meaning.",
    kind: "lesson",
    status: "available",
    order: 3,
    estimatedMinutes: 35,
    prerequisites: ["fractions-ratios-and-proportions"],
    checkId: "signed-numbers-core-check",
    mdxPath: "content/lessons/signed-numbers-and-order-of-operations.mdx",
  },
  {
    slug: "solving-equations-from-zero",
    trackSlug: "mathematical-foundations",
    moduleSlug: "equations-units-and-graphs",
    title: "Solving Equations from Zero",
    summary: "Learn equations as balance statements and solve for unknowns one reversible step at a time.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 45,
    prerequisites: ["signed-numbers-and-order-of-operations"],
    mdxPath: "content/lessons/solving-equations-from-zero.mdx",
  },
  {
    slug: "units-and-dimensional-analysis",
    trackSlug: "mathematical-foundations",
    moduleSlug: "equations-units-and-graphs",
    title: "Units and Dimensional Analysis",
    summary: "Use units as a debugging system for formulas, calculations, simulations, and lab measurements.",
    kind: "lesson",
    status: "available",
    order: 2,
    estimatedMinutes: 40,
    prerequisites: ["solving-equations-from-zero"],
    mdxPath: "content/lessons/units-and-dimensional-analysis.mdx",
  },
  {
    slug: "graphing-functions-for-builders",
    trackSlug: "mathematical-foundations",
    moduleSlug: "equations-units-and-graphs",
    title: "Graphing Functions for Builders",
    summary: "Read and sketch graphs as stories about change, systems, sensors, and design tradeoffs.",
    kind: "lesson",
    status: "available",
    order: 3,
    estimatedMinutes: 45,
    prerequisites: ["units-and-dimensional-analysis"],
    mdxPath: "content/lessons/graphing-functions-for-builders.mdx",
  },
  {
    slug: "algebra-for-engineering-systems",
    trackSlug: "mathematical-foundations",
    moduleSlug: "equations-units-and-graphs",
    title: "Algebra for Engineering Systems",
    summary: "Use equations as models for physical relationships, constraints, and system behavior.",
    kind: "lesson",
    status: "available",
    order: 4,
    estimatedMinutes: 35,
    prerequisites: ["graphing-functions-for-builders"],
    mdxPath: "content/lessons/algebra-for-engineering-systems.mdx",
  },
  {
    slug: "trigonometry-for-drones-and-robotics",
    trackSlug: "mathematical-foundations",
    moduleSlug: "geometry-trig-and-vectors",
    title: "Trigonometry for Drones and Robotics",
    summary: "Convert angles and distances into components, heights, bearings, and field measurements.",
    kind: "lesson",
    status: "available",
    order: 2,
    estimatedMinutes: 40,
    prerequisites: ["algebra-for-engineering-systems"],
    mdxPath: "content/lessons/trigonometry-for-drones-and-robotics.mdx",
  },
  {
    slug: "vectors-from-zero",
    trackSlug: "mathematical-foundations",
    moduleSlug: "geometry-trig-and-vectors",
    title: "Vectors from Zero",
    summary: "Understand vectors as quantities with size and direction, then use components for motion and force.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 45,
    prerequisites: ["algebra-for-engineering-systems"],
    mdxPath: "content/lessons/vectors-from-zero.mdx",
  },
  {
    slug: "python-functions-for-technical-tools",
    trackSlug: "coding-foundations",
    moduleSlug: "technical-python",
    title: "Python Functions for Technical Tools",
    summary: "Package formulas into reusable functions for calculators, simulations, and lab scripts.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 30,
    mdxPath: "content/lessons/python-functions-for-technical-tools.mdx",
  },
  {
    slug: "ohms-law-and-basic-circuits",
    trackSlug: "electronics-and-circuits",
    moduleSlug: "circuit-laws",
    title: "Ohm's Law and Basic Circuits",
    summary: "Relate voltage, current, and resistance, then apply the relationship to practical circuits.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    mdxPath: "content/lessons/ohms-law-and-basic-circuits.mdx",
  },
  {
    slug: "what-is-mechatronics",
    trackSlug: "mechatronics",
    moduleSlug: "systems-primer",
    title: "What Is Mechatronics?",
    summary: "Understand mechatronics as the integration of mechanics, electronics, code, and control.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 25,
    mdxPath: "content/lessons/what-is-mechatronics.mdx",
  },
  {
    slug: "introduction-to-coordinate-systems",
    trackSlug: "drones-gis-remote-sensing",
    moduleSlug: "coordinate-systems",
    title: "Introduction to Coordinate Systems",
    summary: "Map points, frames, and bearings so robots and drones can reason about position.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    mdxPath: "content/lessons/introduction-to-coordinate-systems.mdx",
  },
  {
    slug: "introduction-to-theoretical-physics",
    trackSlug: "theoretical-physics",
    moduleSlug: "mathematical-methods-for-physics",
    title: "Introduction to Theoretical Physics",
    summary: "Preview the physics path and the math/computation habits needed for later study.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 30,
    mdxPath: "content/lessons/introduction-to-theoretical-physics.mdx",
  },
];
