import type { Lesson } from "../../src/lib/types";

export const lessons: Lesson[] = [
  {
    slug: "algebra-for-engineering-systems",
    trackSlug: "mathematical-foundations",
    moduleSlug: "engineering-algebra-and-geometry",
    title: "Algebra for Engineering Systems",
    summary: "Use equations as models for physical relationships, constraints, and system behavior.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    mdxPath: "content/lessons/algebra-for-engineering-systems.mdx",
  },
  {
    slug: "trigonometry-for-drones-and-robotics",
    trackSlug: "mathematical-foundations",
    moduleSlug: "engineering-algebra-and-geometry",
    title: "Trigonometry for Drones and Robotics",
    summary: "Convert angles and distances into components, heights, bearings, and field measurements.",
    kind: "lesson",
    status: "available",
    order: 2,
    estimatedMinutes: 40,
    prerequisites: ["algebra-for-engineering-systems"],
    mdxPath: "content/lessons/trigonometry-for-drones-and-robotics.mdx",
  },
  {
    slug: "python-functions-for-technical-tools",
    trackSlug: "coding-foundations",
    moduleSlug: "technical-python",
    title: "Python Functions for Technical Tools",
    summary: "Package formulas into reusable functions for calculators, simulations, and lab scripts.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 30,
    mdxPath: "content/lessons/python-functions-for-technical-tools.mdx",
  },
  {
    slug: "ohms-law-and-basic-circuits",
    trackSlug: "electronics-and-circuits",
    moduleSlug: "circuit-laws",
    title: "Ohm's Law and Basic Circuits",
    summary: "Relate voltage, current, and resistance, then apply the relationship to practical circuits.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    mdxPath: "content/lessons/ohms-law-and-basic-circuits.mdx",
  },
  {
    slug: "what-is-mechatronics",
    trackSlug: "mechatronics",
    moduleSlug: "systems-primer",
    title: "What Is Mechatronics?",
    summary: "Understand mechatronics as the integration of mechanics, electronics, code, and control.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 25,
    mdxPath: "content/lessons/what-is-mechatronics.mdx",
  },
  {
    slug: "introduction-to-coordinate-systems",
    trackSlug: "drones-gis-remote-sensing",
    moduleSlug: "coordinate-systems",
    title: "Introduction to Coordinate Systems",
    summary: "Map points, frames, and bearings so robots and drones can reason about position.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 35,
    mdxPath: "content/lessons/introduction-to-coordinate-systems.mdx",
  },
  {
    slug: "introduction-to-theoretical-physics",
    trackSlug: "theoretical-physics",
    moduleSlug: "mathematical-methods-for-physics",
    title: "Introduction to Theoretical Physics",
    summary: "Preview the physics path and the math/computation habits needed for later study.",
    kind: "lesson",
    status: "available",
    order: 1,
    estimatedMinutes: 30,
    mdxPath: "content/lessons/introduction-to-theoretical-physics.mdx",
  },
];
