import type { Module } from "../../src/lib/types";

export const modules: Module[] = [
  {
    slug: "math-reentry-toolkit",
    trackSlug: "mathematical-foundations",
    title: "Math Re-entry Toolkit",
    summary: "Arithmetic, estimation, units, fractions, signed numbers, and the habits needed to study again.",
    status: "available",
    order: 1,
  },
  {
    slug: "equations-units-and-graphs",
    trackSlug: "mathematical-foundations",
    title: "Engineering Algebra and Geometry",
    summary: "Equations, dimensional analysis, graphs, functions, and technical problem translation.",
    status: "available",
    order: 2,
  },
  {
    slug: "geometry-trig-and-vectors",
    trackSlug: "mathematical-foundations",
    title: "Geometry, Trigonometry, and Vectors",
    summary: "Distances, angles, triangles, components, and vector reasoning for physical systems.",
    status: "available",
    order: 3,
  },
  {
    slug: "pre-calculus",
    trackSlug: "mathematical-foundations",
    title: "Pre-calculus",
    summary:
      "Polynomial, rational, exponential, and logarithmic functions; conic sections; sequences; complex numbers. The bridge to calculus.",
    status: "future",
    order: 4,
  },
  {
    slug: "calculus-i-differentiation",
    trackSlug: "mathematical-foundations",
    title: "Calculus I — Differentiation",
    summary:
      "Limits, continuity, derivatives, chain rule, implicit differentiation, related rates, optimization, linearization. Anchored to MIT 18.01.",
    status: "future",
    order: 5,
  },
  {
    slug: "calculus-ii-integration-and-series",
    trackSlug: "mathematical-foundations",
    title: "Calculus II — Integration and Series",
    summary:
      "Antiderivatives, fundamental theorem, integration techniques, applications, improper integrals, sequences, series, Taylor expansions. Anchored to MIT 18.01.",
    status: "future",
    order: 6,
  },
  {
    slug: "multivariable-calculus",
    trackSlug: "mathematical-foundations",
    title: "Multivariable Calculus",
    summary:
      "Partial derivatives, gradients, multiple integrals, line and surface integrals, divergence, curl, Green's/Stokes/divergence theorems. Anchored to MIT 18.02.",
    status: "future",
    order: 7,
  },
  {
    slug: "linear-algebra",
    trackSlug: "mathematical-foundations",
    title: "Linear Algebra",
    summary:
      "Vectors, matrices, systems, vector spaces, orthogonality, determinants, eigenvalues, SVD, and applications to data and dynamics. Anchored to MIT 18.06 (Strang).",
    status: "future",
    order: 8,
  },
  {
    slug: "differential-equations",
    trackSlug: "mathematical-foundations",
    title: "Differential Equations",
    summary:
      "First and second order ODEs, systems, Laplace transforms, intro to PDEs and Fourier methods. Anchored to MIT 18.03.",
    status: "future",
    order: 9,
  },
  {
    slug: "probability-and-statistics",
    trackSlug: "mathematical-foundations",
    title: "Probability and Statistics",
    summary:
      "Probability spaces, random variables, distributions, expectation, joint distributions, central limit theorem, estimation, hypothesis testing, regression. Anchored to MIT 6.041 / 18.05.",
    status: "future",
    order: 10,
  },
  {
    slug: "real-analysis",
    trackSlug: "mathematical-foundations",
    title: "Real Analysis",
    summary:
      "The rigorous foundation under calculus: sequences, limits, continuity, differentiability, the Riemann integral, metric spaces. Required for graduate-level math and theoretical physics.",
    status: "future",
    order: 11,
  },
  {
    slug: "abstract-algebra",
    trackSlug: "mathematical-foundations",
    title: "Abstract Algebra",
    summary:
      "Groups, rings, fields, modules. Required for theoretical physics (symmetry, gauge theory) and cryptography.",
    status: "future",
    order: 12,
  },
  {
    slug: "topology",
    trackSlug: "mathematical-foundations",
    title: "Topology",
    summary:
      "Point-set topology, continuous maps, compactness, connectedness; introduction to algebraic topology. Required for general relativity, gauge theory, and modern geometry.",
    status: "future",
    order: 13,
  },
  {
    slug: "technical-python",
    trackSlug: "coding-foundations",
    title: "Technical Python",
    summary: "Functions, scripts, calculations, and small tools for engineering study.",
    status: "available",
    order: 1,
  },
  {
    slug: "data-structures-and-algorithms",
    trackSlug: "coding-foundations",
    title: "Data Structures and Algorithms",
    summary: "Arrays, linked lists, trees, hash tables, graphs; sorting, searching, recursion, dynamic programming, and complexity analysis.",
    status: "future",
    order: 2,
  },
  {
    slug: "numerical-and-scientific-python",
    trackSlug: "coding-foundations",
    title: "Numerical and Scientific Python",
    summary: "NumPy arrays, SciPy, pandas, matplotlib; vectorized computation and the scientific Python stack used in research and ML.",
    status: "future",
    order: 3,
  },
  {
    slug: "software-engineering-practice",
    trackSlug: "coding-foundations",
    title: "Software Engineering Practice",
    summary: "Git, testing, debugging, profiling, packaging, type checking, and the daily habits that separate hobby code from production code.",
    status: "future",
    order: 4,
  },
  {
    slug: "cpp-for-systems",
    trackSlug: "coding-foundations",
    title: "C++ for Systems and Robotics",
    summary: "C++ from first principles: memory, pointers, templates, the STL, and modern C++ features used in robotics, ROS2, and performance-critical code.",
    status: "future",
    order: 5,
  },
  {
    slug: "performance-and-concurrency",
    trackSlug: "coding-foundations",
    title: "Performance, Concurrency, and Distributed Systems",
    summary: "Profiling, multi-threading, async/await, message passing, distributed system patterns, and reasoning about latency and throughput.",
    status: "future",
    order: 6,
  },
  {
    slug: "circuit-laws",
    trackSlug: "electronics-and-circuits",
    title: "Circuit Laws",
    summary: "Voltage, current, resistance, power, and measured behavior.",
    status: "available",
    order: 1,
  },
  {
    slug: "dc-circuit-analysis",
    trackSlug: "electronics-and-circuits",
    title: "DC Circuit Analysis",
    summary: "Mesh and nodal analysis, Thevenin and Norton equivalents, superposition, and energy storage in capacitors and inductors.",
    status: "future",
    order: 2,
  },
  {
    slug: "ac-and-reactive-circuits",
    trackSlug: "electronics-and-circuits",
    title: "AC and Reactive Circuits",
    summary: "Phasors, impedance, frequency response, RLC circuits, and resonance for time-varying signals.",
    status: "future",
    order: 3,
  },
  {
    slug: "semiconductors-and-transistor-circuits",
    trackSlug: "electronics-and-circuits",
    title: "Semiconductors and Transistor Circuits",
    summary: "Diodes, BJTs, and MOSFETs; biasing and small-signal analysis; basic amplifier and switching topologies.",
    status: "future",
    order: 4,
  },
  {
    slug: "op-amps-and-analog",
    trackSlug: "electronics-and-circuits",
    title: "Op-amps and Analog Signal Conditioning",
    summary: "Ideal and real op-amps, classic op-amp topologies, active filters, and analog front-ends for sensors.",
    status: "future",
    order: 5,
  },
  {
    slug: "digital-logic-and-architecture",
    trackSlug: "electronics-and-circuits",
    title: "Digital Logic and Computer Architecture",
    summary: "Boolean algebra, combinational and sequential circuits, finite-state machines, and a first look at how a CPU is built.",
    status: "future",
    order: 6,
  },
  {
    slug: "microcontroller-embedded-programming",
    trackSlug: "electronics-and-circuits",
    title: "Microcontroller Embedded Programming",
    summary: "Arduino, STM32, and ESP32 in C/C++: GPIO, timers, interrupts, ADC/DAC, serial peripherals (UART/I2C/SPI), and embedded patterns.",
    status: "future",
    order: 7,
  },
  {
    slug: "systems-primer",
    trackSlug: "mechatronics",
    title: "Systems Primer",
    summary: "How mechanisms, sensors, software, and actuators become one machine.",
    status: "available",
    order: 1,
  },
  {
    slug: "sensors-and-measurement",
    trackSlug: "mechatronics",
    title: "Sensors and Measurement",
    summary: "Position, force, temperature, IMU, encoders, vision, and ultrasonic sensors; signal conditioning, calibration, and noise filtering.",
    status: "future",
    order: 2,
  },
  {
    slug: "actuators-and-drives",
    trackSlug: "mechatronics",
    title: "Actuators and Drive Electronics",
    summary: "DC motors, servo motors, stepper motors, brushless DC, hydraulic and pneumatic actuators, and the drive electronics that command them.",
    status: "future",
    order: 3,
  },
  {
    slug: "control-systems-theory",
    trackSlug: "mechatronics",
    title: "Control Systems Theory",
    summary: "Feedback, transfer functions, PID, frequency response, stability analysis, state-space models, and observer design.",
    status: "future",
    order: 4,
  },
  {
    slug: "real-time-systems-and-firmware",
    trackSlug: "mechatronics",
    title: "Real-time Systems and Firmware",
    summary: "RTOS concepts, scheduling, interrupt handling, deterministic communication, and firmware patterns for safety-critical systems.",
    status: "future",
    order: 5,
  },
  {
    slug: "integrated-machine-projects",
    trackSlug: "mechatronics",
    title: "Integrated Machine Projects",
    summary: "Multi-week build projects that pull together mechanical design, electronics, firmware, and control: a delta robot, a CNC, a balancing platform.",
    status: "future",
    order: 6,
  },
  {
    slug: "robot-kinematics",
    trackSlug: "robotics",
    title: "Robot Kinematics and Coordinate Frames",
    summary: "Coordinate frames, homogeneous transforms, Denavit-Hartenberg conventions, forward and inverse kinematics for serial and parallel robots.",
    status: "future",
    order: 1,
  },
  {
    slug: "robot-dynamics",
    trackSlug: "robotics",
    title: "Robot Dynamics and Mechanics",
    summary: "Newton-Euler and Lagrangian dynamics for multi-body robots, mass matrices, Coriolis and gravity terms, and simulation of robot motion.",
    status: "future",
    order: 2,
  },
  {
    slug: "motion-planning",
    trackSlug: "robotics",
    title: "Motion Planning and Path Optimization",
    summary: "Configuration space, A* and Dijkstra on grids, RRT and PRM sampling-based methods, trajectory optimization, and obstacle avoidance.",
    status: "future",
    order: 3,
  },
  {
    slug: "perception-and-slam",
    trackSlug: "robotics",
    title: "Perception and SLAM",
    summary: "Sensor fusion, Bayesian filtering, EKF and particle filters, occupancy grids, and modern SLAM (LIO, ORB-SLAM, factor graphs).",
    status: "future",
    order: 4,
  },
  {
    slug: "robot-control",
    trackSlug: "robotics",
    title: "Robot Control",
    summary: "Joint-space and task-space control, impedance and admittance control, force control, and modern model-predictive control for robots.",
    status: "future",
    order: 5,
  },
  {
    slug: "ros-ecosystem",
    trackSlug: "robotics",
    title: "ROS and ROS2 Ecosystem",
    summary: "ROS architecture, nodes, topics, services, actions; ROS2 evolution, DDS, real-time considerations; tooling (rviz, gazebo, MoveIt).",
    status: "future",
    order: 6,
  },
  {
    slug: "field-deployment",
    trackSlug: "robotics",
    title: "Field Deployment and Operations",
    summary: "Reliability engineering for robots, logging and replay, remote operation, safety analysis, and the gap between lab and field.",
    status: "future",
    order: 7,
  },
  {
    slug: "coordinate-systems",
    trackSlug: "drones-gis-remote-sensing",
    title: "Coordinate Systems",
    summary: "Frames, positions, bearings, and field measurements for drones and maps.",
    status: "available",
    order: 1,
  },
  {
    slug: "aerodynamics-and-flight-mechanics",
    trackSlug: "drones-gis-remote-sensing",
    title: "Aerodynamics and Flight Mechanics",
    summary: "Lift, drag, and thrust; airfoil theory at the right level for drones; rotorcraft mechanics; vertical takeoff and stability.",
    status: "future",
    order: 2,
  },
  {
    slug: "flight-control-firmware",
    trackSlug: "drones-gis-remote-sensing",
    title: "Flight Control Firmware (PX4 / ArduPilot)",
    summary: "Open-source flight stacks, cascaded control loops, sensor fusion (EKF), parameter tuning, and writing/modifying flight controller firmware.",
    status: "future",
    order: 3,
  },
  {
    slug: "mission-planning-and-operations",
    trackSlug: "drones-gis-remote-sensing",
    title: "Mission Planning and Operations",
    summary: "Waypoint missions, geofencing, return-to-launch, BVLOS considerations, and the safety practices for operating drones in the field.",
    status: "future",
    order: 4,
  },
  {
    slug: "gis-and-photogrammetry",
    trackSlug: "drones-gis-remote-sensing",
    title: "GIS and Photogrammetry",
    summary: "Geographic information systems, projections, georeferenced data, structure-from-motion, orthomosaic generation, and digital elevation models.",
    status: "future",
    order: 5,
  },
  {
    slug: "multispectral-thermal-and-lidar",
    trackSlug: "drones-gis-remote-sensing",
    title: "Multispectral, Thermal, and LiDAR Sensing",
    summary: "Beyond visible imagery: multispectral and thermal cameras, LiDAR principles, point-cloud processing, and applied remote sensing.",
    status: "future",
    order: 6,
  },
  {
    slug: "image-fundamentals",
    trackSlug: "computer-vision",
    title: "Image Fundamentals",
    summary: "Pixels, color spaces, histograms, convolution, filtering, edges, and morphological operations as the bedrock of all computer vision.",
    status: "future",
    order: 1,
  },
  {
    slug: "geometric-vision",
    trackSlug: "computer-vision",
    title: "Geometric Vision",
    summary: "Camera models (pinhole, distortion), camera calibration, two-view geometry, fundamental and essential matrices, stereo vision.",
    status: "future",
    order: 2,
  },
  {
    slug: "classical-features-and-tracking",
    trackSlug: "computer-vision",
    title: "Classical Features and Tracking",
    summary: "Corner and blob detectors, SIFT/ORB descriptors, Hough transforms, RANSAC, optical flow, and feature-based tracking.",
    status: "future",
    order: 3,
  },
  {
    slug: "deep-learning-for-vision",
    trackSlug: "computer-vision",
    title: "Deep Learning for Vision",
    summary: "Convolutional neural networks, object detection (YOLO, DETR), semantic and instance segmentation, transformers for vision.",
    status: "future",
    order: 4,
  },
  {
    slug: "3d-vision-and-reconstruction",
    trackSlug: "computer-vision",
    title: "3D Vision and Reconstruction",
    summary: "Depth from stereo and monocular cues, structure from motion, multi-view stereo, NeRF and modern neural reconstruction methods.",
    status: "future",
    order: 5,
  },
  {
    slug: "industrial-vision-and-metrology",
    trackSlug: "computer-vision",
    title: "Industrial Vision and Metrology",
    summary: "High-precision measurement with cameras, calibration targets, lighting design, defect detection, and integration with manufacturing systems.",
    status: "future",
    order: 6,
  },
  {
    slug: "embedded-communication-protocols",
    trackSlug: "cloud-networking-telemetry",
    title: "Embedded Communication Protocols",
    summary: "UART, I2C, SPI, CAN, USB; how each works at the wire level, when to use each, and writing drivers for sensors and devices.",
    status: "future",
    order: 1,
  },
  {
    slug: "networking-and-internet-protocols",
    trackSlug: "cloud-networking-telemetry",
    title: "Networking and Internet Protocols",
    summary: "TCP/IP, UDP, HTTP/HTTPS, WebSockets, DNS, TLS, the OSI model, and writing networked services for instrument data.",
    status: "future",
    order: 2,
  },
  {
    slug: "real-time-data-and-messaging",
    trackSlug: "cloud-networking-telemetry",
    title: "Real-time Data and Messaging",
    summary: "MQTT, gRPC, ROS2 DDS, Kafka, time-series databases (InfluxDB, TimescaleDB), and event-driven architectures for telemetry.",
    status: "future",
    order: 3,
  },
  {
    slug: "dashboards-and-time-series",
    trackSlug: "cloud-networking-telemetry",
    title: "Dashboards and Time-series Systems",
    summary: "Grafana, Plotly Dash, custom dashboards, alerting, and the data architecture that makes a fleet of robots observable.",
    status: "future",
    order: 4,
  },
  {
    slug: "fleet-operations-and-reliability",
    trackSlug: "cloud-networking-telemetry",
    title: "Fleet Operations and Reliability",
    summary: "Deployment pipelines for embedded systems, OTA updates, logs and tracing, SLOs, and the operations practice of running a robot or drone fleet.",
    status: "future",
    order: 5,
  },
  {
    slug: "mathematical-methods-for-physics",
    trackSlug: "theoretical-physics",
    title: "Mathematical Methods for Physics",
    summary: "Linear algebra, differential equations, tensors, and variational methods.",
    status: "future",
    order: 1,
  },
  {
    slug: "classical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Classical Mechanics",
    summary: "Newtonian, Lagrangian, and Hamiltonian mechanics.",
    status: "future",
    order: 2,
  },
  {
    slug: "electromagnetism",
    trackSlug: "theoretical-physics",
    title: "Electromagnetism",
    summary: "Fields, potentials, Maxwell equations, waves, and radiation.",
    status: "future",
    order: 3,
  },
  {
    slug: "quantum-mechanics",
    trackSlug: "theoretical-physics",
    title: "Quantum Mechanics",
    summary: "States, operators, wave mechanics, spin, and approximation methods.",
    status: "future",
    order: 4,
  },
  {
    slug: "statistical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Statistical Mechanics",
    summary: "Entropy, ensembles, partition functions, and phase behavior.",
    status: "future",
    order: 5,
  },
  {
    slug: "special-relativity",
    trackSlug: "theoretical-physics",
    title: "Special Relativity",
    summary: "Spacetime, Lorentz transformations, four-vectors, and relativistic dynamics.",
    status: "future",
    order: 6,
  },
  {
    slug: "general-relativity",
    trackSlug: "theoretical-physics",
    title: "General Relativity",
    summary: "Curvature, geodesics, Einstein equations, and gravitational systems.",
    status: "future",
    order: 7,
  },
  {
    slug: "quantum-field-theory",
    trackSlug: "theoretical-physics",
    title: "Quantum Field Theory",
    summary: "Fields, symmetries, particles, interactions, and perturbation theory.",
    status: "future",
    order: 8,
  },
  {
    slug: "cosmology",
    trackSlug: "theoretical-physics",
    title: "Cosmology",
    summary: "Expanding universes, dark matter, dark energy, and early-universe models.",
    status: "future",
    order: 9,
  },
  {
    slug: "research-problems-and-simulations",
    trackSlug: "theoretical-physics",
    title: "Research Problems and Simulations",
    summary: "Numerical experiments, notebooks, and open-ended theoretical investigations.",
    status: "future",
    order: 10,
  },
  {
    slug: "ml-foundations",
    trackSlug: "machine-learning-and-ai",
    title: "ML Foundations",
    summary: "Statistical learning theory, bias-variance, generalization, regularization, and the framing that underlies every ML method.",
    status: "future",
    order: 1,
  },
  {
    slug: "classical-ml-algorithms",
    trackSlug: "machine-learning-and-ai",
    title: "Classical ML Algorithms",
    summary: "Linear and logistic regression, k-NN, decision trees, SVMs, kernel methods, naive Bayes, clustering (k-means, GMM), and ensemble methods.",
    status: "future",
    order: 2,
  },
  {
    slug: "deep-learning-theory",
    trackSlug: "machine-learning-and-ai",
    title: "Deep Learning Theory and Practice",
    summary: "Feedforward networks, backprop, optimization for deep learning, regularization, batchnorm, initialization, and the training playbook.",
    status: "future",
    order: 3,
  },
  {
    slug: "deep-learning-architectures",
    trackSlug: "machine-learning-and-ai",
    title: "Deep Learning Architectures",
    summary: "CNNs, RNNs, LSTMs, transformers and attention, graph neural networks, and modern multi-modal architectures.",
    status: "future",
    order: 4,
  },
  {
    slug: "reinforcement-learning",
    trackSlug: "machine-learning-and-ai",
    title: "Reinforcement Learning",
    summary: "MDPs, dynamic programming, Q-learning, policy gradients, actor-critic, PPO, model-based RL, and sim-to-real transfer for robotics.",
    status: "future",
    order: 5,
  },
  {
    slug: "generative-models",
    trackSlug: "machine-learning-and-ai",
    title: "Generative Models",
    summary: "Autoregressive models, VAEs, GANs, normalizing flows, diffusion models, and large language models as foundation models.",
    status: "future",
    order: 6,
  },
  {
    slug: "ml-systems-engineering",
    trackSlug: "machine-learning-and-ai",
    title: "ML Systems Engineering",
    summary: "Training pipelines, distributed training, mixed precision, GPU/TPU programming, deployment, MLOps, and the systems side of ML.",
    status: "future",
    order: 7,
  },
  {
    slug: "ai-safety-and-alignment",
    trackSlug: "machine-learning-and-ai",
    title: "AI Safety and Alignment",
    summary: "Robustness, adversarial examples, interpretability, alignment problems, evaluation methodology, and the responsible deployment of AI.",
    status: "future",
    order: 8,
  },
  {
    slug: "optimization-foundations",
    trackSlug: "optimization",
    title: "Optimization Foundations",
    summary: "Gradients, descent methods, line search, step-size rules, and convergence theory for unconstrained optimization.",
    status: "future",
    order: 1,
  },
  {
    slug: "convex-optimization",
    trackSlug: "optimization",
    title: "Convex Optimization",
    summary: "Convex sets and functions, LP, QP, SOCP, SDP; duality, KKT conditions; anchored to Boyd & Vandenberghe.",
    status: "future",
    order: 2,
  },
  {
    slug: "nonlinear-optimization",
    trackSlug: "optimization",
    title: "Nonlinear and Nonconvex Optimization",
    summary: "Newton and quasi-Newton methods (BFGS, L-BFGS), trust-region methods, line-search methods, and convergence analysis.",
    status: "future",
    order: 3,
  },
  {
    slug: "constrained-and-discrete-optimization",
    trackSlug: "optimization",
    title: "Constrained and Discrete Optimization",
    summary: "Equality and inequality constraints, Lagrangian methods, interior-point methods, integer and mixed-integer programming, branch-and-bound.",
    status: "future",
    order: 4,
  },
  {
    slug: "applied-optimization",
    trackSlug: "optimization",
    title: "Applied Optimization",
    summary: "Optimization in ML training, robot motion planning, model-predictive control, engineering design, and scheduling.",
    status: "future",
    order: 5,
  },
  {
    slug: "numerical-linear-algebra",
    trackSlug: "numerical-methods",
    title: "Numerical Linear Algebra",
    summary: "Floating-point arithmetic, factorizations (LU, QR, SVD, Cholesky), iterative methods (Krylov, CG, GMRES), sparse matrices.",
    status: "future",
    order: 1,
  },
  {
    slug: "numerical-integration-and-quadrature",
    trackSlug: "numerical-methods",
    title: "Numerical Integration and Quadrature",
    summary: "Newton-Cotes rules, Gaussian quadrature, adaptive quadrature, Monte Carlo integration, and multi-dimensional integration.",
    status: "future",
    order: 2,
  },
  {
    slug: "ode-numerical-methods",
    trackSlug: "numerical-methods",
    title: "Numerical Methods for ODEs",
    summary: "Euler, Runge-Kutta, multistep methods, adaptive step size, stiff systems, symplectic integrators, and stability analysis.",
    status: "future",
    order: 3,
  },
  {
    slug: "pde-and-finite-element-methods",
    trackSlug: "numerical-methods",
    title: "PDE and Finite Element Methods",
    summary: "Finite difference, finite element, and spectral methods for elliptic, parabolic, and hyperbolic PDEs.",
    status: "future",
    order: 4,
  },
  {
    slug: "automatic-differentiation",
    trackSlug: "numerical-methods",
    title: "Automatic Differentiation",
    summary: "Forward and reverse mode autodiff, computational graphs, the internals of JAX and PyTorch autograd, and implications for ML.",
    status: "future",
    order: 5,
  },
  {
    slug: "numerical-stability-and-error-analysis",
    trackSlug: "numerical-methods",
    title: "Numerical Stability and Error Analysis",
    summary: "Floating-point representation, condition numbers, forward and backward error, stability of algorithms, and choosing algorithms reliably.",
    status: "future",
    order: 6,
  },
  {
    slug: "statics-and-mechanics-of-materials",
    trackSlug: "mechanical-engineering",
    title: "Statics and Mechanics of Materials",
    summary: "Forces and moments, free-body diagrams, stress and strain, beams, torsion, and column buckling.",
    status: "future",
    order: 1,
  },
  {
    slug: "cad-and-3d-modeling",
    trackSlug: "mechanical-engineering",
    title: "CAD and 3D Modeling",
    summary: "Parametric modeling in Fusion 360 / OnShape, assemblies, drawings, sheet metal, and CAD workflows for prototyping.",
    status: "future",
    order: 2,
  },
  {
    slug: "materials-science",
    trackSlug: "mechanical-engineering",
    title: "Materials Science",
    summary: "Metals, polymers, ceramics, and composites; properties (strength, stiffness, fatigue, thermal); material selection for engineering design.",
    status: "future",
    order: 3,
  },
  {
    slug: "finite-element-analysis",
    trackSlug: "mechanical-engineering",
    title: "Finite Element Analysis",
    summary: "Principles of FEA, meshing, applying loads and constraints, interpreting stress and deformation results, and FEA tools (Fusion, ANSYS).",
    status: "future",
    order: 4,
  },
  {
    slug: "manufacturing-processes",
    trackSlug: "mechanical-engineering",
    title: "Manufacturing Processes",
    summary: "3D printing (FDM, SLA, SLS), CNC machining, laser cutting, sheet metal, injection molding, and choosing the right process for a part.",
    status: "future",
    order: 5,
  },
  {
    slug: "design-for-manufacturing",
    trackSlug: "mechanical-engineering",
    title: "Design for Manufacturing",
    summary: "Tolerancing, GD&T, fits and clearances, design for assembly, cost estimation, and engineering design reviews.",
    status: "future",
    order: 6,
  },
  {
    slug: "literature-reading-and-synthesis",
    trackSlug: "research-methods",
    title: "Literature Reading and Synthesis",
    summary: "How to read a paper, structured paper notes, citation tracing, building a literature review, and using search engines and arXiv.",
    status: "future",
    order: 1,
  },
  {
    slug: "latex-and-scientific-writing",
    trackSlug: "research-methods",
    title: "LaTeX and Scientific Writing",
    summary: "LaTeX from scratch, mathematical typesetting, figures and tables, BibTeX, journal templates, and structuring a technical paper.",
    status: "future",
    order: 2,
  },
  {
    slug: "reproducible-research",
    trackSlug: "research-methods",
    title: "Reproducible Research",
    summary: "Version control for science, computational environments, notebooks vs scripts, data management, and the reproducibility crisis.",
    status: "future",
    order: 3,
  },
  {
    slug: "presentation-and-communication",
    trackSlug: "research-methods",
    title: "Presentation and Communication",
    summary: "Technical talks, conference posters, demo presentations, technical interviews, and writing for non-specialists.",
    status: "future",
    order: 4,
  },
];
