import type { Module } from "../../src/lib/types";

export const modules: Module[] = [
  {
    slug: "engineering-algebra-and-geometry",
    trackSlug: "mathematical-foundations",
    title: "Engineering Algebra and Geometry",
    summary: "Equations, distances, angles, vectors, and coordinate systems for technical work.",
    status: "available",
    order: 1,
  },
  {
    slug: "technical-python",
    trackSlug: "coding-foundations",
    title: "Technical Python",
    summary: "Functions, scripts, calculations, and small tools for engineering study.",
    status: "available",
    order: 1,
  },
  {
    slug: "circuit-laws",
    trackSlug: "electronics-and-circuits",
    title: "Circuit Laws",
    summary: "Voltage, current, resistance, power, and measured behavior.",
    status: "available",
    order: 1,
  },
  {
    slug: "systems-primer",
    trackSlug: "mechatronics",
    title: "Systems Primer",
    summary: "How mechanisms, sensors, software, and actuators become one machine.",
    status: "available",
    order: 1,
  },
  {
    slug: "coordinate-systems",
    trackSlug: "drones-gis-remote-sensing",
    title: "Coordinate Systems",
    summary: "Frames, positions, bearings, and field measurements for drones and maps.",
    status: "available",
    order: 1,
  },
  {
    slug: "mathematical-methods-for-physics",
    trackSlug: "theoretical-physics",
    title: "Mathematical Methods for Physics",
    summary: "Linear algebra, differential equations, tensors, and variational methods.",
    status: "future",
    order: 1,
  },
  {
    slug: "classical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Classical Mechanics",
    summary: "Newtonian, Lagrangian, and Hamiltonian mechanics.",
    status: "future",
    order: 2,
  },
  {
    slug: "electromagnetism",
    trackSlug: "theoretical-physics",
    title: "Electromagnetism",
    summary: "Fields, potentials, Maxwell equations, waves, and radiation.",
    status: "future",
    order: 3,
  },
  {
    slug: "quantum-mechanics",
    trackSlug: "theoretical-physics",
    title: "Quantum Mechanics",
    summary: "States, operators, wave mechanics, spin, and approximation methods.",
    status: "future",
    order: 4,
  },
  {
    slug: "statistical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Statistical Mechanics",
    summary: "Entropy, ensembles, partition functions, and phase behavior.",
    status: "future",
    order: 5,
  },
  {
    slug: "special-relativity",
    trackSlug: "theoretical-physics",
    title: "Special Relativity",
    summary: "Spacetime, Lorentz transformations, four-vectors, and relativistic dynamics.",
    status: "future",
    order: 6,
  },
  {
    slug: "general-relativity",
    trackSlug: "theoretical-physics",
    title: "General Relativity",
    summary: "Curvature, geodesics, Einstein equations, and gravitational systems.",
    status: "future",
    order: 7,
  },
  {
    slug: "quantum-field-theory",
    trackSlug: "theoretical-physics",
    title: "Quantum Field Theory",
    summary: "Fields, symmetries, particles, interactions, and perturbation theory.",
    status: "future",
    order: 8,
  },
  {
    slug: "cosmology",
    trackSlug: "theoretical-physics",
    title: "Cosmology",
    summary: "Expanding universes, dark matter, dark energy, and early-universe models.",
    status: "future",
    order: 9,
  },
  {
    slug: "research-problems-and-simulations",
    trackSlug: "theoretical-physics",
    title: "Research Problems and Simulations",
    summary: "Numerical experiments, notebooks, and open-ended theoretical investigations.",
    status: "future",
    order: 10,
  },
];
