import type { Module } from "../../src/lib/types";

export const modules: Module[] = [
  {
    slug: "math-reentry-toolkit",
    trackSlug: "mathematical-foundations",
    title: "Math Re-entry Toolkit",
    summary: "Arithmetic, estimation, units, fractions, signed numbers, and the habits needed to study again.",
    status: "available",
    order: 1,
  },
  {
    slug: "equations-units-and-graphs",
    trackSlug: "mathematical-foundations",
    title: "Engineering Algebra and Geometry",
    summary: "Equations, dimensional analysis, graphs, functions, and technical problem translation.",
    status: "available",
    order: 2,
  },
  {
    slug: "geometry-trig-and-vectors",
    trackSlug: "mathematical-foundations",
    title: "Geometry, Trigonometry, and Vectors",
    summary: "Distances, angles, triangles, components, and vector reasoning for physical systems.",
    status: "available",
    order: 3,
  },
  {
    slug: "pre-calculus",
    trackSlug: "mathematical-foundations",
    title: "Pre-calculus",
    summary:
      "Polynomial, rational, exponential, and logarithmic functions; conic sections; sequences; complex numbers. The bridge to calculus.",
    status: "future",
    order: 4,
  },
  {
    slug: "calculus-i-differentiation",
    trackSlug: "mathematical-foundations",
    title: "Calculus I — Differentiation",
    summary:
      "Limits, continuity, derivatives, chain rule, implicit differentiation, related rates, optimization, linearization. Anchored to MIT 18.01.",
    status: "future",
    order: 5,
  },
  {
    slug: "calculus-ii-integration-and-series",
    trackSlug: "mathematical-foundations",
    title: "Calculus II — Integration and Series",
    summary:
      "Antiderivatives, fundamental theorem, integration techniques, applications, improper integrals, sequences, series, Taylor expansions. Anchored to MIT 18.01.",
    status: "future",
    order: 6,
  },
  {
    slug: "multivariable-calculus",
    trackSlug: "mathematical-foundations",
    title: "Multivariable Calculus",
    summary:
      "Partial derivatives, gradients, multiple integrals, line and surface integrals, divergence, curl, Green's/Stokes/divergence theorems. Anchored to MIT 18.02.",
    status: "future",
    order: 7,
  },
  {
    slug: "linear-algebra",
    trackSlug: "mathematical-foundations",
    title: "Linear Algebra",
    summary:
      "Vectors, matrices, systems, vector spaces, orthogonality, determinants, eigenvalues, SVD, and applications to data and dynamics. Anchored to MIT 18.06 (Strang).",
    status: "future",
    order: 8,
  },
  {
    slug: "differential-equations",
    trackSlug: "mathematical-foundations",
    title: "Differential Equations",
    summary:
      "First and second order ODEs, systems, Laplace transforms, intro to PDEs and Fourier methods. Anchored to MIT 18.03.",
    status: "future",
    order: 9,
  },
  {
    slug: "probability-and-statistics",
    trackSlug: "mathematical-foundations",
    title: "Probability and Statistics",
    summary:
      "Probability spaces, random variables, distributions, expectation, joint distributions, central limit theorem, estimation, hypothesis testing, regression. Anchored to MIT 6.041 / 18.05.",
    status: "future",
    order: 10,
  },
  {
    slug: "real-analysis",
    trackSlug: "mathematical-foundations",
    title: "Real Analysis",
    summary:
      "The rigorous foundation under calculus: sequences, limits, continuity, differentiability, the Riemann integral, metric spaces. Required for graduate-level math and theoretical physics.",
    status: "future",
    order: 11,
  },
  {
    slug: "abstract-algebra",
    trackSlug: "mathematical-foundations",
    title: "Abstract Algebra",
    summary:
      "Groups, rings, fields, modules. Required for theoretical physics (symmetry, gauge theory) and cryptography.",
    status: "future",
    order: 12,
  },
  {
    slug: "topology",
    trackSlug: "mathematical-foundations",
    title: "Topology",
    summary:
      "Point-set topology, continuous maps, compactness, connectedness; introduction to algebraic topology. Required for general relativity, gauge theory, and modern geometry.",
    status: "future",
    order: 13,
  },
  {
    slug: "technical-python",
    trackSlug: "coding-foundations",
    title: "Technical Python",
    summary: "Functions, scripts, calculations, and small tools for engineering study.",
    status: "available",
    order: 1,
  },
  {
    slug: "circuit-laws",
    trackSlug: "electronics-and-circuits",
    title: "Circuit Laws",
    summary: "Voltage, current, resistance, power, and measured behavior.",
    status: "available",
    order: 1,
  },
  {
    slug: "systems-primer",
    trackSlug: "mechatronics",
    title: "Systems Primer",
    summary: "How mechanisms, sensors, software, and actuators become one machine.",
    status: "available",
    order: 1,
  },
  {
    slug: "coordinate-systems",
    trackSlug: "drones-gis-remote-sensing",
    title: "Coordinate Systems",
    summary: "Frames, positions, bearings, and field measurements for drones and maps.",
    status: "available",
    order: 1,
  },
  {
    slug: "mathematical-methods-for-physics",
    trackSlug: "theoretical-physics",
    title: "Mathematical Methods for Physics",
    summary: "Linear algebra, differential equations, tensors, and variational methods.",
    status: "future",
    order: 1,
  },
  {
    slug: "classical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Classical Mechanics",
    summary: "Newtonian, Lagrangian, and Hamiltonian mechanics.",
    status: "future",
    order: 2,
  },
  {
    slug: "electromagnetism",
    trackSlug: "theoretical-physics",
    title: "Electromagnetism",
    summary: "Fields, potentials, Maxwell equations, waves, and radiation.",
    status: "future",
    order: 3,
  },
  {
    slug: "quantum-mechanics",
    trackSlug: "theoretical-physics",
    title: "Quantum Mechanics",
    summary: "States, operators, wave mechanics, spin, and approximation methods.",
    status: "future",
    order: 4,
  },
  {
    slug: "statistical-mechanics",
    trackSlug: "theoretical-physics",
    title: "Statistical Mechanics",
    summary: "Entropy, ensembles, partition functions, and phase behavior.",
    status: "future",
    order: 5,
  },
  {
    slug: "special-relativity",
    trackSlug: "theoretical-physics",
    title: "Special Relativity",
    summary: "Spacetime, Lorentz transformations, four-vectors, and relativistic dynamics.",
    status: "future",
    order: 6,
  },
  {
    slug: "general-relativity",
    trackSlug: "theoretical-physics",
    title: "General Relativity",
    summary: "Curvature, geodesics, Einstein equations, and gravitational systems.",
    status: "future",
    order: 7,
  },
  {
    slug: "quantum-field-theory",
    trackSlug: "theoretical-physics",
    title: "Quantum Field Theory",
    summary: "Fields, symmetries, particles, interactions, and perturbation theory.",
    status: "future",
    order: 8,
  },
  {
    slug: "cosmology",
    trackSlug: "theoretical-physics",
    title: "Cosmology",
    summary: "Expanding universes, dark matter, dark energy, and early-universe models.",
    status: "future",
    order: 9,
  },
  {
    slug: "research-problems-and-simulations",
    trackSlug: "theoretical-physics",
    title: "Research Problems and Simulations",
    summary: "Numerical experiments, notebooks, and open-ended theoretical investigations.",
    status: "future",
    order: 10,
  },
];
